### ISSUE TITLE
Understanding Eager Loading without row.children

### ISSUE THREAD

**Issue by avr** [spicywebau/craft-neo#103]
I'm struggling to understand where and how to eager load child blocks in a hierarchical field.  I have this code:

```
{% for row in entry.neoField %}
    {% do row.useMemoized(entry.neoField) %}
{% endfor %}

{% for row in entry.impactContent if row.level == 1 %}
    {% if row.heading %}
        {{ row.heading }}
    {% endif %}

    {# {% set blocks = entry.neoField.find({
        with: ['impactBlocks:impactBlock', 'quote:credit']
    }) %} #}

    {% include '_partials/content-blocks' with { 'blocks' : row.children } only %}

{% endfor %}
```

In a different file, I have: 

```
{% for i, block in blocks %}
    {# Content Goes Here #}
    {% include '_blocks/' ~ block.type ignore missing %}
{% endfor %}
```

I've tried the above code to eager load the blocks and pass `blocks` instead of `row.children`, but then I all the blocks repeated for every row.

**Comment by nickdunn** [comment]
I'm struggling with this too. I am eager loading the Neo field on my auto-loaded entry:

```
{% do craft.app.elements.eagerLoadElements(
    className(entry),
    [entry],
    ['pageContent']
) %}
```

Which correctly returns a flat array for entry.pageContent of all blocks. I then filter by level 1 when looping over them.

```
{% for block in entry.pageContent %}
  {% do block.useMemoized(entry.pageContent) %}
{% endfor %}

{% for block in entry.pageContent if block.level == 1 %}
  <p>Type: {{ block.type }} </p>
  <p>Level: {{ block.level }} </p>
  <p>Children {{ block.children }}</p>
{% endfor %}
```

But `block.children` is still a BlockQuery. Based on https://github.com/spicywebau/craft-neo/blob/master/docs/eager-loading.md#with-hierarchy I was expecting block.children to be an array.

Am I misunderstanding? If so, what is the syntax for getting a block's eager-loaded children?

**Comment by nickdunn** [comment]
Something like:

```
        {% for block in entry.pageContent if block.level == 1 %}
          {% include 'shared/blocks/_' ~ block.type with {
            children: entry.pageContent|filter(child => child.parent.id ?? null == block.id)
          } %}
        {% endfor %}
```

**Comment by ttempleton** [comment]
Firstly, to answer the original question, it looks like `entry.neoField` hadn't been eager loaded prior to the loops, otherwise it'd be an array of blocks and calling `find()` would cause an error. The eager loading of Neo content should happen before the `useMemoized()` loop.

@nickdunn: Looks like there was a small part of that document we missed when updating it for Craft 3, so I've just fixed that. It's correct that `block.children` is a `BlockQuery`, and getting the eager loaded child blocks is just a matter of calling `block.children.all()`.

**Comment by nickdunn** [comment]
Boom, this solved it for me. Thanks!
