### ISSUE TITLE
Has anyone got Neo working with the ElementAPI plugin?

### ISSUE THREAD

**Issue by shealan** [spicywebau/craft-neo#105]
Would love to spit out the Neo fields as pure JSON to consume as an api. Has anyone ever managed to achieve this?

**Comment by rrazong** [comment]
Any success on this?  I'd like to do the same.

**Comment by rhoffmann** [comment]
I experimented a little bit with it and got it working. Basically you need to save your whole Neo entity structure for the field and use it later with different filters. The nested content structure is:

```
provider:
  products: Neo
     destinations: Neo
        amounts: Matrix
```

I also used the `Chain` class to make JSON creation feel a little bit more functional.

But it feels there needs to be an easier approach.

https://gist.github.com/rhoffmann/7b65d65fb685fefe98ceaaada4e57595

**Comment by nfq** [comment]
What happened to the Gist above?

**Comment by corneliusio** [comment]
Just happened to come across and thought I'd share our solution as we do this on many of our projects.

```php
<?php

use benf\neo\elements\Block;

return [
    'endpoints' => [
        'api/neo-block/<id:\d+>' => function ($id) {
            return [
                'elementType' => Block::class,
                'one' => true,
                'criteria' => [
                    'id' => $id
                ],
                'transformer' => function (Block $block) {
                    return [
                        'id' => $block->id
                        // ...
                    ];
                }
            ];
        }
    ]
];
```

In my experience, pretty much anything that extends `craft\base\Element` can be consumed through the Element API plugin.
