### ISSUE TITLE
Querying for entries with empty Neo fields?

### ISSUE THREAD

**Issue by gregorterrill** [spicywebau/craft-neo#110]
This is probably a simple one, I just can't figure out the syntax. Is it possible to query for entries with a Neo field that has no child blocks? Here, eventDates is a Neo field which has one block type: Date. I'm trying to find three events that have no dates. This doesn't work:

`craft.entries.section('events').eventDates(':empty:').limit(3)`

By the way, the reason I'm using Neo instead of Matrix for such a simple case is so that the templates can be consistently shared between this and another Neo field, which has both Sessions and Dates (other event types can have multiple sessions, each of which may have one or more dates).

**Comment by ttempleton** [comment]
That would definitely be the correct syntax and appears to work correctly for me with Neo for Craft 3, but not on Craft 2 (where it finds no entries) so we'll file this as a bug.

**Comment by ttempleton** [comment]
This will be fixed in Neo 1.5.2 which will be released in the next couple of weeks (or you can grab the latest from the [`craft-2`](https://github.com/spicywebau/craft-neo/tree/craft-2) branch now).
