### ISSUE TITLE
Not translateable NEO field in multi locale website only shows latest added block and upon save deletes older blocks

### ISSUE THREAD

**Issue by jripmeester** [spicywebau/craft-neo#111]
I've installed NEO on my website (multi locale : NL, EN & DE) and created a list of possible blocks for a non translateable NEO field. The fields use in the blocks are translateable though.

I've created an entry with some blocks and saved the entry. Upon editing the entry and adding a new block to the NEO field. Everything is saved correctly. Except when i than again edit the entry the NEO field only show the last added block (the title bar of the block stays white and i can't add new blocks as well). When is save the entry the old blocks are deleted and only the last added block (the only one that was showing) is saved.

I've got this situation because i want the client to use the same blocks througout the different languages but only translate the content of the blocks.

This issue is fixed when i made the NEO field translateable as well. But then my client needs to add the blocks for every language.

**Comment by ttempleton** [comment]
Hi @jripmeester,

Not sure if you're still experiencing this issue at this point, or if the affected website continues to run Craft 2, but if so, I was wondering whether [Neo 1.5.1](https://github.com/spicywebau/craft-neo/releases/tag/1.5.1) (which includes some fixes for situations where blocks disappear) resolves the issue?

**Comment by ttempleton** [comment]
Closing this issue now, as we believe this issue report had the same cause as #128, which was resolved in Neo 1.5.1.
