### ISSUE TITLE
Block visibility per Section/EntryType

### ISSUE THREAD

**Issue by pgrzyb** [spicywebau/craft-neo#114]
Hi there, 

needless to say - love your plugin(s, reasons is super cool aswell)!
It could be something that fits Reasons a bit more, but:

Would it be possible to add some kind of a field (list of checkboxes?) in the block settings, that would allow hiding/showing that block depending on the Section or Entry Type that it was used in?
Use case: i have a single generic Neo field, called "Content" in which i have a bunch of different blocks, like Text, Image List, etc. I need to add another block that would only be available on a single Entry Type (in this case, it's an About Us page). If i could hide that block on other entry types, this would be super cool - instead i have to create a new Neo field, with the all the blocks in it duplicated and add that one extra block. If ill need to modify the Image List block in the future, ill have to do it in 2 places instead of 1.

**Comment by haavardb** [comment]
How did you end up solving this @pgrzyb ?

**Comment by pgrzyb** [comment]
Did it the manual way and I guess I will keep doing it untill @benjamminf finds time to tackle this ;) I understand that this is only an improvement for some edge case scenarios, and with the whole plugin porting to Craft 3 Soon™, I am not hoping for any focus on this :)

**Comment by aj-adl** [comment]
Would really love for this to be a feature - to me it's one of the few things that something like Spoon + Matrix has over Neo. 

Defining multiple Neo fields with 90% the same blocks is a frustrating thing as changes get introduced further on in the project lifecycle.

**Comment by jlachancekffein** [comment]
@pgrzyb can I ask you more precision on the manual way to handle it.

I remember use a chunk of code to manage this scenario but I cannot found it anymore.

Can you show me a example of code to manage block related to specific section.

Will be really appreciated.

Thanks

**Comment by Kethatril** [comment]
A quicker way to add this without having to build out a UI would be to provide an Craft PHP event that triggers when the block types are retrieved for display on an entry. This would allow the developer to filter the block types based on the fields parent entry.

**Comment by ttempleton** [comment]
Just released Neo 2.13.0, which includes the [`FilterBlockTypesEvent`](https://github.com/spicywebau/craft-neo/blob/2.13.0/docs/events.md#filterblocktypesevent) that was submitted in pull request #546 - thanks again @myleshyson for that!
