### ISSUE TITLE
Lightswitches don't work before saving once.

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#118]
It seems lightswtiches don't work before you save one time, and it seems to be the case whenever you add a block containing one or more lightswitches.

**Comment by knynkwl** [comment]
I am getting this issue as well.

**Comment by knynkwl** [comment]
Any movement on this?

**Comment by terryupton** [comment]
Any update on this all? Are we best to downgrade still?

**Comment by svenpeeters** [comment]
Update?

**Comment by terryupton** [comment]
Anyone managed to find a fix for this at all?

**Comment by ttempleton** [comment]
This has been fixed and will be included in Neo v1.5.1 (or you can grab the latest from the `craft-2` branch now).
