### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by stevepiron** [spicywebau/craft-neo#123]
Hi,

My project requires babel-polyfill (https://babeljs.io/docs/usage/polyfill/) and so does this plugin. This breaks the scripts execution when using live reload from the back-end. For example, images that are lazyloaded don't load anymore, which is a big problem.

**A suggestion to fix this is to use transform-runtime which polyfills the code without polluting globals:** https://babeljs.io/docs/plugins/transform-runtime

**Comment by ttempleton** [comment]
This will be resolved in Neo 2.8 with the removal of babel-polyfill.
