### ISSUE TITLE
Limit Neo entries

### ISSUE THREAD

**Issue by ghost** [spicywebau/craft-neo#124]
Hi there,

I'm trying to load some Neo matrix blocks on another page and limit the entries to 10 but I can't seem to get it working using .limit(10). 

Here's the code I'm using.
`{% for entry in craft.entries.section('projects') %}
	
	{% for block in entry.globalAgenda.level(1) %}
		
		{% switch block.type.handle %}
			
			{% case 'agendaDatum' %}
				{% if block.agendaDatum >= now %}	
					<table class="agenda_item">
						<tr>
							<td class="table_title performance-date table_col-2-3">{{ block.agendaDatum|date("d.m.Y") }}</th>
							<td class="table_title event-location table_col-1-3">{{ block.agendaLocatie }}</th>
						</tr>
						<tr>
							<td class="performance-title table_col-2-3"><a href="{{ entry.url }}">{{ entry.globalTitle }}</a></td>
							<td class="event-title table_col-1-3"><a target="_blank" href="{{ entry.agendaUrl }}">{{ block.agendaEvenement }}</a></td>
						</tr>
					</table>
				{% endif %}
		{% endswitch %}
		
	{% endfor %}
	
{% endfor %}`

How can I get this thing working?

**Comment by ttempleton** [comment]
There is currently no easy way to limit the returned Neo blocks across an entire section.  My best suggestion for anyone wanting to achieve this is to keep a counter variable of the number of blocks processed, do your for loops over the entries/blocks (*without* a limit parameter, unless you want to limit the number of entries), increment the counter for each block processed, and stop processing blocks once the counter reaches your desired block limit.
