### ISSUE TITLE
Possibility to set the minimum number of child blocks

### ISSUE THREAD

**Issue by terryupton** [spicywebau/craft-neo#125]
Perhaps a future feature enhancement but I am currently implementing a build where i'd like to set the minimum number of child blocks. I know this can be coded for in Twig but ideally i'd like to error trap this before in Craft.

**Comment by martijnluyckx** [comment]
I have the same request! It would be lovely to be able to set a minimum number of children. 

Specifically in my scenario: I have a layout with two CTA calls next to each other, both with the same layout: icon, title, text, button. In the Neo field, I would love the user to be able to select exactly two (can be done with min+max combo) "Icon Tile" blocks.

**Comment by ttempleton** [comment]
I've just added this in the [`enhancement/min-block-settings`](https://github.com/spicywebau/craft-neo/tree/enhancement/min-block-settings) branch, and it'll be included in Neo 3.3.

**Comment by ttempleton** [comment]
Just released Neo 3.3.0 including the min child blocks block type setting.
