### ISSUE TITLE
We miss Neo in Craft 3

### ISSUE THREAD

**Issue by waswebb** [spicywebau/craft-neo#131]
We need Neo for Craft!

**Comment by j-greig** [comment]
What about adding a nice big DONATE button on the Readme page?

I'm sure people would like to send a token of their appreciation your way...

eg https://gist.githubusercontent.com/skratchdot/6668394177f5444bab26/raw/9f9d541aec6ad8c00d7da3b6ce4624a47ec5325a/donate.md

**Comment by JayBox325** [comment]
Go join the big thread about Craft 3 discussion/need/desires here: #121

**Comment by ttempleton** [comment]
Not too long to go now 😃
