### ISSUE TITLE
Craft 3: Default value of Select and MultiSelect is not taken

### ISSUE THREAD

**Issue by vandres** [spicywebau/craft-neo#133]
Hi, found a probably small bug. The default value of Select and MultiSelect fields is not taken:

Definition: 
<img width="1180" alt="bildschirmfoto 2018-07-08 um 15 45 09" src="https://user-images.githubusercontent.com/1436383/42419893-fb0b7d8a-82c5-11e8-9f06-8bc84a7a26bc.png">

Working when used normally:

<img width="381" alt="bildschirmfoto 2018-07-08 um 15 43 11" src="https://user-images.githubusercontent.com/1436383/42419892-fae881d6-82c5-11e8-82c8-38bdac197f30.png">

Not working with Neos blocks:
<img width="543" alt="bildschirmfoto 2018-07-08 um 15 38 54" src="https://user-images.githubusercontent.com/1436383/42419891-fac5c150-82c5-11e8-95d8-8a9177b778f1.png">

**Comment by ttempleton** [comment]
Thanks for reporting this -- it has now been fixed.

**Comment by vandres** [comment]
Thanks man!
