### ISSUE TITLE
400 and stack trace on collapsing or expanding Neo section

### ISSUE THREAD

**Issue by narration-sd** [spicywebau/craft-neo#136]
By and large, Neo dev-3 has been working well in not-too-demanding development - thanks, Ben.

However, today I collapsed a section -- and got a 400 on your intent to save information, though the CP went  ahead and collapsed it. 

Experimenting, expanding acts the same:  CP action ok, but the section came back. I don't know what might  change in the data that you're pulsed/pulsing about...

Here's an example trace. No trace is showing; CP appears and acts normally. I took this from the log. Craft is on dev-develop.

2018-08-21 18:28:23 [192.168.10.1][1][-][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Request missing required param in /home/vagrant/koty-ou_html/vendor/craftcms/cms/src/web/Request.php:758
Stack trace:
#0 /home/vagrant/koty-ou_html/vendor/benjamminf/craft-neo/src/controllers/Input.php(67): craft\web\Request->getRequiredParam('locale')
#1 [internal function]: benf\neo\controllers\Input->actionSaveExpansion()
#2 /home/vagrant/koty-ou_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/vagrant/koty-ou_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/vagrant/koty-ou_html/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-expansion', Array)
#5 /home/vagrant/koty-ou_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-expansion', Array)
#6 /home/vagrant/koty-ou_html/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('neo/input/save-...', Array)
#7 /home/vagrant/koty-ou_html/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('neo/input/save-...', Array)
#8 /home/vagrant/koty-ou_html/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /home/vagrant/koty-ou_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /home/vagrant/koty-ou_html/web/index.php(21): yii\base\Application->run()
#11 {main}
2018-08-21 18:28:23 [192.168.10.1][1][-][info][application] $_GET = [
    'p' => 'admin/actions/neo/input/save-expansion'
]

**Comment by ttempleton** [comment]
Thanks for reporting this!  I believe that this should be fixed now.  Please let us know if you continue to experience errors with expanding/collapsing blocks.
