### ISSUE TITLE
Craft 3 / Undefined in block topbar

### ISSUE THREAD

**Issue by H-i-red** [spicywebau/craft-neo#139]
Found a 🐛 . Upon save the preview for the blocks is lost, returning undefined in `.preview-section`. When I expand/collapse the block it´s shown..

**Comment by ttempleton** [comment]
Are you seeing this issue on blocks with a color field?  I have reproduced the issue for that field type (but the previews for the other fields in the block were still working on page load).

If not, can you please let me know whether you're experiencing this issue just for certain blocks or for all blocks and, if just for certain blocks, what field types those blocks use?

**Comment by H-i-red** [comment]
Hi man ! It seems to only affect the `assets`(Images) field, and the `color` field, everything else seems to work just fine!

**Comment by H-i-red** [comment]
It also happens upon `copy/paste` other block.

**Comment by ttempleton** [comment]
Thanks!  The color and asset previews should now work properly on page load and when copying/pasting blocks.

**Comment by H-i-red** [comment]
👍 it works !
