### ISSUE TITLE
Migration from Craft 2 to Craft 3 

### ISSUE THREAD

**Issue by Osze** [spicywebau/craft-neo#141]
I know NEO for Craft 3 is not 100% done yet but I just had to try to migrate a site from Craft 2 to Craft 3. 

Ran into this issue when migrating NEO. Maybe it helps:

------------
Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_db.craft_neoBlocks' doesn't exist
The SQL being executed was: SELECT id, collapsed
FROM craft_neoBlocks

Migration: benf\neo\migrations\m181022_123749_craft3_upgrade
-----------

On line 40 - 

->from(['{{%neoBlocks}}'])

When changing this to ->from(['{{%neoblocks}}']) it all goes through. Looks ok!

**Comment by ttempleton** [comment]
Oops... not sure how that happened, sorry about that!  Thanks for reporting it!
