### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by theskyfloor** [spicywebau/craft-neo#145]
Hey y'all... this is prob not a great place for this question but I don't know where else to ask it. Now that Neo is released and paid is there a roadmap for feature improvements?  Or is it in more of a maintenance and bug fix mode? Thanks! So happy it's finally on 3 👍

**Comment by tonysambell** [comment]
Thanks @theskyfloor, as we just released NEO on Craft 3 we will initially be focused on bug fixes but as time goes on we plan to add features and improvements also.
