### ISSUE TITLE
Neo Field Causing Error

### ISSUE THREAD

**Issue by 3dgroup** [spicywebau/craft-neo#148]
Existing content will not resave after adding a Neo Field. Also saving new entry gives the following mySQL error:

SQLSTATE[42803]: Grouping error: 7 ERROR: column "elements.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "elements"."id", "elements"."fieldLayoutId", "element...

**Comment by 23d1** [comment]
Yeah, I can't even edit and entry or global set that has a neo field (either empty or not). Getting the grouping error among other SQL related errors.

**Comment by ttempleton** [comment]
Sorry about this.  The issue should be fixed in v2.0.1 but please let us know if you're still getting errors.
