### ISSUE TITLE
Neo 1.4.1 release feed 404 error

### ISSUE THREAD

**Issue by BaReinhard** [spicywebau/craft-neo#153]
Client Side Error is caused due to 
```
public function getReleaseFeedUrl()
	{
		return 'https://raw.githubusercontent.com/benjamminf/craft-neo/master/releases.json';
	}
```

The above url returns a 404 as there is no longer a craft-neo repo for benjamminf

**Comment by ttempleton** [comment]
We'll make sure that this is adjusted to the new feed location in the next release of Neo for Craft 2 (though the next release is likely to be the final release, but even in that case we can at least fix the 404)
