### ISSUE TITLE
Automatically collapse Neo fields

### ISSUE THREAD

**Issue by trangiiieee** [spicywebau/craft-neo#155]
Hi there!

Thanks for making this great plugin!

I have a question for v1.4.1. Is there a way I can inject some javascript into CraftCMS to make all neo fields automatically collapse by default every time I go to an entry? I'm hoping for a solution that is similar to this one: https://craftcms.stackexchange.com/questions/10198/possible-have-matrix-rows-collapsed-by-default-in-the-control-panel#answer-10209

Thank you!

**Comment by ttempleton** [comment]
Hi @trangiiieee,

Thank you for using Neo 👍

All Neo blocks for an entry can be collapsed by running the following script after the blocks have been rendered:

```javascript
$('.ni_block.is-expanded').each(function() {
    $(this).find('.ni_block_topbar').trigger('dblclick');
});
```

There may be some brief performance issues if an entry has many Neo blocks, as each block's collapse animation would occur at the same time, but once that has completed, performance should return to normal.

The script could then be used in a plugin, in the same way as the example Matrix-collapsing plugin from the Stack Exchange link, but using the following in the `init()` method within the `craft()->request->isCpRequest()` check:

```php
craft()->templates->includeJs('$(document).ready(function(){$(".ni_block.is-expanded").each(function(){$(this).find(".ni_block_topbar").trigger("dblclick");});});');
```

Hope that helps!  And if there are any issues, let us know.
