### ISSUE TITLE
Block Types handle should not update dynamically once field has been saved

### ISSUE THREAD

**Issue by robmcfadden** [spicywebau/craft-neo#157]
When you create a Block Type in Neo, the field handle generates dynamically based on the Name you give your Block Type. If you come back to edit this field later, and change the Title of a Block Type, the handle should not change, unless you do so explicitly.

Not a major issue, but I could see it breaking someone's template who wasn't paying attention.

Thanks!

**Comment by ttempleton** [comment]
Thanks @robmcfadden -- we'll make sure this is fixed in the next releases of Neo for Craft 3 and Craft 2.
