### ISSUE TITLE
Live Preview of drafts does not display Neo fields

### ISSUE THREAD

**Issue by kotyy** [spicywebau/craft-neo#158]
When viewing a draft of an entry, if you enter Live Preview mode, the Neo field is not rendered.

I've confirmed the issue on two different installations of Craft 3 Pro with Neo.

Steps to reproduce:
1) Create or duplicate an entry that has a Neo field. 
2) Enter Live Preview mode.
3) Observe that changes to the Neo field are reflected in the Live Preview.
4) Save as a draft.
5) Enter Live Preview mode again, while viewing the draft.
6) Observe that the Neo field is not rendered, changes made to it are not rendered, and that changes to other fields are rendered.

Originally noticed on:
Craft Pro 3.0.29 / Neo 2.0.1
Still occurs on:
Craft Pro 3.0.32 / Neo 2.0.2

**Comment by ttempleton** [comment]
Hi @kotyy,

Thanks for the report, but unfortunately I've been unable to reproduce it thus far.  We have just released v2.0.3 which fixes another issue with drafts; can you please confirm whether you experience this issue with the new release?

Also, do you experience any issues with Neo fields not rendering when viewing live preview of entry revisions?

**Comment by kotyy** [comment]
@ttempleton 

Thanks for your response. There was no issue with entry revisions. I've updated to 2.0.4 and it's working fine now, thanks!
