### ISSUE TITLE
Saving drafts moves nested blocks to top level

### ISSUE THREAD

**Issue by kotyy** [spicywebau/craft-neo#162]
Steps to reproduce:
1. Create a Neo field that has a block (Accordion) with child blocks (Accordion Item). (see screenshots)
2. Create an entry, add an Accordion, add one or more Accordion items. Save the page.
3. Observe that the page is correctly rendered.
4. Modify that entry's content, then save as a draft.
5. The content is not rendered, because the Accordion Items are now at the same level as the Accordion itself.

I've confirmed this occurs in 2.0.4 on two different Craft 3 installs.

![screen shot 5](https://user-images.githubusercontent.com/343253/49180274-cfc00500-f319-11e8-9977-dfd9c1aa6eec.png)
![screen shot 6](https://user-images.githubusercontent.com/343253/49180273-cfc00500-f319-11e8-9a01-8969b8ca2ffd.png)

**Comment by ttempleton** [comment]
This issue has been fixed and will be included in Neo v2.1.0, which will be released over the weekend.
