### ISSUE TITLE
Failed "Deleting stale template caches"

### ISSUE THREAD

**Issue by leigeber** [spicywebau/craft-neo#166]
Hello, getting the following error in the "Deleting stale template caches" queue after any entry change.

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous
The SQL being executed was: SELECT `elements`.`id`, `id`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_neoblocks` `neoblocks` ON `neoblocks`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`
LEFT JOIN `craft_structureelements` `structureelements` ON `structureelements`.`elementId` = `elements`.`id`
WHERE (`neoblocks`.`fieldId`='105') AND (`neoblocks`.`ownerId`='5328') AND (`elements_sites`.`siteId`=1) AND (`content`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND ((`structureelements`.`lft` > '2') AND (`structureelements`.`rgt` < '9') AND (`structureelements`.`root`='47476')) AND (`structureelements`.`level` <= 2)
ORDER BY `structureelements`.`lft`, `elements`.`dateCreated` DESC) `subquery`
INNER JOIN `craft_neoblocks` `neoblocks` ON `neoblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `craft_structureelements` `structureelements` ON `structureelements`.`elementId` = `subquery`.`elementsId`
ORDER BY `structureelements`.`lft`, `elements`.`dateCreated` DESC
```

It appears the 2nd id in the query needs to be qualified with a table name - or if it's referring to the element ID, it's not necessary at all since Craft automatically includes it. Looks like it's coming from: https://github.com/spicywebau/craft-neo/blob/master/src/elements/db/BlockQuery.php#L224

**Comment by ttempleton** [comment]
Hi @leigeber,

I'm having some trouble reproducing this so far.  There shouldn't be a problem with line 224 of BlockQuery.php, though; that just helps set the block type ID for a block query, and should only ever generate something like this:

```sql
SELECT `id`
FROM `craft_neoblocktypes`
WHERE `handle`='media'
```

I'll continue to investigate, but in the meantime, can you please confirm the following:
- This is happening for any entry with a Neo field, regardless of section? (and not happening with any entry that does not have a Neo field?)
- Craft version?

**Comment by leigeber** [comment]
Thanks for looking, I had originally emailed Craft support and they pointed to that bit of code but may not have dug too far. I can confirm it only happens on entries with Neo. Craft version is 3.0.33.

**Comment by ttempleton** [comment]
Are you able to view a page for a newly-created entry with a Neo field without any issues?  Just want to confirm that the problem is only affecting the deletion of old caches and not the creation of new ones.

**Comment by leigeber** [comment]
Yes, everything seems to work as it should other than the template cache busting failing. I did confirm that if I prefix the 'id' selection in BlockQuery.php on 224 with the table names that the issue is resolved. There's a lot going on behind the scenes I didn't look at but the little bit I saw in the craft caches table in that serialized base64 encoded column seems to indicate that if an 'id' column is used in the selection unprefixed it will be used as such in the cache clearing query but at that point its joined causing the id conflict.

**Comment by ttempleton** [comment]
Thanks for your help with this.  We've made some changes to lines 224-226 in line with what is fixing the problem for you.  I'll keep this issue open and the updated code in the `dev-neo-2` branch for now; can you please confirm whether the updated code resolves the problem, and then we'll release it.

**Comment by leigeber** [comment]
Confirmed

**Comment by leigeber** [comment]
@ttempleton It looks like something related back in play now. Getting this on the latest release.

```php
2019-03-20 14:56:34 [-][33][-][info][craft\queue\QueueLogBehavior::beforeExec]  [2897] Deleting stale template caches (attempt: 1) - Started
2019-03-20 14:56:34 [-][33][-][error][craft\queue\QueueLogBehavior::afterError]  [2897] Deleting stale template caches (attempt: 1) - Error (time: 0.506s): SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference "id" is ambiguous
LINE 1: SELECT "elements"."id", "id"
                                ^
The SQL being executed was: SELECT "elements"."id", "id"
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "craft_elements" "elements"
INNER JOIN "craft_neoblocks" "neoblocks" ON "neoblocks"."id" = "elements"."id"
INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "craft_content" "content" ON "content"."elementId" = "elements"."id"
INNER JOIN "craft_structureelements" "structureelements" ON ("structureelements"."elementId" = "elements"."id") AND ("structureelements"."structureId"=458)
WHERE ("neoblocks"."fieldId"=187) AND ("neoblocks"."ownerId"=25758) AND ("elements_sites"."siteId"=1) AND ("content"."siteId"=1) AND ("elements"."archived"=FALSE) AND ("elements"."dateDeleted" IS NULL) AND (("structureelements"."lft" > 2) AND ("structureelements"."rgt" < 9) AND ("structureelements"."root"=7235)) AND ("structureelements"."level" <= 2)
ORDER BY "structureelements"."lft", "elements"."dateCreated" DESC) "subquery"
INNER JOIN "craft_neoblocks" "neoblocks" ON "neoblocks"."id" = "subquery"."elementsId"
INNER JOIN "craft_elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "craft_content" "content" ON "content"."id" = "subquery"."contentId"
INNER JOIN "craft_structureelements" "structureelements" ON ("structureelements"."elementId" = "subquery"."elementsId") AND ("structureelements"."structureId"=458)
ORDER BY "structureelements"."lft", "elements"."dateCreated" DESC
```

**Comment by leigeber** [comment]
Just checking in on this as we've hit it in another project now as well. If you think it may be awhile are you open to a pull request if we can track this down on our end?

**Comment by pvldigital** [comment]
Hi @leigeber, I'll look into this issue some time next week. However you're free to have a look at it yourself and submit a pull request down the track.

**Comment by ttempleton** [comment]
I'm going to close this due to inactivity, and due to changes in Craft 3.5 to how template caching works, which might have resolved this issue if it hadn't already been resolved.  If the issue does persist with Craft 3.5 and Neo 2.8, though, please let us know and we'll reopen.
