### ISSUE TITLE
Multisite - list of elements in Entry/Category field within new Neo blocks always pulls in elements from the primary site

### ISSUE THREAD

**Issue by i-just** [spicywebau/craft-neo#168]
With multiple sites on one Craft installation, when including an Entry/Category selector field in a Neo block, the entries/categories available for selection are the ones from the primary site and not the site currently being edited. If I then save the block, the selected entries are not saved (but the block is) and after that if I try to select an entry again, the list will be from the correct site.

Using Craft 3.0.34; Neo 2.1.0

Steps to reproduce:
- Craft 3 with at least 2 sites set up with some content in each site
- create "Entry" or "Category" type field
- create "Neo" field with a block which pulls in that entry/category field
- assign the neo field to a section
- edit an entry for that section for a non-primary site => the list of entries to choose from is the list of entries/categories from the primary site and not the one currently being edited

Please let me know if any more info is needed.

**Comment by ttempleton** [comment]
Thanks for reporting this @i-just; I can confirm that I can reproduce it.  We'll look into it and have it fixed as soon as possible.

**Comment by naboo** [comment]
Is there an update on this issue @ttempleton? Makes editing multi-sites quite hard for now :)

**Comment by ttempleton** [comment]
@naboo Sorry for the inconvenience with this issue; this has turned out to be a tricky one to fix.  We have definitely not forgotten about it, though, and will continue to investigate why it is happening.

**Comment by naboo** [comment]
> 
> 
> @naboo Sorry for the inconvenience with this issue; this has turned out to be a tricky one to fix. We have definitely not forgotten about it, though, and will continue to investigate why it is happening.

Since it works after the entry has been saved there must be some instance in which the siteId isn't sent with. Would you like some help investigating? If you point me into the right direction(files) I can dig around a little and see. This issue feels pretty crucial to get sorted as authors can't use "Entries" fields at all in multi-site setups (even if its just for two different language versions).

**Comment by ttempleton** [comment]
Thanks, the offer to help investigate is much appreciated -- but we have now identified and fixed the areas where `siteId` was not being set for new/pasted/cloned blocks.  These fixes have been included in Neo v2.1.4.
