### ISSUE TITLE
Craft 3.1 Project Config compatibility

### ISSUE THREAD

**Issue by pablofernandezgh** [spicywebau/craft-neo#169]
When creating a Neo field in Craft 3.1, this gets written in `project.yaml`

`a3fab66a-fed6-4fbd-8a5c-2cdd24e9e51f:

    contentColumnType: string

    fieldGroup: ec5bf6bc-0fc3-454a-bde8-7e4dca8afa51

    handle: testNeoField

    instructions: ''

    name: 'Test neo field'

    searchable: true

    settings:

    localizeBlocks: ''

    maxBlocks: ''

    minBlocks: ''

    translationKeyFormat: null

    translationMethod: site

    type: benf\neo\Field`

When synchronizing the database on another server, the field will be created, but not the blocks and sub blocks inside of this field

Craft version : 3.1.0-beta.4

**Comment by vanpet** [comment]
Same question! It would be really great to make this work with the new Project Config feature to sync the db to the code!

**Comment by N0ps32** [comment]
Hey, do you have an ETA for 2.3? We're starting a very big project with neo just now and I'm trying to judge if it makes sense to write migrations instead of relying on project.yaml.

**Comment by ttempleton** [comment]
@N0ps32 Project config support will now be included in Neo 2.2, which should be released by the end of the week.

**Comment by N0ps32** [comment]
@ttempleton awesome, thank you very much!

**Comment by 23d1** [comment]
Bump; is end of week today or this weekend? 😜

**Comment by ttempleton** [comment]
@23d1 Definitely out by the end of the weekend 😄 Just need to make some updates for compatibility with the new soft-delete functionality, to make sure that blocks get restored in the same order/hierarchy if the owner element is restored, and then it should be ready to go.

**Comment by ttempleton** [comment]
Neo 2.2.0 is out now with project config support.

**Comment by jesuismaxime** [comment]
Nice to know: You will need to resave your Neo field(s) to force the blocks to appear in the project.yaml
