### ISSUE TITLE
Getting unknown property: craft\elements\Entry::duplicateOf

### ISSUE THREAD

**Issue by outline4** [spicywebau/craft-neo#177]
Hi, 
It's the first time I use Neo and it's not working at all. 

I've created a big neo field with all sorts of fields attached to improve my matrix setup. I couldn't save the entry. So I've deleted the neo field and created a new neo matrix with just one field in it (a plain text field), but It still get's stuck with the following error message: 

Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: craft\elements\Entry::duplicateOf

Do you know what could be triggering this? 

I've deleted caches and created a new section just for testing purpose. 

PHP version 7.2.14
Craft Pro 3.0.20
Neo 2.1.4

Tell me which other infos could be valuable to you. 

Any help highly appreciated! 
Stefan

**Comment by ttempleton** [comment]
Hi @outline4,

Sorry about this; Neo 2.1.4 was released with an incorrect Craft version requirement and Craft will need to be updated to 3.0.31 or newer -- see #176 for details.
