### ISSUE TITLE
Craft 3 Clone/Copy+Paste Blocks Hangs

### ISSUE THREAD

**Issue by kellyannmcnamara01** [spicywebau/craft-neo#178]
**Problem:**
When trying to clone or copy+paste a neo block the page just hangs. In my console, I am getting a 500 error. (We have tried this on two of our Craft 3 websites)

**Errors Returning:**
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
`Uncaught TypeError: Cannot read property 'success' of null
    at main.js?v=1548088701:13
    at Object.error (Craft.js:361)
    at c (jquery.js:3317)
    at Object.fireWith [as rejectWith] (jquery.js:3447)
    at l (jquery.js:9274)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)`

**Network Returns:**
`Request URL: .../index.php/admin/actions/neo/input/render-blocks
Request Method: POST
Status Code: 500 Internal Server Error`

**Craft Verisons:** 3.1.3 and 3.1.2.2
**Neo Verison:** 2.1.5

**Ideal Outcome:**
I would like to clone or copy+paste blocks. I used this feature a lot in Craft 2, and absolutely loved it.

**Comment by ttempleton** [comment]
Thanks for reporting this, @kellyannmcnamara01 -- looks like part of a recent fix for an issue involving pasting/cloning blocks on multi-site Craft installations did not properly account for single-site installations.  We'll have release 2.1.6 out shortly.
