### ISSUE TITLE
Duplicating entries with Neo fields doesn't copy field content

### ISSUE THREAD

**Issue by boboldehampsink** [spicywebau/craft-neo#179]
#### Description

Duplicating entries with Neo fields doesn't copy Neo field content.

#### Steps to reproduce
1. Create entry with neo field
2. Add blocks
3. Duplicate entry
4. Blocks are lost in the duplicated entry

#### Other information
- Neo version: 2.1.6
- Craft version: 3.0.37
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: -

**Comment by ttempleton** [comment]
Thanks for reporting this, @boboldehampsink -- turns out the new blocks were being created, but the new block structure wasn't being created properly due to using the incorrect set of block IDs.  Fixed now in 2.1.7.

**Comment by boboldehampsink** [comment]
Thanks!

**Comment by naboo** [comment]
@ttempleton I have a site in which the "Duplicate" function was applied to entry with Neo 2.1.4 causing Neo to render (and save) ~250 blocks for the entry making it unable to browse in Craft (it just keeps looping until the browser freezes). Can I somehow fix this entry in the database to make it "work" again? I can edit tables manually if you tell me how to do it.

Thank you

**Comment by naboo** [comment]
For anyone finding this issue running Neo pre. 2.1.7 and have clients which have used the "Duplicate" function and got their entry destroyed. Updating to the latest version will fix the entry so it can be re-saved.
