### ISSUE TITLE
MySQL error on newly created Neo fields

### ISSUE THREAD

**Issue by kringkaste** [spicywebau/craft-neo#184]
#### Description
When saving an entry with a newly created neo field, an MySQL error occurs:

```
SELECT `id`
FROM `craft_neoblocks`
WHERE (ownerId = :ownerId) AND (fieldId = :fieldId) AND (`id` NOT IN ()). Bound with :ownerId='1407460', :fieldId='544'
```

thrown by NeoService.php line 142.

Existing neo fields are working fine. Only new created fields have this issue.

#### Steps to reproduce
1. Create a new, simple neo field (one block, with one field in the field set).
2. Add the newly created neo field to the field set of a channel section.
3. Edit an entry in the section and add a block and content to the neo field.
4. Save the entry.

#### Other information
- Neo version: 1.4.1
- Craft version: 2.7.4
- Is the affected Craft installation multi-site: no

**Comment by ttempleton** [comment]
Thanks for reporting this, @kringkaste.  This is a strange issue and unfortunately I've been unable to reproduce it so far.  Which versions of PHP and MySQL are you using?

**Comment by kringkaste** [comment]
Hey @ttempleton! We tried to reproduce the error, but we couldn't do it either. Maybe it was a combination of different effects. Thanks for your support!
