### ISSUE TITLE
How copy an entry's neo field value across non-propagated site channels?

### ISSUE THREAD

**Issue by naboo** [spicywebau/craft-neo#185]
#### Description
I have a multi-site in which my channel is set to not propagate entries across sites. I now want to copy an entry from Site A to Site B (no relation, just the same function as "Save as a new entry" but into another site). The channel has the same setup in both sites.

So for regular entries with basic fields there's no issue. `Craft::$app->getElements()->duplicateElement();` does the heavy lifting. I can later update the `siteId` for the entry and set the entry field values using `$entry->setFieldValues($sourceEntry->getFieldValues());`. This of course works for simple fields - it doesn't work for Neo.

What do I need to do in order to get Neo to work? I've noticed in the Neo field array there's the `ownerId` and `ownerSiteId` properties which I guess needs to be updated. But how do I do this on the BlockQuery object? I can't seem to figure it out. Is that enough or does Neo need something else to happen in order to duplicate the content to a new entry (in another site)?

Thank you

#### Other information
- Neo version: 2.1.9
- Craft version: 3.0.39
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes

**Comment by ttempleton** [comment]
Hi @naboo,

Once you have the BlockQuery set up to find the Neo field's blocks from the old entry that you want to copy to the new entry, the blocks can also be copied using `Craft::$app->getElements()->duplicateElement()`:

```php
$duplicatedBlocks = [];

foreach ($blockQuery->all() as $block) {
    $duplicatedBlock = Craft::$app->getElements()->duplicateElement($block, [
        'ownerId' => $entry->id,
        'ownerSiteId' => $entry->siteId,
        'siteId' => $entry->siteId,
        'propagating' => false,
    ]);

    // This is only necessary if you want to copy the block's collapsed state too
    $duplicatedBlock->setCollapsed($block->getCollapsed());
    $duplicatedBlock->cacheCollapsed();

    $duplicatedBlocks[] = $duplicatedBlock;
}
```

Then, a new block structure will need to be created for the `$duplicatedBlocks`, which might look something like this:

```php
$neo = Craft::$app->getPlugins()->getPlugin('neo');

if (!empty($duplicatedBlocks)) {
    $blockStructure = new \benf\neo\models\BlockStructure();
    $blockStructure->fieldId = $field->id;
    $blockStructure->ownerId = $entry->id;
    $blockStructure->ownerSiteId = $entry->siteId;

    $neo->blocks->saveStructure($blockStructure);
    $neo->blocks->buildStructure($duplicatedBlocks, $blockStructure);
}
```

Hope that helps!

**Comment by naboo** [comment]
Thank you @ttempleton. I'll continue with this approach. 👍
