### ISSUE TITLE
Neo field doesn't save settings/layout changes after initial save

### ISSUE THREAD

**Issue by mdominguez** [spicywebau/craft-neo#188]
#### Description
When creating a new Neo field, on initial save all of the settings are saved correctly. But when I re-edit the field and make some changes, they don't get applied on save.

#### Steps to reproduce
1. Create neo field with multi level blocks and limits
2. Save it
3. Try to edit the settings/layout of the field and save, the changes are not applied.

#### Other information
- Neo version: 2.2.3
- Craft version: 3.1.9.1
- Is the affected Craft installation multi-site: Nope
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by leigeber** [comment]
Same end result here, can't update a particular Neo field anymore. In my case I was able to edit the field many times in different ways but then after trying to reorder some groups and types I can no longer make any changes stick. Hard to say what triggered it exactly. No errors anywhere, just silently failing.

**Comment by mdominguez** [comment]
Yes indeed, probably triggered after reordering or multi-level editing groups / block types

**Comment by simeon-uxiliary** [comment]
I'm having the same issue with the same version.

**Comment by zachshallbetter** [comment]
Very serious issue. We have an extremely large client entering content into a production site and we're unable to backtrack or modify existing fields.

**Comment by ttempleton** [comment]
Thanks for reporting, everyone.  This is due to a bug in Craft which will be fixed in the next release -- see craftcms/cms#3832
