### ISSUE TITLE
Deactivated blocks disappear

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#190]
I have experienced this a couple of time now: When deactivating some blocks and saving the page, the deactivated blocks disappear. I am not sure whether they still exist in the database, however, on the CP they are missing.

#### Other information
- Neo version: 2.2.4
- Craft version: Craft Pro 3.1.12
- Is the affected Craft installation multi-site: no

**Comment by Sam-Black-0013** [comment]
I am having the same issue as well

**Comment by ttempleton** [comment]
Thanks @luke-nehemedia and @Sam-Black-0013.  This is fixed in Neo 2.2.5.

**Comment by Sam-Black-0013** [comment]
Thank you very much @ttempleton for the fix ^^
