### ISSUE TITLE
Copy/Paste break Neo field

### ISSUE THREAD

**Issue by outline4** [spicywebau/craft-neo#193]
#### Description

The Copy/Paste Function does not really work in my case. Sometimes when I copy/paste a block it'll break the neo field.

#### Steps to reproduce

1. I choose a block within a block within a block and copy it (first is the layout block, then the column left block, then a content block)
2. when I paste it into a layout block, the blocks get rearranged. like there will be no more layout blocks, only the content blocks within one layout block. It's the same feeling I get when I forget to close a div in a html layout. it's all mixed up, and I have to rebuild the page. 

What I wanted from you is documentation on how exactly what is possible with copy paste?  

Can I paste into a different hierarchy?   
Can I copy content that has children?   
Which field types will work?   

#### Other information
- Neo version: 2.2.5
- Craft version: Craft Pro 3.1.14
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: no

**Comment by ttempleton** [comment]
Hi @outline4,

A copied block can be pasted anywhere within its field that allows that particular block type to exist -- it doesn't have to be within the exact same area in the field's hierarchy unless that's the only place that block type is allowed.  If the copied block isn't allowed in a certain place, the paste option should be disabled.

You can copy blocks that have children -- when Neo copies/pastes a block with descendants, all descendant blocks are copied and pasted with the ancestor block.

Copying and pasting should work with blocks with any field type.  From what I gather from your report, everything you're trying to do should definitely be possible, so I'm wondering if another plugin's field type is conflicting with Neo in some way here.  Do the affected blocks have any field types in common?  Also, does this issue occur with different browsers?

**Comment by dasunr** [comment]
Hi @outline4,

I have looked into this issue and I'm having some trouble reproducing this so far. Are you able to update Neo to the latest version and try again? I will close this issue for now and let me know if this issue happens again.
