### ISSUE TITLE
Unable to copy project config between installations because of neo fields

### ISSUE THREAD

**Issue by cholawo** [spicywebau/craft-neo#195]
#### Description
I was testing the ability to copy the project.yaml file between craft installations to imitate what would happen we deploying to a production environment.    I found that neo fields caused an error during the synchronize process when craft attempts to read an updated project.yaml file.

#### Steps to reproduce
1.  Create two identical craft installations, install neo on both.
1.  (in installation 1) Create a plain text field
2. (in installation 1) Create a neo field, create a block in it and then add the plain text field from step 1 to the field layout
3. Copy the contents of project.yaml from installation 1 to installation 2
4. Open the admin area of the installation 2 and press the "sync" button so it can read the project.yaml
5. See the following error:

```
Status: Internal Server Error

Response: {"error":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fieldId' cannot be null
The SQL being executed was: INSERT INTO neoblocktypes (fieldId, name, handle, sortOrder, maxBlocks, maxChildBlocks, childBlocks, topLevel, uid, fieldLayoutId, dateCreated, dateUpdated) VALUES (NULL, 'Neo Block Containing a Text Field', 'neoBlockContainingTextField', 1, 0, 0, '', 1, '777f1525-495b-4c21-b9af-b3a28720858d', 3, '2019-03-13 14:31:11', '2019-03-13 14:31:11')"}
```

#### Other information
(both craft installations have identical versions of)
- Neo version: 2.2.5 
- Craft version: 3.1.17.2
- Is the affected Craft installation multi-site: no
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by wedot** [comment]
Some problem here

**Comment by ttempleton** [comment]
Thanks for reporting.  This has been fixed in Neo 2.2.6.

**Comment by wedot** [comment]
I've tested to move all configs in project.yaml to a new site again. All blocks of the neo field were not imported in the new installation.

**Comment by ttempleton** [comment]
Hi @wedot, the issue described in the initial post has been resolved, but if you're experiencing issues with not all of the block types importing, you're welcome to submit it as a new issue.  If you do, any information about whether the non-imported block types use a common field or field type, or whether they're all from the same group (basically any info that could help us narrow down why the block types aren't importing) would be much appreciated.
