### ISSUE TITLE
Block permissions

### ISSUE THREAD

**Issue by samuelbirch** [spicywebau/craft-neo#196]
It would be great to be able to have permissions on block types, whether the user has the ability to create that block type or just edit it.

**Comment by mihob** [comment]
This would be an awesome feature!

**Comment by ttempleton** [comment]
I've added this in the [enhancement/block-type-permissions](https://github.com/spicywebau/craft-neo/tree/enhancement/block-type-permissions) branch, and it will likely be released some time next month.

**Comment by ttempleton** [comment]
Just released Neo 3.5.0 with block type create/edit/delete options added to user permissions.

**Comment by benoitblancquaert** [comment]
It would be an added value if block permissions could be turned on/off. The user permissions need to be updated after adding or editing Neo fields, which is quite annoying, especially if you have a large number of user groups.
