### ISSUE TITLE
Disable block types

### ISSUE THREAD

**Issue by samuelbirch** [spicywebau/craft-neo#197]
Is it possible to disable blocks, so that cp users cannot create them.

Existing blocks could ether be read only, edit only or hidden?

**Comment by ttempleton** [comment]
I've added this in the [`enhancement/disable-block-types`](https://github.com/spicywebau/craft-neo/tree/enhancement/disable-block-types) branch, and it'll be released in Neo 3.3.

**Comment by ttempleton** [comment]
Just released Neo 3.3.0 including the block type enabled setting.
