### ISSUE TITLE
Issue with project config and new fields added to new Neo block type

### ISSUE THREAD

**Issue by naboo** [spicywebau/craft-neo#199]
#### Description
When using project config to sync between multiple envs. sometime newly added fields doesn't get added to the Neo field in question. For example if you have a Neo field and you add a new block, and to that block you assign a newly created field from Craft. When you later sync your project config the block type gets added to the Neo field but the field isn't added to the same block type. The field is created in Craft though.

My guess is that Craft first runs the syncing of the changes to the Neo field and later down the order runs the creation of the new Craft field. So maybe this isn't something you can do anything about but I thought I'd start here and check before moving this over to P&T Github.

#### Steps to reproduce
1. Create new block type in Neo field
2. Assign newly created Craft field
3. Sync to new environment
4. The field is created but not added to the new Neo field block type

#### Other information
- Neo version: 2.2.6
- Craft version: 3.1.18
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes

**Comment by ttempleton** [comment]
Thanks @naboo, it is under Neo's control to force the fields to be synced before the block types, so that has been fixed in Neo 2.2.7.

**Comment by kayqq** [comment]
@ttempleton I'm seeing this issue with Neo 2.8.19 and Craft 3.5.17.1

**Comment by ttempleton** [comment]
@kayqq please confirm whether the issue occurs with the latest Craft release, and if so, please open a new issue.
