### ISSUE TITLE
Max blocks not synced correctly when using project.yml

### ISSUE THREAD

**Issue by jurriaanr** [spicywebau/craft-neo#202]
#### Description
I changed the max block on the top level of a neo block locally from 4 to 5. Synced that to the acceptance server. I now do have the option to add a fifth block, but when I do the other 4 blocks are removed and only that single block will remain. If I re-add the other 4 blocks, and save, only a total of 4 is saved. So one of the settings controlling the amount of blocks is not synced correctly

#### Steps to reproduce
1. Add neo block, with a max of x items
2. Sync to other server
3. Change max to x+1 items locally
4. Sync to other server
5. Add the extra block
6. Scream in horror

#### Other information
- Neo version:
2.3.0
- Craft version:
3.1.20.1
- Is the affected Craft installation multi-site:
Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
Yes

**Comment by jurriaanr** [comment]
The databases looks correct and lists 5 blocks

**Comment by dasunr** [comment]
Hi @jurriaanr, 

I'm having some trouble reproducing this so far. Are you able to update to the latest version and try again? 
I'll close the issue for now and if it still persists shall reopen.

**Comment by jurriaanr** [comment]
Yes, It is still a problem, updated to the last version of neoblocks, updated the max items to a higher number, it is not synced on other locations
