### ISSUE TITLE
Limit the nesting level

### ISSUE THREAD

**Issue by gallogiuseppe** [spicywebau/craft-neo#203]
Is it possible to limit the nesting level of children? I'm not saying to limit the number of blocks but the level that can be nested:

eg:

limit to 1 child level
Main block
-- child 1
-- child 2

limit to 2 children levels
Main block
-- child 1
---- child a
---- child b
-- child 2
---- child a
---- child a

**Comment by ttempleton** [comment]
A max level field setting will be added to Neo 2.9.

I'm not sure whether this feature request intended for the setting to be added to the field or the block type, but we've decided it would be better placed on the field: firstly, it's consistent with Craft's behaviour with structure sections (i.e. the entire structure has a single max level, not varying max nesting levels per entry); and secondly, having different nesting level limits per block type could lead to confusion over which limit should apply when a descendant block has its own nesting limit set, whereas with a field setting it's one clear limit that applies to the entire field.
