### ISSUE TITLE
Getting Error while sending QUERY packet errors when caching large sequence of Neo blocks

### ISSUE THREAD

**Issue by aaronbushnell** [spicywebau/craft-neo#204]
#### Description
One of our websites is receiving an error when it attempts to cache a page with a fair amount of Neo blocks. Here's the error:

```
PHP Warning – yii\base\ErrorException
Error while sending QUERY packet. PID=99343
```

When I looked through the logs it looks like Neo is sending a massive amount of data into `templatecachequeries` and a snippet of that action looks like this:

```
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'craft_templatecachequeries' AND kcu.table_name = 'craft_templatecachequeries'
2019-04-03 15:49:22 [-][1][][info][yii\db\Command::execute] INSERT INTO `craft_templatecachequeries` (`cacheId`, `type`, `query`) VALUES (4018285, 'benf\\neo\\elements\\Block', 'TzozMToiYmVuZlxuZW9cZWxlbWVudHNcZGJcQmxvY2tRdWVyeSI6Njg6e3M6NzoiZmllbGRJZCI7czoyOiI1MyI7czo3OiJvd25lcklkIjtzOjU6IjEyNzkyIjtzOjExOiJvd25lclNpdGVJZCI...
```

That garbled data is _very_ lengthy and I assume that amount of data is not possible to inject into the database without drastically sizing up `max_allowed_packet`.

Happy to pass along any additional information if it's useful!

#### Other information
- Neo version: 2.2.8
- Craft version: Craft Pro 3.1.20.1
- Is the affected Craft installation multi-site: Unsure
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by gregorterrill** [comment]
Also just ran into this issue pushing some updates to a staging site. Was working fine on dev where template caching is off, but on staging I was getting an internal server error on certain pages (though they worked fine in Live Preview mode or if I changed the .env environment to "dev").

Error log showed several errors like:

```
General error: 2006 MySQL server has gone away
```
and
```
Error while sending QUERY packet. PID=1765
```


MySQL `max_allowed_packet` was set to 16M, upped it to 32M and the problem went away.

Neo 2.3.5 and Craft 3.1.33.

**Comment by ttempleton** [comment]
I'm not sure what would've been happening to cause this error, but at this point I'm going to close this issue because the `templatecachequeries` table is no longer used as of Craft 3.5.  If there are any other Neo-related template caching errors happening with Craft 3.5, please feel free to open a new issue.
