### ISSUE TITLE
Help wanted Eager Loading 

### ISSUE THREAD

**Issue by meredevelopment** [spicywebau/craft-neo#205]
#### Description
I'm trying to understand how to reduce the DB lookups on a Neo field using Eager Loading. 

I have a Neo field called `componentsMatrix` and in my test page there are 18 Neo items, 5 at level 1, 13 at level 2:

```
{{ entry.componentsMatrix.count() }}  {# Shows "18" #}
```

Without loading the Neo field at all, the page makes 27 Queries (Q). 

With a call like this it's 28Q:
```
{% for block in entry.componentsMatrix.all() %}

{% endfor %}
```

If I attempt to pull the type handle out, like this it's now 51Q:
```
{% for block in entry.componentsMatrix.all() %}
	{{ dump(block.type.handle) }}
{% endfor %}
```

I now attempt to add the suggested `useMemoized` call like so it uses 70Q: 
```
{% for block in entry.componentsMatrix.all() %}
	{% do block.useMemoized(entry.componentsMatrix.all()) %}
{% endfor %}
{% for block in entry.componentsMatrix.all() %}
	{{ dump(block.type.handle) }}
{% endfor %}
```

If I omit the `.all()` on the useMemoized call, like so `{% do block.useMemoized(entry.componentsMatrix) %}` the count is 52Q. 

Can anyone help me understand which - if any - is the right way of using `useMemoized` and how I know that it's working? 

It seems to me that this query counts are very high if it is working. 

#### Steps to reproduce
N/a, theoretical question...

#### Other information
- Neo version: 2.3.0 (same issues/question with 2.2.8)
- Craft version: 3.1.21.1
- Is the affected Craft installation multi-site: No

**Comment by ttempleton** [comment]
The calls to `all()` will each execute a new query, so something like

```twig
{% for block in entry.componentsMatrix.all() %}
	{% do block.useMemoized(entry.componentsMatrix.all()) %}
{% endfor %}
```

is executing a query for all `componentsMatrix` blocks, for each block in `componentsMatrix`.  Furthermore, the memoized data is effectively lost after the loop completes execution -- the `entry.componentsMatrix.all()` being looped over won't exist afterwards.  The blocks should be set to a variable beforehand:

```twig
{% set neoBlocks = entry.componentsMatrix.all() %}
{% for block in neoBlocks %}
	{% do block.useMemoized(neoBlocks) %}
{% endfor %}
{% for block in neoBlocks %}
	{{ dump(block.type.handle) }}
{% endfor %}
```
