### ISSUE TITLE
Issues with saving entries after updating neo plugin

### ISSUE THREAD

**Issue by nmcweb** [spicywebau/craft-neo#206]
#### Description
Whenever I try to update an entry, sometimes the entry returns an Internal Server error message, and won't commit the change. 

#### Steps to reproduce
1. Choose an existing entry (page, or custom entry in this case, event calendar event)
2. Save the entry.
3. Attempt steps 1 - 2 on a few entries. Does not occur on all but some
4. Observe web.log via tail

Below is the reported exception:
<img width="1280" alt="Screen Shot 2019-04-05 at 4 12 31 PM" src="https://user-images.githubusercontent.com/49325186/55660475-bea16c00-57c3-11e9-8497-1d7b8426ce06.png">

#### Other information
- Neo version: 2.3.0
- Craft version: 3.1.21.1
- Is the affected Craft installation multi-site: Yes. For my specific scenario, bilingual (english and french).
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Don't know

**Comment by lukasNo1** [comment]
I got the same Problem when trying to save an existing entry as a new entry (copy) with $element->setFieldValuesFromRequest('fields');

Now saving the element throws this error.
Only since Neo version 2.3.0

**Comment by andrewfairlie** [comment]
We also get this if we try to publish a saved entry with a Neo field.

**Comment by andrewfairlie** [comment]
It looks like this is to do with the new `saveModifiedBlocksOnly` feature.

If in `services/Fields.php` I manually change line `278` from...

```
$isModified = $neoSettings->saveModifiedBlocksOnly ? $block->getModified() : true;
```

to

```
$isModified = $neoSettings->saveModifiedBlocksOnly ? $block->getModified() : true;
```

I am able to publish drafts

**Comment by andrewfairlie** [comment]
Further clarification that may help @benjamminf / @ttempleton this only seems to happen in my test when there's nested / child blocks within a block.

**Comment by 23d1** [comment]
A very common use case. Looking forward to a fix.

**Comment by nmcweb** [comment]
@andrewfairlie  Can confirm your hotfix works like a charm. Thanks!

**Comment by vandres** [comment]
You can disable the setting by creating a `neo.php` in the `config` folder with the following content:

```
<?php

return [
    'saveModifiedBlocksOnly' => false,
];
```
