### ISSUE TITLE
Adding fieldlayout after syncing creates sql error

### ISSUE THREAD

**Issue by jurriaanr** [spicywebau/craft-neo#209]
#### Description
I have a neo block which has been synced to another server with the project.yml file. 
I added a field layout to a block at top level and added 2 fields. On syncing this will throw an sql error. The field layouts and it's fields are also not added to the database. As you can see the syncing tries to recreate the block with insert, instead of updating with an update query.

`The SQL being executed was: INSERT INTO `neoblocktypes` (`fieldId`, `name`, `handle`, `sortOrder`, `maxBlocks`, `maxChildBlocks`, `childBlocks`, `topLevel`, `uid`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES (8, 'Bio\'s', 'bios', 10, 0, 0, '[\"bio\"]', 1, '080a2ffa-afb4-43a0-b37a-165aba38b8da', 73, '2019-04-18 12:05:07', '2019-04-18 12:05:07')`

#### Steps to reproduce
1. create neo block
2. Sync
3. Add field layout
4. Try to sync again

#### Other information
- Neo version: 2.3.1
- Craft version: 3.1.23
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes

**Comment by dasunr** [comment]
Hi @jurriaanr,

I'm having trouble reproducing the issue so far. I have tested with few basic field types and also while syncing a NEO field in multiple steps. Are you able to give more information as to what was your original neo block configuration and the additional field layout changes added for a more thorough investigation?

**Comment by ttempleton** [comment]
Closing this issue now, due to inactivity and the error not being reproducible.  If the error persists for you, please let us know the information that was requested regarding the Neo block configuration and field layout changes that triggered the error, and we will reopen the issue.
