### ISSUE TITLE
 Invalid text representation: 7 ERROR: invalid input syntax for integer

### ISSUE THREAD

**Issue by theskyfloor** [spicywebau/craft-neo#211]
#### Description

Getting a significant error on PostreSQL that prevents me from applying new fields. Please help.

#### Steps to reproduce

[Database Exception – yii\db\Exception.pdf](https://github.com/spicywebau/craft-neo/files/3142275/Database.Exception.yii.db.Exception.pdf)

#### Other information
- Neo version: 2.3.2
- Craft version: Craft Pro 3.1.24
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by ttempleton** [comment]
This seems to be related to my merged pull request #208 to fix an issue with Field Labels compatibility, sorry... I have opened #212 to fix this.
