### ISSUE TITLE
Updating from Craft 2: Translatable does not transfer properly to "manage blocks on per site basis"

### ISSUE THREAD

**Issue by Mosnar** [spicywebau/craft-neo#216]
#### Description
Running update from a Craft 2 site running Neo 1.5.0 migrated all of the blocks over from the primary site into each of the locales; however, the newly created sites contain the Neo blocks with english content rather than their localized version. Upon closer inspection, it appears that the blocks are not set to be managed on a "per-site basis" as one would expect if the Neo field is set to be translatable on the Craft 2 install.

#### Other information
- Neo version: 1.5.0 & 2.3.3
- Craft version: 2.7.3 & 3.1.27
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
They should be!

**Comment by Mosnar** [comment]
I just tried a fresh migration and it worked fine! Must have been user-error!

**Comment by Mosnar** [comment]
Reopening: After further inspection, the problem occurs when a section is resaved, this is because the translation method is stored in the field settings as `"localizeBlocks":"1`. This does get set during the migration process on multi-site intalls.

**Comment by ttempleton** [comment]
This will be fixed in the next Neo release.
