### ISSUE TITLE
Getting "Undefined variable: siteId" error when saving new entries with neo blocks

### ISSUE THREAD

**Issue by yoannisj** [spicywebau/craft-neo#218]
#### Description

Whenever we save an entry with a Neo field which is not empty (happens also with 1 single block in 1 Neo field), we get the following error:

```
PHP Notice – yii\base\ErrorException
Undefined variable: siteId

1. in /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php at line 246
```

The entry gets saved correctly though, and editing the entry further, adding or removing blocks and saving it again works just fine. My guess is that the problematic code only gets called in the `afterElementSave` event, for new entries only.
 
After giving a quick-look at the services' [source code](https://github.com/spicywebau/craft-neo/blob/master/src/services/Fields.php#L228), it seems that the `$siteId` variable is set inside a `if`statement, just before it is used, and that it does not get created in the case of blocks in non-localized neo fields with new owner element.

I believe the fix is just to include a default assignation `$siteId = $query->siteId` before the if statement (the `$siteId` variable defaults to `$query->siteId` in the if statement already).

I will prepare a pull-request, but have not digged deeper into the code, so I am not sure if the issue may require further edits.

#### Steps to reproduce
1. Create a non-localized Neo field in a Craft-CMS3 project
2. Add the field to an entry type
3. Create a new entry of that type, populate the neo field with at least one block, and save

#### Other information
- Neo version: 2.3.4
- Craft version: 3.1.28
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: /
- It may be worth checking if the issue also occurs for non-localized Neo field on a Multi-Site installation.

**Comment by pvldigital** [comment]
Thanks. However this is now not applicable for the latest version.
