### ISSUE TITLE
Getting "Attempting to duplicate an unsaved element." when saving a draft in Craft alpha

### ISSUE THREAD

**Issue by robmcfadden** [spicywebau/craft-neo#220]
#### Description

This is only happening on sections with a Neo field which is why I'm reporting here. If I make a change and let Craft auto-save its draft, then click "Update entry" to save, I get "Attempting to duplicate an unsaved element." Clicking the browser's back button and clicking "Update entry" again seems to save correctly, though.

#### Steps to reproduce
1. Update to latest Craft alpha release.
2. Save an entry with a Neo field.

#### Other information
- Neo version: 2.3.5
- Craft version: 3.2.0-alpha.6.4
- Is the affected Craft installation multi-site: No

**Comment by robmcfadden** [comment]
My bad. This is also happening on entries with a Matrix field.

**Comment by robmcfadden** [comment]
Uggh. Now I can't reproduce what I just saw with only the Matrix field. Maybe a false alarm.

**Comment by jonXmack** [comment]
I'm getting this issue too, in 3.2.0-alpha.7. I make a change to an existing entry, craft does it's draft save, when I click Update entry I get "Attempting to duplicate an unsaved element." I tried the clicking back/update entry again but that didn't do anything for me.

**Comment by robmcfadden** [comment]
@jonXmack - Sometimes when you click back it goes to the current version instead. I've found that if you then choose the draft from the dropdown that Craft just saved and click "Update entry" it will work. Hope that helps you out until this is resolved.

**Comment by jonXmack** [comment]
Unfortunately that's not working for me, very frustrating.

**Comment by timkelty** [comment]
Seems to be fixed in Craft 3.2 beta.1
