### ISSUE TITLE
Feature: Clone a Block Type from one Neo Field to another one.

### ISSUE THREAD

**Issue by jmverges** [spicywebau/craft-neo#221]
Hi,

I feel this could be a useful feature. 

Does anybody know if there is a way to do this? if not, do you think this could be useful?

Thanks in advance

**Comment by alexgilbertDG** [comment]
+1. I do feel having some kind of import/export for each block will be very useful. It could be just a JSON or base64 representation string that you put into the import field and it recreate the block.

**Comment by dasunr** [comment]
Hi @jmverges , @alexgilbertDG ,
This seems like a good feature to have however duplicating block types across fields seems to be outside the functionality of this plugin. 
Although there is a very handy plugin, Architect (https://github.com/Pennebaker/craft-architect) which can be used to duplicate block types across fields.

**Comment by ttempleton** [comment]
Going to revive this feature request, last week we added the ability to clone a block type *within* a field, and we could expand that to allow copying/pasting between fields.

**Comment by ttempleton** [comment]
Just made changes for Neo 2.11 to add copy/paste options to the block type sidebar dropdown menus, which will allow you to copy a block type on one field, then paste it on a different field when editing that field's settings.
