### ISSUE TITLE
Translating fields but not blocks

### ISSUE THREAD

**Issue by joao-proenca-ef** [spicywebau/craft-neo#225]
#### Description
Would it be possible to have the blocks be the same for the different sites, but have the individual fields translatable?

Currently it seems that the only options are:
1. Have `Manage blocks on a per-site basis` disabled so when you add a block to a site, it's added to all sites, but then the fields inside the block aren't translatable (even if they are set as translatable)
or 
2. Have `Manage blocks on a per-site basis` enabled so you can have blocks translatable, but this means that if you want 1 page across all sites, you need to create the structure across all sites manually, instead of only creating it once.

Feels like there should be an option to have the blocks be the same across the sites, but have each field inside individually translatable.

I haven't found a way to do it, seems like it's not supported currently.

#### Other information
- Neo version: 2.3.5
- Craft version: 3.2.0
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: sort of, described in the text

**Comment by pvldigital** [comment]
@joao-proenca-ef this issue is resolved in the latest releases. neo will respect the individual fields translation
