### ISSUE TITLE
Is Neo causing multiple "updating the search index" jobs to be created in Craft 3.2?

### ISSUE THREAD

**Issue by mtnorthrop** [spicywebau/craft-neo#228]
#### Description
In Craft 3.2, when I save an entry with Neo fields, I see that many "updating the search index" jobs are added to the job queue. The number of "updating the search index" jobs that are added to the queue increases exponentially with the number of Neo fields used.

An issue addressing the growing job count was opened on the Craft issue board (craftcms/cms#4507) and @brandonkelly commented that it's necessary for plugins such as Neo, SuperTable, and (possibly) Spoon to implement the `BlockElementInterface`.

Does this issue effect Neo, and could Neo be the cause of these extra jobs?

#### Steps to reproduce
1. Be on Craft 3.2
2. Create an entry with a Neo field and add a number of Neo blocks
3. After saving an entry, click on the queue notifier in the left sidebar to see the number of "updating the search index" jobs that have been created.

#### Other information
- Neo version: 2.3.5
- Craft version: 3.2.2
- Is the affected Craft installation multi-site: No

**Comment by zizther** [comment]
I am experiencing the same thing, along with other issues related with C3.2 and plugins such as Neo and SuperTable which may be causing issues with Drafts.

+1 to look into this issue and support C3.2

**Comment by pvldigital** [comment]
Hi @mtnorthrop and @zizther,

I'm currently making changes/fixes for Craft 3.2 and plan on releasing it in the next couple of days. It should fix most issues relating to 3.2 (including the above).

**Comment by jesuismaxime** [comment]
@pvldigital any release date for this patch?

**Comment by mtnorthrop** [comment]
The patch has been released and I've tested it, but it seems that, in my case, the more Neo blocks I have on a page, the more "updating the search index" jobs I see after I save the page. On a larger page, it looks like it could be 100+ jobs in the queue.

I don't know if this is expected behavior in Craft 3.2, or whether this is a bug in Neo.

**Comment by mtnorthrop** [comment]
I've just updated the plugin in my production environment, and the issue is fixed. I'm still seeing extra jobs in my development environment for some reason, but the issue looks like it's completely fixed in my production environment. So it looks like the patch has worked, at least for me.

**Comment by pvldigital** [comment]
@jesuismaxime yep, the patch does include the implementation of `BlockElementInterface` which should fix the issue.

@mtnorthrop hmm that's strange, it should be working in any environment. I've tested it on my dev and staging, and it looks to be working correctly. I'll have a look at it again and see if I can find any issues.

**Comment by jesuismaxime** [comment]
Yes I confirm that the release patch the issue, I test it last friday (few minutes after my comment) but forget to update here. Thank you!

**Comment by mtnorthrop** [comment]
@pvldigital I'm guessing that the issue I'm having in my dev environment is not directly related to Neo, so it's probably safe to say that this issue has been fixed.
