### ISSUE TITLE
Browser "Leave site?" message appears when moving away from recently saved entry

### ISSUE THREAD

**Issue by jamiewade** [spicywebau/craft-neo#229]
### Description

After you save an entry and wait for the `Updating search indexes` task to complete, then click a Craft link to move away from the entry you have just saved, you receive this browser notification (Chrome) :

![screenshot](https://user-images.githubusercontent.com/6672331/61471436-aa503c00-a97a-11e9-8213-832c71631a1f.jpg)

You get this message even though all tasks have completed, and there is no un-saved changes to the entry.

I originally [reported this issue to Craft](https://github.com/craftcms/cms/issues/4608), but closed it after realising Neo was the culprit.

#### Other information
- Neo version: 2.3.5
- Craft version: 3.2.4.1
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes

**Comment by lukasNo1** [comment]
I had the same issue, the most recent release 2.3.6 fixed it for me though.

**Comment by pvldigital** [comment]
Hi @jamiewade,

As @lukasNo1 has mentioned, release 2.3.6 should capture and fix most of the `leave site?` alert.
