### ISSUE TITLE
JavaScript error in Neo field editor

### ISSUE THREAD

**Issue by KatieMFritz** [spicywebau/craft-neo#232]
#### Description

Neo field editor isn't displaying the blocks I previously set up, I can't create new blocks, and the tabs/fields selector is printing below the main CP screen (see screenshot). The field and its contents are okay in entries where I'm using it, but I can't change its structure.

Console error:
```
jquery.js:3850 Uncaught TypeError: Cannot read property 'menu' of undefined
    at s.constructor.toggleFieldRequire (main.js?v=1563832255:formatted:7702)
    at s.constructor.addFieldToTab (main.js?v=1563832255:formatted:7693)
    at s.constructor.init (main.js?v=1563832255:formatted:7611)
    at s.constructor.constructor (garnish.js:768)
    at s.constructor (garnish.js:40)
    at new s.constructor (garnish.js:40)
    at s.constructor.init (main.js?v=1563832255:formatted:163)
    at s.constructor.constructor (garnish.js:768)
    at s.constructor (garnish.js:40)
    at new s.constructor (garnish.js:40)
```

#### Steps to reproduce
1. Go to Settings > Fields and open previously created Neo field

#### Other information
- Neo version: 2.3.6
- Craft version: Craft Pro 3.2.5.1
- Is the affected Craft installation multi-site: no

![Screen Shot 2019-07-22 at 5 56 05 PM](https://user-images.githubusercontent.com/7085184/61668194-06340100-acaa-11e9-9cea-e7d1bdc05216.png)

**Comment by pvldigital** [comment]
Hi @KatieMFritz,

I'm unable to replicate this issues in 3.2.5.1. 

Looking at the error provided, it seems that issue lies within the field layouts in the neo block. It's unable to find the cog for the field (that displays the options for `Make Required`/`Remove`).

Are you using any non-standard field types within that neo field?

**Comment by KatieMFritz** [comment]
A few. I just recreated the field and it works - I'm guessing maybe something got messed up between changing fields that were included in the original Neo field and all the recent updates.

I'm also seeing some fields in my project.yaml that aren't in the CP, so I may have a bigger issue going on.

Thanks for the response! I'm okay with just recreating my field for now.

**Comment by pvldigital** [comment]
Oh okay no worries. If it happens again you can reopen this issue and i'll have a look into it further.

**Comment by KatieMFritz** [comment]
It did happen again after the rebuild, and I also noticed in project.yaml some Neo blocks hanging out from a field that used to be Neo but I had changed to Matrix. I'm implementing a scorched earth policy - deleted Neo, deleted project.yaml and rebuilt it, trying again. I'll report back if I get the same issue again.

**Comment by pvldigital** [comment]
Tell me how is goes. In the meantime I will do some further testing to see if I can replicate the issue.

**Comment by SwiseWeb** [comment]
FWIW, I just ran into this issue as well. Steps to reproduce:

1. Create a `Neo` field
2. Save `Neo` field
3. Convert that `Neo` field to a `Matrix` field
4. Edit a different `Neo` field, note the JS issue mentioned above
5. Delete the converted `Matrix` field
6. Neo editor is back to normal without the JS issue

**Comment by pvldigital** [comment]
Hi @SwiseWeb,

Thats for listing the steps. I'll try to replicate it and see what I can do.
