### ISSUE TITLE
Craft 2 => Craft 3 - Language Problem

### ISSUE THREAD

**Issue by davidhellmann** [spicywebau/craft-neo#234]
#### Description
We updated an old Craft 2 site to Craft 3. Looks all fine but we noticed that all the content within NEO ist overwritten by the default language. 

#### Other information
- Neo version: 2.3.6
- Craft version: 3.2.7
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: nope

**Comment by Mosnar** [comment]
Maybe related #216 

I was able to get around this by manually adding the `"localizeBlocks":"1` setting to the Neo field settings prior to the migration.

**Comment by davidhellmann** [comment]
@Mosnar I'll try that out. Thanks.

**Comment by pvldigital** [comment]
@davidhellmann with >2.4.0 you'll have to select the propagation method `Only save blocks to the site they were created in`
