### ISSUE TITLE
Duplicated blocks when changing propagation method

### ISSUE THREAD

**Issue by nitech** [spicywebau/craft-neo#242]
#### Description
I believe this problem has arisen when I changed a section's propagation method from `Only save entries to the site they were created in` to `Save entries to all sites enabled for this section`

My Craft CMS has four sites.
The content was originally created in the first site.
The three latter sites were introduced after the content was created

When I change propagation method to `Save entries to all sites enabled for this section`, all entries in the section seem to get four of all neo fields: 

![image](https://user-images.githubusercontent.com/1279436/62860367-46fac500-bd00-11e9-8d19-375566acbe1a.png)

This **doesn't** happen when I change the propagation method to `Save entries to other sites with the same language`.

#### Other information
- Neo version: 2.4.2
- Craft version: 3.2.9
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No

**Comment by nitech** [comment]
As a side note, I also experience that the block appear and disappear in the editor seemingly randomly. I can open an entry and everything but the title is missing. I click save - and suddenly the blocks reappear. 

I also experience that I've added a whole lot of blocks on a few different sites - and when I revisit one of the previous sites, the blocks are suddenly totally gone - and won't appear again even if I click save.

These settings are used: 
 - Section Propagation Method: Save entries to all sites for this section
 - Neo Field Propagation Method: Save blocks to all sites the owner element is saved in

This is driving me quite nuts! Any idea why this is happening - and a possible fix? I tried changing the Neo Fields propagation method to: "Save blocks to other sites with the same language" to no avail. I don't want any other propagation method, because I want the content to appear on at least the same language on all site groups.

**Comment by nitech** [comment]
I think this bug is related to these issues: https://github.com/spicywebau/craft-neo/issues/174 https://github.com/spicywebau/craft-neo/issues/227

It looks like the bug has been fixed, and that I am kind of caught between a rock and a hard place because I upgraded to Craft 3.2 and corresponding Neo upgrades prior to the bug being fixed.

**Comment by nitech** [comment]
Or not. I tried upgrading from a 3.1 database, and even if I first upgraded the 3rd party plugins like craft-neo and then Craft CMS, I still got the duplicates. 

Which means I was kind of stuck with the "broken" database. I did some more testing, and have figured out that when duplicates or no blocks at all are shown, just click  _save_ once and see if the duplicates don't disappear and the missing appear. This works most of the time - but when blocks are missing, they are actually sometimes simply gone - and when I save, the blocks from another langauge (site) appears instead. 

@pvldigital please help. I'm ready to give you access to whatever you need in order to track down and fix this bug. It's a big deal for me.

**Comment by pvldigital** [comment]
Hi @nitech,

Sorry about the silence, been really busy working on another project for the last week.

I'll have a look at the issue today.

**Comment by pvldigital** [comment]
Hey @nitech,

Update: I've made the fixes on my forked repo here: https://github.com/pvldigital/craft-neo/commits/master

We're testing it now so hopefully it will be released soon.

*Note: If you have a **local** version of your craft setup then you should be able test the changes using the repo I linked.

**Comment by nitech** [comment]
Thank you so much @pvldigital. I have the deepest understanding for being busy. 

I do have a local version - but because of time strain (the site goes live today because it is for a conference that starts on monday..!) I just have to push the site to production now, and get back to testing the updated Neo plugin after that.

**Comment by nitech** [comment]
Can you help me along with an example command for installing that particular fork? I don't yet know enough about how to use composer.

**Comment by pvldigital** [comment]
Hi @nitech,

Have a look at this article: https://nystudio107.com/blog/so-you-wanna-make-a-craft-3-plugin. If you search `Adding our plugin` in that article it'll redirect you the method to add a local repo to craft. 

You'll need to clone/download the plugin and place it on your local machine first. You'll then link it using the method in the article.

**Comment by nitech** [comment]
Here are some additional screenshots that illustrate the problem: 

![image](https://user-images.githubusercontent.com/1279436/63098527-6188a480-bf73-11e9-9e1d-411bde3778a2.png)

![image](https://user-images.githubusercontent.com/1279436/63098619-8e3cbc00-bf73-11e9-9327-6fd71ced948f.png)

When I then click "save", everything goes bananas. Craft admin sometimes will redirect to the current entry on a different site (that has the same language) and removing all blocks on all other languages than the current. 

It makes me close to crazy! 

@pvldigital is the fix near a release?

**Comment by pvldigital** [comment]
Is this occurring with the forked repo?

Make sure to check the composer lock file (open and find “craft-neo”) and see if it’s using the symlinked version (it should should the relative/absolute path to the plugin).

I’ve been testing with the forked repo and the issue with the missing blocks and such isn’t occurring for me.

**Comment by pvldigital** [comment]
@nitech I've made a release for the fix.

What i suggest when saving an entry with the problem.
1. Enter an entry to edit
2. Delete any orphan blocks (like your image is shown)
3. Make sure the content and structure of the blocks is correct
4. Save entry.

This should correctly save the entry and duplicate the blocks to the other sites.

If the orphan child still appears then I recommend rebuilding the page by removing all blocks, saving and check if any new blocks appear in the entry. 
If there's still blocks that appear then repeat the process above. This is done so all blocks and structures and removed so the entry will be in a clean slate.

**Comment by nitech** [comment]
Yes. My chains are gone. Thank you so much. 

Perhaps this release also fixes https://github.com/spicywebau/craft-neo/issues/243

**Comment by pvldigital** [comment]
Awesome, good to know it's working for you. Release v2.4.3 should be issue #243 as well.
