### ISSUE TITLE
GraphQL Support in Craft 3.3

### ISSUE THREAD

**Issue by Jones-S** [spicywebau/craft-neo#252]
Now that Craft 3.3 is out with core GraphQL Service, will you add GraphQL support soon?
Or is there a beta version I could use until you have a new release of your plugin?

Cheers

#### Other information
- Neo version: 2.3.6
- Craft version: 3.3

**Comment by pvldigital** [comment]
Hi @Jones-S,

Since GraphQL is now a core feature of Craft we'll be updating neo to support it. It's still in development so i'll give you a heads up when it's about to be released.

**Comment by sgtpenguin** [comment]
Hey @pvldigital.  This is great news!  Any idea of a rough timeline?  I'd also be interested in an alpha/beta situation when that becomes available.

**Comment by pvldigital** [comment]
Hi @sgtpenguin, I would say at the end of this month, maybe? there's no definitive timeline as of yet but i'll try to get it up by the end of this month. I will keep everyone updated on the progress.

**Comment by pvldigital** [comment]
Progress update:

GraphQL now outputs the neo field and its data but the structure for it is incorrect. Will continue working on it and keep you all updated.

**Comment by ca-miked** [comment]
Hi,  I'm running a headless craft + GraphQL + react stack for a new site build that is fast approaching launch. I'm trying to determine whether i need to pivot over to the elements rest api or if you're update for native GQL support will happen in time. 

Don't want you to feel pressured, just wondering if your end of the month or sooner ETA still looks intact? Thanks again for all the efforts on an indispensable plugin!

**Comment by pvldigital** [comment]
Hi @ca-miked, it's still on track to be released the end of the month. But I do have other issues and projects to work on, which could cause a delay. I'll give a heads up if it does get delayed.

Update on progress: 
Single level blocks works and returns the correct structure. There's currently issues with multi level blocks, which I'm currently working on.

**Comment by ca-miked** [comment]
> Hi @ca-miked, it's still on track to be released the end of the month. But I do have other issues and projects to work on, which could cause a delay. I'll give a heads up if it does get delayed.
> 
> Update on progress:
> Single level blocks works and returns the correct structure. There's currently issues with multi level blocks, which I'm currently working on.

Thanks for the update!

**Comment by pvldigital** [comment]
Hi Everyone,

I have created a new branch called `feature\graphql` which includes the grahpql implementation for neo. You can have a look and test it using that branch.

** If you do test it and there's some problems, create a new issue with [GraphQL beta] in the title

I'm going to continue testing it and hopefully release it some time next week.

----

How to:

Let's say you have a neo field called `body`

fragment syntax: {neo field handle}_{block type handle}_BlockType

Single level
```
body {
    ... on body_text_BlockType {
      typeHandle
      text
    }
    
    ... on body_media_BlockType {
      typeHandle
      media {
        url
      }
    }
 }
```

Multi level - only difference is using the children to get inner block types
```
body {
    ... on body_text_BlockType {
      typeHandle
      text
    }
    
    ... on body_myContent_BlockType {
        typeHandle
        
        # getting inner block types
        children {
            typeHandle
            ... on body_contentText_BlockType {
                text
            }
            ... on body_inner_BlockType {
                # getting inner inner block types
                children {
                    ... on body_innerText_BlockType {
                        text
                    }
                }
            }
        }
    }
}
```

**Comment by pvldigital** [comment]
With v2.5.0, GraphQL support has been added.

If you're seeing an error like: `Schema must contain unique named types but contains multiple types named...`, add the below to the query.

```
__schema {
    types {
        name
        description
    }
}
```

For some reason when updating from craft 3.3.2 -> latest, it creates that error. Added the above, query and then removing fixes it.

**Comment by P233** [comment]
I just found that we can also query the `__typename` for `__schema`,  so we won't have the long types list in the return data.

```
__schema {
  __typename
}
```

**Comment by dangayle** [comment]
A fix for this has been made upstream in CraftCMS, but Neo needs to adapt to it:

https://github.com/craftcms/cms/issues/5067

**Comment by pvldigital** [comment]
@dangayle thanks for letting me know. I will implement the changes.

**Comment by pvldigital** [comment]
Done with the changes. I'll make a release for it soon.
