### ISSUE TITLE
Deleting 1 block type --> Deletes ALL block types

### ISSUE THREAD

**Issue by Osze** [spicywebau/craft-neo#253]
#### Description
I've just upgraded to the latest version of Craft and NEO. After upgrade I deleted a block type in a large NEO Field (+40 block types). 
When I clicked Save all Block Types where gone. Only the Group Names where left. ;)

#### Steps to reproduce
1. Deleting a Block Type in a large Neo Field.
2. All Block Types gets deleted after save. (Thankfully I saved my DB)

#### Other information
- Neo version: 2.4.5
- Craft version: 3.3.1.2
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by eliseferguson** [comment]
Just came here to report the same error.  

Reproduced on:
Craft CMS 3.3.0.1
Neo 2.4.5

**Comment by pvldigital** [comment]
Hi @Osze and @eliseferguson, I've reverted the changes to the `handleDeletedBlockType` function which causes the issue. Release v2.4.6 should fix the problem.

Can you both confirm that it works?

**Comment by Osze** [comment]
It Works! 

Thank you very much for the quick fix!

**Comment by eliseferguson** [comment]
Confirmed, worked for me as well.
