### ISSUE TITLE
Field Labels error when saving after updating to 2.4.6

### ISSUE THREAD

**Issue by SamNewism** [spicywebau/craft-neo#255]
#### Description
I updated Craft and Neo and now I can't save my Neo fields. I posted the stack trace below.

#### Steps to reproduce
1. Create field as Neo type
2. Update Neo from 2.4.4 to 2.4.6
3. Attempt to save the Neo field

#### Other information
- Neo version: 2.4.6
- Craft version: 3.3.1.2
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: all (Save blocks to all sites the owner element is saved in)
- Is eager-loading used? No

### Stack trace
yii\base\ErrorException: Undefined offset: 0 in /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/integrations/fieldlabels/FieldLabels.php:57
Stack trace:
#0 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/hun...', 57)
#1 /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/integrations/fieldlabels/FieldLabels.php(57): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/hun...', 57, Array)
#2 [internal function]: benf\neo\integrations\fieldlabels\FieldLabels->benf\neo\integrations\fieldlabels\{closure}(Object(benf\neo\events\BlockTypeEvent))
#3 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(benf\neo\events\BlockTypeEvent))
#4 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('benf\\neo\\servic...', 'afterSaveNeoBlo...', Object(benf\neo\events\BlockTypeEvent))
#5 /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(442): yii\base\Component->trigger('afterSaveNeoBlo...', Object(benf\neo\events\BlockTypeEvent))
#6 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(865): benf\neo\services\BlockTypes->handleChangedBlockType(Object(benf\neo\events\BlockTypeEvent))
#7 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#8 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#9 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(553): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#10 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(389): craft\services\ProjectConfig->processConfigChanges('neoBlockTypes.e...', true)
#11 /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/services/BlockTypes.php(242): craft\services\ProjectConfig->set('neoBlockTypes.e...', Array)
#12 /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/services/Fields.php(114): benf\neo\services\BlockTypes->save(Object(benf\neo\models\BlockType), false)
#13 /home/forge/hunterwater.newism.rocks/releases/45/vendor/spicyweb/craft-neo/src/Field.php(639): benf\neo\services\Fields->save(Object(benf\neo\Field))
#14 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/Fields.php(1567): benf\neo\Field->afterSave(false)
#15 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/Fields.php(832): craft\services\Fields->applyFieldSave('de8602fe-edb1-4...', Array, 'global')
#16 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(865): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#17 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#18 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#19 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(553): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#20 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/ProjectConfig.php(389): craft\services\ProjectConfig->processConfigChanges('fields.de8602fe...', true)
#21 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/services/Fields.php(778): craft\services\ProjectConfig->set('fields.de8602fe...', Array)
#22 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/controllers/FieldsController.php(275): craft\services\Fields->saveField(Object(benf\neo\Field))
#23 [internal function]: craft\controllers\FieldsController->actionSaveField()
#24 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#26 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-field', Array)
#27 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-field', Array)
#28 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('fields/save-fie...', Array)
#29 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('fields/save-fie...', Array)
#30 /home/forge/hunterwater.newism.rocks/releases/45/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#31 /home/forge/hunterwater.newism.rocks/releases/45/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /home/forge/hunterwater.newism.rocks/releases/45/public/index.php(34): yii\base\Application->run()
#33 {main}

**Comment by pvldigital** [comment]
Hi @SamNewism, looks like this issue was caused by the field labels integration update PR. I've reverted the change now in release v2.4.7
