### ISSUE TITLE
Ability to "view" images or examples of blocks when selecting.

### ISSUE THREAD

**Issue by bryantAXS** [spicywebau/craft-neo#256]
Hey guys, I wanted to bring something up and see if you had any thoughts for a potential feature, or a way Neo could be extended.

A problem we run into a lot is that our Neo fields contain a large number of blocks, and the block selector ends up being this massive list of hard to identify terms. eg "Content With Image", "Gallery Listing Left", "Gallery With Text", etc... 

I'm wondering what could be a good way to allow users to quickly see and identify a block while they are toggling the "add block" dropdown?

**Comment by bryantAXS** [comment]
The UI here is obviously much different from Craft and Neo's, but the idea is inline with what I'm discussing above: https://tailwind.build/

**Comment by bryantAXS** [comment]
This is essentially what I'm talking about!

https://github.com/weareferal/craft-matrix-field-preview

**Comment by ttempleton** [comment]
Matrix Field Preview is adding Neo support, so there's no more need for this to be implemented on Neo's end.
