### ISSUE TITLE
Updated fields not synced correctly 

### ISSUE THREAD

**Issue by umkasanki** [spicywebau/craft-neo#265]
#### Description
I added a new dropdown field to a previously created neo field on my local machine. After that, I send the project file to the staging server and start the synchronization. A new field does not appear.
Also, I tried to rebuild my project.yamls before adding field and before sync... It's not helped me too.

**Local:**
![изображение](https://user-images.githubusercontent.com/496132/65662574-46628780-e03d-11e9-8e7e-8487d1517687.png)

**Remote:**
![Remote](https://user-images.githubusercontent.com/496132/65662494-1dda8d80-e03d-11e9-8d1b-9a56e4da3c8e.jpg)

Can I sent you backups by mail?

#### Steps to reproduce
1. Update Neo field
2. Git push
3. Sync with project

#### Other information
- Neo version: 2.4.8
- Craft version: 3.3.4.1
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used? No

**Comment by pvldigital** [comment]
Hi @umkasanki,

Thanks but don't worry about the backups for now. 

Can you check to see if `fieldLayouts` is under `neoBlockTypes` within the project.yaml file?

This issue might be related to #250.

**Comment by jmverges** [comment]
same here

**Comment by pvldigital** [comment]
thanks @umkasanki.

@jmverges I'll be looking into this issue today.

**Comment by pvldigital** [comment]
Hi @umkasanki,

Could you rebuild on your local machine first after getting the latest build, send it to staging and then sync? See if that works for you.

**Comment by umkasanki** [comment]
Yes. I have already tried this approach. sometimes it helps, and sometimes not. and this does not solve the problem. Because A synchronization error occurs quite often when updating previously created fields. Besides the fact that new fields are not added, the content of child fields often disappears.. ((

**Local:**
![изображение](https://user-images.githubusercontent.com/496132/65855382-a6bc3680-e367-11e9-89c5-6d37d9f181b4.png)

**Staging:**
![изображение](https://user-images.githubusercontent.com/496132/65855441-b3d92580-e367-11e9-8628-fa2de590e79e.png)

**Comment by pvldigital** [comment]
Hi @umkasanki,

Strange, I'm unable to replicate the issue.

Could you send through your composer lock file and any other relevant files to plugins@spicyweb.com.au?

**Comment by pvldigital** [comment]
Hi @umkasanki, i'll close this issue for now since it was indicated by your email that it hasn't appeared again. If it does happen again please leave a message and reopen this issue.
