### ISSUE TITLE
Feature request - instructions/helper text available for each block

### ISSUE THREAD

**Issue by epic-elise** [spicywebau/craft-neo#266]
Just wondering if the addition of instructions/helper text for each block inside the Neo field would ever be a future feature?

I can add text to individual fields (eg. Image) but sometimes the usage of that field differs from block to block within the Neo field itself.  In order to maintain a more streamlined system my team prefers to not have separate "image" fields for a background versus a icon, etc but having the ability to indicate to the user what that image field is going to be used for in each block would go miles for maintaining modularity.

Thanks!

**Comment by pvldigital** [comment]
Hi @epic-elise,

You could use our other plugin [Field Labels](https://github.com/spicywebau/craft-fieldlabels) for that functionality. That plugin will allow you to change the name and instructions of that field.

**Comment by epic-elise** [comment]
Okay this is perfect, thanks for pointing it out!
