### ISSUE TITLE
Integrity constraint violation: Duplicate entry when project-config/sync

### ISSUE THREAD

**Issue by jmverges** [spicywebau/craft-neo#269]
#### Description

./craft project-config/sync
Installing plugin "architect" ... done
Applying changes from project.yaml ... error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'hero-1' for key 'neoblocktypes_handle_fieldId_unq_idx'
The SQL being executed was: INSERT INTO `neoblocktypes` (`fieldId`, `name`, `handle`, `sortOrder`, `maxBlocks`, `maxChildBlocks`, `childBlocks`, `topLevel`, `uid`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES (1, 'Hero', 'hero', 1, 0, 0, NULL, 1, '7536040d-3a6e-4eda-8f8c-f1c9834a36ea', 45, '2019-10-01 18:56:49', '2019-10-01 18:56:49')

#### Steps to reproduce
1. I do some changes locally into the neoblocktypes to see project.yaml change
2. I grab database from production and import locally to be in the previous state
3. I do project sync to get my changes  

#### Other information
- Neo version: 2.5.1
- Craft version: 3.3.6
- Is the affected Craft installation multi-site: no
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used? don't know

**Comment by pvldigital** [comment]
Hi @jmverges,

I've been trying to replicate the issue but wasn't able to. Can you me the trace log file to plugins@spicyweb.com.au? Can you also list out the other plugins you've used in conjunction with neo.

**Comment by jmverges** [comment]
Hi @pvldigital ,

thanks for your response. I will as soon as I'm with it, probably on Monday. 

Regards

**Comment by pvldigital** [comment]
Hi @jmverges,

I'm going to close this issue for now. If it does come up again, comment on this issue and i'll reopen it.
