### ISSUE TITLE
Saving and publishing drafts causes content on another site to be overwritten

### ISSUE THREAD

**Issue by mdominguez** [spicywebau/craft-neo#270]
[view screencast](https://cl.ly/72ca869b2246)

It is probably related to #246 but the issue is closed mentioning it should have been fixed in version 2.4.5, but still occurs in version 2.5.3.

Thanks for looking into this, one of our clients sites has lost a tremendous amount of already translated content like this and had to stop content editing until it gets fixed...

#### Other information
- Neo version: **2.5.3**
- Craft version: **3.3.7**
- Is the affected Craft installation multi-site: **Yes**
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: **No**
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: **Save blocks to all sites the owner element is saved in**
- Is eager-loading used? **No**

**Comment by pvldigital** [comment]
Hi @mdominguez, I have replicated the issue and working on a fix now.

**Comment by pvldigital** [comment]
Hi @mdominguez, this issue should be fixed with release v2.5.4.
