### ISSUE TITLE
Maintain or access order of child blocks in GraphQL 

### ISSUE THREAD

**Issue by gregorterrill** [spicywebau/craft-neo#281]
#### Description
I've got a fairly complex content builder Neo field, and I'm trying to access this via GraphQL to populate a Gridsome app. So far it's been working great, but I've run into an issue where I can't figure out how to maintain the order of child blocks in the Craft admin (or even query their order). I have a top-level block (called a Section) that contains child blocks (called Blocks) in this order: Text, Cards, Text. In GraphQL, it always returns them in the order: Text, Text, Cards (so I guess its sorting them based on `typeHandle`?)

I want to maintain their original order or be able to access an order property so I can manually sort the `blocks` array I get back.

Here's the query:
```
query Page($id:[craft_QueryParameter]) {
  craft {
    entries(id:$id, limit:1) {
      title

      ...on craft_guides_guide_Entry {
        
        icon
        photo {
          url
          focalPoint
        }

        sections: guideBlocks(fixedOrder:true) {
          ...on craft_guideBlocks_contentSection_BlockType {
            typeHandle
            heading
            sectionId

            blocks: children {
              typeHandle

              ...on craft_guideBlocks_text_BlockType {                
                heading
                textContent
                alternate
                illustration {
                  url
                }
              }

              ...on craft_guideBlocks_cards_BlockType {
                heading
                textContent
                
                cards: children {

                  ...on craft_guideBlocks_card_BlockType {
                    heading
                    textContent
                    photo {
                      url
                      focalPoint
                    }
                  }
                }               
              }

              ...on craft_guideBlocks_contents_BlockType {
                heading
                jumpLinks {
                  heading
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
```

So essentially I'm looking to be able to do one of these two things:
```
blocks: children(fixedOrder: true) {
  typeHandle
  ...
}
```
or
```
blocks: children {
  typeHandle
  blockNum
  ...
}
```

If there's another way to do this, would love to know!

#### Other information
- Neo version: 2.5.7
- Craft version: 3.3.15

**Comment by pvldigital** [comment]
Hi @gregorterrill,

That's strange, the order of the children blocks returned should be the same as the CMS. I'll have a look into it.

**Comment by pvldigital** [comment]
Hi @gregorterrill,

I've been testing but can't seem to replicate the issue. The order is maintained for the children blocks (same order as the CMS). Tested it with multiple levels as well.

**Comment by gregorterrill** [comment]
@pvldigital Appreciate you taking a look. Here are some screenshots of the above-mentioned example comparing the entry screen vs. the order they're showing in GraphQL:

![Screen Shot 2019-11-13 at 8 54 23 AM](https://user-images.githubusercontent.com/1774747/68770522-4b32c900-05f4-11ea-814b-8ec2c0b192cb.png)
![Screen Shot 2019-11-13 at 9 01 08 AM](https://user-images.githubusercontent.com/1774747/68770549-571e8b00-05f4-11ea-9222-826a80259e0a.png)

I can provide a DB dump as well if that's helpful to diagnose - just let me know where I should send it.

**Comment by gregorterrill** [comment]
@pvldigital After some further testing on other pages I've realized it's not sorting child blocks by block type or CMS order, it's sorting them by `dateCreated` (or possibly some other hidden sequential id). Whatever block I've most recently added always appears last in GraphQL, regardless of type or order. Editing content doesn't change the order, so it definitely seems like its `dateCreated` and not `dateModified`. 

If during your testing, you added all the child blocks within a single save of an entry, it might make sense you couldn't replicate since their `dateCreated` would all be the same. Try this:

1. Create a parent block containing 2 child blocks.
2. Save the entry.
3. Add a third child block to the same parent block.
4. Save again.
5. Try moving that last added block to the first position within the parent block.
6. See that the order of blocks doesn't get updated in GraphQL.

This is replicable for me on a brand new entry (although I should mention I'm also not able to rearrange blocks 1 and 2 which have identical `dateCreated` values, so maybe I'm still missing something).

Top-level blocks **do** keep their CMS order, as I'm able to rearrange the Sections in the screenshot above and they update in GraphQL with no problem.

**Comment by pvldigital** [comment]
Hi @gregorterrill,

Thanks for all the extra info. I am able to replicate and can see what is causing the issue. A fix has been made and I'm testing it right now and will put out a fix soon.

**Comment by pvldigital** [comment]
Fix has been released. v2.5.8.

**Comment by gregorterrill** [comment]
@pvldigital Works perfectly now! Thanks so much!
