### ISSUE TITLE
Filtering entries query with neo fields

### ISSUE THREAD

**Issue by superdonpan** [spicywebau/craft-neo#283]
When querying entries you can filter based on the fields available in the entries and the values for them. So say you want to fetch all "partner" entries which have the field "partnerLevel" with the value "gold". For a normal Craft field you'd query:

{% set partnersQuery = craft.entries()
    .section('partners')
    .partnerLevel('gold')
%}

We've been trying to query the same way with Neo fields but haven't managed to get it to work since the Neo fields sit in blocks. So the usual approach is to loop out the blocks one by one. This makes it impossible to query the original Craft way. Same goes for when you have the field you want to query sitting in a sub block.

Currently we get around this with a function that can grab Neo fields one by one and then we filter with a few if statements when we loop out the content. But this isn't optimal as our query fetches all entries before filtering in the loop. Then queries the db everytime we grab a Neofield and all this means unnecessary code and data for something that should've been filtered already in the original query.

Is there a way to do this that we've missed? If not are you planning to add support for it so we can query on Neo fields?

#### Other information
- Neo version: 2.5.7 
- Craft version: 3.3.14

**Comment by pvldigital** [comment]
Hi @superdonpan,

Currently neo doesn't have that functionality. We can look into implementing this is the future but it'll be difficult because Craft doesn't an easy way to query entries based on a neo blocks contents.

I had a chat with the previous dev and he suggested querying the blocks directly, getting the owner ids from them and then search for the entries.

Something like this:
```{% set neoBlocks = craft.neo.blocks({
    partnerLevel: 'gold',
}).all() %}
{% set ownerIds = [] %}
{% for block in neoBlocks %}
    {% set ownerIds = ownerIds|merge([block.ownerId]) %}
{% endfor %}
{% set entries = craft.entries().section('partners').id(ownerIds).all() %}```

The only issue with this method is that when querying the blocks, it will grab the drafts and revisions blocks too.

**Comment by ttempleton** [comment]
Regarding adding support for directly querying Craft entries based on their Neo field's block's field's contents -- we'd love to be able to do this, but it is unfortunately not possible for us to do.

**Comment by palomamtnez** [comment]
@pvldigital just for the record, what does `partnerLevel ` refers to?

**Comment by pvldigital** [comment]
@palomamtnez `partnerLevel` would be the field handle

**Comment by palomamtnez** [comment]
Thank you.
For some reason, `partnerLevel` caused an error on my local. 

For people looking for a workaround as well, the one I did based on @pvldigital answer was:

```
      {% set searchQuery = craft.app.request.getParam('q') %}
            {% set searchNormal = craft.entries()
                .search(searchQuery)
                .orderBy('score')
                .section('securedEntries')
                .ids()
            %}
            {% set neoBlocks = craft.neo.blocks({
                search: searchQuery
            }).all() %}
            {% set ownerIds = [] %}
            {% for block in neoBlocks %}
                {% set ownerIds = ownerIds|merge([block.ownerId]) %}
            {% endfor %}
            {% set entriesIds = searchNormal|merge(ownerIds) %}
            {% set entries = craft.entries()
                .section('securedEntries')
                .orderBy('score')
                .id(entriesIds) 
            %}
```

Get the searchQuery
Looking for the NEO blocks that contain the searchQuery, 
Get the IDs of the entries that contain those blocks,
Merge those IDs with the entries that also contain the searchQuery in their regular fields (so the search function is not just limited to the NEO results)

**Comment by pvldigital** [comment]
To clarify:
I meant say the handle of the field within the `neo` block.

@palomamtnez 
This is why `partnerLevel` caused the error, you probably didn't have a field with that handle.
So in your workaround, `search` would be the handle of the field and `searchQuery` would be the query value.
