### ISSUE TITLE
relatedTo neo field

### ISSUE THREAD

**Issue by jacobleech** [spicywebau/craft-neo#284]
I've tried the solution below to display entries with a particular neo field value set, however i get an error: Impossible to invoke a method ("relatedTo") on a null variable. 

How would I now go about drilling down into specific block types/fields within the Neo field for the relatedTo argument? It's like the neoField I reference isn't being recognised..

Original solution:

Try this:

```twig
{% set neoRelatedEvents = [] %}
{% for event in craft.entries.section('events') %}
    {% if event.neoField.relatedTo({ targetElement: entry }).total() > 0 %}
        {% set neoRelatedEvents = neoRelatedEvents|merge([event]) %}
    {% endif %}
{% endfor %}
```

_Originally posted by @benjamminf in https://github.com/spicywebau/craft-neo/issues/72#issuecomment-274150695_

**Comment by pvldigital** [comment]
Hi @jacobleech,

I'm not sure if that functionality was ported to craft 3. I'll need to talk to previous developer who ported it.

For now you could try the method in #283.

First you search for the neo block with the field name and value. You'll then loop through the returned blocks for the owners ID which is the entry ID.

```
{% set neoBlocks = craft.neo.blocks({
    fieldName: 'fieldValue',
}).all() %}

{% set ownerIds = [] %}

{% for block in neoBlocks %}
    {% set ownerIds = ownerIds|merge([block.ownerId]) %}
{% endfor %}

{% set entries = craft.entries().section('events').id(ownerIds).all() %}
```

**Comment by jacobleech** [comment]
Hi @pvldigital the section does have a neo field added. The neo field in my case is called 'components' but I actually want to target a block type field within the neo field... Shoul I be able to target a block type like so: neoField.blockType.field?

**Comment by pvldigital** [comment]
Hi @jacobleech,

You shouldn't need to target an inner block type. `relatedTo` should return all blocks that meets the criteria. Can you post an extract of the code you're trying to get working? I'll have a better idea what you're trying to accomplish.

---
If you're trying to filter with a particular block type field value then you could try something like:

```
{% set neoRelatedEvents = [] %}
{% for event in craft.entries.section('events') %}

	{# only get a particular block type #}
	{% set myBlocks = event.neoField.type('blocktype') %}

	{# if it has the blocks #}
	{% if myBlocks.total() > 0 %}
		{% for block in myBlocks %}
			{% if block.text == 'text' %}
				{% set neoRelatedEvents = neoRelatedEvents|merge([event]) %}
			{% endif %}
		{% endfor %}
	{% endif %}

{% endfor %}
```

**Comment by jacobleech** [comment]
Thanks for your response :) 

I don't have code to share, basically I have an entry field as a neo block assigned to 'Entry A', the entry field allows for selection of 'Entry B's.' When rendering out Entry B I want to retrieve all 'Entry A's' that have the current 'Entry B' assigned as a 'related' entry in the neo block. Does that make sense? Sorry if it's a convoluted explanation.

Querying by an exact value doesn't quite work in this instance.. That's why I originally tried using relatedTo.

**Comment by pvldigital** [comment]
Ah gotcha. For this section: `craft.entries.section('events')`, are you querying multiple sections? or just one like the example?

**Comment by jacobleech** [comment]
Just the one section at this stage.

**Comment by pvldigital** [comment]
Going back to your original post, the `Impossible to invoke a method ("relatedTo") on a null variable.` error tells me that the neo field couldn't be accessed.

You could try to check if the field is not null like below:
```
{% set relatedEntryA = [] %}
{% for foundEntry in craft.entries.section('entryASection') %}
	{% if foundEntry.components and foundEntry.components.relatedTo({ targetElement: entryB }).total() > 0 %}
		{% set neoRelatedEvents = neoRelatedEvents|merge([event]) %}
	{% endif %}
{% endfor %}
```

Can you try that and see how it goes?

**Comment by jacobleech** [comment]
Assuming this needs to be:

**Comment by pvldigital** [comment]
yep, that's right. fixed my code.

**Comment by jacobleech** [comment]
So I believe the problem might actually be that the neo block field I want to access the related Entry from is a Super Table field... I need to access components > blockType > superTableField > relatedEntry.

Does that make sense? I can see that foundEntry.components returns data, but for some reason the keyInsights field is null. Even though there are keyInsights assigned. This is the Super Table field. 

Perhaps I need to find a way to then loop over the Super Table field? Tricky given the dump of foundEntry.components doesn't seem to have the data I need :(

**Comment by pvldigital** [comment]
Ahh okay. I think you can use `craft.superTable.getRelatedElements()` to query the data you need for supertables.

Something like this:
```
{% set reverseRelatedElements = craft.superTable.getRelatedElements({
  relatedTo: {
      targetElement: entryB,
      field: 'keyInsights.columnHandle',
  },
  elementType: 'craft\\elements\\Entry',
}).all() %}
```

---

https://verbb.io/craft-plugins/super-table/docs/template-guides/available-variables

**Comment by jacobleech** [comment]
Hmm this still doesn't seem right, the superTable field that I want to query belongs to entryA, not entryB... When I try the code (adjusted with relevant field names) the Array results are empty.

I want to see if entryA's superTable entry field (within the neo field) contains the current entry B... Maybe I'll just make it a manual link 😂

**Comment by pvldigital** [comment]
I wonder if `getRelatedElements` is returning the owner id of the neo field instead of the entry (because the super table field added in neo block).

I think a manual link would be the easiest way or you can try modifying the first example to fit your needs:

** I'm not sure if `relatedTo` works with supertables though.
```
{% set relatedEntryA = [] %}
{% for foundEntry in craft.entries.section('entryASection') %}
	{% if foundEntry.components %}
		 only get a particular block type 
		{% set blocks = foundEntry.components.type('block-type-that-contains-keyInsights') %}

		 if blocks if not empty 
		{% if blocks.total() > 0 %}
			{% for block in blocks %}
				{% if block.keyInsights and block.keyInsights.relatedTo({ targetElement: entryB })|length > 0 %}
					{% set relatedEntryA = relatedEntryA|merge([foundEntry]) %}
				{% endif %}
			{% endfor %}
		{% endif %}
	{% endif %}
{% endfor %}
```

**Comment by jacobleech** [comment]
Perfect! I just needed to add an exclude for the current entry ID and it works just as I'd hoped.

Thanks so much for all your help.

**Comment by pvldigital** [comment]
No worries.
