### ISSUE TITLE
Has the Neo demo license limitations?

### ISSUE THREAD

**Issue by denisyilmaz** [spicywebau/craft-neo#285]
Hi, 

first of all, awesome plugin. I'm using it for several projects now and am currently developing the next one with neo.

But now I found a problem where I don't know if its a limitation to the demo license or more serious bug.

I have a "form builder" built with Neo matrix where you can add multiple steps and to this multiple field blocks as children.
this works great, but now one of our test forms seems to have "one field to much". Meaning: having 93 child blocks in the steps it works fine, but no matter where I put another block and try to save the entry, I get a "internal serve error" without further explanation.

Deleting some random block and adding another random block works fine, its just this one block too much that keeps the page crashing.

My logs don't show anything suspicious. no phperror or 404 not found. I see the post with the json of the fields with response 200, but server crashes anyway.

So: is there a limitation or does neo have any debug options where I could dig to find the issue?
Thanks!

**Comment by pvldigital** [comment]
Hi @denisyilmaz,

Nope, neo doesn't have any demo limitations.

This issue might be related to #257. Can you send me the web.log (to plugins@spicyweb.com.au) after attempting to save?

**Comment by denisyilmaz** [comment]
Hi @pvldigital 

Thanks for the quick response. I finally found the error log for the issue: 
```bash
2019-12-04 21:06:26 [-][2][o48elkt9dmtvkl1cejjpqku3ji][error][yii\base\ErrorException:1] yii\base\ErrorException: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in /var/www/…/vendor/yiisoft/yii2/base/ErrorException.php:43
```

I increased my `max_input_vars` to 2000 and now its works (but takes a long time for saving). 
Is this normal? The example form we build has around 150 fields in the Neo Block field.

**Comment by denisyilmaz** [comment]
Some additional informations about the server:

```	
Nginx latest
PHP 7.3
```

```
1 CPU  (0.6 for php / 0.4 for postgresql)
1GB RAM  (0.55 for php / 0.45 for postgresql)
50GB SSD
```

```
Settings:
file_uploads : true
short_open_tag: false
enable_post_data_reading: true
allow_url_fopen: true
allow_url_include: false
output_buffering: 4096 

Performance:
max_input_time: 120
max_execution_time: 300
max_input_vars: 2000
max_input_nesting_level: 64 
memory_limit: 1024M 
post_max_size: 600M 
upload_max_filesize: 300M 
max_file_uploads: 20 

Error Settings: 
display_errors: false
display_startup_errors: false
html_errors: true
log_errors: true
ignore_repeated_errors: false
track_errors: false
error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT
```

**Comment by pvldigital** [comment]
@denisyilmaz Oh so it was reaching the max capacity for `max_input_vars`, I guess it makes sense with all the fields. I'm not sure we can do anything about that since the limiting factor with php.

Note: You might need to increase `post_max_size` as well.

**Comment by denisyilmaz** [comment]
Is this "error message not being shown in the Backend UI" something that could be resolved? 
But maybe that has to be resolved in CraftCMS, right?

Thanks for your responsiveness and the help. closing this now.
