### ISSUE TITLE
Children won't display or I get all() deprecation notice

### ISSUE THREAD

**Issue by tyssen** [spicywebau/craft-neo#289]
I created a question on [StackExchange](https://craftcms.stackexchange.com/questions/33310/neo-children-wont-display-or-i-get-all-deprecation-notice) and also posted it on the Slack channel but didn't get any replies.

I did see some other issues asking similar sorts of templating questions, but apologies if this isn't the correct place to ask.

**Comment by pvldigital** [comment]
Hi @tyssen,

Sorry for the late reply, I was on break for a while. I'm not sure about the slack channel but all issues and questions should be on GitHub as it keeps everything centralised and it easier to keep track.

---

Regarding your question, it seems like you're trying to use eager loading with neo. Neo does eager loading a bit differently. You can read it here: https://github.com/spicywebau/craft-neo/blob/master/docs/eager-loading.md

Below is an example of the usage:

I assume `pageBuilder` is the neo field and `moduleBody`, `moduleRow` and `moduleColumn` is the neo blocks.

```
{% for module in entry.pageBuilder %}
    {% do block.useMemoized(entry.pageBuilder) %}
{% endfor %}

{% for module in entry.pageBuilder if module.level == 1 %}
    {% if module.type != 'moduleColumn' %}
        {% include '_partials/page-builder/_' ~ module.type %}
    {% endif %}
{% endfor %}
```

**Comment by tyssen** [comment]
Thanks, that seems to have done the trick. I just had to add `.all()` in a few places.

**Comment by pvldigital** [comment]
Awesome, good to know it's working.
