### ISSUE TITLE
Error when fetching block children in console command. (Calling unknown method)

### ISSUE THREAD

**Issue by cjgrauco** [spicywebau/craft-neo#290]
#### Description
Fetching block children from console command gives me the following error:
Calling unknown method: craft\console\Request::getParam(). 
Looks like it stems from the Block class line 574.

#### Steps to reproduce
1. calling MyNeoBlock->children->all() from a console command.

#### Other information
- Neo version: 2.5.9

- Craft version: 3.3.19

- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
Not multi site

- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
Not multisite

- Is eager-loading used?
No

**Comment by pvldigital** [comment]
Hi @cjgrauco,

Is this a custom console command you used or a built in craft one?

**Comment by cjgrauco** [comment]
Hello @pvldigital,
 
It is a custom console command from a module. 

Let me know if you need any more info from me.

**Comment by pvldigital** [comment]
Hi @cjgrauco,

Pushed a fix for the issue. Will make a release for it soon.

**Comment by pvldigital** [comment]
Hi @cjgrauco,

Fix added for release v2.5.10.
