### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by benjamminf** [spicywebau/craft-neo#3]
Seeing as I'm an uncultured [bogan](https://en.wikipedia.org/wiki/Bogan) who can't speak anything other than aussie, additional phrases that need translations are

#### Configurator

- `Block type`
- `The maximum number of blocks of this type the field is allowed to have.`
- `Child Blocks`
- `Which block types do you want to allow as children?`
- `Max Child Blocks`
- `The maximum number of child blocks this block type is allowed to have.`
- `Top Level`
- `Will this block type be allowed at the top level?`
- `Define the types of blocks that can be created within this Neo field, as well as the fields each block type is made up of.`
- `Delete block type`
- `Delete group`
- `Unable to nest Neo fields.`
- `Are you sure you want to delete this block type?`
- `Are you sure you want to delete this group?`

#### Input

- `Add block above`
- `Duplicate block`

#### Converting Neo to Matrix

- `This field is currently of the Neo type. You may automatically convert it to Matrix along with all of it's content.`
- `Convert`
- `By converting to Matrix, structural information will be lost.`
- `Are you sure? This is a one way operation. You cannot undo conversion from Neo to Matrix.`
- `Could not convert Neo field to Matrix`

Obviously not very important, but if anyone has some spare time to translate these phrases into a language they're fluent with, I'll write nice things about you in the README and maybe order you a pizza.

(If you are actually going to do this, I'm happy for you to either open a pull request with the translations implemented or just post them here)

**Comment by benjamminf** [comment]
*German* - Courtesy of Michael Jackson (cheers for that mate!)

- `Add block above => Block oberhalb hinzufügen`
- `Block type => Blocktyp`
- `The maximum number of blocks of this type the field is allowed to have. => Die maximale Anzahl an Blocks des Types, die dieses Feld besitzen darf.`
- `Child Blocks => Kind-Blöcke`
- `Which block types do you want to allow as children? => Welche Blocktypen möchtest Du als Kinder erlauben?`
- `Delete block type => Blocktyp löschen`
- `Delete group => Gruppe löschen`
- `Top Level => Höchste Ebene`
- `Will this block type be allowed at the top level? => Soll dieser Blocktyp für die höchste Ebene erlaubt sein?`
- `Define the types of blocks that can be created within this Neo field, as well as the fields each block type is made up of. => Definiere die Blocktypen, die dieses Neo-Feld haben darf und die Felder, aus denen jeder Block besteht.`
- `Unable to nest Neo fields. => Neo-Felder können nicht verschachtelt werden.`

**Comment by 23d1** [comment]
Swedish:

- `Add block above` → `Lägg till block ovanför`
- `Block type` → `Blocktyp`
- `The maximum number of blocks of this type the field is allowed to have.` → `Den maximalt tillåtna mängden block av den här typen`
- `Child Blocks` → `Underblock` (directly translates to `Barnblock`", but that's weird)
- `Which block types do you want to allow as children?` → `Vilka blocktyper vill du tillåta som underblock?`
- `Delete block type` → `Ta bort blocktyp`
- `Delete group` → `Ta bort grupp`
- `Top Level` → `Toppnivå`
- `Will this block type be allowed at the top level?` → `Ska den här blocktypen tillåtas på toppnivå?`
- `Define the types of blocks that can be created within this Neo field, as well as the fields each block type is made up of.` → `Definera de olika typerna av block som kan skapas i det här neofältet samt vilka fält som ska vara en del av den.`
- `Unable to nest Neo fields.` → `Kan inte nästla Neofält`
- `Duplicate block` → `Duplicera block`
- `Are you sure you want to delete this block type?` → `Är du säker på att du vill ta bort den här blocktypen?`
- `Are you sure you want to delete this group?` → `Är du säker på att du vill ta bort den här gruppen?`

**Comment by benjamminf** [comment]
Thank you so much @23d1 ! I'm going to add them in ASAP, and squeeze it into the 1.4.0 release.

I absolutely hate to bring this up, but I realised I had a few more phrases that have been added in 1.4.0, which I've edited in the original question. If it's not too much to ask, it'd be great to have them translated as well.

Thanks again, super stoked with the contribution 👍 As I'm a man of my word, are you hungry? 🍕

**Comment by 23d1** [comment]
@benjamminf updated! ;) No need for pizza, it's too expensive here in Los Angeles, but if you're ever in town I'll get you drunk, it's the least I could do for this awesome plugin. :) 🍺

**Comment by benjamminf** [comment]
@23d1 cheers for that! Haha well okay then, if you say so. I'll actually be in California over Jan/Feb, and briefly in LA. So maybe I'll take you up on that offer if it works for you 🍻

**Comment by 23d1** [comment]
@benjamminf dope! hit me up when you're heading out!

**Comment by ttempleton** [comment]
Going to close this issue now -- while we always greatly appreciate any translation contributions from the community, at this point we would prefer to discourage posting translations here and instead exclusively encourage pull requests.  Starting with Neo 2.9 (and already added to the [`neo-2.9`](https://github.com/spicywebau/craft-neo/blob/neo-2.9/src/translations/en/neo.php) branch), we will provide a default English translation file to make it easier for people to create translations for other languages.
