### ISSUE TITLE
Can't translate the block group buttons

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-neo#301]
#### Description

I can't translate the block group buttons. However, I can translate the block buttons. Please can you enable the ability to translate this?

![neo-translations](https://user-images.githubusercontent.com/4634192/75334972-053eff80-5889-11ea-90cd-8e05e922ddf4.png)

#### Steps to reproduce
1. Create a Neo field
2. Add translations to locale folder (example `translations/fr/neo.php`)
3. Check Entry fields translation

#### Other information
- Neo version: 2.6.1
- Craft version: Craft Pro 3.4.8

**Comment by pvldigital** [comment]
Hi @romainpoirier,

I'm not sure why that's the case. You should be able to write in any language for the groups.

See below for my example:

![Screen Shot 2020-02-28 at 11 12 41 am](https://user-images.githubusercontent.com/9030408/75498478-6991c880-5a1b-11ea-8cee-0923b511b9f9.png)

Is there any error you can see when saving the field?

**Comment by romainpoirier** [comment]
There is no error when saving the field, neither on the Entry, neither in the browser console. And I can confirm this happen for several of my Neo fields.

In my case, my primary website is in French, the User CP is setup to French, and all of these fields translations are stored inside `translations/fr/neo.php`.

**Comment by pvldigital** [comment]
Ah I understand now. Will have a look into it.

**Comment by romainpoirier** [comment]
This is the content of `translations/fr/neo.php` file:
```
<?php

return array (
	'Articles' => 'Articles',
	'Award' => 'Récompense',
	'Bar' => 'Bar',
	'Blog' => 'Blog',
	'Downloads' => 'Téléchargements',
	'Embed' => 'Intégration',
	'Events' => 'Événements',
	'Exhibitions' => 'Expositions',
	'FAQ' => 'FAQ',
	'Gallery' => 'Galeries',
	'Infos' => 'Infos',
	'Jumbotron' => 'Jumbotron',
	'Links' => 'Liens',
	'Medias' => 'Médias',
	'Posters' => 'Affiches',
	'Quote' => 'Citation',
	'Repeatable' => 'Répétable',
	'Scrolling Texts' => 'Textes Défilants',
	'Single' => 'Unique',
	'Text' => 'Texte',
	'Texts' => 'Textes',
);
```

**Comment by pvldigital** [comment]
Changes has been made for this issue in v2.6.3
