### ISSUE TITLE
Server-side validation to max blocks by type and valid child blocks

### ISSUE THREAD

**Issue by benjamminf** [spicywebau/craft-neo#31]
Currently the restrictions for limiting blocks by their type, and blocks owning child blocks, are entirely cosmetic (in other words, it's only enforced with client-side Javascript). This is fine for the most part, but if someone were to change the rules for a Neo block type, some current values of that field may then violate these rules. At the moment, you're able to continue saving these field values as if nothing has happened. Adding server-side validation will report these conflicts after a save.

**Comment by ttempleton** [comment]
Max blocks by type validation was added in 3.0.0. Validation of the child block types, max child blocks, top level and max sibling blocks of type settings has been added in the [4.x branch](https://github.com/spicywebau/craft-neo/tree/4.x) to be released in 4.0.0.
