### ISSUE TITLE
Update to 2.7.1.1 duplicates/triples neo field blocks

### ISSUE THREAD

**Issue by LarsDol** [spicywebau/craft-neo#318]
#### Description
This morning I updated the plugin to v2.7.1.1. I did this on my local machine first, and deployed to the client's staging server afterwards. Locally, I noticed no problems at all. Then after deploying to the staging server, a lot of the neo blocks were duplicated or even tripled. 

This wasn't fixed after saving the page as suggested. So we had to revert the database to a previous version. Not ideal!

#### Steps to reproduce
1. Update neo plugin (from 2.6.3 to 2.7.1.1)
2. Run migrations (`./craft migrate/all`)
3. Rebuild project config (`./craft project-config/rebuild`)
4. Test changes locally (seems to work perfectly fine)
5. Deploy to remote server (Which automatically runs `./craft migrate/all` on the environment's database)
6. Open any section with a Neo repeater field containing multiple blocks. Many of which now are tripled.

#### Other information
- Neo version: 2.7.1.1
- Craft version: 3.4.10.1

Edit:
It may be useful to know that the site has two languages (sites)

**Comment by zizther** [comment]
Same issue for myself, on the same versions.
Resaving entries did not solve the issue.

**Comment by studiobruikbaar** [comment]
I've got the same problem after updating to 2.7.1.1. (with Craft 3.4.10.1). All blocks are tripled, both in the CMS and front-end. 

Possible useful info: the website contains 3 languages as well.

**Comment by pvldigital** [comment]
Hi All,

I'm sure I know what the issue was and have added a fix for it

**Comment by zizther** [comment]
This issue is fixed for me using v2.7.2

**Comment by pvldigital** [comment]
@zizther awesome.

@LarsDol @studiobruikbaar did it work for you?

**Comment by studiobruikbaar** [comment]
@pvldigital Yes, everything works again after updating to v2.7.2. Thanks for the quick action.

**Comment by pvldigital** [comment]
@studiobruikbaar awesome.

@LarsDol since the others has their issues resolved I assume your one will be as well after updating.

**Comment by LarsDol** [comment]
Hi @pvldigital, thanks for the quick action! We'll test it soon, but currently on the verge of releasing some large updates to the rest of the codebase — so postponing the neo update for a bit. I assume everything works as intended now, as it does for the rest 🙂

If something pops up anyway I'll let you know.
