### ISSUE TITLE
On change event not trigger in redactor fields nested in a Neo when applying a style

### ISSUE THREAD

**Issue by kffein-david** [spicywebau/craft-neo#319]
#### Description
When changing style in a redactor bloc ( adding bold) for exemple, on change event is not trigger.
We need to change content of the redactor ( adding a space for exemple)

#### Steps to reproduce
1. having a redactor field into a new
2. had a bold in the redactor field
3. save the entry
4. reload the page
Result: bold is not applied.

But if we

1. having a redactor field into a new
2. had a bold in the redactor field
3. add a space in the redactor content
4. save the entry
5. reload the page
Result: bold is applied.

Also same step in a redactor not in a neo, Styles change works

#### Other information
- Neo version: 2.7 to 2.7.2
- Craft version:3.4.10.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: save block to all site
- Is eager-loading used? yes

**Comment by pvldigital** [comment]
@kffein-david v2.7.2.2 should fix this issue.
