### ISSUE TITLE
Block structure/order is completely screwed up since updating to 2.7.2.2

### ISSUE THREAD

**Issue by httpster** [spicywebau/craft-neo#320]
#### Description
Since updating to 2.7.2.2 if I need to edit an entry my blocks are all over the place. Completely out of order or no longer nested properly. I have a bunch of content edits I need to make, but now I need to take a screenshot of the page and then essentially rebuild it. Not ideal.

#### Steps to reproduce
1. Edit an existing entry

#### Other information
- Neo version: 2.7.2.2
- Craft version: 3.4.10.1

**Comment by pvldigital** [comment]
Hi @httpster,

Couple of questions:
Did you update from ~2.7.1 to the latest?
Can you check within the `neoblocks` table and see if there's any null values in the `sortOrder` column?
Is this a multisite?
Are you using mysql or postgresql?

If you could, can you send your composer files to plugins@spicyweb.com.au

**Comment by httpster** [comment]
I updated from 2.6.5.1. I've checked my neoblocks table and the sortOrder column is pretty much all 'Null', there are very few rows with an integer value. I am not using multisite, and the database is mysql. I've sent my composer files.

**Comment by pvldigital** [comment]
thanks for the info. it looks like the migration must have failed or didn't start at all for the `sortOrder` column.

can you check in the `migration` table and see if if has a row with `m200313_015120_structure_update` (or similar). if not try running `./craft migrate/up --plugin=neo`,

**Comment by httpster** [comment]
@pvldigital that row is in my migration table. Locally, I deleted that row and reran the migtation and my sortOrder table looks good now. I'll let you know if I notice anything weird, but I appreciate your help!
