### ISSUE TITLE
Resaving a Matrix Block in NEO results in "throw new Exception('Attempting to save an element in an unsupported site.');"

### ISSUE THREAD

**Issue by maxstrebel** [spicywebau/craft-neo#321]
#### Description
If you have a Matrix Block in a NEO Field the first save works fine. If you want to save it you get the error.

#### Steps to reproduce
1. Create a new Matrix Block nested in a NEO Field
2. Save entry
3. Reopen Entry
4. Edit content
5. Save

#### Other information
- Neo version: 2.7.3
- Craft version: Craft Pro 3.4.11
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: Save block to all sites the owner element is saved in
- Is eager-loading used? no

````
yii\base\Exception: Attempting to save an element in an unsupported site. in /var/www/html/vendor/craftcms/cms/src/services/Elements.php:1970
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2328): craft\services\Elements->_saveElementInternal(Object(craft\elements\MatrixBlock), true, false)
#1 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2133): craft\services\Elements->_propagateElement(Object(craft\elements\MatrixBlock), Array, Object(craft\elements\MatrixBlock))
#2 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\MatrixBlock), false, true, true)
#3 /var/www/html/vendor/craftcms/cms/src/services/Matrix.php(774): craft\services\Elements->saveElement(Object(craft\elements\MatrixBlock), false)
#4 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(954): craft\services\Matrix->saveField(Object(craft\fields\Matrix), Object(benf\neo\elements\Block))
#5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2555): craft\fields\Matrix->afterElementPropagate(Object(benf\neo\elements\Block), false)
#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2144): craft\base\Element->afterPropagate(false)
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(benf\neo\elements\Block), false, true, true)
#8 /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php(210): craft\services\Elements->saveElement(Object(benf\neo\elements\Block), false)
#9 /var/www/html/vendor/spicyweb/craft-neo/src/Field.php(689): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry))
#10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2555): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1283): craft\base\Element->afterPropagate(false)
#12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2144): craft\elements\Entry->afterPropagate(false)
#13 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#14 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(376): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#15 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('entries/save-en...', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('entries/save-en...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /var/www/html/web/index.php(21): yii\base\Application->run()
#25 {main}
````

**Comment by maxstrebel** [comment]
Just to add, it also does not save the element to the other site on first save. So this might the cause of the issue?

**Comment by pvldigital** [comment]
Hi @maxstrebel,

Hmm strange. I’ll have a look and see what I can do.

**Comment by Lennso** [comment]
> #### Description
> If you have a Matrix Block in a NEO Field the first save works fine. If you want to save it you get the error.
> 
> #### Steps to reproduce
> 1. Create a new Matrix Block nested in a NEO Field
> 2. Save entry
> 3. Reopen Entry
> 4. Edit content
> 5. Save
> 
> #### Other information
> * Neo version: 2.7.3
> * Craft version: Craft Pro 3.4.11
> * (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes
> * (if multi-site, > 2.4.0) What is the propagation method of the neo field: Save block to all sites the owner element is saved in
> * Is eager-loading used? no
> 
> ```
> yii\base\Exception: Attempting to save an element in an unsupported site. in /var/www/html/vendor/craftcms/cms/src/services/Elements.php:1970
> Stack trace:
> #0 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2328): craft\services\Elements->_saveElementInternal(Object(craft\elements\MatrixBlock), true, false)
> #1 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2133): craft\services\Elements->_propagateElement(Object(craft\elements\MatrixBlock), Array, Object(craft\elements\MatrixBlock))
> #2 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\MatrixBlock), false, true, true)
> #3 /var/www/html/vendor/craftcms/cms/src/services/Matrix.php(774): craft\services\Elements->saveElement(Object(craft\elements\MatrixBlock), false)
> #4 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(954): craft\services\Matrix->saveField(Object(craft\fields\Matrix), Object(benf\neo\elements\Block))
> #5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2555): craft\fields\Matrix->afterElementPropagate(Object(benf\neo\elements\Block), false)
> #6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2144): craft\base\Element->afterPropagate(false)
> #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(benf\neo\elements\Block), false, true, true)
> #8 /var/www/html/vendor/spicyweb/craft-neo/src/services/Fields.php(210): craft\services\Elements->saveElement(Object(benf\neo\elements\Block), false)
> #9 /var/www/html/vendor/spicyweb/craft-neo/src/Field.php(689): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry))
> #10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2555): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
> #11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1283): craft\base\Element->afterPropagate(false)
> #12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2144): craft\elements\Entry->afterPropagate(false)
> #13 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(530): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
> #14 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(376): craft\services\Elements->saveElement(Object(craft\elements\Entry))
> #15 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
> #16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> #18 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
> #19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
> #20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('entries/save-en...', Array)
> #21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('entries/save-en...', Array)
> #22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
> #23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
> #24 /var/www/html/web/index.php(21): yii\base\Application->run()
> #25 {main}
> ```

Same here

**Comment by pvldigital** [comment]
@maxstrebel @Lennso currently trying to replicate the issue. can you tell me what the propagation method is for the matrix field?

**Comment by maxstrebel** [comment]
There are several Matrix Fields in use, but they should all be set to "Save blocks to all sites the owner element is saved in"

I was using Icon Picker (which is now removed) and use Super Table once. But not in the given case.

![image](https://user-images.githubusercontent.com/910594/78111919-b17e8380-73fd-11ea-9442-af8d1657f441.png)

**Comment by Lennso** [comment]
<img width="1676" alt="Bildschirmfoto 2020-04-01 um 14 43 52" src="https://user-images.githubusercontent.com/11076634/78138475-3fbb2f80-7427-11ea-8746-7567666bbedc.png">
<img width="995" alt="Bildschirmfoto 2020-04-01 um 14 43 15" src="https://user-images.githubusercontent.com/11076634/78138487-42b62000-7427-11ea-9a52-1603157b516a.png">

If I want to change Dropdown value, the error occured. i use multi-site-setup and each field is saved on website base.

**Comment by pvldigital** [comment]
@maxstrebel @Lennso i've been trying to replicate the issue on my end but still weren't able to recreate it. is it possible for you to send your db and composer files to plugins@spicyweb.com.au?

**Comment by maxstrebel** [comment]
I will try. This happened on a Client project which I might not be allowed to share. But I'll try to pin it down.

It "might" be an issue with a set siteUrl, as I found out that this can cause trouble with the primarySite, which was new to me. I had set the site URL like this:

```
'siteUrl' => [
    'handle_one' => '...',
    'handle_two' => '...',
],
```

and got the error `An Error occurred while handling another error:
craft\errors\SiteNotFoundException: No primary site exists in /var/www/html/vendor/craftcms/cms/src/services/Sites.php:489` down the road.

I had no time to investigate yet, if siteUrl caused this and if this might have affected NEO. For now I rolled back to 2.6, where the problem did not occur yet.

**Comment by pvldigital** [comment]
@maxstrebel thanks for the update. I'll keep looking into it on my end as well.

**Comment by Lennso** [comment]
Thanks for the fast update. It fixed the problem.

**Comment by pvldigital** [comment]
@Lennso oh the latest release fixed it for you?

@maxstrebel if you have a chance can you test it out as well?

**Comment by maxstrebel** [comment]
@pvldigital sorry, not yet. But I will as soon as go-live is done ;)

**Comment by pvldigital** [comment]
@maxstrebel have you had a chance to test it out?

**Comment by maxstrebel** [comment]
@pvldigital will test next week. Sorry to keep you waiting.

**Comment by maxstrebel** [comment]
Okay, tested it. Works. Though I'm still not sure if this might have been the `siteUrl` parameter, which seems to have issues with default site.

I will try to test it myself when I find the time:

1. New setup without siteUrl in general.php
2. Create Sites via Backend, set a default Site
3. AFTER that: create a siteUrl Array

This happened in my project. As I said, I don't know if that created the problem.
