### ISSUE TITLE
Empty Neo tables left behind after uninstall...

### ISSUE THREAD

**Issue by kerns** [spicywebau/craft-neo#322]
I don't know if this is a bug or if this is how Crafts plugin model is designed by I gave Neo a quick test drive, uninstalled it shortly thereafter, but noticed four (empty) tables remained in my database. I'm inclined to remove them, but wanted to let you know these were being orphaned. Again, maybe this is normal.

**Comment by pvldigital** [comment]
Hi @kerns,

It should be fine to remove them.
