### ISSUE TITLE
NEO field content disappears after preview → save (appears again with reload)

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#323]
#### Description
When I make some changes to a page while being in preview mode, then press "publish changes," the site will reload and all the contents of the Neo field will not show up. It shows an empty Neo field. 
After pressing reload, the field shows up again with all its contents.
I am not sure whether this is purely Neo-related or also craft-related. However, all other fields on that page load just fine.

#### Steps to reproduce
1. Open a page with at least one Neo field 
2. Go into LivePreview and make a change to _any_ field.
3. Leave LivePreview and "Publish Changes"

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.11
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: not multisite
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: not multisite
- Is eager-loading used? no

**Comment by pvldigital** [comment]
Ah i think I know the issue. Will make some changes for it

**Comment by luke-nehemedia** [comment]
Thank you!

**Comment by luke-nehemedia** [comment]
Latest update resolved the issue.
