### ISSUE TITLE
SQL error after updating to 2.7.3

### ISSUE THREAD

**Issue by pablofernandezgh** [spicywebau/craft-neo#324]
#### Description
I run into this SQL error after updating Neo from **2.5.7** to **2.7.3** and Craft from **3.3.14** to **3.4.11**
I go to an entry which contains a neo fields, and this happens

Database Exception – yii\db\Exception
SQLSTATE[42803]: Grouping error: 7 ERROR: column "elements.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "elements"."id", "elements"."fieldLayoutId", "element...
^
The SQL being executed was: SELECT "elements"."id", "elements"."fieldLayoutId", "elements"."uid", "elements"."enabled", "elements"."archived", "elements"."dateCreated", "elements"."dateUpdated", "elements_sites"."slug", "elements_sites"."siteId", "elements_sites"."uri", "elements_sites"."enabled" AS "enabledForSite", "neoblocks"."fieldId", "neoblocks"."ownerId", "neoblocks"."typeId", "neoblocks"."sortOrder", "content"."id" AS "contentId", "content"."field_adCopy", "content"."field_adTitle", "content"."field_alignment", "content"."field_backgroundColor", "content"."field_callToActionText", "content"."field_chipCopy", "content"."field_externalLink", "content"."field_headerTitle", "content"."field_blockId", "content"."field_imageAlt", "content"."field_imageCaption", "content"."field_imageTitle", "content"."field_immowebUrl", "content"."field_ctaLevel", "content"."field_linkUrl", "content"."field_metaDescription", "content"."field_metaKeywords", "content"."field_position", "content"."field_resultListAdCopy", "content"."field_richText", "content"."field_script", "content"."field_secondaryCallToActionText", "content"."field_secondaryExternalLink", "content"."field_isTargetBlank", "content"."field_isTargetBlankSecondary", "content"."field_showSocialMediaShareLinks", "content"."field_size", "content"."field_target", "content"."field_textAlignment", "content"."field_customTitle", "content"."field_titleLevel", "content"."field_videoId", "content"."field_videoTitle", "structureelements"."root", "structureelements"."lft", "structureelements"."rgt", "structureelements"."level", "structureelements"."structureId"
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId", "structureelements"."structureId"
FROM "elements" "elements"
INNER JOIN "neoblocks" "neoblocks" ON "neoblocks"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON ("content"."elementId" = "elements"."id") AND ("content"."siteId" = "elements_sites"."siteId")
LEFT JOIN "structureelements" "structureelements" ON ("structureelements"."elementId" = "elements"."id") AND (EXISTS (SELECT *
FROM "structures"
WHERE ("id" = "structureelements"."structureId") AND ("dateDeleted" IS NULL)))
WHERE ("neoblocks"."fieldId"=2) AND ("neoblocks"."ownerId"=215) AND ("elements_sites"."siteId"=2) AND ("elements"."archived"=FALSE) AND ("elements"."dateDeleted" IS NULL) AND ("elements"."draftId" IS NULL) AND ("elements"."revisionId" IS NULL)) "subquery"
INNER JOIN "neoblocks" "neoblocks" ON "neoblocks"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
LEFT JOIN "structureelements" "structureelements" ON ("structureelements"."elementId" = "subquery"."elementsId") AND ("structureelements"."structureId" = "subquery"."structureId")
GROUP BY "neoblocks"."fieldId", "neoblocks"."ownerId", "neoblocks"."typeId", "neoblocks"."sortOrder"
ORDER BY "neoblocks"."sortOrder"

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.11

**Comment by pvldigital** [comment]
Hi @pablofernandezgh,

Are you using postgresql?

**Comment by pablofernandezgh** [comment]
Hello @pvldigital 
Yes indeed postgresql 10.6

**Comment by pvldigital** [comment]
@pablofernandezgh the latest release contains a fix for sure issue. can you test it out on your end and see if it works?

**Comment by pablofernandezgh** [comment]
Yep that fixed it, thanks a lot
