### ISSUE TITLE
Displaced children

### ISSUE THREAD

**Issue by gglnx** [spicywebau/craft-neo#325]
#### Description

Since upgrading 2.7.3 we got sometimes the problem, that after saving an entry, all children get displaced from thier parents and all blocks are on the root level. Only moving all children to the correct parents after saving helps.

#### Steps to reproduce
I couldn't find a way to reproduce the problem yet.

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.11

**Comment by pvldigital** [comment]
Hi @gglnx,

When the issue occurs were you editing a draft and publishing the changes?

**Comment by gglnx** [comment]
My users say yes (I didn't encountered the problem yet myself), mostly using the live preview.

**Comment by gglnx** [comment]
I reproduced the problem, like you said after editing a draft:

1. Create an entry with a Neo block
2. Publish it
3. Open it again, change like the title and save it as draft
4. Publish the draft

Now the the child blocks are outsite thier parents.

**Comment by pvldigital** [comment]
Hi @gglnx,

The latest release should have fixed the issue. Did you try it out?

**Comment by gglnx** [comment]
Yes, looks goods. Thank you!

**Comment by gglnx** [comment]
I'm sorry. We got still the issue. Our hotfix is to patch out the job creation (`src/services/Fields.php`) and make everything synchronous.

**Comment by yoannisj** [comment]
I have been experiencing the same issue, with live entries as well (not only drafts), on every save, but only for one of the neo fields on the site. I then noticed that the entry were the Neo field was used, also made use of a Preparse field, which was rendered beforeSave and accessed the neo field contents using a `type` criteria.

Updating the Preparse field's twig code to not include any filtering criteria when accessing neo blocks, but rely on array filters instead, fixed the issue:

Removes parent blocks:
```
{% set firstAppointment = element.appointments.type('appointment').one() %}
```

Works:
```
{% set appointments = element.appointments.all() %}
{% set firstAppointment = blocks | filterByValue('type.handle', 'appointment') | first %}
```

After looking in the data stored in the database, it looks like the use of `type('appointment')` prevents saving of the parent blocks, which are of a different type. It could actually remove all other block types, but I could not test this as my field only has 2 block types.

I hope this extra information helps solve the issue!

**Comment by yoannisj** [comment]
@gglnx , it might be worth checking if you have any code that runs on the `Elements::EVENT_BEFORE_SAVE` event and accesses your Neo field blocks in a similar way (by selecting some blocks only with query criteria).

**Comment by pvldigital** [comment]
@gglnx a new release with changes to the job has been made. if you can test it out and see if it resolves your issue.

**Comment by gglnx** [comment]
Now it works. Thank you @pvldigital! :)

**Comment by rbaud** [comment]
We have been experiencing this issue off and on for at least a couple of months, and I can confirm that it is still an issue (this morning) with Neo 2.7.12 and Craft 3.4.21.
