### ISSUE TITLE
Changes to links are not saved

### ISSUE THREAD

**Issue by its-me-mario** [spicywebau/craft-neo#329]
#### Description
Saving changes to a link on a (redactor) rich text field usually don't save changes. When the rich text field content is saved the first time everything seems fine but when editing an existing entry, updates to links don't save. This includes changes to: target, unlinking, link text and link url.

There are no console errors and did not notice any errors in the Craft debug toolbar or the logs.  I've tested the same field without it being in a Neo block and everything works as expected.

#### Steps to reproduce
[Video can be seen here](https://drive.google.com/open?id=1AML1HL1xvBC2jhbdJWDodvToUcUOuJfW)

1. Create (and save) an entry that has a rich text (redactor) field in a Neo block. Make sure the rich text field has a link in it.
2. After the entry is saved, edit the entry and make changes to the link.
3. Save the link changes, then save the entry.
4. Edit the same entry again and see that the changes did not save.

#### Other information
- Neo version: 2.6.5.1
- Craft version: 3.4.10.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: **Not tested with multi-site**
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: **Not tested with multi-site**
- Is eager-loading used? **no**

This WILL work if:
1. make link changes
2. toggle to HTML view
3. toggle back to WYSIWYG view
4. save entry

Also tested with:
- Neo 2.7.3 and Craft 3.4.12 (same issue)
- Neo 2.5.9 and Craft 3.3.20.1 (issue does not exist)
- Neo 2.4.8 and Craft 3.2.10 (issue does not exist)

**Comment by pvldigital** [comment]
Hi @its-me-mario,

It looks like the current detection of changes for redactor isn't working that well with the delta updates. I'll look into rewriting it to make it work as intended.

**Comment by pvldigital** [comment]
@its-me-mario the latest release should have fixed this issue. have you tried it out yet?

**Comment by its-me-mario** [comment]
yes, it is working in 2.7.5.

Thanks!

**Comment by pvldigital** [comment]
Awesome, good to know it’s working for you
