### ISSUE TITLE
Collapsed blocks don't show preview until you click it once

### ISSUE THREAD

**Issue by andrewfairlie** [spicywebau/craft-neo#331]
#### Description
Collapsing blocks is useful on entries with loads of nested blocks. But currently, the preview of what's inside a block doesn't show on page load which reduces how useful it is

#### Steps to reproduce
1. Collapse a block with nested blocks
2. Save the entry
3. Go back to the entry
4. The preview doesn't show until you click it

**On Load**
![image](https://user-images.githubusercontent.com/1772888/79068406-84b05300-7cbe-11ea-8250-1713675b1afa.png)

**After expanding and then collapsing again**
(See top block)

![image](https://user-images.githubusercontent.com/1772888/79068418-9eea3100-7cbe-11ea-9e5d-c84b387b5e16.png)

**GIF in case it's easier to explain**
![Courses](https://user-images.githubusercontent.com/1772888/79068478-11f3a780-7cbf-11ea-8746-a5bbb123f98d.gif)

#### Other information
- Neo version: 2.7.6
- Craft version: 3.4.15
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: N/A
- Is eager-loading used? N/A

**Comment by pvldigital** [comment]
Hi @andrewfairlie,

I'll look into it.

**Comment by pvldigital** [comment]
Hi @andrewfairlie,

Issue with the preview is resolved in the latest version, 2.7.7.
