### ISSUE TITLE
Serialization of 'Closure' not allowed

### ISSUE THREAD

**Issue by jarheadcore** [spicywebau/craft-neo#332]
#### Description
Keep getting the error «Serialization of ‘Closure’ is not allowed» when I try to save an entry that contains a wheelform form field inside a Neo content builder.

#### Steps to reproduce
1. Open entry, select new neo block with wheelform field (to select a form)
2. Save entry -> Error

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.12
- Wheelform version: 2.4.2
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used? -> No

[errormessage screenshot](https://imgur.com/5jPPzgG)

**Comment by pvldigital** [comment]
Hi @jarheadcore,

Can you try updating to the latest version? I've made changes to neo job structure for the last couple versions.

Also if possible can you send your web and queue log to plugins@spicyweb.com.au

**Comment by jarheadcore** [comment]
Good Morning

Updating the plugin solved the issue, thank you for the fast reply

Kind regards
Christian

Am Do., 16. Apr. 2020 um 09:03 Uhr schrieb PL <notifications@github.com>:

**Comment by pvldigital** [comment]
Awesome good to know it worked for you.

**Comment by luke-nehemedia** [comment]
Unfortunately this issue reoccured to me in Craft 4. 

Whenever I access the form variable from within Neo, I get this error.
