### ISSUE TITLE
Assets already uploaded don't appear on new entries

### ISSUE THREAD

**Issue by joruro** [spicywebau/craft-neo#333]
#### Description
Our assets are configured to dynamic upload locations (e.g. `{{object.section.handle}}`)

<img width="589" alt="Screenshot 2020-04-16 at 14 35 14" src="https://user-images.githubusercontent.com/12788171/79456858-87c57f00-7fef-11ea-8062-dc6bed5408d1.png">

It happens that when creating a new entry, the user can't see the already uploaded assets for that location. I also found out that if you then refresh the page, you will be able to see the assets.

![out](https://user-images.githubusercontent.com/12788171/79457059-d6731900-7fef-11ea-992e-7b41ee1af29f.gif)
 
#### Other information
- Neo version: 2.5.10
- Craft version:  3.3.20.1

**Comment by pvldigital** [comment]
Hi @joruro,

There was a similar issue previously, #233, and this was fixed in version v2.6.2.

**Comment by joruro** [comment]
Thanks!

**Comment by joruro** [comment]
Hey @pvldigital 

I've updated the NEO and CraftCMS. The issue was fixed for entries, but for categories I still have the same issue.

Neo version: 2.7.7.1
Craft version: 3.4.16

**Comment by pvldigital** [comment]
@joruro ah really? i'll have a look into it.

**Comment by pvldigital** [comment]
@joruro can you post the sub path used for categories?

**Comment by pvldigital** [comment]
@joruro fix has been made for this issue in v2.7.9

**Comment by pvldigital** [comment]
Hey @joruro, has the release fixed the issue for you?

**Comment by joruro** [comment]
Hey @pvldigital 
Thanks for the fix but still having the same issue. I've updated everything to the latest.

Neo version: 2.7.10
Craft version: 3.4.18

**Comment by pvldigital** [comment]
@joruro ah really? is the issue still happening within the category?

**Comment by joruro** [comment]
Yes, only on the categories now. Entries was fixed

**Comment by pvldigital** [comment]
@joruro hmm that's strange. can you send me the sub path for the asset field?

**Comment by ttempleton** [comment]
I can reproduce this issue with categories and also Craft Commerce products.  I'll test with other element types to confirm those, but it seems like the lack of element ID for new categories and products (as opposed to entries, which already have an ID thanks to the automatic saving of entry drafts) is causing Neo not to be able to set the correct folder to view when dynamic asset paths are involved, so it loads the user's temporary uploads folder instead.  I'll keep looking into it and see if there's another way around this.

**Comment by ttempleton** [comment]
This has been fixed in Neo 2.7.12.  Neo now passes the owner element through to the Neo blocks when rendering the block tabs on an element edit page, rather than just the owner ID, so a dynamic upload path using properties of the owner element will have the appropriate owner to query even if the owner hasn't been saved yet.
