### ISSUE TITLE
relatedTo criteria seems to mess with following queries

### ISSUE THREAD

**Issue by medoingthings** [spicywebau/craft-neo#338]
#### Description
I have a weird behavior of Neo in combination with the `relatedTo` criteria.

When I do this – I get the data I expect:

    {% set defaultTarget = person.shortDescriptions.type('defaultText').one %}
    {% set relatedTarget = person.shortDescriptions.type('relatedText').relatedTo(entry).one %}

But as soon as I switch out those lines into the following – `defaultTarget` becomes `null`:

    {% set relatedTarget = person.shortDescriptions.type('relatedText').relatedTo(entry).one %}
    {% set defaultTarget = person.shortDescriptions.type('defaultText').one %}

So it seems like the query with `relatedTo` in it, messes up the following query. As soon as I remove the `relatedTo` from the query, the second example works, too.

#### Steps to reproduce
1. Have a Neo field with two blocks – one with just a text field (defaultText), another with a text field and an entry field (relatedText)
2. Try the code examples above

#### Other information
- Neo version: 2.7.7.1
- Craft version: 3.4.16
- Is eager-loading used: no

**Comment by pvldigital** [comment]
Hi @medoingthings,

Hmm that is strange. I'll have a look into it.

In the second example what does `defaultTarget` return compared to the first one?

**Comment by medoingthings** [comment]
Thanks for getting in touch @pvldigital.

In the first example I get the Neo block as expected, so I can get the text like this: `{{ defaultTarget.richtext }}`
In the second example `defaultTarget` is `null`.

**Comment by pvldigital** [comment]
@medoingthings ah sorry I didn't read your initial comment correctly, just noticed you said it was `null`. 

As for this issue, it's because `relatedTo` has been set previously in `relatedTarget`, which sets it for the whole query. You'll need to set the `relatedTo` to `null` before it can be queried. Or clone the block query beforehand first so it can do two separate queries.

e.g
```
{% set relatedTarget = person.shortDescriptions.type('relatedText').relatedTo(entry).one %}
{% set defaultTarget = person.shortDescriptions.type('defaultText').relatedTo(null).one %}
```

However it should reset when making a new query so i'll keep looking into it.

**Comment by pvldigital** [comment]
Hmm it looks like the matrix field also behaves like this. I assume this is just how `relatedTo` is used.

**Comment by pvldigital** [comment]
since this inherently how the query works in craft, which neo extends, there's not much I can do. The method I listed above to get around the issue will work though as it clears the `relatedTo` in the query.

**Comment by medoingthings** [comment]
Thanks @pvldigital for digging into this. Good to know there is a workaround. 

Keep up the great work, cheers!
