### ISSUE TITLE
Return value of benf\neo\Plugin::_setupBlocksHasSortOrder() must be an instance of benf\neo\void, none returned after updating from 2.7.6 to 2.7.8

### ISSUE THREAD

**Issue by tyssen** [spicywebau/craft-neo#342]
#### Description
I've just updated Neo from 2.7.6 to 2.7.8 and everything went fine on my local, but when running the update on staging, I got

> Exception 'TypeError' with message 'Return value of benf\neo\Plugin::_setupBlocksHasSortOrder() must be an instance of benf\neo\void, none returned'
> in /vendor/spicyweb/craft-neo/src/Plugin.php:237

in the terminal and the same message when visiting any page, front or back end.

#### Steps to reproduce
1. Composer update on local, everything checks out OK
2. Commit, push to staging
3. Composer install on staging, it reports

> Updating spicyweb/craft-neo (2.7.6 => 2.7.8): Downloading (100%)

and then when it runs through

> @php craft migrate/all

it produces the error.

#### Other information
- Neo version: 2.7.8
- Craft version:  3.4.17.1
- Is eager-loading used? In some places

**Comment by pvldigital** [comment]
Hi @tyssen,

Fix has been made for this issue. Released in v2.7.9

**Comment by tyssen** [comment]
Getting a different error now when trying to create a new entry (resaving old ones works OK):

> Return value of benf\neo\services\Fields::_saveNeoStructuresForSites() must be an instance of benf\neo\services\void, none returned
>  in /vendor/spicyweb/craft-neo/src/services/Fields.php

**Comment by pvldigital** [comment]
Hi @tyssen, which php version are you using?

**Comment by tyssen** [comment]
7.0.33

**Comment by pvldigital** [comment]
Ah that’s probably why. The void return type isn’t available in 7.0. Will make the changes so it’s more compatible.

**Comment by pvldigital** [comment]
@tyssen v2.7.9.1 has removed the `void` return type. This should make it compatible with php 7.0

**Comment by pvldigital** [comment]
@tyssen so is everything good on your end? if so we can close this issue.

**Comment by tyssen** [comment]
Yep, all good.
