### ISSUE TITLE
Update Neo styles to match 3.4

### ISSUE THREAD

**Issue by chasegiunta** [spicywebau/craft-neo#346]
The styles of Matrix blocks have changed slightly (a little more blue, a little less lines) with 3.4 and it sure would be _swell_ if Neo's block styling was updated to match!

**Comment by pvldigital** [comment]
Hi @chasegiunta,

Sure I can do that. Should be available in the next release.

**Comment by pvldigital** [comment]
Hi @chasegiunta,

Just released a new version, 2.7.10. It has styling for neo blocks that are more inline with craft 3.4.
