### ISSUE TITLE
Conditional for first and last Neo blocks of certain type

### ISSUE THREAD

**Issue by tyssen** [spicywebau/craft-neo#347]
I want to have a Neo column block that can contain some text followed by some FAQs followed by more text. Column, text, and FAQ are all separate blocks; columns can contain text and FAQs.

I also want to wrap the FAQs in an element so, as the loop is running, I need a conditional for the first and last FAQ block types.

I thought I might be able to do something like this:

    {% for module in neoField.children.all() %}
      {% set firstFAQ = module.type('moduleFaq').one() %}
      {% set firstFAQId = firstFAQ ? firstFAQ.id : null %}
      {% set lastFAQ = module.type('moduleFaq').last() %}
      {% set lastFAQId = lastFAQ ? lastFAQ.id : null %}
      {% include '_partials/_' ~ module.type %}
    {% endfor %}

and then in the included template, test whether the block ID matches `firstFAQId`/`lastFAQId` but if I try just printing those variables out, I get no output. Does Neo have a different syntax for getting `module.type` in this scenario?

**Comment by pvldigital** [comment]
Hi @tyssen,

You could try something like this instead:
```
{% set firstFAQ = neoField.children.type('moduleFaq').one() %}
{% set firstFAQId = firstFAQ ? firstFAQ.id : null %}
{% set lastFAQ = neoField.children.type('moduleFaq').last() %}
{% set lastFAQId = lastFAQ ? lastFAQ.id : null %}
{% for module in neoField.children.all() %}
  {% include '_partials/_' ~ module.type %}
{% endfor %}
```
Explanation: the `module` is the returned data and not a block query which is why when you try to output the `id` it displays nothing. You'll need to query the `first` and `last` FAQ outside the loop first before doing what you need.

**Comment by tyssen** [comment]
Great, thanks. That's what I needed. 👍
