### ISSUE TITLE
Changes to text/Redactor fields are invisibly lost after required relationship field update

### ISSUE THREAD

**Issue by royslampaq** [spicywebau/craft-neo#350]
#### Description
If changes are made to a Neo field which includes both a Redactor field and a Content or Asset field, where the Asset field fails verification at first, the changes to the Content field seem to still be present, but if the Neo field is saved after the Relation/Asset field is fixed, the changes to the Redactor field are lost.

#### Steps to reproduce
1. Have an entry with a Neo field with a block containing a Redactor field.
2. Make changes to the text of the Redactor field
3. Add a block containing a required Content field to the entry's Neo field, but leave it empty
4. Try to save the Entry. This fails with an error message, and the Content field is highlighted. The Redactor field will still show the changes.
5. Either fill in the required Content field or remove the block containing it.
6. Save the Entry again. This now succeeds, but the changes to the Redactor field are gone, and aren't applied on the front end either.

#### Other information
- Neo version: 2.7.10
- Craft version: Craft Pro 3.4.20
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: 'Only save blocks to the site they were created in'
- Is eager-loading used?: No

**Comment by ttempleton** [comment]
Thanks for reporting this, @royslampaq; turns out the blocks' modified state was not being set on the page reload, causing any blocks not modified after the validation error not to be resaved.  This has now been fixed in Neo 2.7.11.
