### ISSUE TITLE
Collapsed field cover action buttons on right side

### ISSUE THREAD

**Issue by lexislav** [spicywebau/craft-neo#351]
In some cases collapsed Neo field summary covers action buttons on right side and is harder to locate them.
This happens at least when another Neo block or Supertable is nested.
I guess it would desire a bit of tuning.

![image](https://user-images.githubusercontent.com/7147349/82883894-55d6ff00-9f43-11ea-8725-575f1ac505b4.png)

**Comment by ttempleton** [comment]
Thanks for reporting this, @lexislav, it has now been fixed in Neo 2.7.13.
