### ISSUE TITLE
Disabling parent block in live preview causes children to save to top level

### ISSUE THREAD

**Issue by tom-id-au** [spicywebau/craft-neo#356]
#### Description
When editing in live preview, if you disable a block, the child blocks are saved on the same level as the parent block, not child blocks. Does not occur outside of live preview.

#### Steps to reproduce
1. Create a page with a block with child blocks
2. Open in live preview and disable the parent block
3. Save, then check back to find the child blocks on same level as parent (top level)

#### Other information
- Neo version: 2.7.13
- Craft version: Craft Pro 3.4.22.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by tom-id-au** [comment]
It appears to be okay with Neo 2.7.13 and Craft 3.4.20, so I'm assuming it is an issue that has come out in Craft 3.4.21, Craft 3.4.22 or Craft 3.4.22.1. There are lots of changes relating to structures in those Craft updates.

**Comment by ttempleton** [comment]
Thanks for reporting this, @tom-id-au; I can see this behaviour for any case where the parent block is disabled while editing a draft entry, not just when live previewing an entry.  I'll keep looking into what's happening to cause this.

**Comment by ttempleton** [comment]
This was happening during the Neo fields service's `duplicateBlocks()` method call, which internally calls the Craft elements service's `duplicateElement()` method, so I suspect that Craft's element duplication is causing this somehow.  In any case, the newest Neo release v2.7.14 makes sure that a duplicate block has the same level as the original block, which fixes this issue.

**Comment by tom-id-au** [comment]
Thank you @ttempleton for the rapid patch! I've tested on my local and deployed to staging, working there too. 👍
