### ISSUE TITLE
Can't create a new block 

### ISSUE THREAD

**Issue by jacksoncool** [spicywebau/craft-neo#357]
#### Description
I upgraded to the most recent version of Craft and Neo. When I try to create a new neo field, I'm unable to create a new block. This only occurs when creating a new neo field. Not working with existing fields. 

The only way i can make things work correctly is to save the field, then go back in and edit. 

#### Steps to reproduce
1. Create new field 
2. select neo type
3.select block type> nothing happens. 

#### Other information
- Neo version:  2.7.13
- Craft version: Craft Solo 3.4.22.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Hi @jacksoncool,

Similarly to #358 I've been unable to reproduce this, and I'm wondering if any JavaScript errors are occurring when you try this.  If there are JavaScript errors, could you please also let us know the other plugins and plugin versions you have installed?

**Comment by ttempleton** [comment]
I'm going to assume you've got the issue sorted out, then, but if the issue persists, please let us know and we'll reopen it.
