### ISSUE TITLE
Link plugins don't work correctly with Neo 

### ISSUE THREAD

**Issue by jacksoncool** [spicywebau/craft-neo#358]
#### Description
I've tried all the link field plugins and none of them work correctly with neo. The Linkit plugin options do not show up all. And all three including Linkit, The Typed Link field, and LInk none of them can be "replicated" when you are creating an entry. 

#### Steps to reproduce
1.
2.
3.

#### Other information
- Neo version:
- Craft version:
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Hi @jacksoncool,

I've been unable to reproduce this so far, all three link plugins seem to be working with Neo when I test them.  Are there any JavaScript errors when the fields aren't working?

**Comment by ttempleton** [comment]
I'm going to assume you've got the issue sorted out, then, but if the issue persists, please let us know and we'll reopen it.
