### ISSUE TITLE
After updating from craft 2 to craft 3 why  old neo contents are missing in backoffice entries?

### ISSUE THREAD

**Issue by berraisabdelaziz** [spicywebau/craft-neo#359]
#### Description
After updating craft to craft 3 and installing Neo plugin for craft 3, old neo contents not appear for all entries  
#### Steps to reproduce
1. update craft 2 with neo plugin  to craft 3
2. Install new plugin Neo for craft 3
3. Go to backoffice and open entries => old contents built with Neo are missing 

#### Other information
- Neo version: Neo 2.7.9.1
- Craft version: Craft CMS 3.5.0-beta.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:
- (if multi-site, > 2.4.0) What is the propagation method of the neo field:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Hi @berraisabdelaziz,

I've been running some test upgrades, upgrading from Craft 2.9.2 and Neo 1.5.2 to various recent Craft 3.x (including Craft 3.5 beta 1, 2, and the latest from Craft's `3.5` branch at the time of this comment) and the latest release of Neo, 2.7.15.  In my tests so far, all of the Neo blocks are still there after the upgrade, so at this stage I'm not sure what is happening in your case.

That said, we generally won't guarantee that everything will work fine with a beta release of Craft; we would recommend using Neo with the latest stable Craft release.  Are the Neo blocks still there if you upgrade to the latest Craft 3.4 release and Neo 2.7.15?

**Comment by berraisabdelaziz** [comment]
Hi @ttempleton 
Thank you for your reply.
I have the same problem after updating Neo to 2.7.15, But I can't Downgrade craft to 3.4 is not possible.
To explain more my problem: 
-All Fields created with neo appear in back office Fields, but when we open entries from backoffice, neo contents are missing. For example  in my home page with craft 2 I have several neo content like home page slider , ect, now in craft 3 this page is empty no any fields or block exist. I have only the neo dropdown to construct new contents

**Comment by ttempleton** [comment]
Hmm, that is strange.  If you look into the database, are the Neo blocks all still there in the `neoblocks` table?

**Comment by berraisabdelaziz** [comment]
All the tables of neo module exist in our database
![Annotation 2020-06-09 150926](https://user-images.githubusercontent.com/49982155/84151292-6cad4380-aa63-11ea-9e2b-57f3e485065c.png)
neoblocks table
![Annotation 2020-06-09 150601](https://user-images.githubusercontent.com/49982155/84151326-7d5db980-aa63-11ea-8fea-627b473a7965.png)

**Comment by berraisabdelaziz** [comment]
The  neoblockstructures table contains 127 records 
FieldId ("338" 3 times and "459" 124 times), 
ownerSiteId ("1" 7 times and "null" 120 times
![Annotation 2020-06-11 095516](https://user-images.githubusercontent.com/49982155/84360130-ed864f80-abc9-11ea-9cf1-4178a390d29b.png)

For the ownerId column all records are not the same except these values
![Annotation 2020-06-11 101351](https://user-images.githubusercontent.com/49982155/84361700-540c6d00-abcc-11ea-90ad-3f137ffad2f4.png)

**Comment by ttempleton** [comment]
Thanks for posting the screenshots, @berraisabdelaziz.  I can see something strange happening in the second screenshot: there are cases where two structures have the same `ownerId` and `fieldId`, but one of them has `ownerSiteId` = 1, and the other has `ownerSiteId` = null.  I think this is why fields are not showing their blocks: they're looking at the wrong structure.

Could you please try two things for me:
- Firstly, try deleting the row in the `neoblockstructures` table with `ownerId` = 2, `ownerSiteId` = 1, `fieldId` = 459.  I'm assuming that `ownerId` = 2 means this belongs to your Homepage entry, so see if that field's blocks are appearing on the Homepage after deleting that row.
- If that didn't work, restore the database; delete the row with `ownerId` = 2, `ownerSiteId` = null, `fieldId` = 459; and set the other row's `ownerSiteId` to null.

If one of those works, let me know which one, and I'll see if I can write a content migration to handle all of those cases.

**Comment by berraisabdelaziz** [comment]
Thank you @ttempleton my problem is solved
by deleting this line all neo block appear in backoffice
![Annotation 2020-06-15 184419](https://user-images.githubusercontent.com/49982155/84684020-5b1edc80-af38-11ea-9ed7-5255ed232637.png)

**Comment by ttempleton** [comment]
In that case, [this content migration](https://gist.github.com/ttempleton/24344fa944ab09082a5eabc07718c782) should remove all of those cases with `ownerSiteId` = 1.  Save that in your project's `migrations` folder, run it and that should hopefully get all of your blocks to appear again.  Let me know how it goes!

**Comment by ttempleton** [comment]
Oh, I think I misread your comment; if the homepage was the only entry with missing blocks, then it's great that you've got all your blocks back now.  I'll leave my previous comment up with the link to the content migration I wrote, in case it's useful to you or anyone else in the future.  I'll close this issue now, but please let us know if there are any other issues!
