### ISSUE TITLE
Duplicate all selected blocks

### ISSUE THREAD

**Issue by benjamminf** [spicywebau/craft-neo#36]
The duplicate block feature currently only duplicates the block you select the "duplicate" menu item on. Would be handy to be able to duplicate all the currently selected blocks.

**Comment by benjamminf** [comment]
This is actually a pretty complex feature, given that the expected behaviour is largely ambiguous. Should the checked blocks duplicate as a chunk, or should they duplicate under each other? How should blocks of various levels be duplicated together?

**Comment by ttempleton** [comment]
With the v2.1.0 release, Neo will support copying multiple selected blocks from the same level (and their descendants, if any).  The blocks will paste as a chunk, under whichever block has its paste menu option selected.

We do intend to implement copying of blocks from multiple levels and are currently aiming for v2.2.0 with that functionality, which would then complete this issue.

The Duplicate option -- reintroduced and now named Clone in v2.1.0 -- is now intended only for duplicating single blocks (and their descendants) at the same level, and at this stage there are no plans to change this behaviour.

**Comment by ttempleton** [comment]
Copying blocks from different levels has now been added to the `dev-neo-2` branch.  The blocks will be pasted at the same level.  This functionality will be included in v2.2.0.
