### ISSUE TITLE
Field marked as "modified" in Craft 3.4 draft even when nothing was changed

### ISSUE THREAD

**Issue by aaronbushnell** [spicywebau/craft-neo#361]
#### Description
When I create a draft of a page that has a Neo block the draft thinks the Neo field has changed even if none of the content was modified.

![Screen Shot 2020-06-08 at 8 44 26 AM](https://user-images.githubusercontent.com/315202/84031816-59677e80-a964-11ea-93da-578d68977921.png)

#### Steps to reproduce
1. Create an entry and add a Neo block
2. Create a draft of this entry without changing the Neo block

#### Other information
- Neo version: 2.7.15
- Craft version: 3.4.22.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No multi-site
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: No multi-site
- Is eager-loading used? N/A

**Comment by aaronbushnell** [comment]
I don't know enough about the inner-workings of Craft 3.4 to see if the "modified" indicator is just a visual of what's changed or if—upon save—Craft is truly treating the contents of the field as something that needs to be resaved into the database.

I imagine the latter is creating unneeded database queries that could speed saves up, but if it's the former than this is just a visual glitch!

**Comment by ttempleton** [comment]
This has now been fixed in Neo 2.7.16.
