### ISSUE TITLE
Exception when trying to save pages with duplicated entries

### ISSUE THREAD

**Issue by stefangallas** [spicywebau/craft-neo#363]
When I copy and paste a Neo Structure consisting of three nested elements in the Craft Backend, the elements appear in the Backend view, but an exception occurs when saving the page because the parent element cannot be determined. Sometimes the element is still saved in the first attempt, but then the exception occurs the next time the page is saved. As soon as you delete the duplicated entry from the page, the error disappears again. 

In addition, the preview also shows an error when I try to change a duplicated element (so the drafts cannot be saved either).

I have also tried it with individual Neo elements (whether first level or deeper level). Here shows the error up as well, so it doesn't seem to be because they elements are nested.

- Neo version: 2.7.15
- Craft version: 3.4.23
- Multi-site: yes
- What is the propagation method of the neo field: Save blocks to all sites the owner element is saved in
- Is eager-loading used? No

**Additional Info:** The bug is not there in Craft 3.4.13 / Neo 2.7.5 (my last backup before updating)

Thank you very much for your help!

![neo1](https://user-images.githubusercontent.com/50984611/84277251-8b7b0b00-ab33-11ea-8ed0-0f977ff626aa.png)
![neo2](https://user-images.githubusercontent.com/50984611/84277255-8cac3800-ab33-11ea-83e9-978484e9b575.png)

**Comment by ttempleton** [comment]
To elaborate: At this stage, I think this is being caused by a Craft bug, because a number of you have reported this issue over the past few hours, Craft's latest version release was only about 26 hours ago and Neo's latest version release was almost a week ago.

In addition to providing the above-requested information, could you please also downgrade Neo to 2.7.13 and let me know if the error persists?

**Comment by rbaud** [comment]
I have just tested downgrading to Craft 3.4.22.1 and can confirm that the issue does **not** persist. So this does seem to be a conflict related to 3.4.23. I suspect around the changes to `src/services/Elements.php` in [this commit](https://github.com/craftcms/cms/commit/9a16630114780c721a227a5d1f9a07956ee89f5e).

**Comment by ttempleton** [comment]
@rbaud, if you downgrade Neo to 2.7.13 and use that with Craft 3.4.23, does the error still occur?

**Comment by rbaud** [comment]
Just tried, issue exists with Neo 2.7.13 and Craft 3.4.23.

**Comment by ttempleton** [comment]
Thanks @rbaud.  The only recent Neo release that could've affected entry saving was 2.7.14 (the only other releases so far this month, 2.7.13 and 2.7.15, were both fixing JavaScript issues) so at this point it's likely to be a Craft bug introduced in 3.4.23 that is breaking Neo.  I recommend opening an issue over there and linking to this issue so they have all the information.  I'll keep this issue open for now anyway, to prevent duplicate issue reports or just in case they find it is a Neo bug.

**Comment by e-roc** [comment]
I've been experiencing this issue on Craft 3.4.23 with Neo 2.7.15. Just wanted to add a few scenarios I've found that hopefully might help with debugging.

1. For an entry that is having the issue, saving without editing will show the error.
2. If I add or remove a block or I reorder a block, then it saves successfully. 
3. Then if I save again without making changes (or content only edits) the error reappears.
4. Going back to previous revisions, reveals all the content exploded without parent child relationships.

Hope that helps. I will try reverting Craft for now.

**Comment by ambidustrious** [comment]
How Can I revert Craft? I recently updates and now I'm experiencing this issue as well

**Comment by e-roc** [comment]
Edit the composer.json file: change the version of craftcms/craft to 3.4.22.1. Then run `composer update`.

**Comment by ambidustrious** [comment]
Perfect - Problem solved for now. Thank you!

**Comment by stefangallas** [comment]
In the meantime, I have also created a corresponding ticket at Craft CMS:  https://github.com/craftcms/cms/issues/6205

**Comment by brandonkelly** [comment]
Looks like 4b39c14b9fe2d1edb3315558975bd646bf35af18 was the culprit. `duplicateElement()` is now working to position newly duplicated elements in the structure relative to the source element, but that doesn’t factor in the possibility that the source and duplicated elements should belong in different structures altogether, as is the case with Neo blocks.

As of Craft 3.4.24, it will be possible for duplicated elements to opt out of that functionality if their `structureId` property is `null` (craftcms/cms@1100a7d7dff38407bee089e5ce579bfc19200f74), and I just submitted Neo PR #365 to take advantage of that change.

**Comment by brandonkelly** [comment]
@ttempleton Craft 3.4.24 is out now, so it’s safe for you to release that Neo update.

**Comment by ttempleton** [comment]
Awesome, thanks @brandonkelly!
