### ISSUE TITLE
FR: Prepopulate entry 

### ISSUE THREAD

**Issue by nitech** [spicywebau/craft-neo#366]
Is it possible to pre populate an entry upon creation, so it contains a predefined list of sections (based on Neo-fields)?

My intention is to make it easier for users who don't want the freedom of composing their own document/entry. Instead of starting off with a blank canvas, I want to give them the possibility of having the entry prepopulated. 

Kind of what Microsoft is doing in SharePoint Online:

![image](https://user-images.githubusercontent.com/1279436/84652710-5ba17e00-af0c-11ea-9941-701baa748569.png)

**Comment by nitech** [comment]
I see a similar question is asked here, with regards to the matrix-field: https://craftcms.stackexchange.com/questions/9080/setup-default-matrix-blocks-and-default-values-for-sub-fields

**Comment by ttempleton** [comment]
Now possible with the [Content Templates](https://plugins.craftcms.com/content-templates?craft4) plugin.
