### ISSUE TITLE
Couple of different-related errors relating to project config

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#368]
#### Description
I've been developing a major feature for a client that uses 3 Neo fields, a multitude of Super Tables, and even a Matrix field (not to mention all the other, "regular" fields). I got it working great locally, so I pushed the changes to the repo for testing on a staging server.

We set up the staging server with a fresh DB from production, then pulled down the latest changes I had committed. A quick `composer install` worked fine, but when we ran `./craft project-config/sync`, we got this error:

```
Installing plugin “neo” ... done
Applying changes from project.yaml ... error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ‘headerReadabilityTweaks-global’ for key ‘craft_fields_handle_context_unq_idx’
The SQL being executed was: INSERT INTO `craft_fields` (`uid`, `groupId`, `name`, `handle`, `context`, `instructions`, `searchable`, `translationMethod`, `translationKeyFormat`, `type`, `settings`, `dateCreated`, `dateUpdated`) VALUES (‘de8ca116-d644-4f6b-838c-9e409466e9f5’, 29, ‘Header Readability Tweaks’, ‘headerReadabilityTweaks’, ‘global’, ‘’, 1, ‘site’, NULL, ‘benf\\neo\\Field’, ‘{\“maxBlocks\“:\“4\“,\“maxTopBlocks\“:\“4\“,\“minBlocks\“:\“\”,\“propagationMethod\“:\“all\“,\“wasModified\“:false}’, ‘2020-06-17 20:55:33’, ‘2020-06-17 20:55:33’)
```

So I went back to my local environment (where everything still seems to work great), and ran `./craft project-config/rebuild`. That resulted in an error as well:

```
Rebuilding the project config from the current state ... error: Call to a member function getConfig() on null
```

I can send you the console.log for that error; would rather not post it publicly though.

#### Other information
- Neo version: 2.7.15
- Craft version: Craft Pro 3.4.19

![image](https://user-images.githubusercontent.com/1027523/84952664-ff508100-b0fa-11ea-83d0-e13afb923efb.png)

**Comment by proimage** [comment]
[knock knock]

**Comment by ttempleton** [comment]
The sync error is probably not a Neo issue, as Craft is in control of adding a field to the project config, and in this case the error has occurred with a field that happens to be a Neo field (Neo itself only controls adding block types and block type groups to the project config).  Check and make sure there aren't two fields with the handle `headerReadabilityTweaks` in the project.yaml, or there isn't already a `headerReadabilityTweaks` field in the database with a different UID.

Regarding your rebuild error, I was unable to reproduce the error, but Neo 2.7.19 (just released) has some changes to the project config rebuild of block types, and the `getConfig()` call that triggered your error was removed.  Try the update and let me know how it goes.

**Comment by ttempleton** [comment]
I will assume either the 2.7.19 update fixed it or you've otherwise sorted it out, then, but if the issue persists, please let us know and we'll reopen.

**Comment by proimage** [comment]
Yes, sorry, another dev on my team managed to figure this one out somehow, so it fell off my radar. Sorry for not updating you!

**Comment by ttempleton** [comment]
No worries @proimage, glad it's all been sorted!
