### ISSUE TITLE
Design issue in the latest NEO update

### ISSUE THREAD

**Issue by Osze** [spicywebau/craft-neo#370]
#### Description
 When minimizing the NEO structure each block is in the latest update larger than before. Not as nice as before when having many blocks.

![image](https://user-images.githubusercontent.com/4204962/85415664-df431680-b56d-11ea-9195-91359c60b019.png)

The text in the minimized version also shows under the dragging icon.

#### Other information
- Neo version: 2.7.19
- Craft version: 3.4.24

**Comment by ttempleton** [comment]
Hi @Osze,

I'll have a look at fixing the block sizes in the next day or so.

Regarding the text overlapping with the icons, that should have been fixed in Neo 2.7.13; could you please clear your browser cache and let me know if it still occurs?

**Comment by Osze** [comment]
Hi @ttempleton,
Sorry, doesn't seem to be fixed. The text is still overlapping the icons.

**Comment by ttempleton** [comment]
Neo 2.7.20 has just been released with the padding fix for collapsed blocks.

Regarding the text/icon overlap that is still happening for you, could you please answer the following:

- Is it happening on multiple browsers?  If not, with which browser and version is it happening?
- Is it happening on different Craft installs and on different servers?

**Comment by Osze** [comment]
Thanks for fixing the padding-bottom issue!

This is how it looks in Chrome. I also tried on Microsoft Edge and same problem. 

![image](https://user-images.githubusercontent.com/4204962/85683043-2562bc00-b6cd-11ea-8364-2abd8d2c4cb4.png)

By adding overflow: hidden; on the class .ni_block_topbar_left it looks more correct.  (maybe not the best solution)

![image](https://user-images.githubusercontent.com/4204962/85683288-6064ef80-b6cd-11ea-9360-f7377f99c1ac.png)

**Comment by ttempleton** [comment]
Hmm, it definitely should not look like that, the fade-out should happen before the text reaches the icons.

I've just done a brief, Firefox-only test with applying the hidden overflow and the fade-out to .ni_block_topbar_left, and it looks like it should be fine.  I'll have a more comprehensive look with Chrome/Safari/Edge and if everything looks fine, we'll include that in the next release.

**Comment by ttempleton** [comment]
Neo 2.7.21 has just been released, which I believe should resolve the issue with the preview still overlapping the icons in your case.  I'll close the issue now, but if the issue persists, please let me know and I'll reopen it.
