### ISSUE TITLE
Design update not so great - tab strucure preferred

### ISSUE THREAD

**Issue by Osze** [spicywebau/craft-neo#371]
#### Description

The web administrators at my company really dislike the dropdown menu instead of the tab- structure. 

![image](https://user-images.githubusercontent.com/4204962/86241670-a295a180-bba3-11ea-9330-08e5f35ff9a2.png)

Is it possible to change back? Or maybe add a setting so I can change to the old style?

![image](https://user-images.githubusercontent.com/4204962/86241718-bc36e900-bba3-11ea-911e-881fc6f21f2b.png)

**Comment by ttempleton** [comment]
This has now been fixed in Neo 2.7.21.
