### ISSUE TITLE
Neo field layout settings not working with new field layout designer in Craft 3.5

### ISSUE THREAD

**Issue by brandonkelly** [spicywebau/craft-neo#373]
#### Description

Craft 3.5 is getting a new field layout designer (craftcms/cms#4647). It was designed to be as backwards-compatible as possible with current implementations, but looks like Neo is completely discarding the FLD-registered JS, and I guess overriding it with something custom.

https://github.com/spicywebau/craft-neo/blob/ea1e6d8ac55f877c2e04573044f8d8504663250a/src/assets/FieldAsset.php#L109-L115

So whatever you’re doing beyond that point is going to need to be updated. Currently the FLD within Neo settings is just completely unresponsive.

To update a local install before 3.5 is officially released, change your `craftcms/cms` requirement in composer.json to `"3.5.x-dev"`, and then run `composer update`

Let me know if there’s anything I can do to help.

**Comment by ttempleton** [comment]
Thanks for letting us know @brandonkelly, we'll look into it and will let you know if we need any help.

**Comment by 23d1** [comment]
@ttempleton happy to test on my end, let me know when the `craft-3.5-field-layout-support` branch is in a good spot to try out.

**Comment by ttempleton** [comment]
Thanks @23d1, it should be ready to go now!

**Comment by theskyfloor** [comment]
Will Neo be getting the column support? @ttempleton

**Comment by theskyfloor** [comment]
Never mind, I tested it and see that it does!! Fantastic!!

**Comment by 23d1** [comment]
Amazing. Gonna give it a go right now.

**Comment by 23d1** [comment]
Works great so far. Haven't run into any issues yet. 🖖🏻

**Comment by ttempleton** [comment]
Thanks for the feedback @23d1 and @theskyfloor!

Neo 2.8.0 has just been released including this update, with a minimum requirement of Craft 3.5.0-RC6.
