### ISSUE TITLE
Self relation causes entry field to loose value after saving

### ISSUE THREAD

**Issue by medoingthings** [spicywebau/craft-neo#374]
### Description
When setting "Allow self relation" to true for an entry field within Neo, the value gets lost after saving, if the selected entry is the one you are editing at that moment – but only in live preview mode. Kinda hard to explain, see the steps to reproduce.

### Steps to reproduce

1. Add a new entry field and activate the "Allow self relation" option let’s call it `entrySource`
2. Add that field to a Neo field
3. Create a new entry and save it, let’s give it the title `Inception`
4. Edit that entry again and **use the live preview** to add the entry `Inception` to the field `entrySource` (so this is where the self relation option comes into play)
5. Close the live preview and save
6. **Result:** The `entrySource` field is empty, despite the fact that it wasn’t a second ago
7. Add the entry `Inception` to the `entrySource` field _without using the live preview_
8. **Result:** `entrySource` now holds the correct value as expected

This only happens if a self related entry was selected and only when it was selected through the live preview.

If you selected any other page, everything would work as expected.

So this is kind of an edge case, but it confused people and me too.

### Additional info

- Craft version: Craft CMS 3.4.27
- Neo version: 2.7.22
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Is eager-loading used? No.

**Comment by ttempleton** [comment]
Thanks for reporting this, @medoingthings; in my testing, though (with Craft 3.4.28.1 and the latest from the 3.5 beta branch), this is actually happening with all entry fields, not just those within Neo blocks.  I recommend opening an issue with Craft about this.

**Comment by medoingthings** [comment]
That’s funny, because that’s what I did in the first place, but we couldn’t reproduce it anymore on fields outside of Neo 🤔
https://github.com/craftcms/cms/issues/6385
