### ISSUE TITLE
Saving a Neo block's name/handle as 'filter' causes Neo blocks to not show 

### ISSUE THREAD

**Issue by markjoeljimenez** [spicywebau/craft-neo#375]
#### Description
Saving a Neo block's name/handle as 'filter' causes Neo blocks to not show

#### Steps to reproduce
1. Save a Neo block as name/handle:  **filter**
2. Navigate to where the Neo block is being used
3. Neo blocks are not showing

#### Other information
- Neo version: 2.7.14
- Craft version: 3.4.22.1
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to all sites the owner is saved in
- Is eager-loading used? No

I get this error in the web inspector: 

![Capture](https://user-images.githubusercontent.com/5943430/87715735-c77d3d80-c77b-11ea-945f-126adb238a99.PNG)

Perhaps have **filter** as a reserved word?

**Comment by ttempleton** [comment]
Thanks for reporting this, @markjoeljimenez; the error is fixed in Neo 2.7.23, you'll be able to use `filter` as a block type handle now.
