### ISSUE TITLE
Field Validation Display Issue

### ISSUE THREAD

**Issue by javangriff** [spicywebau/craft-neo#377]
Ran into an issue recently when trying to publish a draft entry where a field was failing validation failed to display the fields validation error (in this case the field was the typed link field) within Neo. 

Unfortunately, Craft didn't seem to log the error anywhere either and it wasn't until we added `Craft::dd($draft->getErrors());` to [line 407](https://github.com/craftcms/cms/blob/develop/src/controllers/EntryRevisionsController.php#L407) of the Craft Entry Revisions Controller that we were able to find the source of the issue.

I haven't had a chance to test if this is also an issue with other field types or just with the Typed Link Field specifically, or if the level of nesting would make any difference either. In this case the field was nested 3 levels deep.

#### Other information
- Neo version: 2.7.15
- Craft version: 3.4.27
- (if multi-site) What is the affected Neo field's propagation method: Only save block to the site they were created in
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this @javangriff, turns out it did affect all field types at all levels.  It'll be fixed in Neo 2.8.
