### ISSUE TITLE
Blocks are not propagated across sites in the same group with new propagation method

### ISSUE THREAD

**Issue by genetschneider** [spicywebau/craft-neo#379]
#### Description
Craft 3.5 introduces a new propagation method ["Let each entry choose which sites it should be saved to”](https://github.com/craftcms/cms/issues/5988#issuecomment-622473302). Neo blocks however don't seem to propagate across sites when this propagation method is enabled for sections. Neo field's propagation method is set to "siteGroup".

#### Steps to reproduce
1. Set section propagation method to `custom` or "Let each entry choose which sites it should be saved to"
2. Set Neo's field propagation method to `siteGroup` or "Save blocks to other sites in the same site group" (sub fields' translation method is also siteGroup)
3. Create an entry with a neo field
4. Before saving, add this entry to a site x (x site is in the same site group as the default site)
5. Save entry
6. Entry has neo field saved in default site but not in site x (expected neo field to have same structure as default site entry)

#### Other information
- Neo version: [craft-3.5-field-layout-support](https://github.com/spicywebau/craft-neo/tree/craft-3.5-field-layout-support)
- Craft version: [3.5](https://github.com/craftcms/cms/tree/3.5)
- (if multi-site) What is the affected Neo field's propagation method: `siteGroup`
- Is eager-loading used? no

Gif of problem in action
![neo-bug](https://user-images.githubusercontent.com/19775351/88807901-e687c080-d1ba-11ea-8a22-02b8f18ac46a.gif)

**Comment by ttempleton** [comment]
This is working correctly in the [`dev`](https://github.com/spicywebau/craft-neo/tree/dev) branch, so you'll need to use that branch if you need this functionality before the official Neo 2.8 release.
