### ISSUE TITLE
Search keywords aren't getting generated

### ISSUE THREAD

**Issue by benjamminf** [spicywebau/craft-neo#38]
Searching Neo fields on elements is broken. Problem being that the search keywords method incorrectly starts a task to generate the keywords, where it should be returning the keywords only. Need to move the task to the `onAfterSave()` hook method and have the `getSearchKeywords()` just return the currently saved keywords.

**Comment by benjamminf** [comment]
Hm, I was wrong. Running the task in the `getSearchKeywords` method, while probably not appropriate, wasn't causing any issues like I thought. Seems I'm having an unrelated issue, since my isolated testing shows it working fine.

**Comment by benjamminf** [comment]
It seems the problem is the "Generating search keywords" task is not running (on a particular website I'm working on). Trying to isolate the problem now...

**Comment by benjamminf** [comment]
It seems this is only happening on my local machine – it doesn't seem to do this on any other web server. It's also only happening with one site in particular. Very strange.

**Comment by dhdchicago** [comment]
Thanks for the great plugin. We're having the same issue on a site we're working on. NEO fields are not searchable. From what we can see, search keywords are not generated on both our local machines or our production server (Arcustech).

**Comment by benjamminf** [comment]
@dhdchicago This seems to be a very precarious issue, as it rarely happens but without reason. When you save an entry, on the left sidebar do you see a "Generating search keywords" task start to run?

**Comment by dhdchicago** [comment]
The task doesn't seem to run when we save. We have even tried to rebuild search indexes manually a few times and that runs and finishes but without any NEO related field content.

**Comment by benjamminf** [comment]
@dhdchicago You're right, they aren't generating when you do a manual search index rebuild. I'm working on fixing this bug right now, should be done in a couple of hours.

As for the task sometimes not running after saving an entry, well, I'm still yet to be able to reproduce this since I last encountered this in July. Tasks appear to be a finicky thing in Craft so I might include a configuration setting that allows you to opt out of the task optimisation and just generate keywords normally.

**Comment by benjamminf** [comment]
I've added the config option, and I'll write up how to override the options in the Wiki once I publish 1.4.1

**Comment by dhdchicago** [comment]
Works great, searching NEO fields again. Thanks!

**Comment by JackBewley** [comment]
I was having this same issue. Setting generateKeywordsWithTask to false allowed searching Neo field content to work again.

**Comment by groe** [comment]
Is this still an issue?

**Comment by terryupton** [comment]
Is this still an issue? Once setting generateKeywordsWithTask to false. Do we need to rebuild the Craft Search index?

**Comment by ttempleton** [comment]
Closing this now, as it is no longer an issue as of the Craft 3 version.
