### ISSUE TITLE
Neo Block Title, Tab names not translated in the ACP

### ISSUE THREAD

**Issue by AlexandreKilian** [spicywebau/craft-neo#380]
#### Description
Using the translation method for fields in the ACP (translations/en/site.php), names of block titles and tabs are not getting translated

#### Steps to reproduce
1. Set a block title to a translation key
2. Set a translation for that key in translations/en/site.php
3. Block title is not getting translated in the entries dashboard

#### Other information
- Neo version: 2.7.24
- Craft version:3.4.29.1

**Comment by ttempleton** [comment]
Hi @AlexandreKilian,

This should be working if the block/tab title translations are set in `translations/en/neo.php`.  Try that and let us know if that doesn't work.

**Comment by AlexandreKilian** [comment]
Indeed it does, thx!
