### ISSUE TITLE
Each tab represents all contents of all tabs in 2.8.0 / Craft 3.5.0-RC6

### ISSUE THREAD

**Issue by mheob** [spicywebau/craft-neo#381]
### Description
Since version 2.8.0, in combination with Craft 3.5.0-RC6, all fields are displayed in each tab of a block.

### Steps to reproduce
1. Create a Neo field with two tabs
1. Insert at least one field in each tab
1. Add the Neo field to a section
1. Add the block to the entry and watch / switch the tabs

#### Step 1 and 2
![Screen Shot 2020-08-04 at 11 19 48](https://user-images.githubusercontent.com/3983539/89278996-1c0f2c80-d647-11ea-9b99-1d5d21c4f640.png)

#### Step 4
![Screen Shot 2020-08-04 at 11 30 00](https://user-images.githubusercontent.com/3983539/89279010-203b4a00-d647-11ea-95ab-5d39b47a69d1.png)
![Screen Shot 2020-08-04 at 11 30 10](https://user-images.githubusercontent.com/3983539/89279014-229da400-d647-11ea-9f90-f9a45e3ae801.png)

### Other information
- Neo version: `2.8.0`
- Craft version: `3.5.0-RC6`
- (if multi-site) What is the affected Neo field's propagation method: `no multi-site`
- Is eager-loading used? `No`

**Comment by ttempleton** [comment]
Thanks for reporting this @mheob, it's fixed in 2.8.1.

**Comment by meestaben** [comment]
Hi @ttempleton - I think this might not be completely fixed. I'm seeing the same issue when in Preview mode - all tab contents are displayed, clicking the tabs does nothing. Regular edit mode is fine. Craft 3.5.0 and Neo 2.8.1.

**Comment by ttempleton** [comment]
Thanks for pointing that out @meestaben, that should now be fixed in Neo 2.8.2.
