### ISSUE TITLE
Project configuration changes are being generated unnecessarily on save

### ISSUE THREAD

**Issue by meestaben** [spicywebau/craft-neo#384]
#### Description

Whenever I hit Save on a Neo field, the names of the neoBlockTypeGroups yaml files are being changed. The contents remains the same.

![Screenshot 2020-08-06 at 00 18 29](https://user-images.githubusercontent.com/15892203/89473455-cb98eb80-d77a-11ea-93c8-244ae75f4ff0.png)

In this example I have two Groups called UI Components and Shared Content. This happens on every save.

I think might be a reason why duplicate Block Type Groups suddenly appeared in my staging environment - but this only happened once and I've not been able to reproduce it.

Additionally, the wasModified key in the yaml definition for the Neo field itself is set to true, even if I've not made any changes. 

#### Steps to reproduce
1. Create a Neo field and some blocks
2. Create one or more Block Groups, hit Save
3. Observe the filenames in config/project/neoBlockTypeGroups
4. Go back into your Neo field and hit Save again
5. Observe that the neoBlockTypeGroups filenames have changed

#### Other information
- Neo version: 2.8.1
- Craft version: 3.5.0
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? n/a

**Comment by ccchapman** [comment]
This seems to be the root cause of https://github.com/spicywebau/craft-neo/issues/383.

**Comment by ttempleton** [comment]
This is the expected behaviour with how saving block type groups currently works; when a field's block type groups are resaved, it actually deletes the old groups and saves new ones, which will have new UIDs.  It does appear to be causing #383, though, so we may need to change how it works in the near future.  I'll continue to update on this in #383.

**Comment by ttempleton** [comment]
Neo 2.8.3 has just been released; existing block type groups are now resaved when modified, rather than being deleted and recreated.
