### ISSUE TITLE
Dropdown default value not works

### ISSUE THREAD

**Issue by amici-infotech** [spicywebau/craft-neo#386]
#### Description
I have created a dropdown field and mark one option as default. In Neo, that default field is not pre selected when creating a new NEO block.

#### Steps to reproduce
1. Create a new Dropdown field and add few options.
2. Mark any one option as pre selected.
3. Assign that field into Neo.

#### Other information
- Neo version: 2.8.2
- Craft version: 3.5.1

**Comment by ttempleton** [comment]
Thanks for reporting this, @amici-infotech, it will be fixed in the next release.

**Comment by ttempleton** [comment]
Dropdown field default values should now be correctly applied in Neo 2.8.3.
