### ISSUE TITLE
Dropdowns inside Neo fields don't get the default value after upgrading

### ISSUE THREAD

**Issue by sgtpenguin** [spicywebau/craft-neo#388]
#### Description
After updating to 2.8.2 (and simultaneously Craft to 3.5) dropdown fields inside neo blocks do not default to the selected default value

#### Steps to reproduce
1. Install Craft + Neo
2. Create a dropdown with a default value other than the first, add it to a neo block
3. try it out

#### Other information
- Neo version: 2.8.2
- Craft version: 3.5.1
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? no

**Comment by ttempleton** [comment]
See #386, this will be fixed in the next release.

**Comment by sgtpenguin** [comment]
fantastic.  thank you!

**Comment by ttempleton** [comment]
Dropdown field default values should now be correctly applied in Neo 2.8.3.
