### ISSUE TITLE
Can not drag/drop child block entries to change order

### ISSUE THREAD

**Issue by kaspervdm** [spicywebau/craft-neo#392]
#### Description
When using child blocks, it does not seem to be possible to drag/drop the entries to change the order. The drag-icon is present, but when dragging it is not possible to drop to a new location. 

#### Steps to reproduce
1. Create a parent block type
2. Create a child block type
3. Add multiple child block entries
4. Try to drag/drop the entries to change the order

#### Other information
- Neo version: 2.8.3
- Craft version: Craft Pro 3.5.2
- (if multi-site) What is the affected Neo field's propagation method:/
- Is eager-loading used? no

**Comment by ttempleton** [comment]
Thanks for reporting this @kaspervdm; this was happening due to a bug that was disallowing dragging of child blocks if the new `Max Sibling Blocks of This Type` setting was not set on the block type, and it should now be fixed in Neo 2.8.4.

**Comment by kaspervdm** [comment]
Seems to work great again! Thanks for the fast fix!
