### ISSUE TITLE
Hiding field labels on second and subsequent fields

### ISSUE THREAD

**Issue by brettgullan** [spicywebau/craft-neo#393]
#### Description

I believe this is a bug. I'm trying to hide the field labels on a number of fields for different Neo Blocks. I can activate the `Hide` checkbox on the first field I select. But on the second and subsequent fields, the `Hide` checkbox doesn't respond. I can't click on it, nor tab to it.

If I save the Neo field, then re-enter the edit screen, I can select a Block, edit a field and select the `Hide` checkbox without a problem.

Basically, I can only hide one Block field label per Neo field editing session.

Not a showstopper by any stretch, just a bit tedious!

#### Steps to reproduce
1. Edit a Neo field
2. Select Field Layout for a Block
3. Click the settings icon for a Field, select Hide for label and Apply
4. Click the settings icon for another Field (same Block or different)
5. Hide checkbox won't respond to click

#### Other information
- Neo version:
- Craft version: 3.5.4
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
It looks like we'll need to make a compatibility update for Craft 3.5.4 to properly support the new checkbox, which I'll have a look at in the next couple of days.  In the meantime, setting `__blank__` as the field label override will also hide the label.

**Comment by ttempleton** [comment]
Fixed in Neo 2.8.5.
