### ISSUE TITLE
Required fields doesn't pass validation

### ISSUE THREAD

**Issue by rlapierre-kffein** [spicywebau/craft-neo#394]
#### Description
Redactor fields that are required doesn't pass validation as entry can be saved without any errors. Others fields like image show validation errors when required.

#### Steps to reproduce
1. Insert a redactor field into a neo block
2. Mark as required
3. Try to save the new block with empty data on redactor field.
4. Validation should not throw any errors but let user save entry.

#### Capture

![Alt Text](https://s7.gifyu.com/images/ezgif-4-3ffab93a90b3.gif)

#### Other information
- Neo version: 2.8.6
- Craft version: 3.5.5

**Comment by ttempleton** [comment]
I was able to reproduce this, not only with a Redactor field that was on a Neo block, but also on a Redactor field that was on an entry, so I recommend opening an issue with Craft about this.
