### ISSUE TITLE
"Required field" asterisk disappears on save

### ISSUE THREAD

**Issue by Joorren** [spicywebau/craft-neo#399]
#### Description
When editing a Neo field, making a field required in the Field Layout, there will appear an asterisk after the Field name.
Once you save this Neo field, and open the Field Layout again, the required field will no longer show the asterisk, even though it is still required in the backend.

**Before Save:**
<img src="https://imgur.com/t9vJngu.png" width="20%" />

**After Save:**
<img src="https://imgur.com/bKiNZLm.png" width="20%" />

#### Steps to reproduce
1. Create Neo Field with a block type.
2. Make a field required in the Field Layout of that block type.
3. Save the Neo field.

#### Other information
- Neo version: 2.8.7
- Craft version: 3.5.8
- (if multi-site) What is the affected Neo field's propagation method: `Only save blocks to the site they were created in`
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Fixed in Neo 2.8.8.
