### ISSUE TITLE
Choose where the buttons for child blocks are placed

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#403]
If a block in a Neo field can be a parent block (i.e. it can have child blocks), then the buttons to add them show up at the bottom of the parent block. They also are shown regardless of which field tab is active in the parent block.

It would make a lot more sense if those buttons could optionally be placed _inside_ a specific tab, at a specific location among the parent block's custom fields.

I'm envisioning some sort of "Child Block Placeholder" field (perhaps a new type of those nifty UI elements Craft recently introduced?), which could be dragged into any of the tabs on the parent block to place it among the parent block fields. Not adding it to the field layout would result in the current behavior.

----

For example, let's say we have a pretty standard modular block / page builder Neo field. It has blocks for Heading, Text, and Image—none of which can have child blocks. It also has a Multi-block Container, which can have any of the other top-level blocks as children.

All the blocks have basic container-level customization via fields for margin, padding, text color, BG color, and BG image. These container-level fields are sequestered away into a "Container" tab on each block. The Heading, Text, and Image blocks also have a self-explanatory "Content" tab, with the appropriate fields for each.

In this situation, when we add a Multi-block Container, what we would see is a block with _no_ tabs (even though it has a single tab, "Container"), and all the fields from the "Container" tab would clutter up the majority of the block, hiding through obscurity the buttons to add child blocks at the bottom.

![image](https://user-images.githubusercontent.com/1027523/95356885-d7ff0900-08cf-11eb-9ead-a4f6c43f47e3.png)

The workaround is to add some sort of field to another tab in the parent block, so that the "Container" tab's fields aren't initially visible. Craft's UI Elements work well for this purpose, but it's still less than ideal:

![image](https://user-images.githubusercontent.com/1027523/95357196-3b893680-08d0-11eb-88dd-1499a7410fbd.png)

**Comment by ttempleton** [comment]
Great idea, will add this to the todo list for Neo 2.9.

At the moment, I imagine it working a bit more like the title field for entries/categories, where there is always exactly one element of that type on the field layout (just because I'm not sure if it's possible to have a reusable element that only Neo blocks can use; ideally we would want to allow reuse if possible, though, so the buttons can still be placed on all tabs), and it just wouldn't be displayed if the block isn't a parent.

**Comment by ttempleton** [comment]
This feature isn't going to make it to Neo 2.9, unfortunately, but we will be aiming for a 2.10 release in the next couple of months which would include this.

**Comment by proimage** [comment]
Awwww..... #sadface No worries, m8. :)

**Comment by ttempleton** [comment]
Just released Neo 2.10.0 which adds this feature -- the Child Blocks UI element can be placed in a single position in the field layout, and when the UI element is not placed on the field layout, the child blocks will appear in the usual place.
