### ISSUE TITLE
Fields in Neo always marked as required after editing title or description

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#404]
Note: This seems to be the same as issue 1 in https://github.com/spicywebau/craft-neo/issues/400.

#### Description
In a Neo block's field layout, if a field is added and then its properties are edited in any way—such as customizing or hiding the Title, or customizing the Instructions—then from that point onwards, the Required lightswitch will always be toggled to `TRUE` when opening its properties panel again.

This _doesn't_ mean that at that moment the field is _actually required_, but if the Apply button is clicked without toggling the Required lightswitch to `FALSE`, the Required setting _will_ be set to `TRUE`.

This bug then persists for that field in that Neo block as long as it exists, even after all property customizations have been removed, reverting them to the default values. The only thing that resets the bug is dragging the field out of the field layout, and then back in. However, as before, customizing any of the field's properties triggers the bug again.

![image](https://user-images.githubusercontent.com/1027523/95567484-ac913100-0a2b-11eb-8de4-b616a8c61d16.png)

#### Steps to reproduce
1. Create a Neo field & a block.
2. Add a field to that block.
3. Edit the field's properties (the gear icon) 
4. Change any of the options in the panel that appears except for Required (leave set to `false`).
4. Click Apply.
5. Save the Neo field.
6. Edit the Neo field again.
7. Click the gear icon next to the field you added before.
8. Notice that the Required lightswitch is set to the `TRUE` state.

#### Other information
- Neo version: 2.8.11
- Craft version: Craft Pro 3.5.12.1
- (if multi-site) What is the affected Neo field's propagation method: Not multi-site
- Is eager-loading used? This is a backend problem only.

**Comment by ttempleton** [comment]
Thanks for reporting this -- should now be fixed in Neo 2.8.12.
