### ISSUE TITLE
project-config/apply rebuilds from db instead of using yaml file 

### ISSUE THREAD

**Issue by BrandonJamesBorders** [spicywebau/craft-neo#406]
#### Description
Trying to replicate some quirks I've found lately with this plugin. One is that project-config/apply will not apply changes from the YAML files on changed block handles. I've created a test repository so you could follow along with my steps exactly if you choose.

#### Steps to reproduce
1. In a project, create a new branch.
2. In the new branch, [rename a neo block and update handle](https://github.com/BrandonJamesBorders/neo-test/commit/281e319d9de7c1ed8a4b736bdfcce4461f65ad25). 
3. Revert to the main branch. 
4. Without merging, run ./project-config/apply
5. Expect that the field in the admin would revert to the previous name. Observe that it gets renamed to what you named it in the other branch. 
6. Observe that the yaml file for the changed block is reverted. 

#### Other information
- Neo version: 2.8.12
- Craft version: 3.5.12.1

**Comment by ttempleton** [comment]
This is strange -- clearly there's a bug somewhere, but I'm not really sure *where* at this point.  Neo's `handleChangedBlockType()` seems to be working correctly, as far as I can tell -- it's just being given the *old* block type settings by the project config apply process for some reason.  That said, I don't think it's a Craft bug, because everything works correctly for a Matrix field, and the way Neo works with project config isn't too different to Matrix...  I'll keep looking into it.

**Comment by gquimper** [comment]
Following this thread since we do have this issue as well, applying config is overriding the YAML files. This is a major road block for development collaboration, thanks for looking into this issue. 

We are running the same versions mentioned above (Craft Pro 3.5.12.1 and Neo 2.8.12)

**Comment by ttempleton** [comment]
This seems to be working fine for me now with Craft 3.5.13.1 -- @BrandonJamesBorders @gquimper could you please confirm if this is the case for you?

**Comment by gquimper** [comment]
@ttempleton Did some tests after updating Craft and indeed it seems to fix the sync issue, the YAML were not override by DB values. Thanks for looking into it.

**Comment by ttempleton** [comment]
Thanks for confirming, @gquimper!  I've also just made the fix in Neo for this to work properly with Craft 3.5 releases prior to 3.5.13, which will be included in the next release.
