### ISSUE TITLE
Feed Me Related Error: Call to a member function all() on string - Field.php: 399

### ISSUE THREAD

**Issue by BrandonJamesBorders** [spicywebau/craft-neo#407]
#### Description
When using Feed Me to import entries into a section and instructing it to create related categories, if the category has a neo field the import fails.

#### Steps to reproduce
1. Create a category group and add a neo field to its field layout.
2. Create a section and add a category field with the source of the category group created in step 1.
3. Create a CSV with a title and category column. 
4. In Feed Me, create new feed that reads CSV. Set it to match category on title and create if it does not exist. 
5. Run import and observe Feed Me fail with the following error: `Call to a member function all() on string - Field.php: 399`

I'll make a pull request that shows my temp fix. Not sure on the implications. 

#### Other information
- Neo version: 2.8.12
- Craft version: 3.5.14

**Comment by ttempleton** [comment]
Feed Me doesn't support Neo, unfortunately -- I'd recommend adding a +1 to the feature request at craftcms/feed-me#335.
