### ISSUE TITLE
Project config sync fails

### ISSUE THREAD

**Issue by rauwebieten** [spicywebau/craft-neo#409]
#### Description

When applying a existing project config, a SQL error occurs

```
 SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fieldId' cannot be null
The SQL being executed was: INSERT INTO `neoblocktypes` (`fieldId`, `name`, `handle`, `sortOrder`, `maxBlocks`, `maxSiblingBlocks`, `maxChildBlocks`, `childBlocks`, `topLevel`, `uid`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES (NULL, 'Link button', 'linkButton', 5, 0, 0, 0, '', 1, 'ee4441ef-a1d0-4d8d-85fd-2a2f7f3dc9f1', 11, '2020-10-28 15:00:34', '2020-10-28 15:00:34') (/vagrant/vendor/yiisoft/yii2/db/Schema.php:677)
```

#### Steps to reproduce
1. Create a website with neo fields
2. Use project config to transfer to another environment

#### Other information
- Neo version: 2.8.12
- Craft version: 3.5.14
- (if multi-site) What is the affected Neo field's propagation method:  translationMethod: site
- Is eager-loading used?

**Comment by ttempleton** [comment]
`fieldId` being null implies that the field with the UID specified in the block type's YAML file doesn't exist.  Admittedly we should probably throw an exception the moment we get a null ID, before we try the insert, so I'll make that change for the next release.  I'd recommend double-checking that the field actually does exist in the project config, that the field YAML file hasn't just gone missing somehow or failed to be written by Craft for some reason, but Craft is in control of updating fields in the project config, strictly speaking -- Neo itself only controls updating block types and block type groups after the rest of the field's settings are updated by Craft.
