### ISSUE TITLE
UI slowing down with many neo fields and child blocks.

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#41]
It seems that the UI slows down when an entry has multiple neo fields with a lot of child blocks (not insane amount, but around 10-15 child blocks). It's extra noticeable when scrolling, which becomes sluggish.

**Comment by benjamminf** [comment]
I know what you mean. Unfortunately I don't think there's a whole lot I can do about it. The bulk of the HTML comes from Craft generating fields, and all that HTML is bound to slow down the UI. Large Matrix fields suffer the same problem, though Neo comes with some extra features that do affect performance a little more.

I've built some large Neo fields and while I'm experienced some slow-down, they still perform well enough that it isn't a problem. I don't know how bad it is for you, but if it's unusable then there's probably something wrong.

**Comment by aenrii** [comment]
Definitely usable, so not really a problem other than being slightly annoying. I think I read somewhere that they're updating the UI quite a bit for the next major release, hopefully that sorts it all out... Awesome plugin btw. :)

**Comment by benjamminf** [comment]
(#87) I don't know if this is the cause for anyone else, but I just discovered something that has a serious performance degradation effect with Neo – Rich text fields with fixed toolbars. If rich text fields inside Neo blocks have their fields fix to the top of the browser when scrolling, if this is triggered enough times it causes a huge UI performance hit.

This actually indicates a memory leak issue with Redactor, where events are probably not unbinding and piling up on top of each other. I'll have to submit a bug report with them, but in the meantime you'll just need to disable the fixed toolbar in your Redactor configs – `"toolbarFixed": false`

**Comment by owldesign** [comment]
Any progress on this one? The more child blocks the slower it runs.

**Comment by ttempleton** [comment]
Closing this issue due to its age and inactivity since the release of Neo for Craft 3.  If anyone has any issues with the speed of the UI with Neo and Craft 3, please feel free to open a new issue.
