### ISSUE TITLE
When saving an entry in site X, edited neo block disappears on site Y

### ISSUE THREAD

**Issue by nstCactus** [spicywebau/craft-neo#411]
#### Description

We have a Craft instance having 2 sites: `fr` and `en`. There is a neo field that used to be configured with the *Save blocks to other sites in the same site group* propagation method. Some content were added and at some point we decided to switch to the *Only save blocks to the site they were created in*. We didn't notice anything wrong so we went on adding more content.

A few days ago we notices that editing the content of an entry, sometimes caused some content to disappear on the same entry but in the other language. More specifically if the entry had the same Neo blocks in both language, editing the content of a block in `fr` would cause the block to disappear on the `en` entry. 

I think only blocks created before changing the propagation methods are affected. Newly created blocks seem to be fine and editing them has no effect on the entry in the other language.

#### Steps to reproduce
1. Create a Neo field and set its propagation method to *Save blocks to other sites in the same site group*
2. Create an entry having this Neo field and add some blocks
3. Change the propagation method to *Only save blocks to the site they were created in*
4. Edit one of the existing block in a site
5. The corresponding block is gone in other sites

#### Other information
- Neo version: 2.8.13
- Craft version: 3.5.15
- (if multi-site) What is the affected Neo field's propagation method:  *Save blocks to other sites in the same site group* then *Only save blocks to the site they were created in*
- Is eager-loading used? Yes but this is not relevant: the blocks completely disappear, even from the control panel

This happened over the course of several months without us noticing the issue so we used several different versions of Craft and Neo. This may be hard to reproduce using the given instructions. If it helps, I can provide a database dump and details on which entry is affected.

Thanks in advance

**Comment by ttempleton** [comment]
Thanks for reporting this, it appears that the new propagation method was not being applied to existing blocks.  Neo 2.8.14 has just been released with the fix for this -- including a migration to reapply propagation methods on existing blocks.  My testing has indicated the migration is working fine, but please make sure to backup your database before updating, just in case.

**Comment by nstCactus** [comment]
Thanks for the quick fix!

Unfortunately I'm now getting another error when the new queue job is run but I created a new issue (#413) to tackle that.
