### ISSUE TITLE
Error in "Applying new propagation method to Neo blocks" queue job

### ISSUE THREAD

**Issue by nstCactus** [spicywebau/craft-neo#413]
#### Description

After upgrading to 2.8.14, I get errors in the Craft queue job **Applying new propagation method to Neo blocks**:
> Attempting to save an element in an unsupported site. 

After digging a little, it seems like the issue is thrown when saving a Super table field inside the Neo block (but if I understand correctly how Craft saves data internally, I think nested Matrix field may be affected as well).

I can provide a db dump to help debugging.

#### Steps to reproduce
1. Create a Neo field and set its propagation method to **Save blocks to other sites in the same site group**
1. Create a Super table field with a propagation method of **Save blocks to all sites the owner element is saved in**
1. In the Neo field created in step 1, create a Neo block having the newly created Super table field in its field layout
1. Create an entry having this Neo field and add some blocks
1. Change the propagation method of the Neo field to **Only save blocks to the site they were created in**

#### Other information
- Neo version: 2.8.14
- Craft version: 3.5.15
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to other sites in the same site group then Only save blocks to the site they were created in
- Is eager-loading used? Yes, but this is irrelevant, the issue happens in the control panel.

**Comment by haabe** [comment]
I got this error as well. I got all the Neo fields set to **Only save blocks to the site they were created in**. I also have a mix of Neo blocks and Super Table fields.

**Comment by ttempleton** [comment]
I've not been able to reproduce this error so far -- did this only happen after resaving the Neo field, or did this start happening as soon as the 2.8.14 migration was applied?

**Comment by haabe** [comment]
> I've not been able to reproduce this error so far -- did this only happen after resaving the Neo field, or did this start happening as soon as the 2.8.14 migration was applied?

To me it happened as soon as the 2.8.14 migration was applied. I have not resaved any of the fields.

**Comment by haabe** [comment]
An update on my side. Some of my sites had empty Neo blocks. After adding a block, saving and trying to propagate again, it all checked out OK.

**Comment by nstCactus** [comment]
As for me, I had some serious issues with my Super Table blocks. After fixing them, the migration applies without trouble.

**Comment by ttempleton** [comment]
@nstCactus, @haabe, glad it's sorted out!

**Comment by twosixcode** [comment]
I'm encountering this issue with the migration as well, post update. I'm not sure yet the root cause. What is the upshot here or recommended way to diagnose or fix this?

**Comment by nstCactus** [comment]
In my case, the problem was caused by inconsistencies in super table blocks I had nested in my Neo blocks.
The Super Table *Check content table* utility helped me diagnose but couldn't fix all errors by itself and I had to figure out by myself how to fix them. 
I you also use Super table, it might be worth trying. You can find this utility at `admin/super-table/settings`.

**Comment by twosixcode** [comment]
Thanks. We are not using Supertable. I'm hoping @ttempleton  might have an idea here.
