### ISSUE TITLE
Internally link to another page

### ISSUE THREAD

**Issue by bradleyw92** [spicywebau/craft-neo#415]
I can't seem to find out a way to internally link to another page.

The best option I found was to create a field using entries which enables you to select a page you want to link with however there doesn't appear to be a way to echo that url in twig.

I then wondered whether the entries option was even suitable as that looks like it's getting information from the page you select.

I know there's a URL option but I didn't really want the client having to enter a full URL in manually, I preferred the interface of the entry one.

Any ideas, I may be missing it.

**Comment by ttempleton** [comment]
You can get the `url` property from an entry.  So if your entry field is in a Neo block, your Twig code might look something like this:

```twig
{% for block in entry.yourNeoField.all() %}
    {% set linkedPage = block.yourEntryField.one() %}
    <p><a href="{{ linkedPage.url }}">{{ linkedPage.title }}</a></p>
{% endfor %}
```
