### ISSUE TITLE
Some Blocks are losing field layouts when project config is applied.

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#416]
#### Description
I have a number of blocks that are losing their field layouts when the project config is applied from another computer.

#### Steps to reproduce
1. Created block type and added fields to field layout on one computer. 
2. Commit changes in project config to repository.
3. Pull changes to local repository on other computer and apply project config changes in CP.
4. Go to block in Neo field and field layout is empty.

#### Other information
- Neo version: 2.8.14
- Craft version: 3.5.15.1
- (if multi-site) What is the affected Neo field's propagation method: Not multi-site.
- Is eager-loading used? Haven't implemented templates yet.

**Comment by ttempleton** [comment]
I've been unable to reproduce this so far -- are there any specific fields that are common to the disappearing field layouts?

**Comment by brianrivet-tilt** [comment]
You can close this out. It seems to have fixed itself. I'm going to chalk it up to user error :)

**Comment by ttempleton** [comment]
No worries, glad it's sorted out!
