### ISSUE TITLE
"Applying new propagation method to Neo blocks" Job fails with "Attempting to save an element in an unsupported site."

### ISSUE THREAD

**Issue by twosixcode** [spicywebau/craft-neo#417]
#### Description

This is very similar (really verbatim) to a closed issue https://github.com/spicywebau/craft-neo/issues/413

But the resolution to that issue references Supertable, which we are not using.

> After upgrading to 2.8.14, I get errors in the Craft queue job Applying new propagation method to Neo blocks:

> Attempting to save an element in an unsupported site.

This queued Neo job has 1,000s of items in it and gets about 70% complete before failing with the above error.

#### Steps to reproduce
1. Have Multisite Craft install with Neo field set to "Only save blocks to the site they were created in"
2. Update to Neo 2.8.14
3. Login to Admin panel and note failed "Applying new propagation method to Neo blocks" job in the Queue Manager

#### Other information
- Neo version: 2.8.14
- Craft version: 3.5.15.1
- (if multi-site) What is the affected Neo field's propagation method: "Only save blocks to the site they were created in"
- Is eager-loading used?  No

Besides the failed job, what are the side effects, errors, or warning signs I should be looking for to test the impact of this failed job on my site?

Do you have any suggestions for how to debug this?

Thanks for any help you can provide and please let me know if you need more information.

**Comment by ttempleton** [comment]
The migration running that job was added as part of the fix for #411, so my best guess at this point is that some Neo fields that had already been affected by that issue would be involved.  I don't think this should have any other side effects or other impact on the site, but if you're concerned about that possibility, then feel free to revert to Neo 2.8.13 for the time being.

Are there any warnings in `queue.log` with the format `Unable to duplicate {element} to site {siteId}`?

Do you use a Matrix-in-Neo setup anywhere?

**Comment by twosixcode** [comment]
Thanks for the reply.

> Do you use a Matrix-in-Neo setup anywhere?

Yes, we use Matrix fields within Neo.

> Are there any warnings in queue.log with the format Unable to duplicate {element} to site {siteId}?

No, I did not see any occurences of this warning in queue.log

**Comment by ttempleton** [comment]
> Yes, we use Matrix fields within Neo. Is there something I should look into related to this?

I was thinking about whether the errors could be coming from nested Matrix blocks; even if #413 turned out to be Super Table-specific, I can't yet rule out a situation where nested block element fields are being affected in general, e.g. if there are any cases where the Neo block isn't providing the correct supported sites to them.

> Aside: I believe the Neo fields were set to "Only save blocks to the site they were created in" when we first updated to Craft 3, about a year ago. Their propagation method has not been changed since then. I'm not sure if that makes any difference here, though.

That makes it unlikely that #411 has affected the field, then (I haven't looked deeply into when that bug took effect, but I believe it could've only happened to fields that had their propagation method changed after the release of Craft 3.4).

If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au?

**Comment by twosixcode** [comment]
> If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au?

Sent! Thank you for the continued support here.

**Comment by nordentwickler** [comment]
Hello, we do have the same problem. The job "Applying new propagation method to Neo blocks" fails with "There was a problem getting the parent element." and we do have lots of errors with this messag in queue.log

```
Unable to duplicate “310809” to site 2: Attempting to duplicate an element in an unsupported site. 
2020-12-07 10:45:40 [-][2031][-][error][craft\errors\UnsupportedSiteException] craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported Stack trace:
```

And yes, it is a multi-site installation with neofields including matrix-fields. Should i send the composer.json/lock and db-backup as well?

--

**Comment by ttempleton** [comment]
Thanks for sending the email, @twosixcode; sorry about this, but could you please allow access to the included link for peter@spicyweb.com.au (currently he gets the emails sent to the plugins address) and he'll make sure the files get to me.

Thanks for the offer, @nordentwickler, hopefully we won't need any more database backups to debug this, however I am wondering whether that element with ID 310809 is a Neo or Matrix block?

**Comment by nordentwickler** [comment]
The element with id 310809 is a neo - type-Column: benf\neo\elements\Block

**Comment by ttempleton** [comment]
Thanks @nordentwickler, that makes it less likely that nested Matrix fields are involved with the errors, then.

**Comment by nordentwickler** [comment]
If you need to watch at a running system with this issue, just drop me a line and i could share a screen for you for a local environment.

**Comment by twosixcode** [comment]
@ttempleton I granted peter@spicyweb.com.au access.

**Comment by ttempleton** [comment]
Thanks @twosixcode.  I've identified a number of older Neo blocks that just seem like leftover data that isn't really associated with any sites or block structure anymore, so the queue job's attempt to save these blocks for *any* site will cause the error.  I'm currently doing some testing with deleting that Neo block data and any relevant Matrix data, which so far is working in letting the job complete, but I want to do a bit more testing to be sure it's not deleting anything important.  I'm hoping to have a release in the next day.

**Comment by ttempleton** [comment]
Just released Neo 2.8.15 including the migration to soft-delete the Neo blocks with no associated block structure.  I'll close this issue now, but @twosixcode and @nordentwickler please let me know if you're still getting this error and I'll reopen it.

**Comment by twosixcode** [comment]
Thank you for taking a look. We will test 2.8.15 in the near future and will let you know how it goes.

**Comment by nordentwickler** [comment]
@ttempleton thank you for your work - seems to be allright!
