### ISSUE TITLE
NEO-field-content gets lost

### ISSUE THREAD

**Issue by nordentwickler** [spicywebau/craft-neo#420]
#### Description
I got a very strange behavior on project. There are different neo-fields for different sections - all with the same propagation mode. On a section with a simple neofield (just 4 block types) everything works fine, but on a very complex neo-field if got the following very bad bug:

After creating and saving a new entry with content in the neo-field, the content of the neo field gets lost after creating a new revision or duplicate of the entry. The really bad thing is, that the content of the original entry gets deleted as well, so the content is lost.

Duplicating an existing entry also deletes the content of the neo-field for the original entry as well for the duplicate. This behavior doesn't happen on a section with a simple neo-field.

On thing is different: the complex neo-field uses block-types without fields or tabs in it. Filling theses block-types with ui-elements didn't help.

#### Steps to reproduce
I only can reproduce this bug in this project, on a other projects with the same versions of craft and neo, everything works fine.

#### Logfiles
There are no neo-field or entry-saving related errors in the log files and no javascript errors in the control panel.

#### Other information
- Neo version: 2.8.15.1
- Craft version: 3.5.16
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used : no 

Right now, i don't know how to debug this or what i could change. I updated the project one week ago from craft 3.4.8 to 3.5.16 and from neo 2.7.15 to 2.8.14 and today to 2.8.15 (the bug appeared in 2.8.14 as well). Saving all entries vie cls didn't help. What should i try, how could i debug this really strange behavior? 

Thank you for your help!

**Comment by ttempleton** [comment]
I don't think this is the case if it was working before you updated to Neo 2.8, but just to rule it out -- are you using either the Preparse Field or Scout plugins?  In some cases they have been reported to cause Neo field data loss, see #398 and https://github.com/spicywebau/craft-neo/issues/305#issuecomment-598745689.

If that isn't the case, if possible, could you please send your composer.json/lock and a database backup to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by nordentwickler** [comment]
@ttempleton you guys rock! Never got a better support on a plugin  🚀  👏

After removing the preparse field from the section, saving entries as a revision and duplicating them works like aspected! Thank you very much! This is the reason why a good plugin should be chargeable and should cost a yearly fee!

**Comment by ttempleton** [comment]
No worries @nordentwickler, glad it's working again!
