### ISSUE TITLE
neo fields are not saving properly (after saving the neo field values are disappearing)

### ISSUE THREAD

**Issue by mohan1712** [spicywebau/craft-neo#422]
#### Description
we have migrated our content from v2.6.x to v3.5 of craft and installed neo plugin. some of the contents got missed like images . 

#### Steps to reproduce
1.I have used neo fields and tried to modify the content as some of the images got missed in the entry
2.I saved after the images are uploaded
3. the neo field content was disappeared.

#### Other information
- Neo version:2.8.15.1
- Craft version: 3.5.16
- (if multi-site) What is the affected Neo field's propagation method: NO single site
- Is eager-loading used? no

**Comment by ttempleton** [comment]
Just to clarify, is it just the content of the images field that's disappearing, or the entire Neo block(s)?

Which other plugins do you have installed?

Which version of Neo was your Craft 2 install using?

**Comment by mohan1712** [comment]
> Just to clarify, is it just the content of the images field that's disappearing, or the entire Neo block(s)?
> "the entire blocks of the content is disappearing"
> Which other plugins do you have installed?
> "Navigation, matrixmate,Preparse Field, Reasons"
> Which version of Neo was your Craft 2 install using?
"Neo version on craft2 is 1.4.1"

**Comment by ttempleton** [comment]
Thanks for that, @mohan1712.  This is likely due to an issue with Preparse Field, which has been reported to cause Neo field content to be lost (see #398, which also involves an upgrade from Craft 2).  Disabling the Preparse Field plugin, or removing it from the affected section, should let the Neo field content save properly.
