### ISSUE TITLE
Can't delete groups in 2.8.16

### ISSUE THREAD

**Issue by lenvanessen** [spicywebau/craft-neo#423]
#### Description
Unable to delete and empty group, it just keeps popping up again

**Comment by ttempleton** [comment]
Please edit your issue report to follow the [issue template](https://github.com/spicywebau/craft-neo/blob/2.8.16/.github/ISSUE_TEMPLATE).

**Comment by ttempleton** [comment]
Going to close this as not reproducible, based on the information we have.

If the problem persists, please let us know after you've edited your issue report to follow the issue template, and we'll reopen the issue.

**Comment by DanielDarrenJones** [comment]
Having the same issue as this, is there any information we could provide to help reproduce this?

**Comment by ttempleton** [comment]
@DanielDarrenJones Please open a new issue and provide the information we request in the issue template (the question regarding eager-loading isn't relevant to this case and can be removed).  In particular, I'm interested in what (if anything) changes with the block type groups as far as the database and project config are concerned, if they're not being deleted.
