### ISSUE TITLE
Linking to channel parent rather than entry

### ISSUE THREAD

**Issue by bradleyw92** [spicywebau/craft-neo#424]
#### Description

I have a field for entries which I use for internal buttons and works really well and I can get to my relevant channels or pages nicely. The only drawback I seem to have is being able to link to the actual parent channel / structure on say a homepage CTA button such as /news.

Curious to understand what would be the best route around this please?

**Comment by ttempleton** [comment]
For general Craft CMS issues and questions that aren't specific to the Neo plugin, you might be better off either [opening an issue with Craft](https://github.com/craftcms/cms/issues), or (maybe better in this situation) [checking out some of the Craft resources and community links](https://github.com/craftcms/cms#popular-resources) for some ideas and assistance.
