### ISSUE TITLE
Multisite - Neo blocks disappear after saving it for the first time

### ISSUE THREAD

**Issue by jeffreyschmitz87** [spicywebau/craft-neo#426]
#### Description
We've updated our site from 1 language to a site with 2 languages. Our propagation method in our section is 'Only save entries to the site they were created in'.

## Neo - blocks disappear

The content from the Neo - blocks disappear after we're trying to save an Entry for the first time. After the Entry is saved for the first time the Neo - blocks *won't* remove after a save.

https://user-images.githubusercontent.com/34717885/104708088-88757800-571d-11eb-813f-a042c6e81dc7.mov

## Neo - block don't disappear

I've created a new Entry and edited the postdate from the Entry to make sure the Entry is not active but pending. When I hit the save button the content from the Neo - blocks *don't* disappear.

https://user-images.githubusercontent.com/34717885/104708138-95926700-571d-11eb-88a2-77bc3628813e.mov

## Neo - blocks seems to be deleted

I've looked inside the database and it seems the Neo - blocks are being deleted when you directly post an Entry.

Element from video 1:
![Screenshot 2021-01-15 at 10 38 49](https://user-images.githubusercontent.com/34717885/104708427-fc178500-571d-11eb-95c8-2dd071b9117a.png)

Element from video 2
![Screenshot 2021-01-15 at 10 39 28](https://user-images.githubusercontent.com/34717885/104708494-14879f80-571e-11eb-9b26-18d4f454128a.png)

Do you have any idea what causes this problem?

#### Other information
- Neo version: 2.8.16
- Craft version: 3.5.17.1

**Comment by ttempleton** [comment]
I haven't been able to reproduce this, but I'm wondering if you're using either the Preparse Field or Scout plugins? In some cases they've been reported to cause Neo field data loss, see #398 and https://github.com/spicywebau/craft-neo/issues/305#issuecomment-598745689.

**Comment by jeffreyschmitz87** [comment]
Thanks for your reply. We're not using the Preparse Field or the Scout plugin. I've listed the used plugins below:

- Advanced Url Field
- Amazon S3
- Amazon SES
- Asset Rev
- Expanded Singles
- Imager
- Mailchimp Subscribe
- Neo
- Redactor
- Relabel
- Sentry
- SEOmatic
- Table Maker

**Comment by ttempleton** [comment]
Thanks for that @jeffreyschmitz87.  If possible, could you please send your database backup and composer.json/lock to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by jeffreyschmitz87** [comment]
I would love to do that but we're using 4 custom fields from a module inside our Neo - field which causes errors if I would send over the database and composer.json/lock.

Is it possible to also send a ZIP - file containing the required modules for the custom fields?

**Comment by ttempleton** [comment]
Yeah, please do send those as well.  Thanks!

**Comment by jeffreyschmitz87** [comment]
I've sent you the files via WeTransfer

**Comment by ttempleton** [comment]
Thanks for sending those files.  I was able to reproduce the issue on your setup with the Neo field, but I was also able to reproduce it with a Matrix field, so it seems to be an issue that generally affects block element fields.  I was still unable to reproduce it on my usual testing setup (with either Neo or Matrix), so I'm not sure if this is a Craft bug or if any plugins or modules are causing this, but it doesn't appear to be a Neo bug.

**Comment by jeffreyschmitz87** [comment]
Thanks for your reply and looking into this. I've just sent an email with the same files to the support of Craft.
