### ISSUE TITLE
Blocks are losing position when changing revision of an entry

### ISSUE THREAD

**Issue by 2mas** [spicywebau/craft-neo#427]
#### Description
Hi, Neo-blocks are losing their levels when working with revisions. They all end up on the top-level when switching to older revisions.

#### Steps to reproduce
1. Create some blocks that have child-blocks on a page and save the page:
![image](https://user-images.githubusercontent.com/372362/106146692-431e6500-6177-11eb-93e4-61f69544565d.png)

2. Add something new on the page, a new sub-block is added here, to create revisions:
![image](https://user-images.githubusercontent.com/372362/106146852-7bbe3e80-6177-11eb-8a45-7e3ba7272200.png)

3. Pick an older revision to work with, all blocks are now at the same level, the two blocks on the bottom should be inside of the first one. If one reverts back to this revision, all positions are lost:
![image](https://user-images.githubusercontent.com/372362/106147339-0737cf80-6178-11eb-8e7b-403d3c3934fa.png)

Same behaviour with collapseAllBlocks true/false

#### Other information
- Neo version: 2.8.17
- Craft version: Craft Pro 3.6.1
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to all sites the owner element is saved in.
- Is eager-loading used? No

**Comment by ttempleton** [comment]
I've been unable to reproduce this so far, but I have a couple of questions:

- Does this occur for all entries in all sections, or just specific entries/sections?
- Do the affected entries/sections have any common fields besides the Neo field, particularly from other plugins or modules?

**Comment by 2mas** [comment]
We have a single for the startpage where it occurs, and also in a structure on other entries where it also occurs. I simplified this and removed the other fields to just use a minimum here:

![neo_block_order](https://user-images.githubusercontent.com/372362/106765523-2b445680-6639-11eb-90bc-5e5009e4cc38.gif)

Field type is URL on the externLink field:
![image](https://user-images.githubusercontent.com/372362/106765781-752d3c80-6639-11eb-926c-a7d4160ca294.png)

![image](https://user-images.githubusercontent.com/372362/106765850-88400c80-6639-11eb-9328-7dea154dc577.png)

**Comment by ttempleton** [comment]
Thanks @2mas, unfortunately I'm still unable to reproduce the issue on my usual testing environment.  If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by 2mas** [comment]
Much appreciated, I have sent an email. Thanks!

**Comment by ttempleton** [comment]
Thanks for sending that, @2mas.  After observing what was happening, I was able to reproduce it on my own testing setup.  It looks like it affects entries where the section isn't enabled for the primary site, the block structure isn't being saved for revisions, so we have no record of the block levels.

Interestingly, I found with your setup that after I saved the entry as a draft, then published the draft, it started saving the block structures for new revisions.  This doesn't seem to be working with my own testing setup, though, but it's a potential workaround while I figure out why it's not saving the block structures to start with.

**Comment by ttempleton** [comment]
Tracked this down to a bug in the block structure duplication job, which should now be fixed in Neo 2.8.19.  Since the block structure gets saved for the 'revision' copy of the live entry as soon as the live entry is saved, the revision that appears on the first resave of the entry after updating will still have all blocks at the top level, but any revisions after that should have all blocks in the correct places.

**Comment by 2mas** [comment]
Awesome, thanks!
