### ISSUE TITLE
Add visual indicator when validation error occurs for a field in a tab (when content editing)

### ISSUE THREAD

**Issue by deanfields** [spicywebau/craft-neo#428]
When editing content and a validation error occurs on a field in a neo block tab, theres no visual clue where the issue has occurred. You have to click on every block's tabs to find the culprit. A good solution would be to make the title of the tab red and bold, or add an icon to indicate theres a validation error on that particular tab. It would save a lot of time for content editors.

**Comment by ttempleton** [comment]
Just made an update for the upcoming Neo 2.9 release, which will show tab names in red when one of its fields has a validation error.
