### ISSUE TITLE
Neo field contents completely deleted when publishing a draft

### ISSUE THREAD

**Issue by sgtpenguin** [spicywebau/craft-neo#429]
#### Description
When attempting to publish a previously saved draft, revision, or one that gets automatically created through use of live preview, all the contents of the neo field are erased.

Crazy thing is, I can't reproduce this on a fresh install and haven't seen it on other projects, but it happens consistantly in this one.  Of course it's a huge organizational site and it's been a nightmare for content editors.  Took a while just to narrow down and reproduce the issue from "pages just disappear randomly"

#### Other information
- Neo version: 2.8.19
- Craft version: 3.6.5.1
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Does the affected Craft install use either of the Preparse Field or Scout plugins? In some cases they've been reported to cause Neo field data loss (see #398 and https://github.com/spicywebau/craft-neo/issues/305#issuecomment-598745689).

**Comment by sgtpenguin** [comment]
Yep it's Preparse.  Thank you!!  It's good to know.  Do you happen know if anyone is looking into the cause or has come up with a smooth workaround?  It might be tough to eliminate Preparse from this project.

**Comment by sgtpenguin** [comment]
I found the thread in Preparse that suggests its due to not cloning element queries.  Will be trying this when I get a chance.
https://github.com/besteadfast/craft-preparse-field/issues/36

**Comment by ttempleton** [comment]
I'm not aware of whether this is being looked into on the Preparse Field end, sorry, but hopefully cloning the element query fixes it!
