### ISSUE TITLE
Project Config yaml array strings

### ISSUE THREAD

**Issue by kayqq** [spicywebau/craft-neo#430]
#### Description
I notice that the way project config saves child blocks is different depending on save or rebuild. Sometimes its saved as new lines and sometimes they are saved as a string of an array. These inconsistencies are polluting the my commit diffs. It only happens for Neo fields

![image](https://user-images.githubusercontent.com/19341583/108289031-86e70780-7142-11eb-913e-6a1bbe14a202.png)

#### Steps to reproduce
1. php craft project-config/rebuild
2. edit and save any Neo field
3. watch the yaml changes

#### Other information
- Neo version: 2.8.19
- Craft version: 3.5.17.1
- (if multi-site) What is the affected Neo field's propagation method: Translate to all sites
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this @kayqq, should be fixed now in Neo 2.8.22.
