### ISSUE TITLE
Dynamic Asset Folders with existing Matrix Asset field.

### ISSUE THREAD

**Issue by joepagan** [spicywebau/craft-neo#432]
#### Description

Trying to use an existing "Matrix -> Asset" field's location where the previous value  was `imageText/{owner.slug}` which is now ALSO used in a Neo field. 

Trying the following value: `imageText/{{ object is neoblock ? object.owner.slug : object.slug }}` results in this alert when I try upload:

>The Image field’s Asset Location setting has an invalid subpath (“imageText/{{ object is neoblock ? object.owner.slug : object.slug }}”).

Also tried replacing `object.slug` with `owner.slug` in the else, any ideas on how I can resolve this?

#### Other information
- Neo version: ^2.9
- Craft version: 3.6.8
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? no

**Comment by ttempleton** [comment]
In this case, you would need to check whether the Matrix block's owner is a Neo block:

```twig
{{ owner is neoblock ? owner.owner.slug : owner.slug }}
```

This raises a good point that the documentation assumes the case of an asset field directly on the Neo block, and doesn't consider a case like this with Matrix (or Super Table) in-between, so I'll update the documentation in the near future to account for that.
