### ISSUE TITLE
Buggy UI Click Events

### ISSUE THREAD

**Issue by mythdigital** [spicywebau/craft-neo#439]
#### Description
The UI editor is extremely buggy when using within Craft. Click events are targeting drop downs and a simple click somewhere random within Craft is opening lots of different dropdown windows randomly. I've attached a few screenshot example.

#### Steps to reproduce
1. Add several pieces of content
2. Randomly click anywhere and it cycles through the "Settings" tab and opens random dropdown windows

#### Other information
- Neo version: 2.9.2
- Craft version: Craft Pro 3.5.17.1
- Is eager-loading used? Not sure

![image](https://user-images.githubusercontent.com/33261341/113904157-abb63d80-97c9-11eb-8881-67494838ce1a.png)
![image](https://user-images.githubusercontent.com/33261341/113904201-b8d32c80-97c9-11eb-8071-2b3cf38e43b3.png)
![image](https://user-images.githubusercontent.com/33261341/113904284-d4d6ce00-97c9-11eb-8860-911f91220161.png)

**Comment by ttempleton** [comment]
I've been unable to replicate this so far, unfortunately.  Could you please confirm the following:

- Web browser and version
- Other installed plugins
- Whether any JavaScript errors are occurring

**Comment by ttempleton** [comment]
Going to close this one as not reproducible for now, but if the behaviour persists with the latest version of Neo, please let us know the above-requested information and we'll reopen it.
