### ISSUE TITLE
Conditionals + duplicate block feature

### ISSUE THREAD

**Issue by palomamtnez** [spicywebau/craft-neo#440]
#### Description

Is it possible to add conditionals on the NEO blocks ?
I mean, in a block display a field depending on the value of another field.
Are there plans to support this ?

Also, it would be really cool if the feature to duplicate a block is supported (e.g. having a _Content_ block type, and this one has lots of fields, but if there is the need to create another block really similar to this one, at the moment I can just duplicate it manually).

**Comment by ttempleton** [comment]
Conditionals are probably out of scope for Neo, and better placed as a plugin that works across Craft that Neo can integrate with -- Neo used to work with the Reasons plugin back on Craft 2, and while Reasons has removed its plugin support on Craft 3, we'd be happy to be able to support it again if that decision is reversed.

Regarding duplicating block types, though, I've made some changes to add that feature, which will be released in Neo 2.11.

**Comment by ttempleton** [comment]
Slight change of plans for block type cloning; rather than being held back until Neo 2.11, it's now possible in Neo 2.10.5.
