### ISSUE TITLE
Neo - blocks not working with craft 3.6.12

### ISSUE THREAD

**Issue by schmidtsonian** [spicywebau/craft-neo#441]
#### Description
Since I updated to craft 3.6.12 Neo is not working anymore:
I can't save or delete anything.
I can't collapse any block
If there is an error (no required field filled), the block created is being eliminated.
If I add a new block, the content is not being saved.

Wen I add a new block, this happend:
![image](https://user-images.githubusercontent.com/2094546/114651748-27bcf380-9caa-11eb-8d39-75d609da68ca.png)

#### Other information
- Neo version: 2.9.5
- Craft version:  3.6.12

**Comment by schmidtsonian** [comment]
looks like .pill is not longer supported: https://github.com/craftcms/cms/issues/7705

**Comment by ttempleton** [comment]
Thanks for reporting this, should be working again with Neo 2.9.6.
