### ISSUE TITLE
Question Regarding Eager Loading

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#442]
I'm running Neo v. 2.9.6 and Craft 3.6.12.

I have a few questions regarding Eager loading. I get the idea of iterating through all of the Neo blocks first to create the memoized version of the content data and then using the array syntax to access the blocks.

I have my templates separated out into a lot of different includes. In those includes, if I want to access the children of the current Neo Block, I have been doing this to loop over the child blocks:

`{% for child in block['children'] %} `

I also use a conditional inside the loop to include the appropriate template for each block type, like this:

```
{% for child in column['children'] %}	  
	  {% if child.type.handle starts with 'row' %}
		  {%
			include [
			  'bodyblocks/project/rows/' ~ child.type.handle,
			  'bodyblocks/_core/rows/' ~ child.type.handle,
			  'bodyblocks/project/rows/row',
			  'bodyblocks/_core/rows/row'
			] with { 'row' :  child, 'loadType': loadType }
		  %}
	  {% elseif child.type.handle starts with 'repeater' %}
		  {%
			include [
			  'bodyblocks/project/repeaters/' ~ child.type.handle,
			  'bodyblocks/_core/repeaters/' ~ child.type.handle,
			  'bodyblocks/project/repeaters/repeater',
			  'bodyblocks/_core/repeaters/repeater'
			] with { 'repeater' :  child }
		  %}
	  {% elseif child.type.handle starts with 'accordion' %}
		{%
		  include [
			'bodyblocks/project/accordions/' ~ child.type.handle,
			'bodyblocks/_core/accordions/' ~ child.type.handle,
			'bodyblocks/project/accordions/accordion',
			'bodyblocks/_core/accordions/accordion'
		  ] with { 'accordion' :  child }
		%}
	  {% elseif child.type.handle starts with 'tabSet' %}
		{%
		  include [
			'bodyblocks/project/tabs/' ~ child.type.handle,
			'bodyblocks/_core/tabs/' ~ child.type.handle,
			'bodyblocks/project/tabs/tabSet',
			'bodyblocks/_core/tabs/tabSet'
		  ] with { 'tabSet' :  child }
		%}
	  {% elseif child.type.handle starts with 'tabPanel' %}
		{%
		  include [
			'bodyblocks/project/tabs/' ~ child.type.handle,
			'bodyblocks/_core/tabs/' ~ child.type.handle,
			'bodyblocks/project/tabs/tabPanel',
			'bodyblocks/_core/tabs/tabPanel'
		  ] with { 'tabPanel' :  child }
		%}
	  {% else %}
		  {%
			include [
			  'bodyblocks/project/blocks/' ~ child.type.handle,
			  'bodyblocks/_core/blocks/' ~ child.type.handle,
			  'bodyblocks/project/blocks/block',
			  'bodyblocks/_core/blocks/block'
			] ignore missing with { 'block' :  child, 'loadType': loadType  }
		  %}
	  {% endif %}
{% endfor %}
```
Am I checking the type handles correctly for eager loading?

Also, I'm a bit confused about how to incorporate eager loading of asset fields etc. inside of my Neo blocks. Is the data for the child asset fields also included in the memoized data from the original loop through? I don't know if I should be trying to eager load the asset fields then, or if I am supposed to eager load them when I access the child blocks for rendering. For instance, do I add the with lines for eager asset fields into the loop where I iterate through all of my blocks up front likes this?

```
{% set pageNeoBlocks = entry.pageBuilder.with(['backgroundImage', 'imageAsset', 'listParentEntry', 'listSpecificEntries', 'seoImage']).all()
{% for block in pageNeoBlocks %}
	{% do block.useMemoized(entry.pageBuilder) %}
{% endfor %}

{% for block in entry.pageBuilder if block.level == 1 %}
	{% include 'bodyblocks/_core/locationRender' with { layoutLocation: block } %}  
 {% endfor %}
```

or do the eager loaded asset/entry fields need to be included elsewhere?

Thanks!

**Comment by ttempleton** [comment]
Yep, checking the block type handles like that in the first example should be fine.  The only thing I would say is, I'd recommend using `column['children'].all()` rather than just `column['children']`, since it's still acting like any regular block query, it's just querying the memoized data for the child blocks instead of the database.

Regarding eager loading of entry/asset sub-fields of Neo blocks: Firstly, the memoized data added to each block in the first loop *does* include all eager loaded data from those fields, so it's definitely best to eager load those fields upfront like in your example.  That said, in your `with()` parameter, you'll need to prepend the block type handle to the handle of the field being eager loaded (this also means that, if you have a single sub-field that exists in more than one block type that you want to eager load for each block type, you'll need to list it separately for each block type in `with()`).  Secondly, you should use `pageNeoBlocks` in `block.useMemoized()` and in your second loop.  Something like the following:

```twig
{% set pageNeoBlocks = entry.pageBuilder.with(['blockType1:backgroundImage', 'blockType2:backgroundImage', 'blockType2:imageAsset', 'blockType3:listParentEntry', 'blockType4:listSpecificEntries', 'blockType5:seoImage']).all() %}
{% for block in pageNeoBlocks %}
	{% do block.useMemoized(pageNeoBlocks) %}
{% endfor %}

{% for block in pageNeoBlocks if block.level == 1 %}
	{% include 'bodyblocks/_core/locationRender' with { layoutLocation: block } %}  
{% endfor %}
```

Hope that helps, and let us know if you have any additional questions!

**Comment by brianrivet-tilt** [comment]
Thanks, Thomas. I ended up setting it up like this because I had some other fields in the entries that were going to need eager loading as well and the entries are auto-injected. It appears to be working but I wanted to confirm if it looks right to you.

```
{% do craft.app.elements.eagerLoadElements(
 className(entry),
 [entry],
 ['seoImage', 'headerImage', 'headerLinkButtons', 'headerBackground', 'pageBuilder', 'pageBuilder.sectionStandard:backgroundImage', 'pageBuilder.column:backgroundImage', 'pageBuilder.columnHalf:backgroundImage','pageBuilder.columnMain:backgroundImage', 'pageBuilder.columnSidebar:backgroundImage', 'pageBuilder.columnSlideContent:backgroundImage',  'pageBuilder.contentWrapper:backgroundImage', 'pageBuilder.accordion:backgroundImage', 'pageBuilder.tabSet:backgroundImage', 'pageBuilder.slide:backgroundImage', 'pageBuilder.ctaStandard:imageAsset', 'pageBuilder.image:imageAsset', 'pageBuilder.slideContentImage:imageAsset', 'pageBuilder.contentVideo:imageAsset', 'pageBuilder.repeaterItemContentLink:imageAsset', 'pageBuilder.repeaterEntryChildList:listParentEntry']
) %}

{% extends "_layout" %}

  
{% block pageContent %}
	{# Preparation for the eager-loaded Neo field #}
	
	{% for block in entry.pageBuilder.all() %}
		{% do block.useMemoized(entry.pageBuilder) %}
	{% endfor %}
	
	{% for block in entry.pageBuilder if block.level == 1 %}
		{% include 'bodyblocks/_core/locationRender' with { layoutLocation: block } %}  
	 {% endfor %}
	  
{% endblock %}

```
Thanks!

**Comment by ttempleton** [comment]
`entry.pageBuilder` should be used in the first loop, rather than `entry.pageBuilder.all()` -- trying to call `.all()` should cause an error since `entry.pageBuilder` should just be an array of blocks at that point.  Otherwise, it looks good!
