### ISSUE TITLE
Color styles missing on cloning the blocks

### ISSUE THREAD

**Issue by ajosys** [spicywebau/craft-neo#447]
#### Description
We are working on an existing Craft website for our clients. We have upgraded Craft 2.7 website to Craft 3.6. We have a valid license of NEO plugin 

Now the issue is that when we clone any section on any page then color styles, button styles (used by LJ color picker)  do not copy to the new cloned section. The styles get changed or missed.

Attached are couple of examples of what is happening.
Now our website is Live and we have found this issue, which is critical.

![Clone2](https://user-images.githubusercontent.com/6337363/117042919-31c29700-ad2a-11eb-8d08-eeac66d4f945.png)
![Clone1](https://user-images.githubusercontent.com/6337363/117042925-338c5a80-ad2a-11eb-8a6a-a6fcf67e28c7.png)

Can you please let us know what is solution for that. Your help would be highly appreciated.

#### Steps to reproduce
1. Create new NEO block on any page, and put some color styles on Buttons, links etc.
2. Use LJ Color picker fields on these Button Styles, Link colors, Line colors 
3. Clone the same block, 
Here you will see in new cloned block that Color styles are changed or completely missed.

#### Other information
- Neo version: 2.8.16
- Craft version: 3.6.12
- LJ Color Picker: 1.0.2
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
I reproduced this with Neo, but I also reproduced it using [Smith](https://plugins.craftcms.com/smith) to clone a Matrix block with an LJ Color Picker field, so the buggy LJ Color Picker behaviour isn't caused by Neo and you should report it to the LJ Color Picker developer.

**Comment by ttempleton** [comment]
I opened a pull request with LJ Color Picker https://github.com/lewisjenkins/craft-color-picker/pull/2 which will fix the bug.  Until it's merged and released, you can apply the fix locally by opening the file `vendor/lewisjenkins/craft-color-picker/src/fields/Spectrum.php` and changing line 68 from:

```php
if ($this->isFresh($element)) {
```

to:

```php
if ($this->isFresh($element) && $value === null) {
```
