### ISSUE TITLE
NEO child block not showing when live preview or preview page 

### ISSUE THREAD

**Issue by fei-yump** [spicywebau/craft-neo#454]
#### Description
The child blocks are not showing when preview the page.

#### Steps to reproduce
1. Under page edit page, click "Live preview" or "Preview this page" button.
2. The page is not showing any child blocks.

#### Other information
- Neo version: 2.9.7
- Craft version: 3.6.14
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? No

After my investigation, found in the file Block.php (vendor/spicyweb/craft-neo/src/elements/Block.php), in function "public function isDraftPreview()" line 588. Not sure is it because craft update but I print out $route, the controller shows "preview/preview" which is different to this file "entries/view-shared-entry". After I change this line the child block shows up.

OLD: if ($route && $route[0] == 'entries/view-shared-entry') 
SUGGEST: if ($route && $route[0] == 'preview/preview')

Not sure this is correct solution or not. Thanks

**Comment by ttempleton** [comment]
This sounds like the same issue as #451, which was fixed in Neo 2.9.8 yesterday.  I'm going to close this issue for now, but if you're still having issues with it after updating, let us know and we'll reopen.
