### ISSUE TITLE
Add a thumbnail to a block button so the user sees an example with its intended usage

### ISSUE THREAD

**Issue by bartwttewaall** [spicywebau/craft-neo#460]
#### Description
This would be a nice improvement: adding an image to a block that would popup when you mouse over a block button.
We have content managers, tasked with setting up pages with components that are non-intuitively named like 'horizontal cta list'. A picture is worth a thousand words, right? A thumbnail preview of the block would help them greatly.

**Comment by ttempleton** [comment]
This seems pretty similar to #256 which is now implemented by the [Matrix Field Preview](https://plugins.craftcms.com/matrix-field-preview) plugin, so I definitely recommend checking out Matrix Field Preview.
