### ISSUE TITLE
Group names containing no top-level blocks still appear in top-level dropdown

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#461]
### Description
I'm using groups for blocks that are set to not display on the top level, but inside other top-level blocks. Those group titles are still displaying in the main top-level selection box on the front end with no children.

### Steps to reproduce
1. Create a group containing blocks with "Top Level" disabled.
2. Open the top-level menu on the front end (on a narrow enough width that the top-level buttons become a dropdown menu).

#### Expected Behavior
Groups containing no top-level blocks should not display in this dropdown menu.

#### Actual Behavior
Group titles display with no blocks below.

![Screen Shot 2021-06-02 at 10 56 47 AM](https://user-images.githubusercontent.com/42223501/120530062-f00d2680-c391-11eb-8316-fbf71998b20c.png)
![Screen Shot 2021-06-02 at 10 56 14 AM](https://user-images.githubusercontent.com/42223501/120530070-f3081700-c391-11eb-974b-eea1df34e091.png)

### Other information
- Neo version: 2.9.9
- Craft version: 3.6.15
- (if multi-site) What is the affected Neo field's propagation method: N/A
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Just implemented a fix for this which will be released as part of Neo 2.10.

**Comment by ttempleton** [comment]
Neo 2.10.0 has just been released, which includes the fix for this.
