### ISSUE TITLE
Version update issues from v2.9.6 to v2.9.12

### ISSUE THREAD

**Issue by minalove** [spicywebau/craft-neo#465]
#### Description

Hi, I'm trying to upgrade the version from `2.9.6` to `2.9.12` but I have an error. 

```
One of Neo’s migrations failed.

yii\base\ErrorException: array_filter() expects parameter 1 to be array, string given
Migration: benf\neo\migrations\m210603_032745_remove_blank_child_block_types
Output:
Exception: array_filter() expects parameter 1 to be array, string given (/app/vendor/spicyweb/craft-neo/src/migrations/m210603_032745_remove_blank_child_block_types.php:35)
#0 {main}
```

#### Steps to reproduce
1. Go to the admin page
2. Go to utilities
3. Update Neo's version

FYI, some of YAML has childBlocks as array string format.
childBlocks: '["tile"]'

#### Other information
- Neo version: 2.9.6
- Craft version: Updated  3.6.12 to 3.6.16
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Thanks for reporting this, it should now be fixed in Neo 2.9.13.
