### ISSUE TITLE
Exception when querying posts from other sites with Neo blocks

### ISSUE THREAD

**Issue by gglnx** [spicywebau/craft-neo#472]
#### Description

I'm querying posts from another site (ID 2) on site ID 1 and query then the blocks for a Neo field. I'm getting following exception:

> yii\base\ErrorException
>
> First parameter must either be an object or the name of an existing class
> 
> vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php in handleError at line 517
> vendor/craftcms/cms/src/web/ErrorHandler.php in handleError at line 76
> vendor/craftcms/cms/src/web/ErrorHandler.php in property_exists
> vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php in _ownerElementHasProp at line 517
> vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php in _isDraftRequest at line 529
> vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php in beforePrepare at line 438
> vendor/craftcms/cms/src/elements/db/ElementQuery.php in prepare at line 1382
> vendor/yiisoft/yii2/db/QueryBuilder.php in build at line 227
> vendor/yiisoft/yii2/db/Query.php in createCommand at line 157
> vendor/yiisoft/yii2/db/Query.php in all at line 249
> vendor/craftcms/cms/src/db/Query.php in all at line 152
> vendor/craftcms/cms/src/elements/db/ElementQuery.php in all at line 1547
> vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php in all at line 270

I think the error was introduced with 2.9.7 and `allowOwnerDrafts`. `_ownerElementHasProp` uses `Craft::$app->getElements()->getElementById` but without a site id, so on site 1 a post only from site 2 isn't found.
 
#### Steps to reproduce
1. Create two sites, a section with one Neo field without propagation.
2. Create a post only on site 2.
3. Open site 1 and try to query the post from site 2.

#### Other information
- Neo version: 2.10.3
- Craft version: 3.6.17
- What is the affected Neo field's propagation method: `none`
- Is eager-loading used? No.

**Comment by ttempleton** [comment]
This was fixed in Neo 2.10.4 (see #469).

**Comment by gglnx** [comment]
Oh, great. Sorry for missing the issue. Thank you <3
