### ISSUE TITLE
Graphql mutations

### ISSUE THREAD

**Issue by EmptyStreets** [spicywebau/craft-neo#474]
Hi, 

Considering using neo for the upcoming project. Does neo support graphql mutations (native craft feature)?

**Comment by ttempleton** [comment]
Yes, Neo supports GraphQL mutations.  It works mostly the same as with [Matrix fields](https://craftcms.com/docs/3.x/graphql.html#matrix-fields-in-mutations), but with a couple of [small differences](https://github.com/spicywebau/craft-neo/blob/2.10.5/docs/graphql.md#mutations) to be aware of.
