### ISSUE TITLE
FR: Return flattened structure in GraphQL query

### ISSUE THREAD

**Issue by membla** [spicywebau/craft-neo#475]
#### Description

As GraphQL does not support recursion, in a tree structure of arbitrary depth it's very handy to be able to query for the full flattened structure and let the client recreate the tree, thus being able to just write a query like:

```
leaf {
   children {
      id
   }
}
```

instead of having to do:

```
leaf {
   children {
      children {
          children {
             ...etc
          }
      }
   }
}
```

I saw this was actually how it was implemented before:
https://github.com/spicywebau/craft-neo/issues/425

And while the current implementation makes for straightforward queries when you know the number of levels you want to query (and the structure isn't too deep), could we have an option to also return the flattened structure (either using a new input argument or perhaps by using `level:-1`)?

**Comment by ttempleton** [comment]
Hmm, this should have been possible by setting the field query `level: 0`, but that doesn't seem to be working at the moment.  Will work on a fix for that.

**Comment by ttempleton** [comment]
Setting `level: 0` on the field should now be working in Neo 2.10.6.

**Comment by membla** [comment]
Fantastic – thank you!
