### ISSUE TITLE
Max. siblings ignores blocks added using 'add block above'

### ISSUE THREAD

**Issue by bram-dewitte** [spicywebau/craft-neo#477]
#### Description
I have a Neo-field with a block that you can add a child-block to. On the child-block I have the setting "Max Sibling Blocks of This Type" set to 4.
When making an entry and after adding 4 children to the parent block, the button underneath the childblocks becomes disabled. When you click the cog on the top right of one of the child-blocks, you can still choose the option "add block above".
This allows you to have more child blocks than your max limit is set to.

#### Steps to reproduce
1. Make a Neo-field
2. Add a block.
3. Give said block a child block.
4. Set max siblings setting on child-block to 4.
5. Make an entry using your new blocks.
6. When you've hit the maximum of 4 child-blocks, click the cog on the top right of a child-block.
7. Click "Add block above".

#### Other information
- Neo version:
- Craft version:
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Thanks for reporting that -- the fix has just been released in Neo 2.10.8 and will also be included in 2.11.1.
