### ISSUE TITLE
How to create migration that adds child to block?

### ISSUE THREAD

**Issue by weotch** [spicywebau/craft-neo#478]
Consider a Neo configuration with children like this:

![Blocks - CMS 2021-07-10 at 2 12 33 PM](https://user-images.githubusercontent.com/77567/125176515-e5ac2c80-e188-11eb-93b9-66303b4de7ee.jpg)

I would like to make a Craft migration that creates blocks and their children.  Here's an example:

```php
// Create entry
$section = Craft::$app->sections->getSectionByHandle('towers');
$type = $section->getEntryTypes()[0];
$tower = new Entry();
$tower->sectionId = $section->id;
$tower->typeId = $type->id; 

// Add Neo blocks
$tower->setFieldValues([
    'blocks' => [
        [
            'type' => 'wrapper',
            'children' => [
                [ 
                    'type' => 'spacer',
                    'fields' => [ 'spacing' => 'm' ],
                ],
            ],
        ]
    ],
]);

// Save it
Craft::$app->elements->saveElement($tower);
```

In this example, the `wrapper` block gets created but the `spacer` one does not.  I was just guessing at `children` as the property to add my array of child blocks to.  Thank you in advance for guidance!

**Comment by ttempleton** [comment]
What you'd need to do in this case is to provide all blocks in one array, but also provide the `level` property for each block, setting the first block to `1` and the child block to `2`.  When the field value is set like that, any level 2 block(s) immediately following the level 1 block will be detected as child(ren) of that block.  Using your example, this should work:

```php
$tower->setFieldValues([
    'blocks' => [
        [
            'type' => 'wrapper',
            'level' => 1,
        ],
        [
            'type' => 'spacer',
            'level' => 2,
            'fields' => [ 'spacing' => 'm' ],
        ],
    ],
]);
```

**Comment by leevigraham** [comment]
This works, except I needed to start at level 0… and then make the children level 1. If I started at level 1… only one child block was created.
