### ISSUE TITLE
Losing all content on page save

### ISSUE THREAD

**Issue by JordanMed** [spicywebau/craft-neo#480]
#### Description
Any time I  add a new block/remove a block/make an edit, all of my content is deleted from my page. Revisions are also losing all of their content on reverting to an older version.

#### Steps to reproduce
1. Make any change in an entry wait until it auto saves, then manual save.
2. All neo blocks are now empty, sometimes the new one I created has the correct info but all other blocks are empty. 
3. Revert to older version (ex. revision 18).
4. Revision 18 is now empty
5. Content from Revision 18 is now placed into current version and my page is back.

#### Other information
- Neo version: 2.11.1
- Craft version: 3.7.3.2
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used? yes

![126175196-5396663c-031f-4127-b1f9-011505c0d887](https://user-images.githubusercontent.com/54858742/126175720-93fb8af3-510b-4238-b851-1e7055da249e.png)
![126175431-a515d00f-3311-4e2b-86b2-e3aa74d84642](https://user-images.githubusercontent.com/54858742/126176038-48249f2d-fbc8-42e8-b5d7-86bbb2a78cdd.png)
![126174968-39f2ee00-2793-4bdb-ac41-595a1e539315](https://user-images.githubusercontent.com/54858742/126176040-2bf0e43e-bb4e-484d-90ca-afca3c2a9ada.png)

**Comment by brandonkelly** [comment]
Seems related to #479.

**Comment by JordanMed** [comment]
I've read through #479 I'll try rebuilding my project config and report back the results.

**Comment by jegra** [comment]
we've been encountering the same issue - content is being lost upon saving entries.  have isolated it to content stored with neo fields (other fields within the page do not appear to be affected)...

**Comment by ttempleton** [comment]
I haven't been able to reproduce the entry content loss on save yet.  According to the discussion in craftcms/cms#9601 this might not be Neo-specific, but I'll leave this issue open for now.

**Comment by brandonkelly** [comment]
This actually ended up being a Craft bug (craftcms/cms#9601). Just released Craft 3.7.4 with a fix.

**Comment by ttempleton** [comment]
Thanks for the update @brandonkelly!
