### ISSUE TITLE
[FR] Require child blocks or provide more Min Blocks options

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#482]
#### Description
When I create a container block for a page builder field, the block is pointless without child blocks (text, image, etc). I'd find it very useful if there were a way to require certain blocks to have child blocks, either by marking the "Child Blocks" field placeholder as required, or even better, being able to specify a corresponding minimum number of X every place where we can already specify a maximum number of X:
![image](https://user-images.githubusercontent.com/1027523/126496508-28292301-7eb5-4511-973a-f75af6d6dc3e.png)

#### Other information
- Neo version: 2.11.1
- Craft version: 3.7.4

**Comment by ttempleton** [comment]
I've added the min settings in the [`enhancement/min-block-settings`](https://github.com/spicywebau/craft-neo/tree/enhancement/min-block-settings) branch, and they'll be included in Neo 3.3.

**Comment by ttempleton** [comment]
Just released Neo 3.3.0 including the min settings.
