### ISSUE TITLE
Question: get related block from other site

### ISSUE THREAD

**Issue by rauwebieten** [spicywebau/craft-neo#484]
#### Description

I have a question. Given a block "A" on a neo field in "site A"
How can I query the db to find the related (propagated) block for "site B"?

Is this what the canonicalId is for?

(setting: all blocks are propagated on all sites)

#### Other information
- Neo version: 2.11.0
- Craft version: Craft Pro 3.7.4
- (if multi-site) What is the affected Neo field's propagation method: save blocks to all sites

**Comment by ttempleton** [comment]
If the Neo field's blocks are saved for all sites, then a block will have the same `id` across all sites and you can use that along with `siteId` to get the version of the block for site B. Assuming site B's `id` is 2, you would do something like:

(Twig)
```twig
{% set blockB = craft.neo.blocks({
    id: blockA.id,
    siteId: 2,
}).one() %}
```

(PHP)
```php
$blockB = \benf\neo\elements\Block::find()
    ->id($blockA->id)
    ->siteId(2)
    ->one();
```

The `canonicalId` is unrelated, it's used to relate live entry blocks to the versions of those blocks that exist in entry drafts and revisions.
