### ISSUE TITLE
Rearranging blocks is not saved until adding or removing a block

### ISSUE THREAD

**Issue by swissmexxa** [spicywebau/craft-neo#488]
#### Description
When reordering Neo-Blocks the new ordering does not get saved. Neither on save and on preview. It does not make any difference if rearranging children blocks or first level blocks. The new order is only saved if I add a new block or I delete an existing one. It even works if I add a new block and delete it right away.

#### Steps to reproduce
1. Add multiple Neo blocks with/without children on a page
2. Save page
3. Reopen page and rearrange blocks
4. Resave page and reopen page
5. Order is now reset to previous order
6. Rearrange blocks
7. Add new block or delete an existing block | Add new block and delete it again
8. Resave page
9. New Order is now saved

#### Other information
- Neo version: 2.11.3
- Craft version: 3.7.6
- Is eager-loading used? no

**Comment by ttempleton** [comment]
Thanks for reporting that -- should now be fixed in Neo 2.11.4.
