### ISSUE TITLE
[Feature Request] Warn / list unused fields on Neo deletion

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#490]
#### Description
When deleting a Neo field, it would be very handy if it could display a list of the custom fields (with edit links) that were in use by that Neo field, **and** are not used anywhere else in the site (incl. Globals, Assets, entry field layouts, etc). This would make it vastly simpler to know what other fields are safe to delete if a given Neo field is no longer needed.

Thanks!

**Comment by ttempleton** [comment]
[Field Manager](https://plugins.craftcms.com/field-manager) should work fine for this purpose (and for telling you about any other unused fields), so I definitely recommend that.

**Comment by proimage** [comment]
Ahh, good to know, thanks! In the past I seem to recall Field Manager's Neo support being a bit quirky, but it looks good now.
