### ISSUE TITLE
Syntax error on m210812_052349_fix_single_site_block_structures

### ISSUE THREAD

**Issue by jerome2710** [spicywebau/craft-neo#491]
#### Description
The 2.11.6 update pushed an hour ago (CC: @ttempleton) contains a syntax error in the added migration:

```
*** applying m210812_052349_fix_single_site_block_structures
Exception 'ParseError' with message 'syntax error, unexpected ')''

in /app/vendor/spicyweb/craft-neo/src/migrations/m210812_052349_fix_single_site_block_structures.php:49
```

The last `,` should not be there: https://github.com/spicywebau/craft-neo/blob/master/src/migrations/m210812_052349_fix_single_site_block_structures.php#L48

**Comment by ttempleton** [comment]
Thanks for pointing that out (for the record, I was using PHP 8, where that is valid syntax). Will fix and release shortly.

**Comment by jerome2710** [comment]
Thanks for the quick fix! Not all of our projects are yet running on PHP 8, this one was 7.X indeed.
