### ISSUE TITLE
Translating "Move Down" in the block dropdown field

### ISSUE THREAD

**Issue by scandella** [spicywebau/craft-neo#492]
Hi,
There is no no entry in the translation file for the "Move Down" option in the dropdown field of the block settings.
Even when I create one, this option stay untranslated.

Thanks for your help.

![CleanShot 2021-08-19 at 15 26 13](https://user-images.githubusercontent.com/1114307/130076751-2baf4a82-fb55-4c50-b7b1-bdb58b0d819f.png)

**Comment by ttempleton** [comment]
Thanks for reporting this -- those options should now be translatable in Neo 2.11.7.

(Note: the button text has now been changed to "Move up" and "Move down" in Neo 2.11.7 for consistency with how they're capitalised on Matrix blocks.)
