### ISSUE TITLE
An exception is thrown when a preview page is generated containing a neo field. 

### ISSUE THREAD

**Issue by magnessjo** [spicywebau/craft-neo#495]
#### Description

Our needs are probably unique; we are generating preview URLs within the templates (it's a weird business requirement).  We are getting the error that we create a preview token for a page with a neo field (See attached).  

From what I know (I'm a novice with Craft tokens), the code `$route && $route[1][$prop] !== null` looks correct to me.  `getTokenRoute` returns false or an array.  I'm not sure how the revisionId ($prop) is not catching on the null check, though.  The token is generated by us and has a route of 'preview/preview'.  Example of token creation below.  

```
      {% set token =
        craft.app.tokens.createToken(
          [
            'preview/preview',
            {
              elementType: 'craft\\elements\\Entry',
              sourceId: article.id,
              siteId: 1
            }
          ]
        )
      %}
```

Any guidance would be appreciated.  Thanks! 

<img width="1552" alt="Screen Shot 2021-08-27 at 2 36 47 PM" src="https://user-images.githubusercontent.com/856595/131188684-1ceb56cc-fff5-492c-a56d-e99bda4cbea3.png">

#### Other information
- Neo version: 2.11.8
- Craft version: 3.7.10

**Comment by ttempleton** [comment]
Thanks for reporting this – we should've been checking if the property existed on the token at all, not just if it was set to `null`. Should be working now in Neo 2.11.9.
