### ISSUE TITLE
Can't publish entry if field in a disabled neo block is invalid

### ISSUE THREAD

**Issue by Harry-Harrison** [spicywebau/craft-neo#497]
#### Description
If I have a neo field on the page that is Disabled and field within that block doesnt pass validation, Craft is unable to save the page and I'm shown the errors.

#### Steps to reproduce
1. Have a neo field on an entry and have a required field within a block of the neo filed
2. Create an entry and disable a neo block with the required field in it
3. Save the entry

#### Other information
- Neo version: 2.11.7 (Downgraded from 2.11.9 to help with speed issue)
- Craft version: 3.7.11
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this — should be fixed in the next Neo release.

**Comment by ttempleton** [comment]
Just released Neo 2.11.10 which includes the fix for this issue.
