### ISSUE TITLE
Saving empty childBlock fields in project config

### ISSUE THREAD

**Issue by iainhenderson** [spicywebau/craft-neo#502]
When saving Neo fields in the CMS, Neo saves empty childBlock property values as empty strings in the project config. Rebuilding the config or reapplying the config in Craft (through the CMS or command line) saves empty childBlock parameters as nulls

![Screen Shot 2021-09-13 at 3 36 22 pm](https://user-images.githubusercontent.com/775758/133031424-8fd23422-a65f-4603-994d-e5fe5542c093.png)

I believe this issue may be related to https://github.com/spicywebau/craft-neo/issues/430 The behaviour may have been fixed for arrays, but there may be some typecasting missing for empty values.

This inconsistent behaviour can lead to regular back and forth changes in the config files, which can makes it harder to see meaningful config changes in our commits.

#### Steps to reproduce
1. run project-config/apply --force
2. Modify and save a Neo field 
3. Make a commit
4. run project-config/apply --force again.
5. Make a commit

#### Other information
- Neo version: 2.11.12
- Craft version: 3.7.12
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this, should be fixed in Neo 2.11.13.
