### ISSUE TITLE
Neo showing empty field on entry for specific user

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#503]
#### Description

We have a Neo field that we are using for a page builder. My client created a page by duplicating another page and then editing the content on the copy. After saving the page, when she goes to the page to make edits, the Neo field appears to be empty on her screen, but for other users, including users in the same user group, the Neo field shows all of the content blocks, etc. as it should be. I can 

#### Steps to reproduce
1. Log in as admin. View the Oktoberfest entry under Pages, note the Neo field has content blocks
2. Go to Users and log in as the user with the issue, view the Oktoberfest entry again, note the empty Neo field.
3. Log back in as admin and then log in as another user in the same group, view the same post again, and note the Neo field has all the blocks.

#### Other information
- Neo version: 2.1..13
- Craft version: 3.7.13
- (if multi-site) What is the affected Neo field's propagation method: no
- Is eager-loading used? yes

I can provide credentials and directions as to specific users to use to check the issue privately.

**Comment by ttempleton** [comment]
Could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, and we'll have a look at it.

**Comment by brianrivet-tilt** [comment]
Hi, I've seen this issue resurface, but it does not appear to be a caching issue after all. It seems to be tied to something with the draft system. When I log in as the user who was having the issue, I see it on my machine as well. The dropdown at the top of the entry with the issue shows unsaved edits to the entry, but when I look down the neo field isn't showing any of the content blocks. If we tell Craft to discard the changes, the entry goes back to normal. I just wanted to see if having unsaved edits in a draft can cause any sort of issue with Neo that you are aware of.

**Comment by ttempleton** [comment]
I'm unaware of issues with Neo and unsaved edits in a draft at the moment; my guess would've been that something is going on when saving the provisional draft for an entry that's causing the Neo blocks to not be duplicated for the provisional draft in some cases, but that seems impossible in this case if it's only showing an empty field for one user.

Are there any JavaScript errors when the field is empty?
