### ISSUE TITLE
Tried to load an unregistered type error on Live Preview GraphQL mutation

### ISSUE THREAD

**Issue by membla** [spicywebau/craft-neo#504]
#### Description

Running a GraphQL mutation using a live preview token results in a `Tried to load an unregistered type "blockContent_NeoInput"` error. The same query seems to work well when using GraphiQL. The error presents itself as identical to what was experienced by another third party GraphQL type [here](https://github.com/craftcms/cms/issues/7551) but I am not sure if it is.

Potential solution: https://github.com/craftcms/cms/issues/7551#issuecomment-783387212

**Comment by ttempleton** [comment]
Could you please provide detailed steps to reproduce the error with Neo.
