### ISSUE TITLE
Neo blocks are lost when switching between versions

### ISSUE THREAD

**Issue by jimyhse** [spicywebau/craft-neo#506]
#### Description
Neo blocks are lost when we're reverting a page to a previous version and then restoring it back.

#### Steps to reproduce
1. Create a new page entry
2. Add a neo block ("block 1") to the page and click on 'Save and continue editing' (_revision 1_)
3. Add a neo block ("block 2) to the page and click on 'Save and continue editing' (_revision 2_)
4. Select _revision 1_ of the page and click on 'Revert entry to this revision'. Current revision will now contain "block 1" - which is correct.
5. Select _revision 2_ of the page and click on 'Revert entry to this revision'. Current revision will now contain only "block 1". The second block "block 2" is lost!

![example](https://user-images.githubusercontent.com/91942722/135992438-1883753f-698c-45a7-9fdf-7e8458dbfbe0.png)

#### Other information
- Neo version: 2.11.13
- Craft version: 3.7.14
- Is eager-loading used? No

**UPDATE:**
We cannot reproduce this bug in version 2.11.8 of Neo, so it must have been introduced after that.

**Comment by ttempleton** [comment]
I'm able to reproduce this with Matrix as well, so I'll assume it's a Craft bug affecting both field types. Will be happy to reopen the issue if it turns out to be a separate bug, though.

**Comment by jimyhse** [comment]
Thank you for your quick response! I'll report the bug to craft.

**Comment by brandonkelly** [comment]
@ttempleton Just fixed this for Matrix blocks. The fix for Neo will probably be similar: https://github.com/craftcms/cms/commit/752e9e92e0051dc4c34dbcdc6c6cff9668bb5b42

**Comment by ttempleton** [comment]
@brandonkelly Thanks!

@jimyhse The fix for Neo blocks is now included in Neo 2.11.14.
