### ISSUE TITLE
Draft Entry Content Missing when upgrading from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by wesleyhuang23** [spicywebau/craft-neo#507]
#### Description
Upgraded from craft 2 to 3 and the content in the drafts has gone missing, but the matrix blocks are still intact. Is there anyway to salvage or migrate the content over? One thing I noticed was the draft id was 130 in craft 2 and changed to 23 in craft 3, but in the db tables in craft 3 after the upgrade does not exist anymore.

#### Steps to reproduce
1. Upgrade Craft 2 to 3

#### Other information
- Neo version: 2.11.14, craft 2 version: 1.5.2
- Craft version: 3.7.17, craft 2 vserion: 2.9.2
- (if multi-site) What is the affected Neo field's propagation method: No
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Going to close this issue for now and assume it was the Redactor field. Let me know if that isn't the case and which field type(s) it's happening with and I'll reopen it.
