### ISSUE TITLE
Eager loading child block fields

### ISSUE THREAD

**Issue by leightonhughes** [spicywebau/craft-neo#511]
#### Description
I'm trying to eager load an assets field which is located in a set of children blocks. The entry is in another section as I'm reusing these entries with an entries field.

This is the one I'm having troubles with. Is there some syntax that I've missed or is there a limit on the depth?
'snippets:reusableSnippetsMain.neoPageBuilder.testimonials.testimonialGroup.blockquote.author:neoImage',

I've been successful with other blocks like this:
'snippets:reusableSnippetsMain.neoPageBuilder.imageGallery:neoImage',

#### Other information
- Neo version: 2.11.15
- Craft version: 3.7.17.2
- Is eager-loading used? Yes

**Comment by ttempleton** [comment]
No need to give the path of descendant block types down to the one with the eager loaded assets field — just giving the child block type with the assets field is enough (e.g. if `author` is the child block type needing its `neoImage` eager loaded, then just `snippets:reusableSnippetsMain.neoPageBuilder.author:neoImage` should be fine).

**Comment by leightonhughes** [comment]
Hi @ttempleton, still coming up short with this unfortunately.
Wondering whether it's because it's a neo field within a neo field. I'm able to eager load an assets field from a second level neo field block but not inside another child block. Are you available on discord to discuss?
