### ISSUE TITLE
The fields setup in my Neo are not indexed by Craft

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-neo#520]
#### Description
The fields setup in my Neo are not indexed by Craft:
- Of course, the fields that are setup in the Neo are searchable (the magnifying glass icon is displaying in each field line of `/admin/settings/fields`);
- This happens both on an old version (`Neo 2.9.7` + `Craft Pro 3.6.14`) than the latest one (`Neo 2.11.18` + `Craft Pro 3.7.21`);
- This happens both on the Craft CP search (from `/admin/entries`) than on my search page on front-end;
- I have resaved all entries twice using `./craft resave/entries` + `./craft resave/matrix-blocks`;
- `optimiseSearchIndexing` setting is untouched from default config;

#### Other information
- Neo version: 2.9.7 & 2.11.18
- Craft version: Craft Pro 3.6.14 & 3.7.21
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Going to close this for now, based on the discussion in craftcms/cms#10120, but happy to reopen it if any Neo bugs turn out to be involved.
