### ISSUE TITLE
Propagation method "Custom" missing

### ISSUE THREAD

**Issue by TheFunkyMonk** [spicywebau/craft-neo#522]
#### Description
I have a multi-site install that needs the "Custom" block propagation method, which is available for Matrix fields, but not for Neo fields.

On Matrix fields, the options available are:
- Only save blocks to the site they were created in
- Save blocks to other sites in the same group
- Save blocks to other sites with the same language
- Save blocks to all sites the owner element is saved in
- Custom

Where "Custom" allows for an expression to be inserted (in this case, limiting translation to a specific entry type). Can this be added to Neo?

#### Steps to reproduce
1. Create a new Neo field on a Craft multi-site install
2. View available translation methods
3. "Custom" option is missing from list

#### Other information
- Neo version: 2.11.19
- Craft version: 2.7.23
- (if multi-site) What is the affected Neo field's propagation method: N/A
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Added this to Neo 2.12, which will be released next week.

**Comment by ttempleton** [comment]
Neo 2.12.0 has just been released including the custom propagation method.

**Comment by TheFunkyMonk** [comment]
Awesome, thanks for the quick support!
