### ISSUE TITLE
Add the ability to limit the block types available for a given usage of a Neo field.

### ISSUE THREAD

**Issue by Kethatril** [spicywebau/craft-neo#524]
#### Description
We have a number of entry types that share certain block types but not others. Currently we have to manually duplicate these shared block types between the Neo fields for each entry type. This is prone to user error, and if these shared block types change then they have to be updated in many places.
It would be nice to have the ability to limit the allowed block types based on the entry type of the entry a Neo field is displayed in (or some other criteria).
We are currently using javascript to achieve this but it is fairly fragile.

Longer term it would be nice to be able to share block types between Neo fields, but that seems like a much more complex job.

**Comment by ttempleton** [comment]
This was requested previously by #114 — it's a great idea, I don't have a time frame for it yet but it's definitely planned to happen.
