### ISSUE TITLE
Matrix blocks (within a Neo field) are not reverted correctly

### ISSUE THREAD

**Issue by jimyhse** [spicywebau/craft-neo#527]
#### Description
Matrix blocks (within a Neo field) are not reverted correctly.

#### Steps to reproduce
1. Create a Matrix field with a block containing a plain text field
2. Create a Neo field with a block containing the matrix field
3. Create a page entry type with the Neo field
4. Create and save an entry of the new page type with the text set to "Version 1"
5. Update the text to "Version 2" and save the page again
6. Revert the page to the first revision. The text will be set to "Version 2",  instead of "Version 1".

Example after revert:
![example](https://user-images.githubusercontent.com/91942722/145591421-74271fef-4a97-4e59-9904-978252d70fb4.png)

#### Other information
- Neo version: 2.11.21
- Craft version: 3.7.25.1
- (if multi-site) What is the affected Neo field's propagation method: -
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Looks like this also happens when a Matrix field is in a Super Table field, so I recommend opening an issue with Craft about this.

**Comment by brandonkelly** [comment]
@ttempleton I was able to fix this on Matrix’s end (https://github.com/craftcms/cms/commit/b69399caf71d9a02d82fad76ff04db6add46f73f) however I suspect a similar bug could still exist if the fields were reversed, with Neo inside of Matrix. So you should probably make the same fix there.
