### ISSUE TITLE
Setting unknown property: benf\neo\Field::propagationKeyFormat

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-neo#529]
#### Description
I worked on multiple branches, sharing the same database, and now got this error each time I try to load a page from CP or front-end:

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: benf\neo\Field::propagationKeyFormat
```

I tried to uninstall/reinstall Neo twice, clear all caches, composer install / update, ... but always get this error.
This error only disappears when the Neo field is uninstalled, which is not what I'm looking for.

Any idea why and how to fix this?

#### Other information
- Neo version: 3.7.26
- Craft version: 2.11.21
- Multi-site: yes, but without propagation
- Is eager-loading used? No

**Comment by ttempleton** [comment]
The `propagationKeyFormat` setting was added in Neo 2.12.0 — I'm guessing one of your branches is using 2.12.0 or 2.12.1 instead of 2.11.21. Updating any branches using 2.11 to 2.12 should fix it.
