### ISSUE TITLE
Persistant "Component class 'benf\neo\Field' belongs to an uninstalled plugin (Neo)" error

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-neo#530]
#### Description
I have a project that required multiples branches, and multiple databases (as a few settings where stored in DB only, not in project config).
After merging from one branch to another, I got this error:
`Component class 'benf\neo\Field' belongs to an uninstalled plugin (Neo).`

It's not the first time I got it and can easily fix it like this:
`composer require spicyweb/craft-neo`

When it's not enough:

1. I try again with `composer remove spicyweb/craft-neo` before the other one
2. I run `./craft plugin/enable neo`

Or alternatively:

1. Uninstall plugin from `/admin/settings/plugins`
2. Install plugin from `/admin/settings/plugins`

Unfortunately, I still got the same error that the plugin is missing.
Even after running:
```
./craft project-config/rebuild
./craft project-config/apply
```

In `/admin/settings/fields` all my Neo fields are still showing benf\neo\Field in red color text.

Any idea how to fix this?

#### Other information
- Neo version: 2.12.1
- Craft version: 3.7.27.1
- Multi-site: yes, but without propagation
- Is eager-loading used? No

**Comment by romainpoirier** [comment]
I finally found that this was probably due to a project config file conflict.
In some version, the Neo plugin has probably been disabled and/or uninstall because of error.
It was effectively disabled/uninstalled, but things were not updated in the project config file.
This was resulting with the `Component class 'benf\neo\Field' belongs to an uninstalled plugin (Neo) error` even if it was installed and an active plugin.

**Comment by ttempleton** [comment]
I don't think Neo would've caused this as the plugin itself shouldn't be doing anything to affect its own installed/uninstalled state, but I'll keep an eye on craftcms/cms#10323.
