### ISSUE TITLE
Populating Neo Field from PHP

### ISSUE THREAD

**Issue by khamer** [spicywebau/craft-neo#535]
Hey there, I'm writing tests and am looking to populate a Neo field from PHP, similar to how you can populate Matrix fields or [Super Table fields](https://verbb.io/craft-plugins/super-table/docs/template-guides/php-example). I thought that this would work:

```php
$entry->setFieldValues([
  'myNeoField' => [
    [
      'type' => 1, //block type
      'fields' => [
        'someBlockField' => 'something here',
      ],
    ],
  ],
]);

Craft::$app->elements->saveElement($entry);
```

But it doesn't. I've tried using the block handle for `type`, nesting the blocks behind a `'blocks' =>` key, using the arbitrary `new1`, `new2`, keys like Super Table and vanilla Matrix blocks can use - nothing. Any tips would be most appreciated. Thanks.

**Comment by ttempleton** [comment]
You're on the right track regarding the use of `blocks`, `new1`, `new2`, etc. keys and using the block type handle — you just need to also set the `sortOrder` of the blocks, as well as some other block properties that are optional (but likely to be needed in the case of `level` in particular).

The following example adjusted for your Neo field / block type handles should work:

```php
$entry->setFieldValues([
    'myNeoField' => [
        'blocks' => [
            'new1' => [
                'type' => 'blockType1',
                'level' => 1, // optional, defaults to 1
                'enabled' => true, // optional, defaults to true
                'collapsed' => false, // optional, defaults to false
                'fields' => [
                    'someBlockField' => 'something here',
                ],
            ],
            'new2' => [
                'type' => 'blockType2',
                'level' => 2,
                'enabled' => true,
                'collapsed' => false,
                'fields' => [
                    'someBlockField' => 'something else here',
                ],
            ],
        ],
        'sortOrder' => [
            'new1',
            'new2',
        ],
    ],
]);

Craft::$app->elements->saveElement($entry);
```
