### ISSUE TITLE
Localized fields nested in localized Neo blocks overwritten by source values when publishing multiple languages

### ISSUE THREAD

**Issue by sidedwards** [spicywebau/craft-neo#536]
## 🐛 Bug description

As the title describes, localized fields nested within _localized Neo blocks_ are getting overwritten by source values when publishing drafts in multiple languages. Non-localized Neo blocks are working as expected.

## 👣 Reproduction steps

1. Create a Neo field with the propagation method "Only save blocks to the site they were created in" (i.e., "Localized").
2. Add localized fields within the Neo block.
3. Open an Entry and create two separate drafts.
4. In the first draft, update the localized field values within the Neo block.
5. In the second draft, switch to another site and update the localized field values within the Neo block.
6. Apply the first draft.
7. Localized field values should reflect updates from step 4.
8. Apply the second draft.
9. See error. The localized field value updates from the first draft are reverted to the original content.
  _Note: I'm noticing some duplicate blocks as well in the second applied draft._

## 📚 Resources

https://user-images.githubusercontent.com/11489608/151844605-fa67ecf5-8f73-4e71-ae69-14ca773b8134.mp4

## ⚙️ Other information
- Neo version: 2.12.3
- Craft version: 3.7.30.1
- (if multi-site) What is the affected Neo field's propagation method: "Only save blocks to the site they were created in"

## 🔗 References

This was a similar issue in the Super Table plugin that has since been resolved.
- https://github.com/verbb/super-table/issues/434

**Comment by ttempleton** [comment]
Thanks for reporting this! Fixed now in Neo 2.12.4.

**Comment by sidedwards** [comment]
@ttempleton, thank you so much for the quick fix 🙏
