### ISSUE TITLE
How would I fetch a single Neo block by its ID?

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#544]
#### Description
I need to get at the contents of a single Neo block, without knowing what field, entry, or even section it belongs to[^1]. With Matrix, it seems like there is a `craft.matrixBlocks()` thing that would allow that kind of direct-to-block access. I see [Neo's API](https://github.com/spicywebau/craft-neo/blob/master/docs/api.md) lists one of the parameters as `id`, so I tried:

```twig
{% set foo = craft.neo().id(neoBlockId).one() %}
```

But all I got was this:

> Neither the property "id" nor one of the methods "id()", "getid()"/"isid()"/"hasid()" or "__call()" exist and have public access in class "benf\neo\Variable".

What am I doing wrong?

#### Steps to reproduce
1. Create a Neo field & assign it to a Section
2. Create an entry in said Section, and populate it's Neo field with a block.
3. Try to fetch the contents of said block from a template that otherwise isn't connected to the Neo field's entry whatsoever.

#### Other information
- Neo version: 2.12.4
- Craft version: Craft Pro 3.7.30.1
- (if multi-site) What is the affected Neo field's propagation method: There's two fields, both of which are set to "Only save blocks to the site they were created in"
- Is eager-loading used? Not yet

[^1]: If need be, I could probably get any of the above information, it just really complicates matters, so the less I need to, the better.

**Comment by ttempleton** [comment]
The Neo equivalent of `craft.matrixBlocks()` is `craft.neo.blocks()`, so `craft.neo.blocks().id(neoBlockId).one()` should work. I don't think `craft.neo.blocks()` is mentioned anywhere in the documentation, so I'll make a note to add it in the near future.
