### ISSUE TITLE
Javascript problem with settings dropdown menu

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#545]
I'm seeing an issue in the control panel on a client site where if the user clicks the gear menu on a Neo block in the control panel the menu appears then disappears almost immediately and then when it disappears if you try to click the menu again, it just jumps to the top of the page, like the javascript for the menu isn't firing properly.

#### Other information
- Neo version: 2.12.4
- Craft version: 3.7.33
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used? don't believe so but don't think it is applicable.

**Comment by ttempleton** [comment]
This sounds like issue #541 where this was happening with nested Matrix blocks; if it's the same issue, then updating to Neo 2.12.5 will fix it.
