### ISSUE TITLE
upgrade Neo,Applying new propagation method to Neo blocks，keep running!!!

### ISSUE THREAD

**Issue by dsfofwuc** [spicywebau/craft-neo#547]
#### Description
We upgraded from craftcms3.4 and craft-neo2.5.10 to craftcms3.7.28 and neo2.12.5 and found some problems. After the upgrade, Queue has been running. It has been running for about 20 hours, and it is still increasing. The specific The composer configuration file is as shown below, the Queue Manager screenshot is as follows, and the queue.log file is detailed in the attachment. Please help to see what the problem is, thank you
#### Steps to reproduce
1.Upgrade craftcms and Neo

#### Other information
- Neo version:2.12.5
- Craft version:3.7.28
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?
![image](https://user-images.githubusercontent.com/37402393/158318395-8670a571-6c0b-4010-97de-89a7d7874b15.png)
![image](https://user-images.githubusercontent.com/37402393/158318556-782937c9-fae0-4f39-a3e3-2cb38790a6b6.png)
![image](https://user-images.githubusercontent.com/37402393/158318741-754db860-b070-4142-92d6-fb0852d548dd.png)
![image](https://user-images.githubusercontent.com/37402393/158318797-cc797df1-5dfb-4b77-8440-dd664d8871e1.png)
![image](https://user-images.githubusercontent.com/37402393/158318828-95619f4a-24f3-497f-87ad-fe5159b1b3f0.png)

**Comment by dsfofwuc** [comment]
Hope for a quick fix, thanks

**Comment by ttempleton** [comment]
See https://github.com/spicywebau/craft-neo/issues/526#issuecomment-990529143 for an explanation of why this happened. As mentioned in that comment, if you've never changed the propagation method on any of your Neo fields, then it's safe to cancel the jobs.

I'll add a console command to add the jobs later this week, instead of doing it through a migration, and I'll see if I can reduce the number of jobs at the same time.

**Comment by dsfofwuc** [comment]
> See [#526 (comment)](https://github.com/spicywebau/craft-neo/issues/526#issuecomment-990529143) for an explanation of why this happened. As mentioned in that comment, if you've never changed the propagation method on any of your Neo fields, then it's safe to cancel the jobs.
> 
> I'll add a console command to add the jobs later this week, instead of doing it through a migration, and I'll see if I can reduce the number of jobs at the same time.
-------------------------------------------------------------
@ttempleton 
Thank you, I cancel all the jobs, I feel no error; but the craftcms page is very slow to load, save data is also very slow and save Entries 504 time out

**Comment by ttempleton** [comment]
There were some performance issues with Neo and Matrix fields, but they should have been fixed a few months ago. Does it load and save fine if Neo is disabled?

(As a side note, Neo 2.13.0 has just been released, which moves the reapplying of Neo fields' propagation methods to a console command, `php craft neo/fields/reapply-propagation-method`. Reapplying using the `--by-block-structure` option may be required to fix the bug mentioned in https://github.com/spicywebau/craft-neo/issues/526#issuecomment-990529143 and may still generate a large number of jobs, but shouldn't be as many as before, as it now skips blocks that belong to an entry revision.)

**Comment by dsfofwuc** [comment]
> There were some performance issues with Neo and Matrix fields, but they should have been fixed a few months ago. Does it load and save fine if Neo is disabled?
> 
> (As a side note, Neo 2.13.0 has just been released, which moves the reapplying of Neo fields' propagation methods to a console command, `php craft neo/fields/reapply-propagation-method`. Reapplying using the `--by-block-structure` option may be required to fix the bug mentioned in [#526 (comment)](https://github.com/spicywebau/craft-neo/issues/526#issuecomment-990529143) and may still generate a large number of jobs, but shouldn't be as many as before, as it now skips blocks that belong to an entry revision.)

@ttempleton After Neo is disabled, the save entry is still 504, but refreshing the page data is saved again; 504 will appear every time you save

**Comment by ttempleton** [comment]
It doesn't seem to be caused by Neo, then, if it's still happening when Neo is disabled. I see you've also opened https://github.com/craftcms/cms/issues/10759 so hopefully the suggestions there resolve your issue.
