### ISSUE TITLE
Error during migration

### ISSUE THREAD

**Issue by mikewink** [spicywebau/craft-neo#548]
#### Description

While updating my production system I got this error while running `php craft migrate/all`.

```shell
Checking for pending migrations ...
Total 1 new Neo migration to be applied:
    - m220228_081104_add_group_id_to_block_types

Apply the above migration? (yes|no) [no]:yes
Create database backup? (yes|no) [yes]:yes
Backing up the database ... done
*** applying m220228_081104_add_group_id_to_block_types
Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'plugin:neo-m220228_081104_add_group_id_to_block_types' for key 'migrations_track_name_unq_idx'
The SQL being executed was: INSERT INTO `migrations` (`track`, `name`, `applyTime`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('plugin:neo', 'm220228_081104_add_group_id_to_block_types', '2022-03-16 11:06:35', '2022-03-16 11:06:35', '2022-03-16 11:06:35', '38fb8151-8d90-4560-8a20-c41f1c4831a7')
```

I did the same operation on my local system where I did not run into this. Running the the migration command again says that there is nothing to migrate.

#### Other information
- Neo version: now 2.13.0, before was 2.12.5
- Craft version: 3.7.36
- (if multi-site) What is the affected Neo field's propagation method: "Only save blocks to the site they were created in"
- Is eager-loading used? yes

**Comment by ttempleton** [comment]
Not sure how that has happened, but it wouldn't be caused by Neo - plugins are not in control of inserting the row into the `migrations` table themselves.

That said, you should be able to resolve it by deleting the existing row for the `m220228_081104_add_group_id_to_block_types` migration and then running `php craft migrate/up --plugin=neo`.
