### ISSUE TITLE
2.13.0 is broken on installation

### ISSUE THREAD

**Issue by boboldehampsink** [spicywebau/craft-neo#549]
#### Description

See screenshot with stack trace

<img width="1329" alt="Screen Shot 2022-03-17 at 09 20 09" src="https://user-images.githubusercontent.com/378974/158766770-86e2c8de-c395-49dc-a645-5d5b7ac2c592.png">

**Comment by ttempleton** [comment]
Thanks for reporting - should be fixed now in 2.13.1.
