### ISSUE TITLE
craft.neo.blocks()

### ISSUE THREAD

**Issue by jacksoncool** [spicywebau/craft-neo#550]
Can you provide a short example on how to use the `craft.neo.blocks()` tag?

**Comment by ttempleton** [comment]
Say you want to get all blocks that belong to a specific Neo field, that are related to a specific entry. You could do that with either of the following:

```twig
{% set relatedBlocks = craft.neo.blocks({
    fieldId: someNeoField.id,
    relatedTo: someEntry,
}).all() %}
```

```twig
{% set relatedBlocks = craft.neo.blocks().fieldId(someNeoField.id).relatedTo(someEntry).all() %}
```

`craft.neo.blocks()` returns a Neo block query that supports the same parameters as other types of [Craft element queries](https://craftcms.com/docs/3.x/element-queries.html), and also parameters supported by [Matrix block queries](https://craftcms.com/docs/3.x/matrix-blocks.html#parameters).
