### ISSUE TITLE
Project Config Incompatibility / Misuse

### ISSUE THREAD

**Issue by AugustMiller** [spicywebau/craft-neo#551]
#### Description

Due to the implementation of [4660645](https://github.com/spicywebau/craft-neo/commit/466064508ac9774eff5638f0ebca5bf453d2247c) as a fix for #217, Neo appears to allow updates to Project Config in the process of responding to other changes.

Specifically, Neo attaches to the appropriate [`update` event](https://github.com/spicywebau/craft-neo/blob/62f04af4b9ee70498840b1c6bb7a3947eb380069/src/Plugin.php#L139) to update a block, but calls `set()` again, _even in circumstances when the event is triggered by the change itself_, squashing changes to any other blocks in the same field.

After some research today, `ProjectConfig::readOnly` is probably not a good indicator of the source of the changes—in fact, it's mostly just an environmental flag that the service uses internally; the correct check would probably be against `ProjectConfig::getIsApplyingYamlChanges()`! The Project Config service [already protects against inadvertent writes](https://github.com/craftcms/cms/blob/develop/src/services/ProjectConfig.php#L505-L512) in `readOnly` mode.

I think it's just a matter of updating [this](https://github.com/spicywebau/craft-neo/blob/62f04af4b9ee70498840b1c6bb7a3947eb380069/src/services/BlockTypes.php#L263) and [this](https://github.com/spicywebau/craft-neo/blob/62f04af4b9ee70498840b1c6bb7a3947eb380069/src/services/BlockTypes.php#L289) to `!$projectConfigService-> getIsApplyingYamlChanges()`—or at least it resolves the cyclical writes in my local environment, while still allowing “real” changes to the field settings via the CP.

Some abstract notes I'm compelled to record as my understanding of Project Config develops…

I believe the intent is to separate explicit configuration (in essence, calls to `ProjectConfig::set()`) from database changes. In practice, this means that Neo (or any other plugin) would only ever interact with the Project Config service _in response to CP changes_; then, atomic operations on the database (i.e. `Db::update()`) would be performed _in response to events emitted by the Project Config service_—either as part of the same request, or later in another environment, via the CLI, CI pipeline, etc.

#### Related Issues
- #217 
- #406 

#### Steps to reproduce

Unfortunately I don't have a good idea of how we ended up here. One of our apps just… stopped cooperating with our workflow—my partner made some changes, and my local installation would no longer apply changes without immediately reverting and deleting them from the on-disk YAML files. At the risk of sounding flippant, I'm not sure how it _ever_ worked! We've been making updates to this particular page builder pretty regularly over the last 12–18 months, and this is the first time it's cropped up… although we've certainly had our fair share of Project Config-related [conflicts](https://github.com/craftcms/cms/issues/7795)! 😂

#### Other information
- Neo version: 2.13.1
- Craft version: 3.7.37
- (if multi-site) What is the affected Neo field's propagation method: —
- Is eager-loading used? —

**Comment by AugustMiller** [comment]
I've submitted [a similar issue](https://github.com/solspace/craft3-freeform/issues/304) to FreeForm, because it uses a similar cyclical `set()` call, but within a Migration. We encountered both issues on the same app, at the same time, which made debugging really interesting!

Overnight (this morning?), I realized that this is actually only a problem when integrating changes from one development environment into another, when `allowAdminChanges` is set to `true`. This also implicitly sets `ProjectConfig::readOnly` to `false`, and allows Neo to re-write its own settings.

In deployment/CI, we don't observe the same symptoms, because the check of `readOnly` fails and the subsequent `set()` call is not made. :v:

**Comment by ttempleton** [comment]
Thanks for reporting this - should be fixed now in Neo 2.13.2.

**Comment by AugustMiller** [comment]
Brilliant, thanks for the quick fix!

At first, I couldn't tell how this was going to work—but I see now that because the Block Types are in their own PC “namespace,” those atomic updates (`handleChanged*`, `handleRemoved*`) aren't affected by the top-level `Field` check. I like it! 😎
