### ISSUE TITLE
Feature Request: Console command to resave all neo blocks and update search indexes

### ISSUE THREAD

**Issue by tekstrand** [spicywebau/craft-neo#557]
#### Description
It would be great to have a CLI option to resave neo blocks and update the search indexes similar to [entries/assets/matrix blocks](https://craftcms.com/docs/3.x/console-commands.html#resave).

We're trying to reduce the size of our searchindex using the Relax plugin https://github.com/ostark/craft-relax#update-search-index

**Comment by ttempleton** [comment]
Just released Neo 2.13.5 with the `resave/neo-blocks` command, which takes the same options as `resave/matrix-blocks`.
