### ISSUE TITLE
Saving an element with a large number of blocks is slow/times out

### ISSUE THREAD

**Issue by tekstrand** [spicywebau/craft-neo#558]
#### Description
We're trying to save entries with around 300 blocks, and experiencing very long save times, causing timeouts.

#### Steps to reproduce
1. Add lots of blocks to a page, we're seeing this start to happen around the 200 block count
2. Save the entry

#### Other information
- Neo version: 2.13.3
- Craft version: 3.7.31
- (if multi-site) What is the affected Neo field's propagation method: Only save blocks to the site they were created in
- Is eager-loading used? n/a

**Comment by ttempleton** [comment]
I'm going to assume this is the same issue as https://github.com/craftcms/cms/issues/10759, in which case you should follow the suggestions from https://github.com/craftcms/cms/issues/10759#issuecomment-1068902844 until you upgrade to Craft 4.

**Comment by ttempleton** [comment]
I'll suggest doing some testing with a Matrix field and seeing if you get significantly better performance than with Neo. Besides having to create block structures, the way Neo blocks are saved is pretty much the same as how Matrix blocks are saved, so if the performance of the two fields is similar, then it'd be better to comment on that issue, but the issue should be resolved by the performance improvements mentioned in that issue as coming to Craft 4.
