### ISSUE TITLE
FR: Collapse all Neo/Matrix blocks by default when opening an Entry in the CMS

### ISSUE THREAD

**Issue by development-lameco** [spicywebau/craft-neo#559]
#### Description
_Not sure if this is a FR for the Neo Plugin or the way Craft handles Matrix fields in general._

We use Neo/Matrix blocks to create a list of page elements (blocks) to create a very dynamic content page.

Now when you use a lot of elements (blocks) on a single page, because you have a lot of content, this creates a long list of blocks to scroll through to find the one you are looking for.

We think it would help if all these blocks are collapsed by default if you open an Entry in the CMS.

#### Steps to reproduce
1. Create multiple NEO blocks
2. Add multiple blocks to a page

#### Other information
- Neo version: 2.13.4
- Craft version: 3.7.38

**Comment by ttempleton** [comment]
You can do this with Neo fields by setting the following in the file `config/neo.php` in your project:

```php
<?php

return [
    'collapseAllBlocks' => true,
];
```

**Comment by development-lameco** [comment]
Sorry, we must have missed this config option.

**Comment by ttempleton** [comment]
Yeah, my bad, it doesn't seem like I mentioned it anywhere in the documentation. I'll make a note to add that soon.

The other plugin setting is `optimiseSearchIndexing` (defaults to `true`) which controls whether to skip updating search indexes for Neo blocks that have no sub-fields set to use their values as search keywords, or that belong to Neo fields that aren't set to use the field's values as search keywords.
