### ISSUE TITLE
Craft 4: Editing field layout of one block affects other blocks

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#560]
#### Description

I am trying to set up a Neo field with various blocks. I have found that editing one block type clobbers the others.

#### Steps to reproduce

1. Make a new neo field
2. Set up a few blocks, each with different fields in them
3. Save
4. Edit the neo field
5. See that all of the blocks now have the same field in them
6. Edit one of the blocks
7. Save
8. Edit the neo field
9. See that all of the blocks now have the field you just switched to, not only the single block you edited

See video:

https://user-images.githubusercontent.com/199635/164323815-f678666b-424b-4221-b227-efb0927d9687.mp4

#### Other information
- Neo version: 3.0.0-beta.2
- Craft version: 4.0.x-dev at 22be557
- (if multi-site) What is the affected Neo field's propagation method: multi-site is on. Propagation method is whatever default is.
- Is eager-loading used? Whatever is default

**Comment by ttempleton** [comment]
Thanks for reporting that, it turned out that all new block types' field layouts were getting assigned the same UID, so saving each field layout would overwrite the previous one. That should be fixed now in 3.0.0-beta.3.
