### ISSUE TITLE
Usability: when adding a new block type, the "settings" tab should be selected, not "field layout"

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#561]
#### Description

When I click to add a new block type, I want the panel on the right to default to the "settings" tab, not whatever tab I was most recently using.

I just made a different block, and so "field layout" was active. Now I make a new block and "field layout" is still active. I can launch into adding fields to it, and it's then easy to forget I didn't go through the "settings" and name the thing yet, and saving will fail.

This has been an annoyance while evaluating Neo. (In the video in the bug report I opened a moment ago you can see me go to enter the name of the new block before realizing I'm still on the wrong tab, every single time, even though I've done this a bunch of times already.)

#### Steps to reproduce
1. Add a new block type
2. Fill in settings, switch to field layout, add whatever
3. Add a new block type
4. Panel still has "field layout" tab active

#### Other information
- Neo version: 3.0.0-beta.2
- Craft version: 4.0.x-dev at 22be557
- (if multi-site) What is the affected Neo field's propagation method: whatever default is
- Is eager-loading used? whatever default is

**Comment by ttempleton** [comment]
Fair enough, just made this change for the next beta release (https://github.com/spicywebau/craft-neo/commit/592c6dff141dbb8c00bdece7e8c2a66a7a0a1acd).

**Comment by tremby** [comment]
I see that it's been applied any time I switch block. If that's how you like it, I don't have any strong objections, but the only time I really meant it should flip back to the first tab is when clicking "+ block type" to add a new one.

**Comment by ttempleton** [comment]
Ah, sorry, I misread. I've changed it in 3.0.0-beta.3 to change to the settings tab when adding a block type, not when selecting one.
