### ISSUE TITLE
[Craft 4] - `_hasSearchableBlockType` variable comparison is string compared to int

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#564]
#### Description

Trying to save a block. `_hasSearchableBlockType` throws an exception due to a strict comparison:

![image](https://user-images.githubusercontent.com/25124/166405474-09f9efe2-4943-4c63-bdf7-4efb544605e2.png)

![image](https://user-images.githubusercontent.com/25124/166405482-764f0f43-022c-44dc-9564-077821bef713.png)

#### Other information
- Neo version: Neo 3.0.0-RC3 
- Craft version: Craft CMS 4.0.0-RC2

**Comment by ttempleton** [comment]
Thanks for pointing that out. Since it's using the same code for that on Craft 3 as well, I've just released Neo 2.13.7 to fix that, and it'll be fixed for Craft 4 in the next Neo 3 release.
