### ISSUE TITLE
[Craft4] Hiding title in Neo field layout editor throws error

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#565]
Edit field in layout editor to trigger slide out:

![Screen Shot 2022-05-03 at 4 16 36 pm](https://user-images.githubusercontent.com/25124/166411599-57a79e95-7e85-4ac5-997e-8877fa65309a.png)

Click Apply (throws JS error):

![Screen Shot 2022-05-03 at 4 16 58 pm](https://user-images.githubusercontent.com/25124/166411610-cff7612a-0120-4f37-bfb4-3111e4f6eb35.png)

Click "Leave Page" in hope field still save s (it doesn't)

![Screen Shot 2022-05-03 at 4 17 19 pm](https://user-images.githubusercontent.com/25124/166411614-3c2433be-e991-446f-bfb8-33952c521ba1.png)

@brandonkelly could this be an issue with the slideout editor? Normal field editing works fine.

**Comment by ttempleton** [comment]
That will be fixed in the next Craft release (https://github.com/craftcms/cms/issues/11026).

**Comment by brandonkelly** [comment]
4.0.0-RC3 is out now with this change.
