### ISSUE TITLE
Neo performance issues

### ISSUE THREAD

**Issue by angrybrad** [spicywebau/craft-neo#568]
#### Description

Debugging some performance issues on a site that has Neo installed.

Looks like this commit introduced some significant unintended overhead: https://github.com/spicywebau/craft-neo/commit/d2c58e0393aefdee1f4de343cdc5202faa00d43b

<img width="681" alt="CleanShot 2022-05-03 at 15 42 47@2x" src="https://user-images.githubusercontent.com/61869/166585331-17de4cc6-383d-473f-afa1-61726f6bb7ff.png">

The scenario is, on an entry page with a complicated IA, editing an entry's title so a provisional draft is created, then clicking "save and continue" to promote it to a live entry. The entire request takes 1:45 and 1:05 of that is running the SQL necessary to restore the elements triggered from the above commit. It feels like there should be some extra guard checks there to ensure it only runs in the exact scenario it was trying to fix, instead of how broadly it runs now.

#### Other information
- Neo version: 2.13.7 and head of 3.x branch
- Craft version: 3.7.40 and 4.0.0-RC3

**Comment by ttempleton** [comment]
Thanks for reporting that. Reverting entry revisions with Neo fields seems to now be working fine after removing that code, so I've just released Neo 2.13.8 with that change, and that change will also be made in the next Neo 3 release.
