### ISSUE TITLE
[FR] Block picker

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#569]
Having some kind of block picker with icons and descriptions would be a welcomed addition.

I'm not sure how this could work with nested blocks.

In our current build we're overriding the NEO css so the "Add a block" button is always shown:

![image](https://user-images.githubusercontent.com/25124/166633501-e93b19ad-6354-42a8-86d0-4f5ed556e602.png)

Example from Webflow

![image](https://user-images.githubusercontent.com/25124/166633271-796217b7-65e1-466b-a6f9-5e088330dc8d.png)

Example from Vizy

![image](https://user-images.githubusercontent.com/25124/166633436-7aff50a4-c1bc-41f5-bfd3-54dd3d4778b0.png)

**Comment by bryantAXS** [comment]
Agree 100% - I would love this.

**Comment by ttempleton** [comment]
I'm pretty keen to add this soon - just wondering if anyone has feedback on whether the choice between this and the existing buttons should be set at the plugin or field level?

**Comment by leevigraham** [comment]
My Vote: **Plugin Level**: Content admins don't need two UI's

**Comment by leevigraham** [comment]
@ttempleton I just took a look at the main branch, nice work getting this in!

A little bit of feedback. The icons / buttons need to be way smaller. Here's a couple of mockups:

![Screenshot 2023-01-16 at 3 08 50 pm](https://user-images.githubusercontent.com/25124/212596828-5ae93ff0-05d2-4456-9c0a-41dffe17eaf3.png)
![Screenshot 2023-01-16 at 3 04 54 pm](https://user-images.githubusercontent.com/25124/212596835-8caed7a9-8967-417a-a8fb-f15cfd5ea256.png)

I think I actually prefer the list style as its much easier to scan down the list.

**Comment by leevigraham** [comment]
@ttempleton Looks like you're using the Granish menu javascript and overriding a lot of styles. Pairing back your customisations and adding a few tweaks we get something like:

![Screenshot 2023-01-16 at 3 36 25 pm](https://user-images.githubusercontent.com/25124/212599637-05c98818-6fd8-4040-a2a6-c60cab5b9fda.png)

**Comment by Mathias-Syversen** [comment]
This looks really promising!

Having the option to override the template that prints out this list would be amazing.
We could have huge custom pickers with screenshots and design or just a simple list.

Neo could then come with a simple list / grid by default.

Kinda like what Matrix Field Preview does, but maybe not as big, custom / override template for this would open the door to make something similar:
![screenshot-16](https://user-images.githubusercontent.com/53942798/212691101-4d2feeeb-2ba2-4a47-9788-be0144668ace.jpg)

**Comment by ttempleton** [comment]
Thanks for the feedback!

@leevigraham regarding the list style, I've just made some changes to replace the `useNewBlockGrid` setting with `newBlockButtonType`, which has the following options:

- `'matrix'`: the traditional, Matrix-inspired buttons/dropdowns;
- `'grid'`: the Vizy-inspired grid as you've already seen it;
- `'list'`: styled similarly to what's shown in your last screenshot.

Regarding the grid icon size, I'll have a chat to our dev team about that when I get a chance on Thursday and will update here.

@Mathias-Syversen I think allowing custom new block button/menu styles is a great idea! I'm not sure if it's feasible in the short term, since all of the new block buttons/menus are currently rendered in JavaScript, but it's something I'd definitely like to do in the future.

**Comment by bryantAXS** [comment]
I love seeing all this chatter and movement happening here! Thanks for the great work folks :)

**Comment by leevigraham** [comment]
I'm with @Mathias-Syversen,

The modal looks great and gives users much more information. We have all the elements to build that (image / icon, title, and description).

I would love to see this as an option…

**Comment by ttempleton** [comment]
I've just made some changes to:

- make the icons smaller on the grid, as suggested;
- change the name of the setting from `newBlockButtonType` to `newBlockMenuStyle`;
- change the `'matrix'` option to `'classic'`.

Sorry about the repeated setting name changes 😅

Happy to hear any other feedback on how the grid/list styles could be improved. Regarding adding the ability to customise/override the new block menu - please feel free to open a new issue for that.

**Comment by ttempleton** [comment]
I've just released Neo 3.6.0 with the grid/list menu styles.

**Comment by Mathias-Syversen** [comment]
The icons seems to be saved in project config as a relation to an asset?
This wont work when pushing to production. Also activating admin changes to add the icons in production is a no go.
How is this supposed to work?

**Comment by rauwebieten** [comment]
Having the same issue as [Mathias-Syversen](https://github.com/Mathias-Syversen)

This feature is not working in a setup with a local development combined with a production environment where 1. the development assets are not available, and 2. the admin changes are not allowed.
