### ISSUE TITLE
Method Illuminate\\Support\\Collection::level does not exist after updating to Craft 4

### ISSUE THREAD

**Issue by peaffenzeller** [spicywebau/craft-neo#570]
#### Description
according to the plugin store, NEO is already supporting craft 4.
we just updated our project to Craft 4, but now when I open graphiql, I can't run queries on NEO fields anymore.
seems to be a problem with the resolvers in craft-neo.

```
"errors": [
    {
      "debugMessage": "Method Illuminate\\Support\\Collection::level does not exist.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "trace": [
        {
          "file": "/Users/peter.affenzeller/Documents/projects/global-careersapp/craftcms/src/vendor/spicyweb/craft-neo/src/gql/resolvers/elements/Block.php",
          "line": 71,
          "call": "Illuminate\\Support\\Collection::__call('level', array(1))"
        },
        {
          "file": "/Users/peter.affenzeller/Documents/projects/global-careersapp/craftcms/src/vendor/craftcms/cms/src/gql/base/ElementResolver.php",
          "line": 88,
          "call": "benf\\neo\\gql\\resolvers\\elements\\Block::prepareQuery(instance of craft\\elements\\Entry, array(0), 'dtcContentBuilder')"
        },
        {
          "file": "/Users/peter.affenzeller/Documents/projects/global-careersapp/craftcms/src/vendor/spicyweb/craft-neo/src/gql/resolvers/elements/Block.php",
          "line": 24,
          "call": "craft\\gql\\base\\ElementResolver::prepareElementQuery(instance of craft\\elements\\Entry, array(0), array(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        ...
```

#### Steps to reproduce (I guess)
1. Create a new test field with type `NEO` and a content block
2. Create a structure using the test field
3. Create an entry and add some test content
4. Open graphiql and try to query the entry with its content

As long as I only query fields other than the NEO field, everything works fine. As soon as I try to query the NEO test content, I get the above error.

#### Other information
- Neo version: 3.0.0 (also tried 3.0.0-beta.1)
- Craft version: 4.0.0-RC3 (also tried 4.0.0.1)

**Comment by ttempleton** [comment]
Thanks for reporting that bug - should be fixed now in Neo 3.0.1.
