### ISSUE TITLE
"Unable to nest Neo fields." Message on Neo field in Craft 4

### ISSUE THREAD

**Issue by idawgik** [spicywebau/craft-neo#572]
#### Description
I have a new in development site updated to Craft 4 using Neo. I've configured the Neo field like I do on all other sites I've built, but on the entry edit page, instead of the Neo field being shown, it's just a message saying "Unable to nest Neo fields." 

![Screen Shot 2022-05-06 at 10 58 08 AM](https://user-images.githubusercontent.com/5238797/167178289-1bc5ae40-2233-418b-822c-c14cf20267fb.png)

I'm not nesting Neo inside of anything else, it's just it's own standalone field. Never had this issue on any other site previously, so not sure what I'm doing wrong.

#### Steps to reproduce
1. On Craft 4 create a Neo field
2. Add field to section
3. Go to edit page and see error

#### Other information
- Neo version: 3.0.1
- Craft version: 4.0.1
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to all sites the owner element is saved in
- Is eager-loading used? No

**Comment by ttempleton** [comment]
There seems to be a bug in Neo at the moment where Twig errors cause this to happen instead of the actual error being displayed.

- In your browser's dev tools, does the network activity show a 500 internal server error?
- Which field / UI element types are your Neo block types using?

**Comment by idawgik** [comment]
Found the issue in the logs. Turns out it was an issue with a Redactor config on a field used in Neo.

**Comment by ttempleton** [comment]
Ah, glad you resolved that.

Just released Neo 3.0.2 with a fix for the "Unable to nest Neo fields" error displaying instead of the actual error, which should hopefully make this kind of issue easier to debug in the future.

**Comment by yoannisj** [comment]
I  just ran into this issue again with Neo 3.4.0 on Craft 4.2.7, when using an oEmbed field inside Neo.

It tuns out that oEmbed field throws an error:
```
[19-Oct-2022 10:10:45 America/Los_Angeles] PHP Fatal error:  Declaration of wrav\oembed\jobs\BrokenUrlNotify::execute($queue) must be compatible with craft\queue\JobInterface::execute($queue): void in /var/www/html/vendor/wrav/oembed/src/jobs/BrokenUrlNotify.php on line 22
```

.. and I believe Neo catches the error and shows its nesting error (the nesting error does not appear anymore after removing the nested oembed field). Maybe Neo is using a slightly too aggressive `try {} catch() {}` statement?

**Comment by ttempleton** [comment]
Fields' `inputHtml()` methods are being called a second time after an error occurs, with extra namespace depth added. With Neo, that triggers the nesting error. I'll collect some more information about it and open a Craft issue soon.
