### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#573]
#### Description
When accessing the form-variable (or even only passing it to another script via include) I get the error:
> Serialization of 'Closure' is not allowed

Outside of Neo everything works fine. 

#### Steps to reproduce
1. Create a Neo field and add a Wheelform field to it
2. Try to output the contents of the Neo field one by one
3. Access the wheelform field or any value of it (e.g. `form.id`) 4. 

A similar error (but in the backend) [was already reported once](https://github.com/spicywebau/craft-neo/issues/332) some time ago. Maybe there's a similar problem. 

#### Other information
- Neo version: 3.0.2
- Craft version: 4.0.1
- (if multi-site) What is the affected Neo field's propagation method: No multisite
- Is eager-loading used? No

**Comment by ttempleton** [comment]
I'm unable to reproduce this with Neo - have you tried this in a Matrix field? If that works, could you please provide a template example of form access that's causing the error?

**Comment by ttempleton** [comment]
No worries - glad it's resolved!
