### ISSUE TITLE
Cannot assign craft\fields\Matrix to property benf\neo\models\BlockType::$_field of type ?benf\neo\Field

### ISSUE THREAD

**Issue by sietsedeglee** [spicywebau/craft-neo#575]
#### Description
When trying to either: 
1. Execute a project-config/rebuild 
2. Execute a GraphQL request
Craft fails with the following exception:
```
TypeError
Cannot assign craft\fields\Matrix to property benf\neo\models\BlockType::$_field of type ?benf\neo\Field
```

Indication of the error message:
<img width="1285" alt="Screenshot 2022-05-10 at 01 38 39" src="https://user-images.githubusercontent.com/2853159/167515390-ddf12fdc-cc1a-4860-990b-fb16bb49cd6a.png">

No matter which query is submitted the following GraphQL error occurs:
<img width="475" alt="Screenshot 2022-05-10 at 01 39 29" src="https://user-images.githubusercontent.com/2853159/167515448-c57cedba-92c3-4f14-a485-dedecf2205e0.png">

#### Steps to reproduce
1. Rebuild the project config either using the Admin CP or Console
2. Open the GraphQL IDE and execute any query.

I tried resaving/rebuilding all content types, but unfortunately that did not resolve the issue. Craft and all plugins are up-to-date.

#### Other information
- Neo version: 3.0.2
- Craft version: Craft Pro 4.0.1
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? n/a

**Comment by ttempleton** [comment]
I'm unable to reproduce this, but it sounds like a Neo block type has somehow ended up with a `fieldId` that matches a Matrix field. Can you please check either the `fieldId` column of the `neoblocktypes` database table, or the `field` properties of the block types in the `neoBlockTypes` in the project config, to see which of these (if any) are associated with a Matrix field?

**Comment by mihob** [comment]
I encounter the same problem, while trying to create a new neo field

**Comment by sietsedeglee** [comment]
@ttempleton I can confirm that there was indeed a Matrix field referenced in the `neoblocktypes` db table. Switching it back to Neo fixed the problem, also manually removing the problematic row from the `neoblocktypes` table. I remember that in the past I converted this field from Neo to Matrix using the 'Convert from Neo' button that shows up once you switch.

Could it be possible that there is a small issue with the conversion not cleaning up all data from the `neoblocktypes` table?

**Comment by ttempleton** [comment]
You were right about the conversion not cleaning up the old Neo block type data, @sietsedeglee, thanks for pointing that out. I've just made some fixes for the next release, which will clean up any old block types and block type groups still left in the Neo tables after their fields were converted to Matrix, and conversions of Neo fields to Matrix will now delete the Neo block types / groups.
