### ISSUE TITLE
`.inReverse().one()` on a Neo query removes block from future queries

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#576]
#### Description
Ran into a strange issue where querying the last item of a set of Neo blocks prior to querying all the blocks will remove the block from the second query. I'm not able to reproduce this behavior with a standard entry selector field I tested on.

#### Steps to reproduce
1. Create a Neo field with at least 1 block type
2. Populate an entry with multiple Neo blocks
3. Set a reference in the template to the last block prior to the same for all blocks:
```
{% set lastBlock = entry.neoBlocks.level(1).inReverse().one() %}
{% set allBlocks = entry.neoBlocks.level(1).all() %}
```
4. `allBlocks` is now missing the last Neo block.

#### Other information
- Neo version: 2.13.8
- Craft version: 3.7.41
- Is eager-loading used? No

**Comment by ttempleton** [comment]
I wasn't able to reproduce this, `allBlocks` still had all the blocks for the field - albeit they were still in reverse order, due to how element queries as field values works in Craft 3. I'm guessing what you're seeing is somehow related to that. Does it also happen with Matrix fields?

**Comment by turnstylerj** [comment]
Ah, you're totally right–it was the reversing of the order that made it look as if the block was missing in my case. Appreciate your taking a look!
