### ISSUE TITLE
craft\services\Elements::getElementById(): Argument #1 ($elementId) must be of type int, null given

### ISSUE THREAD

**Issue by claus0618** [spicywebau/craft-neo#577]
#### Description
I'm migrating a website that was formerly built using an old version of CodeIgniter. We started the migration on Craft 3 and are now looking to upgrade it to Craft 4.

The code was running fine on Craft 3, but now on Craft 4 it gives me this error when the entry is new. If the entry exists, it runs fine.

**craft\services\Elements::getElementById(): Argument #1 ($elementId) must be of type int, null given, called in /app/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php on line 484**

I have a plugin to migrate data from json files, inside that plugin I have:

```
$entry = new Entry();
$entry->title = 'testing';
$entry->sectionId = 1;
$entry->typeId = $entryType[0]->id;
$entry->authorId = 1;
$entry->enabled = true;

$existingMatrixQuery = $entry->getFieldValue('neoFieldHandle');
$existingMatrixArr = $field->serializeValue($existingMatrixQuery, $entry);
$count = 0;

foreach($jsonRow as $row){
   $existingMatrixArr['new'.$count] =  
    [
        'type' => $blockTypeHandle, //blockTypeHandle
        'fields' => [
            'predefinedProvisions' => [$predefinedTerm->id] ?? '',
            'statusSelect' => $row['status'] ?? '',
        ],
        'collapsed' => true
    ];

    $count++;
}

$entry->setFieldValue($neoFieldName, $existingMatrixArr);
Craft::$app->elements->saveElement($entry);
```

I suspect it's because the block ownerId is getting to the neo methods null, but until that point that id doesn't exist yet.

#### Other information
- Neo version: 3.0.3
- Craft version: 4.0.2

**Comment by ttempleton** [comment]
Thanks for reporting, that should now be fixed in Neo 3.0.4.
