### ISSUE TITLE
Collapsed global neo field fails to save collapsed state

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-neo#581]
I'm using a Neo field to generate a global nav for my website. The field is assigned as global field within Craft. The nav is fairly long so to keep things organized I collapse the blocks within the UI but once I hit "Collapse" it throws the js error: Uncaught TypeError: Cannot read properties of undefined (reading 'duplicatedElements')" in main.js. On save and refresh, all of my collapsed elements have been expanded. I have other neo fields assigned to entries and they behave as expected. 

#### Steps to reproduce
1. Add a neo field to a global set within settings
2. Navigate to that field within globals and attempt to collapse it 

#### Other information
- Neo version: 2.13.9
- Craft version: Craft Pro 3.7.42
- (if multi-site) What is the affected Neo field's propagation method: N/A
- Is eager-loading used? N/A

**Comment by ttempleton** [comment]
Thanks for reporting, this should now be fixed in Neo 2.13.10. This issue also affects Neo on Craft 4, so the fix will be included in the next Neo 3 release as well.
