### ISSUE TITLE
PHP How to update an existing neo block field value on an existing entry

### ISSUE THREAD

**Issue by joepagan** [spicywebau/craft-neo#585]
#### Description

Hey, I've looked through the repo's issues for some examples though I'm not 100% on what is required to achieve this at the moment. Forgive me if I've missed something obvious.

Typically to update values we use `$entry->setFieldValues`, though in the case of updating a field on a neo block I presume we would need to provide the entire neo field again (all blocks included) with our edited value?

[this](https://github.com/spicywebau/craft-neo/issues/486#issue-953015729) seems to be the only example I can find of doing this, though it seems rather dramatic to have to create such a nested multi-dimensional array just to update one value, and would be a little overwhelming to do that with so many potential blocks and vluaes.

In my scenario I wish to update a checkbox field so here is what I have tried:

```php
  $neoBlocks = $entry->neo->all();
  foreach ($neoBlocks as $block) {
    $blockType = $block->getType();
      if ($blockType->handle === 'searchBar') {
        $searchBarOptions = $block->searchBarOptions;
        if ($searchBarOptions) {
          $newOptions = [];
          $newOptions[] = new OptionData('Label', 'value', true, true);  
          $searchBarOptions->setOptions($newOptions);

          try {
            $entry->setFieldValue('neo', $neoBlocks);
            $success = Craft::$app->elements->saveElement($entry);
```

This does pass, and the entry is saved, though the saved values do not appear when viewing the entry unfortunately.

Any help here would be appreciated, thanks in advance.

#### Other information
- Neo version: "spicyweb/craft-neo": "2.9.12",
- Craft version: "craftcms/cms": "3.6.8",
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? no

**Comment by ttempleton** [comment]
If you just want to change subfield values, and you don't want to add/remove blocks or make any other type of block structure changes, then you can set the subfield value on the block and then save the block itself:

```php
$newOptions[] = new OptionData('Label', 'value', true, true);
$block->setFieldValue('searchBarOptions', $newOptions);
$success = Craft::$app->elements->saveElement($block);
```

It shouldn't be necessary to set the entry's field value for the Neo field, or to save the entry separately unless you're making other changes to it.

**Comment by joepagan** [comment]
Perfect, thanks so much!
