### ISSUE TITLE
[FR] Block visibility condition

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#587]
#### Description

When using Neo for a content-builder matrix style field for sites, we almost always run into a few situations where a page has a one-off block that isn't being used anywhere else on the site. We can just make these fields directly on the entry field layout, but if the design calls for them to be in-between other Neo blocks, there aren't really any good options outside of creating a block in the shared set that's only used in one location.

One potential way to solve this would be to allow a custom "visibility condition" for blocks, where I could specify something like:

```
{ entry.type.handle == 'customEntryType' }
```

Where the block it applied to would only display to the author if the entry type is set to a custom one intended for that block to be used. Would this be possible?

**Comment by ttempleton** [comment]
There's the `FilterBlockTypesEvent` added in Neo 2.13 (usage notes for [Neo 2](https://github.com/spicywebau/craft-neo/blob/2.13.10/docs/events.md#filterblocktypesevent) / [Neo 3](https://github.com/spicywebau/craft-neo/blob/3.0.5/docs/events.md#filterblocktypesevent)) - unless you mean something like the condition rules in Craft 4?

**Comment by turnstylerj** [comment]
Nice, thank you! This works (and is my first time using a module). This is perfect for situations where different sections use 90% of the same blocks but have a few that should only be scoped to certain ones.

I think it would be a great feature to expose this in the UI when creating Neo blocks, similar to how selecting "Custom" for a field's translation method allows an expression for matching entries. Something like:

![Screen Shot 2022-05-27 at 9 35 58 AM](https://user-images.githubusercontent.com/42223501/170741645-86e6bc9b-7622-4e52-9c81-f68243171f60.png)

Maybe tucked under an "Advanced" toggle you see when creating other fields. What do you think?

**Comment by ttempleton** [comment]
Yeah, it would be good to be able to set filtering rules in the block type settings. I'll have a look at it for either the 3.1 or 3.2 release.

**Comment by ttempleton** [comment]
I've added block type conditions in Neo 3.2.0, in the form of Craft 4's condition fields. Neo by default will add individual condition fields for using block types when editing entries, categories, assets, users, tags and addresses, as well as (if Craft Commerce is installed) products, variants, orders and subscriptions. There's also [an event](https://github.com/spicywebau/craft-neo/blob/3.2.0/docs/events.md#setconditionelementtypesevent) that other plugins can use to register other element types to get their own condition fields.
