### ISSUE TITLE
Craft CMS 4 and Conditions on Neo Blocks

### ISSUE THREAD

**Issue by sinnathurai** [spicywebau/craft-neo#589]
#### Description
We use the plugin extensively and with lots of Neo blocks. With Craft CMS 4, the Condition Fields has been released. This works very well with the Neo plugin. But still it would be desirable if you could set the conditions to a neo block.

Is there already a way to do it or is it intended to be used in this way?

#### Other information
- Neo version: 3.0.5
- Craft version: Craft CMS 4.0.3

**Comment by ttempleton** [comment]
There isn't currently a way to do this through the block type settings, but some form of solution is planned (#587).

In the meantime, the [`FilterBlockTypesEvent`](https://github.com/spicywebau/craft-neo/blob/3.0.5/docs/events.md#filterblocktypesevent) can be used to set conditions on block types being allowed to be used.
