### ISSUE TITLE
Group titles showing on top level when no grouped items are available

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#592]
#### Description
I'm assuming this is related to [461](https://github.com/spicywebau/craft-neo/issues/461)–I noticed on Craft 4 that when I have a group of blocks with nested elements that aren't available on the top level, the group title still shows up in the expanded view. The group title is correctly hidden in the dropdown view that's triggered when there's not enough room to display all the blocks.

In this screenshot, the "Call to Action" group title contains only blocks that are available on the 2nd level inside the top-level block.
![Screen Shot 2022-06-01 at 12 49 42 PM](https://user-images.githubusercontent.com/42223501/171489794-87d0baf6-da57-42a8-bd23-10a04bd93df7.png)

#### Steps to reproduce
1. Create a Neo block with a child block not available on the top level
2. Assign the child block to a group with a title

#### Other information
- Neo version: 3.0.5
- Craft version: 4.0.3
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to all sites
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting that - should be fixed now in Neo 3.0.6.
