### ISSUE TITLE
504 Timeouts on Neo Field Edit Screen

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#593]
I'm running Craft 4.0.3 with Neo 3.0.6. I'm running into an issue on my local environment where I'm getting 504 timeouts when I try to go to the Neo field edit screen.

#### Steps to reproduce
1. go to the CP to the Settings > Fields screen.
2. Click on the Page Builder field to edit

#### Other information
- Neo version: 3.0.6
- Craft version: 4.0.3
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used? not yet, currently working on templates

I can send you a dropbox link to my project config and composer files.

**Comment by ttempleton** [comment]
This will be mostly fixed in Craft 4.0.4, and then some changes in Neo 3.1 will resolve the last bit of it (see https://github.com/spicywebau/craft-neo/issues/580).
