### ISSUE TITLE
Bogus Block Queries (Craft 2 -> 3 Upgrade)

### ISSUE THREAD

**Issue by smockensturm** [spicywebau/craft-neo#595]
When I dump two block queries (one working, one not), I see the following.

GOOD
`object(benf\neo\elements\db\BlockQuery)#2953 (89) { ["fieldId"]=> string(2) "91" ["ownerId"]=> int(45) ["ownerSiteId"]=> NULL ["typeId"]=> NULL ...`

BAD
`object(benf\neo\elements\db\BlockQuery)#2799 (89) { ["fieldId"]=> array(1) { [0]=> string(2) "91" } ["ownerId"]=> array(1) { [0]=> int(4123) } ["ownerSiteId"]=> NULL ["typeId"]=> array(1) { [0]=> string(2) "27" } ...`

Whay are all those IDs arrays and not strings?

What might cause this to happen and how can I fix it?

Thanks.

**Comment by smockensturm** [comment]
Also: the bogus (not working) query is massive. The good one seems much more reasonable. Both are trying to parse the same field.

**Comment by smockensturm** [comment]
Just tried to make a brand new page with a brand new Neo content block field (same as above) with a simple text block.

So the upshot of all of this... Neo is not working with Craft 3 in our current situation.

Craft: 3.7.44
Neo: 2.13.11
PHP: 7.4
mariaDB: 10.5:

**Comment by ttempleton** [comment]
Difficult to say what's going wrong to make the second block query not work without an example of code you're running or an action in Craft where it reliably happens, but it's normal for Neo (and Matrix, for that matter) to run block queries where ID parameters are set (or re-set, if the parameter had already been set to a numeric value) to an array of one ID.

Regarding the case where the Neo field isn't rendering - just want to confirm that when you say "No errors get thrown" that includes any JavaScript errors in the browser console?
