### ISSUE TITLE
FR: Ability to disable item grouping

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#598]
#### Description

In some cases it would be great to be able to completely disable grouping of child blocks. This would be set at the parent block settings level.

Example: Image gallery that only has two possible child options:

![image](https://user-images.githubusercontent.com/25124/172763273-bae02864-d98a-4875-879f-3055c39749fc.png)

In this case it would be great to just show the two buttons side by side.

**Comment by ttempleton** [comment]
Just released Neo 3.5.0 with this block type setting.
