### ISSUE TITLE
How to determine if field is on a block

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#599]
I'm trying to determine if a field is added to a block type. I tried using is defined and it returns true. I looked at [issue 51](https://github.com/spicywebau/craft-neo/issues/51) and tried using is not empty instead, but that errors out.

Here's my code:
`
{% if section.applyRevealToChildElements is not empty %}
do stuff...
{% endif %}
`
The error I get is:
Calling unknown method: benf\neo\elements\Block::applyRevealToChildElements()

Which I'm guessing is happening because the field is not added to the block type, but that's exactly what I'm trying to determine. 

Can you tell me what the best way is to do this?

Thanks!

**Comment by ttempleton** [comment]
Checking `is not empty` should definitely still work as long as the field handle being checked is any existing field's handle; I only get the unknown method error if I check a field handle that doesn't exist. Can you please double check the field handle is valid?

**Comment by brianrivet-tilt** [comment]
The handle was the problem. Thanks!
