### ISSUE TITLE
Changed block positions don't get saved

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#60]
When I rearrange Neo blocks within an entry and save the entry, the new positions don't get saved (in every case). Not all blocks seem to be affected. It's hard to pinpoint when it's working and when not. Looks like newer added blocks store their positions when rearranged but blocks from older edits don't.

Could you think of something what could cause this issue? I can try to find more clues, let me know how I can help pinpoint it.

I noticed this this a while back for the first time, but couldn't pinpoint what was happening exactly. Saving the whole entry as a new one solved the issue back then. Now I see the same behaviour in a new project.

Cheers

**Comment by doubouil** [comment]
Yup, can confirm it more or less appeared randomly. In my case my matrix field within the Neo value can be dragged and dropped, but position is the same after saving the entry (while editing)

**Comment by benjamminf** [comment]
@superflausch Very interesting... I have not run into this issue before. The only thing I can think of is that the order of the input fields are not being posted to the server in the correct order, in which case would be a PHP or server-related issue. But I don't think this would be the case as you'd probably see the same issue with traditional Matrix fields – actually, are you?

Chances are there's an issue when saving the new structure for the Neo field, in that it's not using the newly created structure but keeping the old one. Are you perhaps using locales on your site?

@doubouil I think you're actually seeing an entirely different bug, for which I can actually replicate! Neo blocks monitor changes to their fields so they only save when they need to, but the modification detection is not capturing reorderings on Matrix (and SuperTable) fields.

**Comment by jpoiri** [comment]
Seeing the same issue, using a matrix field in a neo block, doesn't keep the order unless you change the block content. Any workaround?

**Comment by superflausch** [comment]
@benjamminf I will try to document the next occurrence a little better. We just had a single locale active at that moment, but there were two active ones before and we plan to add additional locales on that project in the close future.

We also noticed the issue with the order of nested matrix fields @doubouil mentioned.

**Comment by benjamminf** [comment]
@jpoiri @superflausch The issue with Matrix orders is an unrelated issue (#69) which I've now fixed. I'm still looking into the other issue though.

**Comment by ttempleton** [comment]
Neo 2.7 introduced the `sortOrder` block property, which should ensure block orders are always saved correctly.
