### ISSUE TITLE
UI Problem - No Expand Option in Gear Dropdown on Collapsed Blocks that are Collapsed when Entry is Saved, 

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#602]
I am not getting an expand option in the gear menu on collapsed Neo blocks that are collapsed when the entry is saved. Only Collapse. If I add a new block and collapse it without saving the entry, the expand option is still available.

#### Steps to reproduce
1. Go into a Neo Field
2. Collapse a Block and Save the changes to the entry
3. Go Back to Entry and try to Expand Neo Block, no expand option in menu, only collapse

#### Other information
- Neo version: 4.0.4
- Craft version: 3.1.0
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used?Yes

**Comment by ttempleton** [comment]
Thanks for reporting - just added a fix for the next release.

**Comment by ttempleton** [comment]
Just released Neo 3.1.1 which includes the fix for this issue.
