### ISSUE TITLE
Block-selector UI bug

### ISSUE THREAD

**Issue by mariuswestgaard** [spicywebau/craft-neo#604]
#### Description
Hi!
We're having issues with the Neo Field UI in Craft 4, where the field block-"selector" is pushed outside content-area, and overlapping the settings-area. Then, after refreshing the page, it's displaying as dropdown, not buttons.

See image below, where the block-selector is outside content-area, and overlapping the settings-area.

![Screenshot 2022-06-17 at 15 34 34](https://user-images.githubusercontent.com/27733229/174308843-a694d85d-8ed0-4522-9e0d-71e5ec85ed7a.png)

After reloading dashboard, the selector is displayed as a dropdown, as it should, when selector is too wide.

![Screenshot 2022-06-17 at 15 36 19](https://user-images.githubusercontent.com/27733229/174309388-848934fa-4c9e-4ab0-a046-712e1f8b2f21.png)

#### Steps to reproduce
1. Create an NEO field
2. Create many blocks in Neo (enough to be wider than the content-area on your screen), and add the field to an entry.
3. In the dashboard, click to create a new entry.
4. When in the article in cms, refresh to get the dropdown.

#### Other information
- Neo version: 3.1.0
- Craft version: 4.0.4

**Comment by ttempleton** [comment]
Thanks for reporting that - just fixed it for the next release.

**Comment by ttempleton** [comment]
Just released Neo 3.1.1 which includes the fix for this issue.
