### ISSUE TITLE
3.1.1 Neo block on save splits off child block from parent and adds them as top level block

### ISSUE THREAD

**Issue by CompleteBaltics** [spicywebau/craft-neo#605]
#### Description
First of great plugin, thanks you very much for creating and maintaining it, it is truly appreciated.

We have noticed that after 3.1+ we started to see some weird behavior with our Neo blocks. We have quite a complicated setup where an entry can have multiple neo fields, with multiple top level blocks that can have child blocks. Sometimes when saving these entries, one of those top level blocks looses it's child blocks and they are added as top level blocks next to the parent block. It happens between separate Neo fields and inside of a single Neo field on an entry when we save it. The child blocks as top level blocks are added to the Neo field the parent is in. We can rearrange the child blocks and nest  them again in the parent block they were originally in, but saving this change usually misplaces some other blocks children.

Have checked the logs for any errors that might have occurred, but they seem clean. If you need i can provide more detail of our setup.

#### Steps to reproduce
1. Create multiple neo fields with top level blocks that can have child block
2. Assign the fields to a single entry type (we have ours on separate tabs)
3. Create top level blocks in these fields and add some child blocks
4. Save the entry, usually at this point we see some child blocks placed as top level blocks. If not we can try and create another top level block with child block and save again. Then one of the top level blocks in any of the Neo fields will loose it nested blocks.

#### Other information
- Neo version: 3.1+
- Craft version: 4.0.4
- (if multi-site) What is the affected Neo field's propagation method: not a multi site
- Is eager-loading used? no eager-loading, using Craft in headless setup.

**Comment by ttempleton** [comment]
I wasn't able to reproduce this, but I just wanted to clarify that by 3.1+ you mean that you can reproduce it on 3.1.0 as well as 3.1.1? There was a change in 3.1.1 related to saving block structures for provisional drafts that maybe could've had a negative effect that I didn't catch, but there shouldn't have been any changes in 3.1.0 to affect entry saving at all.

If it happens on 3.1.0 as well as 3.1.1, could you please send a database backup and your composer.json/lock files to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by CompleteBaltics** [comment]
Sorry for the premature close... Miskicked...

**Comment by ttempleton** [comment]
Thanks for confirming that it's happening with 3.1.1. I've been trying a few different things and still unable to reproduce, so if possible, could you please send us the database backup and composer.json/lock files? Happy to look at the current database where it's happening, or at a minimal reproduction if you'd prefer that.

**Comment by Mathias-Syversen** [comment]
Can confirm a save on 3.1.1 flattens my neo fields.

**Comment by ttempleton** [comment]
@Mathias-Syversen If you can reliably reproduce that, could you please send in your database backup and composer.json/lock files to plugins@spicyweb.com.au, along with details of the entry where it happens.

**Comment by ttempleton** [comment]
I still haven't been able to reproduce this issue, but it did turn out that there was a bug where block structures weren't being resaved when provisional drafts were resaved and the Neo blocks had changed, so I've added a fix for that in Neo 3.1.2.

I'd be interested to know if that's resolved this issue; if it hasn't, it'd definitely be appreciated if someone with the issue could please send their database backup and composer.json/lock files to us, if possible, so we can have a look.

**Comment by CompleteBaltics** [comment]
@ttempleton I am terribly sorry for the late reply, had a lot on my plate recently. But i have tested the 3.1.2 update and the issue seems to be gone. I tried replicating the same steps on the setup we were having the issue on and now it works as designed. As hard as i tried to break the plugin, it stood solid. Thanks a lot for the super quick fix. Cheers!

**Comment by ttempleton** [comment]
Awesome, glad to hear it's fixed!
