### ISSUE TITLE
Clone Block Feature Hanging Up

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#606]
I'm having an issue where if I try to clone a block the clone appears, but then there is a spinner beneath it that stays there and a few errors are listed in the javascript console in my browser (Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)).
If I refresh the screen, the clone is no longer present. 

#### Steps to reproduce
1. Load DB and project config from this link: https://www.dropbox.com/sh/u4zqp8wsswo8y3d/AAChaFDiByVOg-x-XW7im7Qja?dl=0
2. Open Home Page entry and go to Neo field to where the Slide block is
3. Try cloning it.

#### Other information
- Neo version: 3.1.1
- Craft version: 4.0.4
- (if multi-site) What is the affected Neo field's propagation method: not multi site
- Is eager-loading used? yes, but this is happening in the CP

![js_errors](https://user-images.githubusercontent.com/72757910/174883142-818a1462-bbff-41f6-b52c-5b4fd7059343.jpg)

**Comment by ttempleton** [comment]
Thanks for reporting that. It turned out to affect cloning blocks that use the child blocks UI element, and I've added a fix for the next release.

**Comment by ttempleton** [comment]
Just released Neo 3.1.2 including the fix for this issue.

**Comment by brianrivet-tilt** [comment]
I’m not sure the update resolves the problem. Now it will only allow me to clone a block if it is empty. Once I add children to it cloning is no longer available as an option.

**Comment by ttempleton** [comment]
I'm unable to reproduce that, but it would likely be unrelated to the error that caused this issue, so if it's happening with Neo 3.4.0, please feel free to open a new issue for it.

**Comment by brianrivet-tilt** [comment]
Honestly I'm not sure any more either :). We kind of revamped our setup so the files etc. that I sent you are pretty out of date now. I haven't seen any of these issues lately, so if you want to close this issue I'm ok with that.
