### ISSUE TITLE
Eager loaded block children return non-0 indexed array

### ISSUE THREAD

**Issue by low** [spicywebau/craft-neo#607]
#### Description

When using eager loading for a complex neo field, any block children returned by `$block->getChildren()->all()` can return a non-0 indexed array, throwing off some custom API module's output.

Looks like `BlockQuery::_getFilteredResult()` needs an `array_values()` when returning the result; this commit might have caused it: https://github.com/spicywebau/craft-neo/commit/11a73418b7c4cc9771b2e59d599e2ef4093f265e

#### Steps to reproduce
1. Create a neo field with multiple blocks with multiple children
2. Without eager loading, loop through parents and get children using `$block->getChildren()->all()`
3. Repeat the same, but with eager loading
4. Check differences in array indices.

#### Other information
- Neo version: 2.13.11
- Craft version: 3.7.44
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? Yep!

**Comment by ttempleton** [comment]
Thanks for reporting - that'll be fixed in the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `2.x-dev as 2.13.11` and running `composer update`.

**Comment by ttempleton** [comment]
Just released 2.13.12 with the fix for this issue.
