### ISSUE TITLE
Neo blocks are duplicated on front end if viewing a page with unsaved changes

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#610]
#### Description
I'm seeing a weird behavior where if I make a change to an entry and don't save it, if I view that page on the front end or in the live preview mode all of the neo blocks are displayed over and over again on the page. They are fine in the control panel, and if I save the entry, the front and and preview go back to normal.

#### Steps to reproduce
1. Load the site with the config and database here: https://www.dropbox.com/sh/u4zqp8wsswo8y3d/AAChaFDiByVOg-x-XW7im7Qja?dl=0
2. go to the home page entry and make any change you like, but don't save.
3. View the page in the browser or in the live preview

#### Other information
- Neo version: 3.1.3+ (I'm currently running 3.1.4 and still seeing it, but was running 3.3.3 and seeing it as well)
- Craft version: 4.0.5.2
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used? yes

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in Neo 3.1.5.
