### ISSUE TITLE
Neo Blocks copy once propagation method

### ISSUE THREAD

**Issue by bsye** [spicywebau/craft-neo#613]
#### Description
I'm using Neo to create a multilingual editorial site and I noticed that there isn't a way to propagate blocks only once when the content is created.

If i set "Save blocks to all sites the owner element is saved in" I can't edit the blocks in other languages, I can only manage the translations for the fields that i set as "translatable".

And if i set "Only save blocks to the site they were created in" I have to repeat all the data entry in the other languages.

I was wondering if there's a way to copy the content of an entry only once, when the entry is published for the first time. I don't know if it is already possible, but it would be really helpful.

#### Other information
- Neo version: 3.1.5
- Craft version: Craft Pro 4.0.2

**Comment by ttempleton** [comment]
Neo blocks are supposed to be duplicated for the other sites when creating a new entry, and it was a bug that it wasn't happening, so I've just fixed that for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.1.5` and running `composer update`.

**Comment by bsye** [comment]
> Neo blocks are supposed to be duplicated for the other sites when creating a new entry, and it was a bug that it wasn't happening, so I've just fixed that for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.1.5` and running `composer update`.

Perfect! Thank you very much! I've tested and it seems correct now

**Comment by ttempleton** [comment]
Just released Neo 3.1.6 including this fix.
