### ISSUE TITLE
Field layouts lost when setting up Neo field

### ISSUE THREAD

**Issue by tigerchick** [spicywebau/craft-neo#614]
When saving a Neo field upon setting it up for the first time, if the required fields "Name" or "Handle" have been left blank, Craft disallows the save and highlights the missing fields in red. All good except that it also looses all field layout information that had been setup for each block type. 
A small but highly annoying issue!

Other information
Neo version: 3.1.5
Craft version: Craft SOLO 4.1.0.2
Multi-site: No
Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this - I'm assuming this is an unintended side effect of lazy loading block type field layout designers from Neo 3.1.0 onwards. I'll have a look into how we can fix that.

**Comment by ttempleton** [comment]
That should be fixed now in Neo 3.1.8.
