### ISSUE TITLE
Neo block fields not saving in slideouts 

### ISSUE THREAD

**Issue by sjeng** [spicywebau/craft-neo#617]
#### Description
Neo blocks are not saving when editing an element in the slideout view. They do save correctly when editing in the dedicated entry edit page.

After debugging, it appears that the cause is the data structure for Neo block fields in the `save-draft` requests is incorrect, _but only when in the slideout context_.

Here's the correct structure:

```
array(1) {
  ["neoBlockField"]=>
  array(2) {
    ["blocks"]=>
    array(1) {
      ["new0"]=>
      array(4) {
        ["type"]=>
        string(4) "text"
        ["enabled"]=>
        string(1) "1"
        ["level"]=>
        string(2) "01"
        ["fields"]=>
        array(1) {
          ["richText"]=>
          string(11) "<p>test</p>"
        }
      }
    }
    ["sortOrder"]=>
    array(1) {
      [0]=>
      string(4) "new0"
    }
  }
}
```
And here is what's being sent by when in slideout:

```
array(2) {
  ["sortOrder"]=>
  array(1) {
    [0]=>
    string(4) "new0"
  }
  ["neoBlockField"]=>
  array(1) {
    ["blocks"]=>
    array(1) {
      ["new0"]=>
      array(4) {
        ["type"]=>
        string(4) "text"
        ["enabled"]=>
        string(1) "1"
        ["level"]=>
        string(2) "01"
        ["fields"]=>
        array(1) {
          ["richText"]=>
          string(11) "<p>test</p>"
        }
      }
    }
  }
}
```

#### Steps to reproduce
1. Create 2 new entry types, A and B. 
2. Create a neo block field. Add to entry A field definition.
3. Create an entry field for entry A. Add to entry B field definition.
4. Create a new Entry A element, but just fill in the title and nothing else.
5. Create a new Entry B element. Select the new Entry A element in the entry field.
6. Now double click on the Entry A element. Slideout edit screen should appear.
7. Add a new instance to neo block field, and save Entry A element. No error message should occur, but if you edit the element again, you should see that change has been lost, and was never saved.

#### Other information
- Neo version: 3.1.6
- Craft version: 4.1.2

**Comment by ttempleton** [comment]
Thanks for reporting this - confirming that I can reproduce the issue. Will have a look into what's causing it today.
