### ISSUE TITLE
Clone/Copy/Paste Not Working Consistently

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#620]
I'm seeing an issue where the clone and copy/paste features on some blocks aren't working consistently. If you look at the home page entry in the setup located in the dropbox link below, there are a couple of blocks of type "Slide". I created the first one from scratch and the second by cloning. However,  I can't create any additional clones. I've also encountered situations where I can't copy/paste a block into a spot where I should be able to.

#### Steps to reproduce
1. Load the site at this dropbox link: https://www.dropbox.com/sh/u4zqp8wsswo8y3d/AAChaFDiByVOg-x-XW7im7Qja?dl=0
2. Got to edit the home page.
3. Try to clone the slide block, or create other blocks where you should be able to clone. They won't work consistently.

#### Other information
- Neo version: 3.1.7 (though it may affect earlier version s as well)
- Craft version: 4.1.4
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? yes

**Comment by ttempleton** [comment]
Thanks for reporting that - should be fixed now in Neo 3.1.8.
