### ISSUE TITLE
Error while upgrading from 3.1.8 to 3.2.0

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#625]
#### Description

There seems to be an error in a migration of the update:

```
*** applying m220723_153601_add_conditions_column_to_block_types
    > add column conditions text NOT NULL DEFAULT '[]' AFTER `sortOrder` to table {{%neoblocktypes}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'conditions' can't have a default value
```

#### Steps to reproduce
1. Upgrade Neo 3.1.8 to 3.2.0

#### Other information
- Neo version: 3.1.8
- Craft version: Craft Pro 4.1.4.1
- MySQL 8.0.29

**Comment by ttempleton** [comment]
Thanks MySQL 🙃

Thanks for reporting that @mihob - should be fixed now in Neo 3.2.1.
