### ISSUE TITLE
Large amount of queue jobs

### ISSUE THREAD

**Issue by mikeatmostlys** [spicywebau/craft-neo#626]
#### Description

I am seeing a large amount or queue jobs after saving an entry. Some were expected, but I didn't expect this many.

Most of the jobs are for:
- Updating search indexes
- Pruning extra revisions

This entry is part of a Craft multi-site install with 5 sites in total. The entry has 3 neo fields in its field layout.

Any insight would be appreciated if this is an anomaly. Thanks!

#### Other information
- Neo version: 3.2.1
- Craft version: 4.1.4.1
- (if multi-site) What is the affected Neo field's propagation method: "Only save entries to the sites they were created in."
- Is eager-loading used? Back-end related

<img width="1850" alt="Screen Shot 2022-07-25 at 11 55 47 AM" src="https://user-images.githubusercontent.com/92817780/180834896-8787543b-4e87-4c83-87c6-4821fadf81b8.png">
<img width="1325" alt="Screen Shot 2022-07-25 at 11 57 59 AM" src="https://user-images.githubusercontent.com/92817780/180834905-af6227b6-7b06-4e7c-8749-9cf7dfcf3105.png">
<img width="1322" alt="Screen Shot 2022-07-25 at 11 58 22 AM" src="https://user-images.githubusercontent.com/92817780/180834906-a8c8adb5-ac29-4de6-9acb-d0086ec11e78.png">

**Comment by ttempleton** [comment]
The number of "updating search index" jobs would likely be expected - Neo does have some optimisations in place by default to not update search indexes for Neo blocks if they don't have any searchable content, but as long as the Neo field a block belongs to is set to be searchable, the block's type has a field layout and any fields on the field layout are searchable, then search indexes will be updated for that block when it's saved.

I think the number of "pruning extra revisions" jobs is probably expected, as I assume they're deleting old Neo blocks that belonged to the old entry revisions that need to be deleted. But I'll test that and compare it with Matrix, and update here with what I find.

**Comment by ttempleton** [comment]
Sorry for the delay in updating this issue! I've tested this with Matrix and Neo with a low `maxRevisions` setting, and confirmed that I'm getting a decent number of "pruning extra revisions" jobs related to both Matrix and Neo blocks. This looks like it's happening with both Matrix and Neo due to the the fact that Matrix/Neo blocks created for entry revisions in Craft 4 are recognised as being block revisions themselves, so excess block revisions will eventually be pruned much like entry revisions.

**Comment by mikeatmostlys** [comment]
Thank you for checking on this!
