### ISSUE TITLE
Issues with Cloning Blocks in CP

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#628]
#### Description
I'm seeing buggy behavior when trying to clone blocks in the CP. I have a block that I tried to clone that is not showing any buttons to add child elements etc. when it should be showing them and it also isn't cloning any of the child elements of the original either. I also had a block that I created a clone from previously that when I tried to disable the clone it kept disabling the original instead of the clone. The files to see this are at this dropbox link: https://www.dropbox.com/sh/5hni5m6fjwva4ns/AADFpN2QIf8DemcKl1usEYkHa?dl=0

#### Steps to reproduce
1. load the site and go to the home page entry. The second to last block a page section with a heading block inside of it. The last block was created as a clone of the one of above it. When I created the clone, it didn't clone the child block inside it. It also doesn't show the buttons to add child blocks until you save the entry.
2. If you add content to the clone block so you can see it on the front end, then try disabling the clone, it disables the original instead and leaves the clone visible on the front end.

#### Other information
- Neo version: 3.2.2
- Craft version: 4.2.0
- (if multi-site) What is the affected Neo field's propagation method: not multi-site
- Is eager-loading used? yes

**Comment by brianrivet-tilt** [comment]
Also, just to clarify, when I try to disable the clone, the CP shows the clone as disabled but it displays the clone on the front end even though it is disabled and in the CP and it doesn't show the original block even though it is enabled.

**Comment by ttempleton** [comment]
Thanks for reporting that - should be fixed now in Neo 3.2.3.
