### ISSUE TITLE
Nested neo blocks are deleted on 2nd save

### ISSUE THREAD

**Issue by rene-haefliger** [spicywebau/craft-neo#629]
#### Describe the bug
When nested elements are edited, all elements inside the neo-block are deleted. E.g. Accoreon block and associated accordion items.

#### To Reproduce

1. Create a Neo Field with a blocktype on first level
2. Create a blocktype not available on first level
3. Allow the sub blocktype in the first level blocktype
4. Add Content on both levels
5. Save
6. Edit sub blocktypes
7. Save

#### Behavior
Sub blocktypes are deleted

#### Expected behavior
Changes should be saved

#### Other information
- Neo Version 3.2.2
- Craft Version 4.2.0.1
- Is eager-loading used? No

**Comment by ttempleton** [comment]
I'm unable to reproduce this - if possible, could you please send your composer.json/lock files and database backup to plugins@spicyweb.com.au and let us know where this is happening, and we'll have a look.

**Comment by ttempleton** [comment]
Thanks for sending that through @rene-haefliger, unfortunately I'm having trouble running it locally for some reason... That said, I have just released Neo 3.2.3 which includes some fixes related to unexpected Neo block behaviour - could you please try the new version and let me know if that resolves the issue?

**Comment by rene-haefliger** [comment]
The error is no longer present. Thanks.
