### ISSUE TITLE
Reverting a revision doesn't bring back the Neo blocks

### ISSUE THREAD

**Issue by WHITE-developer** [spicywebau/craft-neo#632]
#### Description
Reverting a revision doesn't bring back the Neo blocks

#### Steps to reproduce
1. Have an entry with revisions and Neo blocks
2. (Have no blocks in the current revision)
3. Open a revision
4. Click the "Revert content from this revision"
5. New revision created, but no Neo blocks updated/brought back

#### Other information
- Neo version: 3.2.3
- Craft version: 4.2.0.2
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used?: yes (irrelevant for the backend tho)

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.2.3` and running `composer update`.

**Comment by ttempleton** [comment]
Just released Neo 3.2.4 with that fix.
