### ISSUE TITLE
Entry block type conditions are not working

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#634]
#### Description

It looks like entry block conditions are not working. When selecting a specific entry type, the block is never displayed, not even for the selected entry type.

#### Steps to reproduce
1. Choose an entry type as block condition
2. Edit an entry with the chosen type
3. The block with the condition is not visible

#### Other information
- Neo version: 3.2.3
- Craft version: Craft Pro 4.2.0.2

**Comment by ttempleton** [comment]
It looks like this line:

https://github.com/spicywebau/craft-neo/blob/310a07c585494ce5daaf8019471bbf0239af5a2f/src/assets/InputAsset.php#L119

Where `$condition` is the `craft\elements\conditions\entries\EntryCondition` with the entry type rule, and `$owner` is an entry where the entry type's UID matches the one recorded in the `EntryCondition`, is incorrectly returning `false`, which is a Craft bug.

**Comment by mihob** [comment]
Thanks for checking!

**Comment by angelokeirsebilck** [comment]
Is this something they are planning to fix? Can't seem to find a open issue on craft.

**Comment by ttempleton** [comment]
I assume they're not aware of it yet, but I'll work on a new issue to let them know.

**Comment by ttempleton** [comment]
I've just opened the issue: https://github.com/craftcms/cms/issues/11914
