### ISSUE TITLE
[3.3.2] Cannot delete block

### ISSUE THREAD

**Issue by maxstrebel** [spicywebau/craft-neo#641]
#### Description

Sorry to spam here. At the moment some parent blocks seemingly cannot be deleted.

#### Steps to reproduce
1. Create a Neo block with child blocks
2. Add parent and child blocks in entry
3. Save
4. Delete the parent
5. Save

#### Other information
- Neo version: 3.3.2
- Craft version: latest
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

https://user-images.githubusercontent.com/910594/184973974-81f80b9a-a3d1-4c9e-a40c-f603e2c20949.mov

**Comment by ttempleton** [comment]
Thanks for reporting this - just added a fix for the next release.

**Comment by maxstrebel** [comment]
Thank you Thomas
