### ISSUE TITLE
Cloned block does not have enable option on the cog + after saving the page, disabled block gets enabled

### ISSUE THREAD

**Issue by azad6026** [spicywebau/craft-neo#644]
#### Description

I have encountered this issue in a Craft CMs 4 project with Neo plugin 3.3.3.
Simple explanation for issues:

    1. If you clone an enabled block or even copy and paste it in the page, there is no way to enable it again within the cog.
    2. If you save the page, the disabled block(or any other disabled block) get enabled. (This is a temporary way I could enable the block from the item 1, but this is not the correct way).

#### Steps to reproduce

1. Clone a block or copy and paste it within the page
2. The block will be disabled once cloned. Now try the cog for the block and you see no option to enable it.
3. If you save the page, block gets enabled afterwards.

#### Other information
- Neo version: 3.3.3
- Craft version: 4.2.1.1
- (if multi-site) What is the affected Neo field's propagation method: single site
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting those bugs - should be fixed now in Neo 3.3.5.

**Comment by azad6026** [comment]
Thank you so much for fixing it so quickly. It was important for us. I will try it on now. Cheers.
