### ISSUE TITLE
Can not move a node when the target node is same.

### ISSUE THREAD

**Issue by maxstrebel** [spicywebau/craft-neo#647]
#### Description

I have some pages, that have scrambled and broken NEO blocks on them (https://github.com/sebastian-lenz/craft-linkfield/issues/233, https://github.com/spicywebau/craft-neo/issues/637). My client and me now rebuilt some of the pages that have broken blocks on them, as we cannot repair them (blocks keep getting orphaned or appear on other places).

When we try to move the remaining blocks (not the ones lost because they, we think, are orphaned not) or to delete the entry, we see the error: "Can not move a node when the target node is same."

After I saw the error, the contents of the page are completely gone (which is unsettling). But then I can delete it.

#### Steps to reproduce
1. Have orphaned and broken blocks on the page
2. Try to move them or delete the entry
3. See the error

#### Other information
- Neo version: latest
- Craft version: latest
- (if multi-site) What is the affected Neo field's propagation method: save to site group
- Is eager-loading used?

**Comment by ttempleton** [comment]
Is that reliably reproducible if you've taken a database backup beforehand, and restore the backup after the error occurs?

**Comment by ttempleton** [comment]
Going to close this in favour of #677 for now - will update this issue when that one is resolved, and will reopen this issue if they turn out to have unrelated causes.
