### ISSUE TITLE
Gateway timeout when required fields aren't filled on a parent & child Neo setup

### ISSUE THREAD

**Issue by JasonStainton** [spicywebau/craft-neo#648]
#### Description
We're having a pretty big issue at the moment. When trying to save an entry with a Neo field that has children and required fields that are not filled I get a gateway time out but very occasionally the error I've attached below. If I make the fields on the parent and child blocks not required the entry will happily save the neo field with empty fields.

Setup wise the system report requirements are all met so I wouldn't think it's an issue with execution time or memory limits. I have other Neo fields with many blocks (but no children) and these all save and validate fine.

I'm getting this happening consistently for me so it would be nice to know if it's happening to anyone else, if not I'll have to dig into my environment a little more.

Let me know if there's anything else I could try and share to help debug this.

#### Steps to reproduce
1. Create a multi-site (this might not be necessary but it is my current setup).
2. Create a Neo field with a parent and child block. Add a field to each and mark either or both required (I've used a simple string).
3. Assign the field to an entry (any type will do).
4. Add parent block and child, do not fill in required fields, and hit save. I usually get a 504 gateway timeout or the below error where the array key number is changeable.

#### Other information
- Neo version: 3.3.6
- Craft version: 4.2.3
- (if multi-site) What is the affected Neo field's propagation method: Custom key, but tested issue happens on each setting.
- Is eager-loading used? No

#### Stack trace

```
yii\base\ErrorException: Undefined array key 23 in /var/www/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php:161
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/vendor...', 161)
#1 /var/www/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php(161): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/vendor...', 161)
#2 /var/www/vendor/spicyweb/craft-neo/src/Field.php(705): benf\neo\validators\FieldValidator->validateAttribute(Object(craft\elements\Entry), 'timeoutTest')
#3 /var/www/vendor/craftcms/cms/src/base/Element.php(2359): benf\neo\Field->validateBlocks(Object(craft\elements\Entry), NULL)
#4 /var/www/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:timeoutTe...', Array, Object(yii\validators\InlineValidator), Object(benf\neo\elements\db\BlockQuery))
#5 /var/www/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:timeoutTe...')
#6 /var/www/vendor/craftcms/cms/src/base/Element.php(2260): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry))
#7 /var/www/vendor/yiisoft/yii2/base/Model.php(369): craft\base\Element->afterValidate()
#8 /var/www/vendor/craftcms/cms/src/services/Elements.php(2572): yii\base\Model->validate()
#9 /var/www/vendor/craftcms/cms/src/services/Elements.php(795): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, NULL)
#10 /var/www/vendor/craftcms/cms/src/controllers/ElementsController.php(882): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 [internal function]: craft\controllers\ElementsController->actionSave()
#12 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/save', Array)
#16 /var/www/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/save', Array)
#17 /var/www/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/public/index.php(9): yii\base\Application->run()
#20 {main}
```

#### Neo block setup

<img width="600" alt="image" src="https://user-images.githubusercontent.com/27767499/189110721-51dae79f-f76a-43a2-b124-b69240d4e6af.png">

**Comment by ttempleton** [comment]
Thanks for reporting that - just fixed it for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.3.7` and running `composer update`.

**Comment by ttempleton** [comment]
Neo 3.3.8 has just been released including the fix for this.
