### ISSUE TITLE
A way to visually identify blocks or block types

### ISSUE THREAD

**Issue by louderthan10** [spicywebau/craft-neo#65]
Still really loving this field, but one of the issues that I (and any of our CMS users) often experience is that it's really difficult to find/discern between different blocks in the control panel (this is also a problem with Matrix). Especially when an entry is longer or has nested blocks.

Would love a simple way to visually separate between blocks so it's easier to find things and see that you are editing a block within a block. Some potential ideas:

• Allowing blocks to have titles or color identifiers
• Making it compatible with something like [Matrix Colors](https://github.com/lindseydiloreto/craft-matrixcolors)
• Even just adding classes to each block/block type so we can apply custom CSS styles using [Control Panel CSS](https://github.com/lindseydiloreto/craft-cpcss)

Cheers!

**Comment by louderthan10** [comment]
Doh, just saw that the plugin actually _does_ generate classes for each block type, and used the Control Panel CSS plugin to add some visual separation. 

I still think it would be awesome to have something built-in, but this solution definitely works for us for the time being.

**Comment by benjamminf** [comment]
Yeah I added in those class names for this exact reason. I've thought about a block type colouring setting, but I don't have any plans as of yet to implement. I figure the class names are a good enough start for those who really need it.

I'll keep this open for now though.

**Comment by ttempleton** [comment]
Closing this issue now due to Neo support being included in Matrix Colors 3.0.0.
