### ISSUE TITLE
Entry Type Condition not working

### ISSUE THREAD

**Issue by angelokeirsebilck** [spicywebau/craft-neo#650]
#### Description

Block with Entry Type condition not showing.

![image](https://user-images.githubusercontent.com/42614667/189482814-2bfb50a2-4282-4d3c-a127-37962dada20d.png)
![Schermafbeelding 2022-09-10 om 13 40 13](https://user-images.githubusercontent.com/42614667/189481762-fcb15f14-3635-408d-8480-ed3cebebeeed.png)

#### Steps to reproduce
1. Create a block
2. Add Entry Type condition
3. Check entry and test if block appears when entry type is selected

#### Other information
- Neo version: 3.3.7
- Craft version: 4.2.3

**Comment by ttempleton** [comment]
See https://github.com/spicywebau/craft-neo/issues/634#issuecomment-1200957454.
