### ISSUE TITLE
Feature Request: Specify child blocks in "Child Blocks" UI element

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#652]
### Description
One of the situations I occasionally run into and need to reach for a one-off Matrix field since I'm unable to nest Neo blocks as designed is when I have multiple sets of child blocks needed with different behavior.

### Example
<img width="1068" alt="Screen Shot 2022-09-13 at 12 09 51 PM" src="https://user-images.githubusercontent.com/42223501/189989110-f42d1825-f9cc-499d-903a-45fe2c9b1df6.png">

For this block, I need to create the ability for the author to create "rows" representing each image gallery/text pair, where they should be able to add two types of nested blocks:
- Image/caption block
- Call to action button

The Image/Caption block should be unlimited so they can add as many as they'd like in each gallery, but the Call to Action block should be limited to one instance (and is a block we're re-using elsewhere in this Neo field with consistent behavior.

### Problem

Since child blocks can only exist in a single instance within a block, there's no way to have a repeatable child block alongside a non-repeatable different child. The only solution here is to create a one-off matrix field for the Call to Action button and use it in the field layout designer of the Neo block.

### (Potential) Solution

The "Neo Blocks" UI element allows child blocks to be inserted at a custom position in a block's field layout. If this UI element was made so you can use multiple instances of it (like the built-in UI elements) and had an option inside it to specify which child blocks it corresponded to, we could create these sorts of custom child block configurations.

**Comment by ttempleton** [comment]
This sounds close enough to #513 that I'd consider it a duplicate, so feel free to give a 👍 reaction to that one if you'd like to see this - but if I'm understanding your use case correctly, and please do correct me if I'm wrong, could you achieve this by setting the call to action block type's 'Max Sibling Blocks of This Type' setting to 1?
