### ISSUE TITLE
Validation error when saving parent block with children

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-neo#655]
I have a block which is allowed child blocks. I have it set up that 1 child blocks is required, since Neo v3.3.8 saving an entry with this block which contains 1 or more child blocks now has incorrect validation, it says 1 child block is required even though it has 1 or more child blocks within it.

The child blocks in my case are not top level, so can only be child blocks.
This issue only seems to be an issue with new child blocks, if a block has existing children it does not throw a validation error.

<img width="998" alt="Screenshot 2022-09-15 at 18 07 53" src="https://user-images.githubusercontent.com/1436378/190468748-c2b94ba3-4a88-42e0-921f-e693fded5ea3.png">

<img width="495" alt="Screenshot 2022-09-15 at 18 11 32" src="https://user-images.githubusercontent.com/1436378/190468765-be9cec76-56dd-4cc3-8876-6302f2b6b8d5.png">

#### Other information
- Neo version: 3.3.8
- Craft version: 4.2.4

**Comment by ttempleton** [comment]
Thanks for reporting that - should be fixed now in Neo 3.3.9.
