### ISSUE TITLE
Unclear visual indication when a Neo Block type with a tabbed layout has an error on an Entry

### ISSUE THREAD

**Issue by mscherr-fastspot** [spicywebau/craft-neo#656]
#### Description

> _This is a little difficult to describe, so please follow up if you need any more information. I also did not see a current ticket for this, so I apologize if it exists already._

When a Neo field has a Block Type with a tab based field layout and there is an error in an entry, it is unclear that:

1. There is an error
2. Where the error is coming from in the blocks structure

Example:

Saving an entry with a Neo block field error shows the "alert icon" on the tab 👍:

![CleanShot 2022-09-15 at 16 49 26](https://user-images.githubusercontent.com/61987508/190506133-7a6a1d56-4bc1-4fcc-8365-edfb8b16ba48.jpg)

Moving to the "Components" tab, it is unclear where the error is 👎:

![CleanShot 2022-09-15 at 16 51 02](https://user-images.githubusercontent.com/61987508/190506366-f4089515-06f0-4284-85d0-76167503439d.jpg)

The error is actually here, inside the "Cards" tab of the "Card Group" Neo block type:

![CleanShot 2022-09-15 at 16 51 30](https://user-images.githubusercontent.com/61987508/190506431-24754456-21ef-4e28-8f39-73d9fc92e3ef.jpg)

I think it would be great if the Neo block tab could have a similiar visual alert icon (like the "Components" tab above) to indicate an error is within. I am open to other suggestions for relaying that information.

#### Steps to reproduce
1. Create a NEO Block field
2. Create a Block Type that contains at least two tabs
3. Mark a field in the second tab as "Required"
4. Go to an entry with the Neo Block field, add the created Block Type and try to save the page without filling in the required field from the second tab
5. Observe it is unclear there is an error within the second tab

#### Other information
- Neo version: 3.3.8
- Craft version: 4.2.5
- (if multi-site) What is the affected Neo field's propagation method: N/A
- Is eager-loading used? N/A

**Comment by ttempleton** [comment]
Thanks for reporting this! I've partially fixed this now in Neo 3.3.9, for cases where subfields of the block itself have errors. From your screenshot, it looks like you're using the child blocks UI element; this isn't fixed for that case, but I'll let you know when it's fixed, once I've figured out the best way to fix that case.

**Comment by mscherr-fastspot** [comment]
Thanks for the quick reply!

And to confirm, yes I am using the Child Blocks UI element.

**Comment by ttempleton** [comment]
I've just fixed this for the child blocks UI element case for the next release: if a descendant block has a validation error, blocks using the child blocks UI element will show an error indicator on the tab that contains the UI element.

![Screenshot 2022-09-19 at 14-35-24 Homepage - Craft 4](https://user-images.githubusercontent.com/19421878/190951066-f4066c92-0629-4f69-aef0-679286d314b5.png)

**Comment by ttempleton** [comment]
Neo 3.4.0 has just been released including the fix for the child blocks UI element.
