### ISSUE TITLE
Neo Block conditions missing additional visibility conditions

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#657]
#### Description
Neo blocks have a few visibility conditions available in their configuration now:
![Screen Shot 2022-09-19 at 5 01 09 PM](https://user-images.githubusercontent.com/42223501/191139575-73ef7252-e3ca-4fc1-9be1-b64be33b19b0.png)

However, many additional ones have been added to Craft's visibility conditions:
![Screen Shot 2022-09-19 at 5 00 59 PM](https://user-images.githubusercontent.com/42223501/191139623-ad44f6e2-0264-4758-bc35-e72fd084ea1b.png)

I'm specifically needing "Section", but would it be possible to get some/all of these additional conditions added to Neo?

#### Other information
- Neo version: 3.3.9
- Craft version: 4.2.4

**Comment by ttempleton** [comment]
I didn't put in any other rules that weren't relevant specifically to Neo blocks, but it makes sense that there should be some rules that concern properties of the owner element. At least for now (until it's possible for us to show/hide subfields dynamically based on condition rules), I'd only want to add rules for things like entry section, category group etc. that won't actually change. I'll have a look at adding those soon.

**Comment by ttempleton** [comment]
I've just added condition rules for the owner element's section, entry type, asset volume, category group, user group or tag group. Neo 3.4.0 will be released in the next couple of days, just a few small changes I want to make elsewhere first, but in the meantime, you can take advantage of the new condition rules by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.3.9` and running `composer update`.

**Comment by ttempleton** [comment]
Neo 3.4.0 has just been released including the new condition rules.

**Comment by turnstylerj** [comment]
Awesome, thanks for the quick update!
