### ISSUE TITLE
[FR] Restrict blocks to certain user groups

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#658]
It would be great if the use of blocks could be limited to certain user groups. For example, we have some blocks that should only be used by admins. It would be ok if other user groups could see these blocks, but not edit, remove or add.

Is something like this already possible or planed?

**Comment by ttempleton** [comment]
No plans for this currently, but block permissions were previously requested by #196, so feel free to give a 👍 reaction to that feature request if you'd like to see this added.
