### ISSUE TITLE
[FR] Ability to add conditions to subfields based on whether block is a child or top level

### ISSUE THREAD

**Issue by tigerchick** [spicywebau/craft-neo#663]
#### Description
It would be useful to conditionally show a subfield depending on whether or not the Neo block is top level or a child of another block.
This is a Feature Request.

**Comment by tigerchick** [comment]
And to take it a stage further - add the ability to conditionally show a subfield based on the field values of parent block.

**Comment by ttempleton** [comment]
This is a great idea, and something I'd love to add when it's possible for us to implement #579.

**Comment by ttempleton** [comment]
The ability to add conditions to subfields based on the block's level is now implemented in the [`enhancement/dynamic-block-conditions`](https://github.com/spicywebau/craft-neo/tree/enhancement/dynamic-block-conditions) branch and will be released in Neo 3.7.0.

I'll have a look soon into whether we can add condition rules based on the parent block's field values.

**Comment by ttempleton** [comment]
[We can and have!](https://github.com/spicywebau/craft-neo/commit/b410893f6774fb40ed456cbd56b5599dc7b76bdd)

**Comment by ttempleton** [comment]
Neo 3.7.0 has just been released with those new condition rules.
