### ISSUE TITLE
Suggestion, regarding large diffs and resulting merge conflicts due to cascading sortOrder changes

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#667]
We have a small team working on a large website. We're using neo and have dozens and dozens of block types in our "content builder" Neo field.

In our workflow we often have many components partially built at once, and they are individually going to go through review before being merged to mainline.

Whenever a block is added, the `sortOrder` field of every single block after it changes in Craft's yaml files. If a block is added at the very top of the list, that means every single block definition file is touched. We have open pull requests touching dozens and sometimes over a hundred files, and they're a nightmare to review since we scroll though page after page of sort order changes.

If two blocks have been added, or worse, if one changeset adds one, and another adds two, those diffs conflict. This gets worse and worse as we have more changesets open.

It can lead to bad merges, which sometimes gives us errors when Craft wants to update its config based on the yaml file changes. Sometimes we mess up and a block has ended up in the wrong section -- I'm not sure exactly what causes this but I suspect the section headings aren't quite part of the same sort order series as the blocks themselves, so there's nothing protecting a block from accidentally slipping to the next section when its sort order number changes.

I have a couple of suggestions which may help with this. Please bear in mind I have no idea about Neo's internals, so it could be that these suggestions are useless. Still, worth asking, I think.

### Ordered array rather than sort order

Can the sort order be done away with? Perhaps by replacing it with an index file with an ordered array of all blocks.

Each change would now reorder just this list, or add or remove entries. They wouldn't need to be enumerated.

### Allow gaps in sort order

If that isn't possible, how about incrementing by some large value like 10 or 100 between each block, instead of 1?

When a block is created or dragged, check the sort orders of the blocks before and after it. Check there's room, and if so, pick the number about half way between them for the new sort order. If we're at one edge or the other, add or subtract 10 (or 100) as appropriate. Allow the number to go negative. If there wasn't room (direct siblings are ordered 51 and 52 for example), either change their numbers to distribute among *their* direct siblings, or take the nuclear option and renumber everything.

Each change would generally now not affect the sort order of any other blocks.

### Sort order as a float

Or, potentially simpler, can the sort order be floats? Then there's always room to put a new number between other existing ones.

**Comment by ttempleton** [comment]
I think storing ordered arrays in the project config would be good. I'll see if I can look into this soon.

**Comment by elfacht** [comment]
+1 for the array approach. 

We are facing the same issue here: 30+ blocks and when two devs are working on this field in two different branches there will be always either conflicts or missing or misplaced blocks. 

Current workaround: no simultaneously tickets for Neo blocks on the same field. Which is not that pleasing.

**Comment by ryanleichty** [comment]
We’re running into this exact same issue. Multiple devs working on different branches, large diffs all related to sort order 😓

**Comment by ttempleton** [comment]
Putting this on the 4.0.0 milestone in case it turns out any breaking changes are involved. Will definitely try to do it earlier if possible, though.

**Comment by fvwanja** [comment]
+1 🙏

**Comment by ttempleton** [comment]
This is now implemented in 4.0.0-beta.1, and your project config data should be migrated to the new format on upgrading to Neo 4.
