### ISSUE TITLE
Defining NEO field as "not translatable"

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#668]
#### Description
A clients site has a couple of translations. After some years, we restructured the site and removed all the translations. Now, there are only two sites present. I disabled translation on all fields. The only field that still shows the "translated" icon in the list is my NEO field. This now causes problems on entries that are shared between both sites which should not be translated, but are translated now. 

Is there any way I can define the field as "not translatable"? 
As mentioned before, literally _all_ field (so also all fields included in the NEO field) are not translatable. When creating a new neo field it is also listed as not translated. It is thus just that existing field.

#### Other information
- Neo version: 2.13.15
- Craft version: 3.7.59
- (if multi-site) What is the affected Neo field's propagation method: Only save blocks to the site they were created in
- Is eager-loading used? No

**Comment by ttempleton** [comment]
For Neo fields (and Matrix and Super Table, for that matter), the definition of "not translatable" is that their propagation method is set to "Save blocks to all sites the owner element is saved in".
