### ISSUE TITLE
No expand option available when using collapseAllBlocks in global settings for Neo

### ISSUE THREAD

**Issue by rydncn** [spicywebau/craft-neo#672]
#### Description
No expand option when `collapseAllBlocks` setting is used. When clicking on the settings cog menu it still says Collapse with no Expand option. Clicking on the Collapse option doesn't trigger anything.

#### Steps to reproduce
1. Set `collapseAllBlocks` to true in `config/neo.php`.
2. Go into an entry and click the settings for the collapsed Neo field.
3. No expand option in the menu, only collapse

![collapse](https://user-images.githubusercontent.com/42733708/200566623-d931156c-b45b-4908-bfaf-b6d56dd4d758.png)

#### Other information
- Neo version: 3.4.1
- Craft version: 4.3.1
- (if multi-site) What is the affected Neo field's propagation method: Not a multi-site
- Is eager-loading used?: No

**Comment by ttempleton** [comment]
Thanks for reporting that - just released Neo 3.5.0 with the fix.
