### ISSUE TITLE
Missing DB column "groupChildBlockTypes" in the "neoblocktypes" table

### ISSUE THREAD

**Issue by hw-01010** [spicywebau/craft-neo#675]
#### Description
The DB Column `groupChildBlockTypes` is missing in the `neoblocktypes` table.
I think the DB Migration may have been forgotten after the new feature was added.
This resultet in an error after saving a Neo Block.
(I created my own migration to fix it)

#### Steps to reproduce
1. Create a neo Block and save it
2. Add a child to any block and save it, it should throw an error

#### Other information
- Neo version: 3.5.1
- Craft version: 4.3.1
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
The migration wasn't forgotten, but it sounds like it didn't run - I've just released Neo 3.5.2 which runs another migration for a new block type setting, so hopefully the one for `groupChildBlockTypes` runs as well.

I'll close this issue for now, but please let me know if you still have this issue with 3.5.2.
