### ISSUE TITLE
Duplicating a Child Block Allows Users to "Override" Max Child Settings

### ISSUE THREAD

**Issue by sjstark** [spicywebau/craft-neo#679]
#### Description
Found while a user was editing things in the CMS, duplicating a child block allowed them to override/get past the Max Child settings set on the parent block of the Neo field.

#### Steps to reproduce
1. Make a Neo Field with a top level and child blocks
2. Set Max and Min Blocks
3. Create Entry that uses this block
4. Duplicate any children and it will allow it to get past Max Child Settings in the Neo Settings

#### Other information
- Neo version: 3.5.2
- Craft version: 4.3.2

https://user-images.githubusercontent.com/6759557/204220783-ce7ac975-d34f-4b02-80c7-baa2011a671e.mov

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in Neo 3.5.4.
