### ISSUE TITLE
Content Summaries for SuperTable + Child Blocks

### ISSUE THREAD

**Issue by davidhellmann** [spicywebau/craft-neo#68]
We discussed it in Slack. It would be cool to have this Feature for Neo. 
Thanks @benjamminf :)

![image](https://cloud.githubusercontent.com/assets/764292/21384061/045cae64-c769-11e6-832d-40e50e5002c4.png)

**Comment by johanneslamers** [comment]
This! Exactly this!

**Comment by vandres** [comment]
@ttempleton Hi, is this feature on the roadmap? My client would love to see it

**Comment by ttempleton** [comment]
Hi @vandres, this feature has now been completed and will be included in Neo v2.2.0.

**Comment by vandres** [comment]
@ttempleton WOW!, that was quick. Thank you
