### ISSUE TITLE
Control panel JS error

### ISSUE THREAD

**Issue by Zsavajji** [spicywebau/craft-neo#680]
Hi, 
after the update to Neo 3.5.4, the CP throws a JS error.
This is caused by the new check on the pasteData, which can be an empty object. 
The `pasteData.blocks` variable can be null, creating an exception when checking against its length.

```
  if ((!pasteDisabled || !cloneDisabled) && parentBlock) {
      const maxChildBlocks = parentBlock.getBlockType().getMaxChildBlocks()

      if (maxChildBlocks > 0) {
        const childBlockCount = parentBlock.getChildren(blocks).length
        const pasteBlockCount = pasteData.blocks.length
        pasteDisabled ||= childBlockCount + pasteBlockCount > maxChildBlocks
        cloneDisabled ||= childBlockCount >= maxChildBlocks
      }
```
#### Steps to reproduce
1. Update to Neo 3.5.4
2. Load an entry in the control panel, with a Redactor field
3. Redactor field does not get loaded, errors in JS console.

Thanks.

**Comment by ttempleton** [comment]
Whoops, thanks for reporting that! Fixed now in Neo 3.5.5.
