### ISSUE TITLE
`project-config/rebuild` deletes `cms/config/project/neoBlockTypes/*`

### ISSUE THREAD

**Issue by joepagan** [spicywebau/craft-neo#681]
#### Description

Hi, hitting a weird issue here, do you have any ideas?

`project-config/rebuild` deletes `cms/config/project/neoBlockTypes/*`
I have to re-save every neo field in field settings, for them to come back
Without them, the fields will disappear from entry types after a project-config/apply and content does not render on the frontend, though the content appears to stay in the database if the fields are reinstated by reverting the missing project config files and re-applying.

#### Other information
- Neo version: "spicyweb/craft-neo": "3.5.4",
- Craft version: "craftcms/cms": "4.3.3",
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
I'm unable to reproduce this - but does it work if you downgrade to Neo 3.5.2? There was a change in 3.5.3 which involved code called (among other cases) when rebuilding the project config, although it shouldn't have affected the project config rebuild.

**Comment by ttempleton** [comment]
Please disregard the previous comment - it turned out I had reproduced it, but the file browser hadn't refreshed yet 😅

Anyway, thanks for reporting this! It's fixed now in Neo 3.5.6.

**Comment by joepagan** [comment]
Thanks for the fast fix, I can confirm rebuild no longer deletes the project config files!
