### ISSUE TITLE
Neo block queries can return duplicate blocks if the blocks are owned by both an entry/category and one of its drafts

### ISSUE THREAD

**Issue by rajparekh-pd** [spicywebau/craft-neo#682]
#### Description

Hi, it seems that $allowOwnerDrafts on BlockQuery is broken.

I am trying to query with Block:findAll with ownerId, and it is returning me elements from draft entries as well. I tried to set it explicitly yet, I can see the query still returns elements from drafts.

#### Steps to reproduce
1. Create an entry
2. Create a draft of the entry 
3. Run 
```
Block::findAll([
  'ownerId' => $entry->id,
  'allowOwnerDrafts' => false,
]);
```
4. The output will have elements from both original and duplicate elements

I also checked the rawSql BlockQuery generates and tried running it. It still gives multiple elements even when I can see it is trying to enforce draftId be null

#### Other information
- Neo version: 3.5.7
- Craft version: 4.3.4

**Comment by satheesht** [comment]
Tried Block::find (BlockQuery) way as well. No luck. 
```
$blocks = Block::find()
	->ownerId($entry->id)
	->level(1)
	->site($entry->getSite()->handle)
	->allowOwnerDrafts(true)
	->allowOwnerRevisions(false)
	->all();
```
Returns blocks linked to both `active` and `draft` entry

**Comment by ttempleton** [comment]
Thanks for reporting this. It turned out not to be related to the `allowOwnerDrafts` property, but rather the fact that if a block is owned by both an entry and one of its drafts, it belongs to two block structures, and Neo wasn't doing enough to ensure only the version of the block from the correct block structure was returned in the query, so you'd have duplicates appear.

I've just fixed that for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.5.7` and running `composer update`.

**Comment by rajparekh-pd** [comment]
Thanks, so much for the quick response!

**Comment by ttempleton** [comment]
I've just slightly improved the fix for this issue, and have released Neo 3.5.8 with that fix.

**Comment by ttempleton** [comment]
Reopening this issue, I've removed the fix in 3.5.12 due to it causing other issues.

**Comment by widewebpro** [comment]
I get same bug with duplicate children blocks. I solved this problem by removing the Eager Loading.

**Comment by ttempleton** [comment]
First I'll need to figure out how to fix it without [breaking a bunch of other stuff](https://github.com/spicywebau/craft-neo/issues?q=is%3Aissue+created%3A2022-12-06T00%3A00%3A00%2B00%3A00..2022-12-09T00%3A00%3A00%2B00%3A00+in%3Atitle+NOT+yaml).

In the [bugfix/682](https://github.com/spicywebau/craft-neo/tree/bugfix/682) branch, I've restored the attempted fix for this issue to mostly the same state it was in for Neo 3.5.11, before it was reverted. I've also added tests for some of the other things that went wrong, and will likely add more. I'll update here again when a beta release is out.

**Comment by josh-attwood** [comment]
We are still experiencing this issue and it has been a while now. Do we have any updates on when we can expect a fix for this?

**Comment by ttempleton** [comment]
The 4.0.0-beta.1 release is out - I believe this issue is fixed in that release.
