### ISSUE TITLE
Neo 3.5.10: Block structure gets mangled again

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#684]
#### Description

After the update to 3.5.10 neo block structure gets mangled again.  When I save an entry that has a block with a child block, the child block is suddenly on the same level as the parent block. This does not happen consistently, currently it always affects the block I changed before.

These ongoing issues that corrupt the data are really a big problem. 

#### Steps to reproduce
1. Edit a block that has a child block.
2. Save the entry 
3. Child block is suddenly on the same level ist the parent block

#### Other information
- Neo version: 3.5.10
- Craft version: Craft Pro 4.3.4

**Comment by ttempleton** [comment]
Unable to reproduce this - please send your composer.json/lock and database backup to plugins@spicyweb.com.au, and we'll look into it.

**Comment by mihob** [comment]
Sorry, i really can't send you the complete database filled with customer data. Is there any other to help you?

These issues are not really consistent. Sometimes child blocks are suddenly on the same level as the former parents blocks or they a moved to another block. Sometimes whole blocks vanish. It looked like you had solved the problem with version 5.3.7, but in 5.3.10 it's back.

Reverting to 5.3.7 solves the problem.

**Comment by forcehobbit** [comment]
Can confirm this bug. We also rolled the version back to v3.5.7 to get rid of this problem. I will send you the composer files and a db dump.

**Comment by ttempleton** [comment]
Thanks for sending that in. Could you please set your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.5.10`, run `composer update` and let me know if that resolves the issue for you?

**Comment by ttempleton** [comment]
Neo 3.5.11 has just been released which should fix this issue. Please let me know if the issue persists in any way, though.

**Comment by smcyr** [comment]
On my end, I have blocks that are supposed to be on level 2 (Banner block below Banner Carousel), but after 3.5.11, they are all on the same level. If I drag those to be on level 2 and save the entry, it keeps resetting to level 1.

**Comment by ttempleton** [comment]
Were the blocks at level 1 even before saving the entry?

**Comment by kamiljedrkiewicz** [comment]
@ttempleton we have still this problem, our grid system disappear after save and in logs we can see:

![image](https://user-images.githubusercontent.com/10044812/206476351-f4f401dd-87b2-4f06-9b02-a0d13dad1c57.png)

After changing "Min Child Blocks" to 0, all blocks appear as level 1 after saving.

**Comment by smcyr** [comment]
Yes, but I tried with the my database from production and the levels are fine even after saving. Maybe there's something wrong with my local database after I updated to previous versions of Neo, but after dragging the blocks inside the other blocks, it should keep the right level probably?

**Comment by ttempleton** [comment]
I've reverted the fix for #682 as that was what was causing this, among other issues. So this should be working properly again in 3.5.12.

**Comment by smcyr** [comment]
I updated to 3.5.12 and it seems to fix the issue now on my end. Thanks
