### ISSUE TITLE
Issue with children and level

### ISSUE THREAD

**Issue by stevendierick** [spicywebau/craft-neo#685]
#### Description

Accessing children or a block's level no longer works since the latest version.

We have a menu field with two types, an item type and a dropdown type. The dropdown is a child of item. This all works fine in the CP. But we can no longer access its children and filter by level when trying to render the menu on the front-end.

It seems as if both children and level are `null`.

For example:

```
{% set headerMenu = header.fieldHeaderMenu.collect()|default(null) %}

{% if headerMenu %}
    {% for item in headerMenu|filter(item => item.level == 1) %}
        {% set label = item.fieldLabel|default(null) %}
        {% set dropdown = item.children.all()|default(null) %}

        <nav>
            <div>{{ label }}</div>

            {% if dropdown %}
                <ul>
                    {% for item in dropdown %}
                        ...
                    {% endfor %}
                </ul>
            {% endif %}
        </nav>
    {% endfor %}
{% endif %}
```

#### Other information

- Neo version: 3.5.10
- Craft version: 4.3.4

**Comment by ttempleton** [comment]
I'm unable to reproduce this - could you please confirm if this occurs with 3.5.9 or 3.5.7? And if this is reliably reproducible e.g. on a new entry, could you please provide steps to reproduce that are as detailed as possible in case I'm missing something?

**Comment by stevendierick** [comment]
Might have found the culprit: eager loading.

We also eager load the Neo field. Remove the eager loading and it works:

```
{% do craft.app.elements.eagerLoadElements(
    className(header),
    [header],
    ['fieldNavTop']
) %}
```

**Comment by ttempleton** [comment]
Thanks, that has helped me reproduce it. Could you please set your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.5.10`, run `composer update` and let me know if that resolves the issue for you?

**Comment by stevendierick** [comment]
That seems to have resolved this issue for me. Thanks!
