### ISSUE TITLE
Neo not rendering on front end after update to 3.5.10+

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#690]
#### Description
We have a couple of site that use Neo where the Neo block content does not render to the front end after updating to Neo 3.5.10 or above. The problem corrects if we downgrade to 3.5.5, but there could still be an issue with versions between 3.5.5 and 3.5.10

#### Steps to reproduce
1. update to 3.5.10 or 3.5.11 
2. Go to front end
3. Note absence of content

#### Other information
- Neo version: 3.5.10 or above (possibly others)
- Craft version:
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? yes

**Comment by ttempleton** [comment]
Fixed in 3.5.12
