### ISSUE TITLE
Block children not accessible in Element API

### ISSUE THREAD

**Issue by corneliusio** [spicywebau/craft-neo#691]
#### Description
Believe this is an issue that was introduced with Neo 3.5.10. When using Element API to access blocks, the queried block is returned as expected, but any reference to `$block->children->all()` returns an empty array.

#### Steps to reproduce
https://github.com/mostlyserious/neo-example 
(can provide DB if needed)

#### Other information
- Neo version: 3.5.10
- Craft version: 4.3.4
- Element API version: 3.0.1.1
- Is eager-loading used? Has no effect either way.

I don't believe this is an issue with Element API as reverting Neo to version 3.5.9 resolves the issue.

**Comment by ttempleton** [comment]
Fixed in 3.5.12

**Comment by corneliusio** [comment]
Yep! Looks like that did it. Thanks for the quick turnaround.
