### ISSUE TITLE
Importing Neo fields into Craft 4

### ISSUE THREAD

**Issue by danleecpi** [spicywebau/craft-neo#693]
### What question would you like to ask?

I'm importing fields from an earlier version of a site into Craft 4 with the latest version of Neo.

I run into the following error:

`Undefined array key "alwaysShowDropdown"`

How do I amend my import json to accomodate this new feature?

**Comment by ttempleton** [comment]
`alwaysShowDropdown` is a new property of block type groups, so setting `alwaysShowDropdown: null` for your block type groups in your JSON will do it.

That said, you should be able to import it without getting an error and it should just get set to `null` by default, so there might be a bug somewhere. How are you importing your Neo field data into Craft?

**Comment by danleecpi** [comment]
@ttempleton I'm using the Field Manager Plugin to import the exported json.

**Comment by ttempleton** [comment]
Thanks @danleecpi, I can reproduce the error. I'll have a look into how that would best be fixed.

**Comment by ttempleton** [comment]
That should be working now with Neo 3.5.13.

**Comment by danleecpi** [comment]
Thanks @ttempleton - I'll let you know what I find today.
