### ISSUE TITLE
Matrix of matrix scrapped when changing the entry type

### ISSUE THREAD

**Issue by gaelpleeroy** [spicywebau/craft-neo#695]
### Bug Description

When I switch entry type of the same section the nesting matrixes get removed.

### Steps to reproduce

1. Create a Neo field with matrix in matrix
2. Create a section with two entry types with the same Neo fields
3. Save an entry with content in those Neo matrixes
4. Now switch the Entry Type to the other one and watch the matrix inside the matrix (level 2) get scrapped

### Expected behaviour

The data should be there whatever the nesting.

### Neo version

3.5.13

### Craft CMS version

4.3.5

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this - is this happening to Neo child blocks or a nested Matrix field? And is there any chance that another installed plugin could be interfering?
