### ISSUE TITLE
Move block up/down options

### ISSUE THREAD

**Issue by benjamminf** [spicywebau/craft-neo#7]
Sometimes blocks can get pretty long, if they have a lot of content or children in them. Dragging them to change their position can get a little clunky in these cases. Would be good to have an option on the dropdown menu for each block to move their positions up and down as an alternative to dragging.

**Comment by benjamminf** [comment]
Another idea might be to auto-collapse the children container when dragging blocks. This will also help alleviate the pain of reordering very long blocks.

**Comment by benjamminf** [comment]
I'm deciding to not implement this feature. Adding any more menu items will overcrowd the menu, and auto-collapsing dragged blocks won't actually do anything, as dragging distance is dictated by all non-dragged blocks. The alternative is to manually collapse whatever blocks you need.

**Comment by ttempleton** [comment]
Reopening this: Matrix fields have move up/down options as of Craft 3.5, so it'd be good if Neo could do it too.

**Comment by ttempleton** [comment]
Now implemented in the [`neo-2.9`](https://github.com/spicywebau/craft-neo/tree/neo-2.9) branch.
