### ISSUE TITLE
Block query results on front-end being duplicated while appearing correctly in control panel

### ISSUE THREAD

**Issue by jrrdnx** [spicywebau/craft-neo#703]
### Bug Description

Not sure if related to #682 or not so I wanted to open a new issue, but feel free to close this if it's a duplicate. Essentially, front-end queries are outputting the same block twice in a row instead of that block and its sibling. It seems to occur only when allowing Child Blocks, but I can't be sure. Everything appears as normal in the control panel when editing an entry.

Quick and dirty example: instead of parent block A, with children B, C, and D, it will output parent A, with children B, C, and C.

### Steps to reproduce

Unfortunately we haven't found a way to reproduce this _reliably_. To resolve the issue, even though the block appear correctly when editing an entry in the control panel we've created the new block(s) with the same content and deleted the old and results start appearing correctly on the front-end. Would very much welcome some assistance in debugging.

### Neo version

2.13.15

### Craft CMS version

3.7.62

### Does this issue involve templating, and if so, is eager-loading used?

This is a templating issue, and eager loading is not used

**Comment by ttempleton** [comment]
This seems unrelated to #682, but I'm unable to reproduce it locally. If possible, could you please send a database backup and your composer.json/lock files to plugins@spicyweb.com.au, along with an example of an entry that has this issue, and we'll have a look.
