### ISSUE TITLE
FR: Automatically add required child blocks

### ISSUE THREAD

**Issue by TheFunkyMonk** [spicywebau/craft-neo#706]
## Description
If I have a block set to require at least x child blocks, and only one type of child block available, it would be nice to (at least have the option to) automatically add required child blocks when the parent block is created.

## Example
![Screen Shot 2023-01-30 at 1 31 18 PM](https://user-images.githubusercontent.com/1728770/215599619-47d16410-1f46-4938-9e08-e977cd0468b2.png)
![Screen Shot 2023-01-30 at 1 30 39 PM](https://user-images.githubusercontent.com/1728770/215599532-1a586eb6-35ee-4174-95fc-6695cf2aac4f.png)
I have a top-level Neo block "Images" meant as a container for the author to be able to add one or more child "Image" blocks. The block isn't usable without at least one child block, so it'd be nice to save the author an extra click and provide the default fields when the block is created.

**Comment by ttempleton** [comment]
Fair enough. I've just added this to the [`enhancement/dynamic-block-conditions`](https://github.com/spicywebau/craft-neo/tree/enhancement/dynamic-block-conditions) branch, since that's basically the 3.7.0 dev branch at this point. I'll update here when 3.7.0 is released.

**Comment by ttempleton** [comment]
Neo 3.7.0 has just been released with that improvement.
