### ISSUE TITLE
Add a custom folder setting for block type icons

### ISSUE THREAD

**Issue by rauwebieten** [spicywebau/craft-neo#710]
### What would you like to see added to or changed in Neo, and why?

The new block picker feature is a nice update.
But,

This feature is not working in a setup with a local development combined with a production environment. Because:
1. the development assets are not available in the production environment, furthermore, the project config contains references to assets that are not available in the production env.
2. admin changes are not allowed in the production environment, so "fixing" the assets on the production env is not possible.

I think a solution with picking icons from a custom folder instead of a asset volume, is better.
Then you can commit the custom folder with icons in your git repo, and deploy on the production env.
(I see vizy is doing it also this way)

see also https://github.com/spicywebau/craft-neo/issues/569

**Comment by ttempleton** [comment]
Block type icons are tracked across environments by storing the following in the project config:

- The icon asset's volume UID - which is also part of the project config so won't change between environments;
- The icon's folder path within the volume, and filename - which, while not part of the project config, it would be expected that the same asset file would exist at the same location, relative to the volume root, for each project environment.

I've just retested this with the latest version of Neo (3.6.4) and confirmed this is working for me.

I'm happy to take feedback on whether changing block type icons to use a custom folder plugin setting would be the generally preferred solution for the next major Neo version, and I'm happy to take any bug reports related to the current behaviour. For now, though, unless I'm misinterpreting your comments, this feature appears to be working as expected.

**Comment by ttempleton** [comment]
Another option could be to add a plugin setting to switch between the current behaviour and your suggestion.

**Comment by rauwebieten** [comment]
Hi, thanks for the suggestion, I will test this today in our setup.
According to your explanation, I expect this to work.

**Comment by rauwebieten** [comment]
Hi,

Suggested workflow works. 
Indeed, the asset is referenced in the project config, but by filename, not by ID.

So after deploying simply uploading the icons in the right location fixes this issue. (this can be automated with your build pipeline)

Thanks for the quick help
