### ISSUE TITLE
[FR] Global Set Condition

### ISSUE THREAD

**Issue by chrismlusk** [spicywebau/craft-neo#711]
### What would you like to see added to or changed in Neo, and why?

Would it be possible to set rules to allow block types to be used on Global sets?

Specifically, I currently use the Entry Condition field to limit blocks that are allowed on certain sites. Example:

<img width="635" alt="Screenshot 2023-02-16 at 11 53 24" src="https://user-images.githubusercontent.com/5922913/219447967-dc1f798f-5b21-4084-9f7a-254e8497ef6c.png">

I'd like to be able to do this exact thing on Globals, too.

**Comment by ttempleton** [comment]
Fair enough. I've just added this to the [3.7](https://github.com/spicywebau/craft-neo/tree/3.7) branch, and will update here when 3.7.0 is released.

**Comment by ttempleton** [comment]
Neo 3.7.0 has just been released, with the ability to set global set conditions on block types.

**Comment by vebjorn** [comment]
I can not get this to work for the life of me. As with the screenshot from @chrismlusk - in order to get to a global I have to use "Site" first, then, fields added to a global-variable set becomes visible. If you then save and think everything is peachy, it's gone the next time you view the conditions for said Neo-block.

**Comment by chrismlusk** [comment]
For what it's worth, the Global Set Condition rule is visible for me underneath the Address Condition rule. (I'm testing on an existing Neo field that has zero conditions applied.)

I was able to set a new Global Set rule, save, navigate away, and return to the edit page for this Neo field, and the conditions I added were there as expected.

**Comment by ttempleton** [comment]
@vebjorn please feel free to open a new bug report with any additional info that might be helpful.
