### ISSUE TITLE
FR: Paste to empty Neo fields

### ISSUE THREAD

**Issue by ccchapman** [spicywebau/craft-neo#713]
### What would you like to see added to or changed in Neo, and why?

You cannot paste to an empty Neo field.  There must be at least one block in the Neo field to find the paste UI.  This can be an annoyance or a blocker in the case of Neo fields that only allow one block.  Is there a way to do this?

**Comment by ttempleton** [comment]
This will be possible with the next release of the [Batch Actions](https://plugins.craftcms.com/batch-actions) plugin - see https://github.com/spicywebau/craft-batch-actions/issues/1.

**Comment by ttempleton** [comment]
We've just released Batch Actions 1.2.0 with the ability to do this.
