### ISSUE TITLE
Issues when changing propagation method

### ISSUE THREAD

**Issue by domstubbs** [spicywebau/craft-neo#717]
### Bug Description

When I adjust the propagation method for a Neo field I’m running into the same “There was a problem getting the parent element” error mentioned in #621 and #692.

If I hit retry the job fails again, but it seems to make a bit more progress each time. After a few retries the job is logged as completed.

Separate or perhaps to related to this is the new propagation behaviour doesn’t match my expectations. I have a site with preexisting content and I was expecting that when I changed from “Save blocks to all sites the owner element is saved in” to "Only save blocks to the site they were created in” I would retain copies of existing content in all sites, but any _new_ blocks would only be saved to the site they are created in.

That seems to be what happens when I make an equivalent change to a Matrix field – and is backed up by [this Craft ticket](https://github.com/craftcms/cms/issues/5182) – but with my Neo field all existing content is being deleted from the secondary site.

Is this the expected behaviour with propagation method changes or are the job errors indicative of the cloning process failing?

Thanks.

![neo-job-failure@2x](https://user-images.githubusercontent.com/717265/223114579-b202f372-149b-4ffa-abad-ecd41d09039a.png)

### Steps to reproduce

1. Change Neo field propagation method to "Only save blocks to the site they were created in"

### Neo version

3.7.0

### Craft CMS version

4.3.10

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm able to reproduce the job error when I've made changes to an entry without saving (likely the same cause as #682) but I'm not able to reproduce the field content loss on the second site.

If the affected entry has any drafts or a provisional draft, could you please delete/discard the drafts and let me know if changing the propagation method then resolves the content loss issue. If it doesn't, then if possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, along with which entry is being affected, and we'll have a look.

**Comment by ttempleton** [comment]
Thanks for sending those through @domstubbs. It turned out there was some old block structure data that should've been deleted, that was interfering with the propagation method change (related to https://github.com/spicywebau/craft-neo/issues/708#issuecomment-1420312363 although not actually the cause of that issue as it turned out). There was some code added to Neo 3.6.3 to clear that data out as part of Craft's garbage collection, so if you run `php craft gc/run` and then change the propagation method, it should work. Please do let me know if you still run into issues after doing that, though.

**Comment by domstubbs** [comment]
Thanks for taking the time to review the DB Thomas, I really appreciate it. You’re absolutely right, manually running GC prior to the propagation change addresses both issues – the jobs complete successfully and the secondary site data is being retained as expected.
