### ISSUE TITLE
Issue when update block

### ISSUE THREAD

**Issue by aodihis** [spicywebau/craft-neo#718]
### Bug Description

I have a page builder field using Neo that have 3 levels and inside it there is also a Super Table, Text, Image etc. 
I have an issue when I am updating the content if the new block I create is not as the last block. Usually I use add block above to do this. There are 2 issue I found.

1. Sometimes when I click add a block or even add an asset button the block replaced by the block below it.
2. Sometime when I editing/ or add the block in the middle or the first one, when I save the entry the last block data is lost.

### Steps to reproduce

1. Open an entry that already have data on Neo Field.
2. Click on add block above.
3. Try to add new block (anything, in my case I add and image block).
4. Click save

### Expected behaviour

In step 3 is the first issue, in my case after I click on add image block then the Asset field will appear, but when I click on add an asset button the field data replaced by another block below it.

In step 4 is the second issue, after I click save when I check again the data the last block is lost the data.

### Neo version

3.7.0

### Craft CMS version

4.3.10

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this, but by any chance are you using the Typed Link Field plugin? There have been reports of empty Typed Link Fields causing issues with Neo (and Matrix) blocks, see https://github.com/sebastian-lenz/craft-linkfield/issues/233.

If you're not using Typed Link Field, then if possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, along with which entry is being affected, and we'll have a look.

**Comment by aodihis** [comment]
@ttempleton yes, I have the link field plugin inside it. Thank you for answer, will check for it.
