### ISSUE TITLE
Drag & Drop blocks no longer works

### ISSUE THREAD

**Issue by Mathias-Syversen** [spicywebau/craft-neo#719]
### Bug Description

When trying to grab a block and drag it somwhere else, it seems the JS grabs the outmost block instead.
So when trying to grab an image block inside section -> column -> image, the entire section block is tragged around, with all its content.

### Steps to reproduce

1. Create neo with 2-3 levels
2. Try to drag lvl 2-3 item
3. See level 1 item getting dragged

### Neo version

3.7.0

### Craft CMS version

4.4.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
This appears to be working fine with Craft 4.3.10 and then not working properly with 4.4.1, so I'm assuming this is a bug in Craft itself that is interfering with Neo's functionality. Happy to reopen the issue if that turns out not to be the case, though.

**Comment by chrismlusk** [comment]
FWIW, @ttempleton, I have a Neo block with a Matrix field, and I can still drag and drop those child blocks as expected. I only experience the problem with Neo child blocks.

Neo — 3.7.1
Craft — 4.4.1

**Comment by ttempleton** [comment]
All blocks in a Neo field belong to the same block sorting instance, whereas a nested Matrix field will have its own. I assume that's why the nested Matrix field would be unaffected.

**Comment by ttempleton** [comment]
Just to wrap things up as far as this issue is concerned - that bug is now fixed in Craft 4.4.3.
