### ISSUE TITLE
Neo imports failing with Feed Me 5.1.1, DataHelper::fetchValue() expects 3 arguments.

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#727]
### Bug Description

I'm not actually sure if this is something that needs to be fixed on the Neo or Feed Me side, but the current version of Feed Me (5.1.1) fails to import Neo fields, logging the following error:

```
Too few arguments to function craft\feedme\helpers\DataHelper::fetchValue(), 2 passed in /vendor/spicyweb/craft-neo/src/integrations/feedme/Field.php on line 203 and exactly 3 expected
```

Downgrading to Feed Me 5.0.5 resolves the issue.

I'm assuming something needs to change on the Neo side to accommodate the changes introduced in the larger Feed Me [5.1.0 release](https://plugins.craftcms.com/feed-me/changelog?craft4#v5.1.0), but let me know if this issue needs to be filed with Feed Me.

### Steps to reproduce

1. Install Feed Me 5.1.1
2. Attempt to import JSON matching Neo's expected import structure

### Neo version

3.7.3

### Craft CMS version

4.4.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Looks like a `$feed` argument was added to [`DataHelper::fetchValue()`](https://github.com/craftcms/feed-me/blob/2528d15a9e234338a00a36d43bc0c3546316f831/src/helpers/DataHelper.php#L122) in Feed Me 5.1.0, which is required ([and which wasn't mentioned in the release notes](https://github.com/craftcms/feed-me/blob/2528d15a9e234338a00a36d43bc0c3546316f831/CHANGELOG.md#510---2023-03-17)). This is a breaking change, which will also affect any code in other packages that happens to use `DataHelper::fetchValue()`, so we won't be making any changes to Neo to resolve the error; the `$feed` argument will need to be made optional.

**Comment by turnstylerj** [comment]
Thanks for the analysis! I'll file a bug with Feed Me.
