### ISSUE TITLE
Active tab changes when manipulating other blocks

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#728]
### Bug Description

If a block (Block A) has several tabs and any of them expect the first one is selected changes to other blocks (Block X), like deactivating a block or adding a new one for example, will reset the tabs of Block A to the first one. But only the tab itself gets reset to the first one, the content of the tab stays the same. Here a short screen recording of the behaviour.

After I observed the behaviour some more it looks like that this happens when a change triggers the auto save feature.

https://user-images.githubusercontent.com/539103/227903943-dbdac563-4ffa-44dd-8a97-d5bb031dbe2f.mov

### Steps to reproduce

1. Have an entry with several blocks with multiple tabs (and fields within)
2. Select another tab than the first one in one of the blocks
3. Manipulate another block, like deactivating it or adding a new block

### Expected behaviour

Not sure what the expected behaviour is change entirely to the first tab or stay at the currently active tab (which I think would make more sense). But now it's kinda both or neither.

### Neo version

3.7.4

### Craft CMS version

4.4.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - the expected behaviour is indeed to stay with the active tabs. Fixed now in Neo 3.7.5.
