### ISSUE TITLE
Redactor disappears after entry save if entry has an error.

### ISSUE THREAD

**Issue by mike-moreau** [spicywebau/craft-neo#732]
### Bug Description

We're using a Neo field with several blocks, one of which contains a redactor field.

When saving an entry with an error (such as a required field that is missing), the redactor field disappears after save.

The console shows the following javascript error `Uncaught ReferenceError: new0 is not defined`

<img width="925" alt="Screenshot 2023-04-05 at 4 34 37 PM" src="https://user-images.githubusercontent.com/92817780/230217264-512cf732-62af-4a77-a2f7-9429b6d66480.png">

<img width="895" alt="Screenshot 2023-04-05 at 4 35 32 PM" src="https://user-images.githubusercontent.com/92817780/230217288-cecde6bd-e072-41b0-a25a-38a206c66db7.png">

<img width="1150" alt="Screenshot 2023-04-05 at 4 41 18 PM" src="https://user-images.githubusercontent.com/92817780/230218753-43bd24d0-926e-4037-a0f2-aaf594d9e4d9.png">

<img width="1182" alt="Screenshot 2023-04-05 at 4 41 25 PM" src="https://user-images.githubusercontent.com/92817780/230218765-98bb2e74-0393-49df-b5e0-ff99440b3be6.png">

I've tried to create a minimal, reproducible example, on a new Craft install but haven't been able to replicate it yet.

I've also tried clearing control panel resources to no effect.

Happy to provide more info if it would be helpful.

### Steps to reproduce

1. Add a neo field to an entry
2. Attempt to save the entry so it will error (missing required field)

### Expected behaviour

WYSIWYG stays visible

### Neo version

3.7.5

### Craft CMS version

4.4.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this – turned out it happened if draft autosaving was disabled. Fixed now in Neo 3.7.6.

**Comment by mike-moreau** [comment]
Thank you!
