### ISSUE TITLE
FR: Add functionality to Neo to override Field Limit for certain fields

### ISSUE THREAD

**Issue by justcookin** [spicywebau/craft-neo#734]
### What would you like to see added to or changed in Neo, and why?

Add functionality where the Field Limit for certain fields(namely Plain Text fields) can be overridden from Neo. The goal is to reuse existing fields in multiple places using Neo, but the only drawback is that the Field Limits have to be set at different amounts, which in turn limits our ability to reuse these fields. 

For example, if Neo was able to override the Field Limit we could create an initial Plain Text field with a Field Limit of 100 characters. Now whenever we want to use this field within a Neo field we could add it, then adjust the Field Limit (from within Neo) to anything under 100 characters. It seems that all this would take is overriding the maxlength attribute in the CMS field.

**Comment by ttempleton** [comment]
I'm not sure that this is possible for us as a plugin to do, but in any case might be better implemented at the Craft field layout level (maybe related: https://github.com/craftcms/cms/discussions/8404).
