### ISSUE TITLE
Option to select static folder as source for block type icons 

### ISSUE THREAD

**Issue by LarsDol** [spicywebau/craft-neo#739]
### What would you like to see added to or changed in Neo, and why?

Hi!

Would it be possible to add the option to select block type icons from a static assets folder? We're running into issues when using the media library, as it doesn't intuitively sync between different (dev) environments.

I suspect my request is similar to https://github.com/spicywebau/craft-neo/issues/710, but manually uploading icons to different (local) environments doesn't really seem feasible to us. We've tried to create a separate asset volume for Neo Icons, checked into git. The problem there is that the asset's database entry still doesn't exist, and upon changing fields in Craft the icon settings tend to be removed from the project config.

For our company, it would make a lot more sense to be able to select icons from a pre defined set of `svgs` that are stored in a directory which is checked into git. At the moment this prevents us from using the `list` or `grid` views for Neo, even though they contribute to a much better UX of the CMS.

Thanks in advance!
Lars Dol

_Front-end Lead @ [Digital Natives](https://www.digitalnatives.nl)_

**Comment by ttempleton** [comment]
Fair enough, will look at this for Neo 3.8.

**Comment by ttempleton** [comment]
I've added this in 4.0.0-beta.1, and also added a [console command for converting block type icons from the existing format](https://github.com/spicywebau/craft-neo/blob/4.0.0-beta.1/docs/console-commands.md#neoblock-typesconvert-icons). For now, assets are still the default way to set block type icons, but that will probably change in the future.
