### ISSUE TITLE
"Group Child Block Types = false" setting temporarily lost when duplicating block

### ISSUE THREAD

**Issue by ThomasRitter75** [spicywebau/craft-neo#740]
### Bug Description

When a neo block has the setting not to group child blocks and a block of that type is duplicated in an entry in the control panel, that setting is temporarily lost. After saving and re-opening the entry

### Steps to reproduce

1. create a neo block with children and the setting "Group Child Block Types = false"
2. create an entry with a block of that type => The setting is respected and child block buttons are correctly not grouped.
3. duplicate that block within that entry => The setting is NOT respected and child block buttons are grouped in submenus
4. save that entry
5. re-open that entry => The setting is respected and child block buttons are correctly not grouped again.

### Expected behaviour

The setting should always be respected.

### Neo version

3.7.0

### Craft CMS version

4.4.7.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 3.7.8.
