### ISSUE TITLE
Duplicate content on same entry from one site to another

### ISSUE THREAD

**Issue by hadomskyi** [spicywebau/craft-neo#744]
### What question would you like to ask?

Hi all,

We are working on copy content functionality. 

Could you please help me to understand, is there anything wrong what we do when we try to duplicate content on same entry from one site to another. We use this code:

```
    /**
     * @param ElementInterface $from
     * @param ElementInterface $to
     *
     * @throws ElementNotFoundException
     * @throws Exception
     * @throws InvalidFieldException
     * @throws Throwable
     */
    private function copyEntryContent(ElementInterface $from, ElementInterface $to): void
    {
        ...

        $fieldLayout = $from->getFieldLayout();
        $fields = $fieldLayout ? $fieldLayout->getFields() : [];

        foreach ($fields as $field) {
            
            ...

            // Check if the field is of Neo type and the required classes and methods are available
            if (
                get_class($field) === CraftliltpluginParameters::BENF_NEO_FIELD
                && class_exists('benf\neo\Plugin')
                && method_exists('benf\neo\Plugin', 'getInstance')
            ) {
                // Get the Neo plugin instance
                /** @var \benf\neo\Plugin $neoPluginInstance */
                $neoPluginInstance = call_user_func(['benf\neo\Plugin', 'getInstance']);

                // Get the Neo plugin Fields service
                /** @var \benf\neo\services\Fields $neoPluginFieldsService  */
                $neoPluginFieldsService = $neoPluginInstance->get('fields');

                // Clear current neo field value
                $neoField = $to->getFieldValue($field->handle);
                foreach ($neoField as $block) {
                    Craft::$app->getElements()->deleteElement($block);
                }
                Craft::$app->getElements()->saveElement($to);

                // Duplicate the blocks for the field
                $neoPluginFieldsService->duplicateBlocks($field, $from, $to);

                continue;
            }

           ...

        }
    }
```

We're delighted with the Neo plugin for Craft CMS! Thanks for developing this fantastic tool that has greatly improved our content management capabilities. Your hard work is truly appreciated!

Thanks in advance!

**Comment by ttempleton** [comment]
There shouldn't be any need to delete the blocks belonging to `$to` before duplicating the `$from` blocks over - those blocks should get deleted automatically during the duplication.

Other than that, your code should work - I've just tested a content migration based on your code to duplicate blocks from the same entry between sites, and that worked. If it isn't working for you after removing the old block deletion code, is there an error that occurs or does the target site just end up with no blocks? Also, which Craft CMS and Neo versions are you using?

**Comment by ttempleton** [comment]
Hmm, your reply makes me think the draft blocks are losing track of their canonical blocks. `duplicateBlocks()` [does assume the copied block is the canonical block if the target owner element isn't the canonical owner](https://github.com/spicywebau/craft-neo/blob/2.12.5/src/services/Fields.php#L363), so that might be causing your issue.

If you change the above-linked line to set `'canonicalId' => $target->getIsDerivative() ? $block->getCanonicalId() : null`, does that resolve your issue? If not, then is there any chance you can send to plugins@spicyweb.com.au a database backup, composer.json/lock files, and the full version of the code you're running?
