### ISSUE TITLE
 Setting of a Neo field

### ISSUE THREAD

**Issue by Mateusc59** [spicywebau/craft-neo#751]
### Bug Description

In the setting of a Neo field,Max and min child fields keep their values even if the child box is unchecked in the settings fields (they should be reset to zero or taken into account if there is no child).
Also, it would be nice to display the errors in the entry form, it was hidden far away in the code (Thanks for the html inspector!!)
Thanks 

### Steps to reproduce

1. Add a parent and a children in the fields (neo / content / add a block type)
2. in the child blocks if there is an number inside Min Child Blocks or Max Child Blocks and if you unchecked the box the value is still take into account
3. After you try to save the entry there is no explicit error message 

### Expected behaviour

Error show on the craft rather than in the html inspector or they should be reset to zero or taken into account if there is no child

### Neo version

3.7.7

### Craft CMS version

Craft Pro 4.4.8

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - just fixed it for the next release. Note that you will need to resave the Neo field after upgrading for the fix to take effect.
