### ISSUE TITLE
Structure not created after propagation setting change unless entry is saved with dirty fields

### ISSUE THREAD

**Issue by mike-moreau** [spicywebau/craft-neo#755]
### Bug Description

We encountered a bug after changing the propagation setting for a Neo field from "Save blocks to all sites the owner element is saved in." to "Only save blocks to the site they were created in."

The blocks are propagated to the new sites as expected. But new structures are not created for each site.

Editing an entry with dirty fields and re-saving does create the structures. But we expected structures to be created for each site when the setting was changed and propagation occurred.

### Steps to reproduce

In a CraftCMS installation with at least two sites. Create a section and add a Neo field to that section.

- Set the propagation settings of the Neo field to: “Save blocks to all sites the owner element is saved in.”
- Create a new entry.
- And add blocks to the entry's NEO field.

In this example, the Entry id is `35289` and the Block id is `35292`.

There is one structure id `12435` for both sites. And the blocks belongs to that one structure as expected.

<img width="1627" alt="structures-before-change" src="https://github.com/spicywebau/craft-neo/assets/92817780/10a8c6ca-fde8-46b8-9c29-9a16ba7e5fbf">

<img width="1629" alt="structure-elements-before-change" src="https://github.com/spicywebau/craft-neo/assets/92817780/db2d60bf-44d2-4069-b7af-17d24658117c">

Then:
- Change the propagation settings on the Neo field to "Only save blocks to the site they were created in."
- Wait for propagation to complete.

The Entry id as before is `35289`

Blocks have propagated and are specific to each site. Block id `35292` and block id `35295`.

But there is only one structure id `12435` for both sites. And all blocks belong to that structure.

<img width="1523" alt="structures-after-change" src="https://github.com/spicywebau/craft-neo/assets/92817780/fa997d03-f59a-4a43-80b6-ec623fea9872">
<img width="1522" alt="structureelements-after-change" src="https://github.com/spicywebau/craft-neo/assets/92817780/f6959b50-c423-453a-a797-6f06ef7aedc2">

I expect there should be two structures at this point, one structure for each site.

Then
- Make a change to the entry to get the fields dirty and save the entry.

Now we see two structure ids, one for each site: `12447` and `12446`

And each block belongs to its own structure.
<img width="1523" alt="structures-after-change-edit-save" src="https://github.com/spicywebau/craft-neo/assets/92817780/91db5c0a-3b11-4c96-9e0b-ea5c0b4ca783">
<img width="1526" alt="structure-elements-after-end-change-save" src="https://github.com/spicywebau/craft-neo/assets/92817780/8b5f7a08-7795-47c5-b454-2b76b91e6824">

### Expected behaviour

That propagating blocks to a new sites would also create structures at the time of propagation.

That a save would not be required to create new structures.

### Neo version

3.7.9

### Craft CMS version

4.4.12

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in.

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this and sorry for the delay in addressing it; it's now fixed in 4.0.0-beta.1.
