### ISSUE TITLE
Having NEO Block parent > Neo Block CHILD > Supertable field > Redactor field > Redactor has image button, when you press it, image picker (asset picker) doesn't show anything.

### ISSUE THREAD

**Issue by bkrsmanovic** [spicywebau/craft-neo#756]
### Bug Description

As title said, create fields like this:
Having NEO Block parent > Neo Block CHILD > Supertable field > Redactor field inside.

If that redactor has image button, and you select to show it, nothing pops up.
Should be like this:
![image](https://github.com/spicywebau/craft-neo/assets/15169280/bb4a393f-51e9-4f09-95f6-9cd6ebfda7c2)

It actually looks like this:
![image](https://github.com/spicywebau/craft-neo/assets/15169280/5efdaf02-5fbf-44f5-b0e3-9af777173b49)

NOTE: There is no console error, there is no Network error, no nothing. Just rendered HTML that appears does not have anything inside.

### Steps to reproduce

1. Create NEO blocks
2. Add 1 block "Parent block"
3. Add repeating child block called "Child block"
4. Inside Child block, add Supertable field
5. Inside supertable field, add Redactor field
6. Inside Redactor field, use Default mode and try to add Image. Nothing shows.

### Expected behaviour

It should allow you to select images in nested child > supertable > redactor field.

### Neo version

3.7.9

### Craft CMS version

4.4.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by bkrsmanovic** [comment]
@ttempleton I can confirm it works with supertable on parent, it works with supertable on child. But it doesnt work in Redactor: 
![image](https://github.com/spicywebau/craft-neo/assets/15169280/674457f7-04ca-484f-810d-ef4e7eb39bc1)
![image](https://github.com/spicywebau/craft-neo/assets/15169280/64551c99-d38b-436a-9fb9-ed7459e88612)

**Comment by ttempleton** [comment]
If possible, could you please send in your composer.json/lock files and database backup to plugins@spicyweb.com.au and let us know which entry / category / other owner element this is happening with, and we'll have a look.

**Comment by bkrsmanovic** [comment]
@ttempleton I have sent relevant files to email. Let me know how it goes.

**Comment by ttempleton** [comment]
Thanks for sending those files. It turned out that in the Super Table field's settings, the Redactor subfield's Available Volumes setting was set not to have any available volumes. Adding some available volumes caused the image button to work as expected.
