### ISSUE TITLE
Remove unused data from NEO fields

### ISSUE THREAD

**Issue by lennonpuype** [spicywebau/craft-neo#757]
### What question would you like to ask?

Hi,

I ran into a issue with a very large DB. I'm doing some logic in a cronjob but the DB is getting larger and larger.
In the past I got this issue with Matrix blocks but because of the craft command `./craft gc/run --delete-all-trashed=1`.
I was able to get rid of the data that was getting overwritten in a matrix field.

Is there any way of removing existing fields the same way with like a garbage collector for Neo Fields since this only works for matrix fields like that one line?

My DB is 430mb atm because of that issue I didn't keep track with because I didn't think further which is obviously my fault, but hopefully there is a easy way of doing this without removing any data that is currently active for the entries where this field is assigned to?

Thanks in advance!

**Comment by ttempleton** [comment]
As far as I can tell, Craft garbage collection should do for Neo everything it does for Matrix. Definitely possible I've overlooked something, though.

Could you please clarify what data it is that you're trying to remove (e.g. is it the entire Neo field data, deleted blocks from a Neo field)? I'd like to have a look at my usual testing environment and compare how Neo compares with Matrix for what you're trying to do.

**Comment by lennonpuype** [comment]
Hi,

The content of the NEO exists from only plaint text and a matrix of plain text.
Here is some example code from when the field should be overwritten. After this, the old data is actually removed so I assume that it should get collected either way I overwrite this?

The main things which could give you some insight is the end of the code I thing where $blocks get set and overwrites the buildings. The buildings is a neo field of a matrix of plain text fields in the row and a field of plain text

![Screenshot 2023-06-21 at 11 39 25](https://github.com/spicywebau/craft-neo/assets/30866096/4a4909dc-4a92-4e6b-bcaf-277729e7c04e)
![Screenshot 2023-06-21 at 11 39 40](https://github.com/spicywebau/craft-neo/assets/30866096/3540495a-cfc3-4006-97a2-7cc4bf91c39f)
![Screenshot 2023-06-21 at 11 39 45](https://github.com/spicywebau/craft-neo/assets/30866096/26d212e0-02c8-4c7e-a443-acd7c4017a6e)
