### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by JshGrn** [spicywebau/craft-neo#758]
### Bug Description

Running migration causes the below:

<details><summary>Details</summary>
<p>

*** applying m220409_142203_neoblocks_owners_table
    > dropping {{%neoblocks_owners}} if it exists ... done (time: 0.000s)
    > create table {{%neoblocks_owners}} ... done (time: 0.036s)
    > add foreign key craft_fk_lfpxtuznmhbjbubdtjxhykqzpapdbmiciyol: {{%neoblocks_owners}} (blockId) references {{%neoblocks}} (id) ... done (time: 0.126s)
    > add foreign key craft_fk_xxrnqnoobigslyyqtdcdzvpjweehapycghwe: {{%neoblocks_owners}} (ownerId) references {{%elements}} (id) ... done (time: 0.032s)
    > execute SQL: INSERT INTO {{%neoblocks_owners}} ([[blockId]], [[ownerId]], [[sortOrder]])
SELECT [[id]], [[ownerId]], COALESCE([[sortOrder]], 1)
FROM {{%neoblocks}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db`.`craft_neoblocks_owners`, CONSTRAINT `craft_fk_xxrnqnoobigslyyqtdcdzvpjweehapycghwe` FOREIGN KEY (`ownerId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE)

</p>
</details> 

### Steps to reproduce

1. run composer update to update to the latest neo (from craft 3 latest version)
2. run php craft up
3. wait for neo migration to fail

### Expected behaviour

Should migrate without failure by handling foreign key checks

### Neo version

3.7.12

### Craft CMS version

4.4.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I haven't seen this happen, but there was a similar issue with Matrix fields https://github.com/craftcms/cms/issues/13121 so this must be the Neo equivalent bug. I've applied that fix to the equivalent Neo migration in the 3.8 branch. Neo 3.8 should be out next week, I'll update here when it happens. In the meantime, you can apply the fix by generally following the instructions from https://github.com/craftcms/cms/issues/13121#issuecomment-1522484796, except for the change to your `composer.json` being the change of your `spicyweb/craft-neo` requirement to `3.8.x-dev as 3.7.12`.

**Comment by ttempleton** [comment]
Just released Neo 3.8.0 with the fix for this.
