### ISSUE TITLE
User / User Groups permissions not working

### ISSUE THREAD

**Issue by joelod** [spicywebau/craft-neo#759]
### Bug Description

When I set Neo related user permissions to an user or user group, the user can still create and/or remove Neo blocks, even if those two options are not enabled.

### Steps to reproduce

1. Create a Neo type field with multiple block types (as admin)
2. Add blocks to an entry that has that field (created in 1.) and save (as admin)
3. Create User Group for editors ("Editors") with only the "Edit" checkbox enabled on all block types (in Neo type field created in 1.)
4. Login as a new user with "Editors" permission
5. Edit the entry saved in 2.
6. Create, Remove and sort the blocks added by the admin, even without permissions to do it

### Neo version

3.7.12

### Craft CMS version

4.4.14

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
The removal of create/delete options for Neo blocks is working as expected for me. Is the 'Ignore Permissions' setting (under the advanced block type settings) disabled for your block types?

The ability to sort blocks would still be expected to work, though, since that falls under editing the block.

**Comment by joelod** [comment]
> The removal of create/delete options for Neo blocks is working as expected for me. Is the 'Ignore Permissions' setting (under the advanced block type settings) disabled for your block types?
Was enable! I wasn't aware of this setting, it kind of solved the issue. But now I'm still able to clone a block. And also, when I click in "Add a block above", some type of bug seems to happen that makes all the blocks disappear.

> The ability to sort blocks would still be expected to work, though, since that falls under editing the block.
Ok I see thanks, wasn't aware of that.

**Comment by ttempleton** [comment]
> But now I'm still able to clone a block. And also, when I click in "Add a block above", some type of bug seems to happen that makes all the blocks disappear.

Thanks for pointing those out, completely forgot to remove those options 😅
That's fixed now in the 3.8 branch. Hoping to have 3.8 released early next week but will update here when it happens.

**Comment by ttempleton** [comment]
Just released Neo 3.8.0 with the fix for this.
