### ISSUE TITLE
Migration Failure When Updating/Downgrading between 3.7.9 and 3.7.12

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#760]
### Bug Description

I'm seeing the following error in the migration stage when trying to run updates to a staging site I have set up:

> Applying changes from your project config files ...
> - removing matrixBlockTypes.7a8209a6-1eda-4933-a928-e7bbfb9ad98f.fieldLayouts.667e515a-d531-4130-9272-617b98cbcc3b.tabs.0.elements.0 ... 
>   - removing matrixBlockTypes.7a8209a6-1eda-4933-a928-e7bbfb9ad98f ... done
>   done
> - removing matrixBlockTypes.53e04b39-f0c0-4047-a3ad-b77fe60d31f0.fieldLayouts.5012d86f-71cd-4517-adca-7d4e64e69b6b.tabs.0.elements.0 ... 
>   - removing matrixBlockTypes.53e04b39-f0c0-4047-a3ad-b77fe60d31f0 ... 
> **error: Getting unknown property: benf\neo\Field::contentTable**
>     - updating dateModified ... done
>     - removing meta.__names__.7a8209a6-1eda-4933-a928-e7bbfb9ad98f ... done
>     - removing meta.__names__.53e04b39-f0c0-4047-a3ad-b77fe60d31f0 ... done

I also tried reversing the updates and then re-running them, but when I reversed the update I got the same error. To reverse I restored the DB from a backup, changed the composer json file back to it's previous versions, ran composer update and rebuilt the config and then pushed everything, and I got the error again. Can you help me to troubleshoot?

### Steps to reproduce

Try upgrading from Neo 3.7.9 to 3.7.12.

### Neo version

3.7.9, 3.7.12

### Craft CMS version

4.4.13-4.4.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
That's pretty strange - it looks like it's happening during Matrix block type deletion which made me think that a Matrix field had been changed to a Neo field, but the Matrix block type deletion process is supposed to [check that the parent field is actually a Matrix field](https://github.com/craftcms/cms/blob/4.4.14/src/services/Matrix.php#L419) before accessing `contentTable`, and that is working as expected for me.

At this point I can't say for certain whether this is a Craft or Neo bug. If possible, could you please send in to plugins@spicyweb.com.au your composer.json/lock files, database backup from the staging environment, and project config files you're trying to apply, and we'll have a look.

**Comment by brianrivet-tilt** [comment]
Sorry for the delay in response. I've sent the requested files to the email address requested.

**Comment by ttempleton** [comment]
Thanks for sending those files in. I can confirm based on the existing project config that the Matrix block type `53e04b39-f0c0-4047-a3ad-b77fe60d31f0` belonged to what is now a Neo field. The stack trace for the error showed that it happened as a result of actions by the [Blitz](https://github.com/putyourlightson/craft-blitz) plugin while (I assume) old Matrix blocks of that type were being deleted. Disabling Blitz and then applying the project config worked, so at this point I'm assuming this is a bug with Blitz, and that the code they're running when this happens will need to handle cases where Matrix blocks belong to a field that's been converted to a non-Matrix field type.
