### ISSUE TITLE
Converting from a Matrix field

### ISSUE THREAD

**Issue by horizonguides** [spicywebau/craft-neo#762]
### What question would you like to ask?

I've seen question and docs related to converting from Neo back to Matrix. Are there any resources to help convert an existing Matrix field to Neo?

I have a large Matrix field that includes many different blocks/types/fields. I think I've reached the limits and would like to convert it to Neo (regret not using it from the start!). Is there anything that already exists to help?

**Comment by ttempleton** [comment]
No, there's no in-built way to convert Matrix fields to Neo at the moment. It's something I'd like to have in Neo, but the major sticking point for it is Matrix block types having their own fields - meaning we can't guarantee that a global field (or even a field from a different block type within the same Matrix field) with a certain handle doesn't already exist, or that it is the same field type and has been configured in the exact same way.

The only idea I've had to resolve the above is to add something like timestamps or block type IDs to the Matrix subfield handles when creating global fields from them, and require that users clean up any undesired field duplication that does occur as a result - but that feels like far from an ideal solution. I definitely welcome any better ideas that anyone has.

**Comment by horizonguides** [comment]
That's interesting, thanks for the response. As you said, far from an ideal but it feels like a start. I'll have a play with that and if I find anything promising I'll update this thread.
