### ISSUE TITLE
Drag/Drop Causing Errors

### ISSUE THREAD

**Issue by raray** [spicywebau/craft-neo#766]
### Bug Description

Data from fields is removed when dragging-and-dropping while a draft autosave is in-progress.

https://github.com/spicywebau/craft-neo/assets/1738632/bbc836c6-3c58-460f-8670-5237ce83dacb

### Steps to reproduce

1. Add at least two Neo fields to a block.
2. Make a change to one of the fields.
3. While the entry is still auto-saving the draft, reorder the fields via drag-and-drop.

### Expected behaviour

Data should not be lost and the fields should be correctly reordered.

### Neo version

3.8.1

### Craft CMS version

4.4.15

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I wasn't able to reproduce this, but there was potentially a small time between draft autosave and Neo checking which subfields should be visible, where resaving the draft could probably confuse Neo a bit, and I suspect that's what's happened here. I've released Neo 3.8.2 with changes to prevent that. If 3.8.2 doesn't resolve your issue, please if possible send your composer.json/lock files and database backup to plugins@spicyweb.com.au, and let us know which entry you can reliably reproduce this with, and we'll have a look.

**Comment by arne-vdw** [comment]
I have the same issue with Neo version 3.9.11 and Craft CMS version 4.5.12

**Comment by ttempleton** [comment]
@arne-vdw If your issue persists with version 4.0.0, could you please open a new issue with detailed steps to reproduce.

**Comment by arne-vdw** [comment]
@ttempleton As requested, I have created a [new ticket](https://github.com/spicywebau/craft-neo/issues/823) for the above mentioned issues

**Comment by raray** [comment]
I apologize for failing to respond to this ticket. As far as I am aware, the previous fix resolved our issue.
