### ISSUE TITLE
Neo causing issues with slideout modals

### ISSUE THREAD

**Issue by mediabeastnz** [spicywebau/craft-neo#767]
### Bug Description

We're getting a strange issue on a production Craft site which seems to be caused by a Neo error when saving/updating content within a slideout modal.

The following trace is what we see in our logs but isn't super helpful.

I'm unsure what would cause this - we're using Neo to build page blocks and that is all.

```2023-07-12 22:44:26 [web.ERROR] [yii\web\HttpException:400] Request missing required body param 
{
    "trace":
        ["
#0 /container/application/vendor/spicyweb/craft-neo/src/controllers/Input.php(197): craft\\web\\Request->getRequiredBodyParam('siteId')","
#1 [internal function]: benf\\neo\\controllers\\Input->actionUpdateVisibleElements()","
#2 /container/application/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","
#3 /container/application/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","
#4 /container/application/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('update-visible-...', Array)","
#5 /container/application/vendor/craftcms/cms/src/web/Application.php(304): yii\\base\\Module->runAction('neo/input/updat...', Array)","
#6 /container/application/vendor/craftcms/cms/src/web/Application.php(607): craft\\web\\Application->runAction('neo/input/updat...', Array)","
#7 /container/application/vendor/craftcms/cms/src/web/Application.php(283): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))","
#8 /container/application/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","
#9 /container/application/public/index.php(12): yii\\base\\Application->run()","#10 {main}"],
    "memory":3415648,
    "exception": "[object] (yii\\web\\BadRequestHttpException(code: 0): Request missing required body param at /container/application/vendor/craftcms/cms/src/web/Request.php:913)"} 
```

<img width="394" alt="Screenshot 2023-07-13 at 12 51 59 PM" src="https://github.com/spicywebau/craft-neo/assets/909749/dc417514-7930-49ea-97b6-29988a1f79fc">

### Steps to reproduce

1. install neo
2. make a field with neo
3. try saving content using Craft's slideout modals
4. in production

Using Craft 4.4.15 and Neo 3.7.6

### Expected behaviour

entry is saved as expected.

### Neo version

3.7.6

### Craft CMS version

4.4.15

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - it turned out we weren't sending back the site ID when checking which Neo subfields should or shouldn't be showing based on any conditions set. Fixed for the next release.

**Comment by ttempleton** [comment]
Just released 3.8.2 including the fix for this bug.

**Comment by mediabeastnz** [comment]
Hey @ttempleton I installed this version and cleared caches, etc etc but still seem to have the issue on production :/

Any other ideas or things we might need to change?

**Comment by ttempleton** [comment]
Does that only happen in the production environment?

Is the stack trace the same or different in any way? Just wondering if there's a different server error that's also causing this.

**Comment by mediabeastnz** [comment]
I can't find anything in the logs now that point to NEO or any other plugin for that matter. I might open this on Craft as well.
Feel free to close this (i'll report back).

**Comment by ttempleton** [comment]
No worries, happy to reopen if it turns out to still be Neo-related.
