### ISSUE TITLE
Neo gets stuck in an endless loop deleting old structures when using a DB cluster

### ISSUE THREAD

**Issue by JoshCoady** [spicywebau/craft-neo#768]
### Bug Description

We are currently running Craft 3.8 and Neo 2.13.16 in production and I am working on upgrading to Craft 4 and Neo 3. We run Craft in AWS fully serverless with ECS Fargate and RDS serverless and have been running it that way for years.

In testing the upgrades, we noticed that publishing (applying draft) fails most of the time but occasionally works and after publishing fails, other things start to fail also because of an open transaction:
```
[web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
```

We eventually figured out that publishing wasnt actually failing, the request to publish was just timing out, but there was still DB changes happening.

So I monitored the open transactions with the following query and noticed that a transaction is started about the time publish is initiated and it remains open for 30-60 min.
```
SELECT p.*, trx_query, t.*
FROM information_schema.innodb_trx t
    JOIN information_schema.processlist p ON t.trx_mysql_thread_id = p.id
```

I turned on query logging and noticed it is basically stuck in a loop executing this sequence over and over:
```
2023-07-12T05:43:58.518774Z   39 Query	SELECT `id`, `structureId`, `ownerId`, `siteId`, `fieldId`
FROM `craft_neoblockstructures`
WHERE (`fieldId`=X) AND (`ownerId`=Y) AND (`siteId`=Z)
LIMIT 1
2023-07-12T05:43:58.519783Z   39 Query	SAVEPOINT LEVEL3
2023-07-12T05:43:58.520874Z   39 Query	DELETE FROM `craft_structures` WHERE `id`=W
2023-07-12T05:43:58.521920Z   39 Query	DELETE FROM `craft_neoblockstructures` WHERE (`id`=W) AND (`ownerId`=Y) AND (`siteId`=Z) AND (`fieldId`=X)
2023-07-12T05:43:58.522980Z   39 Query	RELEASE SAVEPOINT LEVEL3
```

I tracked this down as likely being related to this code (and/or other similar snippets) first introduced in Neo 3.6.3:
```php
// Delete any existing block structures associated with this field/owner/site combination
while (($blockStructure = Neo::$plugin->blocks->getStructure($field->id, $owner->id, $siteId)) !== null) {
    Neo::$plugin->blocks->deleteStructure($blockStructure, true);
}
```

So I downgraded Neo to 3.6.2 and we do not have the publishing issue with 3.6.2. I then upgraded to 3.6.3 to confirm it was not anything after that since we downgraded from 3.8.0, but we did not have the issue in  3.6.3 either. So I proceeded to test the intervening versions and it looks like the issue was introduced in 3.7.8. So maybe it was the addition of the hard delete param to that loop?

I think the underlying issue is this loop has no safety checks against running indefinitely. There should be a failsafe built in here such that each structure is only ever attempted to be deleted once. On the surface, this loop looks like it should not be infinite, but it makes at least two assumptions:
1. The delete did not silently fail
2. The delete is acting on the same data source as the get

I'm pretty sure the issue we are experiencing is due to #2. When using a database cluster, there is no guarantee that read queries are run against the same database instance that write queries are run against. They are eventually consistent, but not always immediately.

I propose switching these while loops to foreach to guarantee that they only ever act on each structure once.

For example if we add this funciton to src/services/Blocks.php
```php
public function getStructures(int $fieldId, int $ownerId, ?int $siteId = null): ?BlockStructure[]
{
    $blockStructures = [];

    $query = $this->_createStructureQuery()
    ->where([
    'fieldId' => $fieldId,
    'ownerId' => $ownerId,
    'siteId' => $siteId,
    ]);

    $results = $query->all();

    foreach ($results as $result) {
        $blockStructures[] = new BlockStructure($result);
    }

    return $blockStructures;
}
```

And then change the while loop to a foreach:
```php
// Delete any existing block structures associated with this field/owner/site combination
$blockStructures = Neo::$plugin->blocks->getStructures($field->id, $owner->id, $siteId);
foreach ($blockStructures as $blockStructure) {
    Neo::$plugin->blocks->deleteStructure($blockStructure, true);
}
```

Since the structure itself is lazy-loaded, each of these should only take up memory for 5 ints plus a bit of overhead, so I think somewhere around 50-100 bytes, but let's make that way higher and call it 1 KB. In that case, even if there are 10000 structures for this field/owner/site combination it would only take up 10 MB of memory. So I think it is safe to load them in all at once.

If there are still concerns about loading them all, the code could be changed to query for just the IDs and then loop over each ID. That would be another way to only attempt to delete the same structure once.

### Steps to reproduce

Prerequisite: Setup Craft on a clustered/load-balanced DB service (in our case AWS RDS Aurora Serverless v1 with MySQL 5.7)

1. Create a draft from an existing entry
2. Make a minor edit and wait for it to auto save (I dont know if this part is necessary, but I kept doing it for consistency -- the edit I made was to a plain text field, not to a neo field)
3. Publish the draft

The publish ends up timing out, then if you check the DB it is stuck in the loop described above.

I only ever tested this sequence, so I dont know if there are other things that might trigger it.

### Expected behaviour

The publish completes successfully without timing out and without locking the database in a transaction that stays open for upwards of an hour.

### Neo version

3.7.8

### Craft CMS version

4.4.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
That while loop's in there due to an old bug with the Craft 2 version of Neo where you could end up with more than one block structure for an owner/field/site combination - the loop might not even need to be there anymore, but if it does, I'm happy to change it to a foreach loop as you've suggested. I'll be able to have a look at that on Friday.

**Comment by JoshCoady** [comment]
Great, thanks!

**Comment by ttempleton** [comment]
@JoshCoady I've made the change to a foreach solution in the 3.x branch - could you please change your  `composer.json` file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.8.2`, run `composer update` and let me know if that resolves the issue?

**Comment by JoshCoady** [comment]
Thank you. I have confirmed that it resolves the issue. I did a test with 3.7.7, did not have the issue. Upgraded to 3.7.8 and confirmed it did have the issue. Then upgraded to 3.x-dev and no longer had the issue.
