### ISSUE TITLE
Project config block type YAML `description` field is inconsistent

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#770]
### Bug Description

I'm reviewing a pull request now which changes some Neo block types. A lot of files are altered which just change a `description: ''` to `description: null`.

It's an annoyance, since it adds noise.

It's not the first time I've seen this. I've also seen the opposite change: from `description: null` to `description: ''`.

It seems like some operations set it one way and other set it the other way, though I have not narrowed down the specifics.

### Steps to reproduce

(This is a guess)

1. Make a new neo field.
2. Look at `description` of `.../config/project/neoBlockTypes/*.yaml`
3. Add a new block type
4. Look again at description, it may have changed pointlessly.

### Expected behaviour

Stability on files which haven't changed in a meaningful way.

### Neo version

3.8.2

### Craft CMS version

4.4.14

### What is the affected Neo field's propagation method?

"Save blocks to all sites the owner element is saved in"

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by tremby** [comment]
The message above originally said that I've seen it go from `''` to `null` but I wasn't sure if I'd seen it change from `null` to `''`. Well I just saw it go the other way, from `null` to `''`. I think the only action I took was altering which child blocks are permitted within a particular parent block.

**Comment by tremby** [comment]
Right now, with project config in sync, I renamed a neo block (both its name and its handle).

I checked the yaml files right after.

- A different block ("A") which allowed the renamed block as a direct child changed its description from `''` to `null`.
- Another different block ("B") which allows no children changed its description from `''` to `null`.
- A yaml file which represented the renamed field was deleted. The old description was `null`.
- A new yaml file which respresents the renamed field was created. The description is `''`.

I then went back to neo and after making no changes at all hit save.

- Only now did the old name of the renamed block disappear from the allowed children list of one block. (This seems like a different bug.)
- Block "A" from above changed its description from `null` to `''`.
- The renamed block changed its description from `''` to `null`.
- Block "B" from above changed its description from `null` to `""`.

I then went back and again made no changes and hit save.

- Block "A" changed back to `null`.
- Block "B" changed back to `null`.

One more time: now no further changes.

Next I made a single change: adding my renamed block back to the list of allowed children of block "A":

- Block "A" changed back to `''`.

Saved again with no changes:

- Block "A" changed back to `null`.

Again: no changes.

Edited a different block, renaming its handle but not its name.

- Yaml file deleted, description was `null`.
- Yaml file created, description is `''`.

Save with no changes: changed to `null`.
Save with no changes: no change.

Added the latest renamed block as an allowed child of the previously renamed block.

- Only now did the old name of the newly-renamed block disappear from the list of allowed children.
- New name is added to its allowed children list.
- Description of that same parent changes to `''`.

Save again with no changes: changes to `null`
Again: no change.

Hopefully this helps.

**Comment by ttempleton** [comment]
Thanks for reporting - should now be consistently saving as `''` in Neo 3.8.4.

**Comment by tremby** [comment]
I'm currently on version 3.9.10 and this popped up again.

A bunch of neo block types' definitions just flipped their descriptions from `null` to `''` after I edited one block.

**Comment by ttempleton** [comment]
I'm guessing that those block types were last edited prior to the bug being fixed (hence still being set to `null`), in which case that sounds like the fix is working as expected.

If there's another case where descriptions are able to be set to `null`, please feel free to open a new issue with detailed steps to reproduce.
