### ISSUE TITLE
Block content disappears

### ISSUE THREAD

**Issue by davidwebca** [spicywebau/craft-neo#771]
### Bug Description

We developed a website for our client and recently there are blocks made with craft-neo that randomly disappear. They’re never the same and seemingly just become removed altogether. They also don’t exist in the history of the page so it’s impossible to rollback. They seem to disappear randomly when we haven’t even made any change to the website but that is to confirm.

I’ve looked through the GitHub issues and tried to learn about the different times this issue happened in the past and they don’t seem to apply to our case.

We use multiple languages and added a third one lately, but have yet to enter new content so it shouldn't be related to that.

### Steps to reproduce

1. Create content
2. Add new languages
3. Save entries 

Some blocks completely disappear from the page and even from previous versions of the page in the history.

### Expected behaviour

The content should stay or at least be preserved in the save history.

### Neo version

3.7.12

### Craft CMS version

4.4.14

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, along with information about which entry this happens with, and we'll have a look at it.

**Comment by davidwebca** [comment]
Sent!

**Comment by ttempleton** [comment]
It doesn't look like we've received that email - could you please confirm that it's been sent to the correct address?

**Comment by ttempleton** [comment]
Thanks @davidwebca we have received those files. Unfortunately I can't reproduce the issue yet, but I see that the revisions with missing Neo blocks on the affected site don't seem to have any block structure data left in the database... My best guess, based on that, is that when creating the new site and copying existing content over to the new site, Neo has mistakenly _moved_ its content to the new site instead of copying it. Trying that with another new site seems to be working as expected for me, though.

I might test this a bit more with other entries I haven't tried yet, and see if I can figure it out.

**Comment by davidwebca** [comment]
Hi! I'm back from vacation, sorry for the delay. 

The only thing I see is that a cron or scheduled job would cause fields to be out of sync? But how would the content of the entrie's history be deleted from the database too then? 🤔 I'm just as confused as you. 

If you need it, I can give you access to the full website live.

**Comment by davidwebca** [comment]
It actually happened again just today on even more pages. 😫  I'll send more details if/when I find something.

**Comment by mjniland1** [comment]
I'm unsure if this is related to the same issue, but we've also been experiencing disappearing neo-blocks. It usually occurs when a user changes the sort order of the blocks. I'd be happy to send over any project files if necessary.

https://github.com/spicywebau/craft-neo/assets/56364768/6d3d40a2-476c-4c6f-9ba9-0f3ed49b5b11

**Comment by ttempleton** [comment]
@davidwebca Maybe a silly question but these aren't cases where the entries have been deleted and restored, are they? I've recently been made aware of a bug where Neo content for a deleted entry and its revisions isn't being restored with the owner entry, so thought I'd ask just in case.

@mjniland1 Could you please send the DB backup and composer.json/lock files to plugins@spicyweb.com.au and we'll have a look.

**Comment by mjniland1** [comment]
Sent!

**Comment by davidwebca** [comment]
I ran ```php craft utils/fix-field-layout-uids``` out of despair after trying everything and it logged this.

```
Looking for duplicate UUIDs ...
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.0.
    Setting to 34add45b-1f0f-4f17-9cea-7793fa541137.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.1.
    Setting to 72c7c4fa-339b-442b-af31-c9a4e713548f.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.2.
    Setting to aefd1c62-02fb-4fcc-8ca5-4f7e5c6bd43a.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.3.
    Setting to f21cd21c-e979-4f84-b8d1-e00afcb8819f.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.4.
    Setting to a3ad1077-3b68-4c22-8781-04d4a7fc2753.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.0.elements.5.
    Setting to 86444b62-addc-4a29-9fe6-be1420898f62.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.1.elements.0.
    Setting to e7e504b9-460a-4ba1-bbe2-6e788e5dd515.
    > Missing UUID at neoBlockTypes.2313f1d8-15b2-4027-baa5-95b3ba5a8dc2.fieldLayouts.eeb078bb-3e0e-4e83-91ae-fbe1197f9e90.tabs.2.elements.0.
    Setting to 831833e2-f9b2-45d9-b3e8-a684383814f1.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.0.
    Setting to b8d5ce66-55d0-40c3-83b9-6d5ab041586f.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.1.
    Setting to e4328ee6-4d87-4c2d-9295-ecfcf6c5d21b.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.2.
    Setting to 24f79969-bd05-40b9-b92c-38581e3dff15.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.3.
    Setting to d1681107-6bab-46a3-85bc-09961ef1e36d.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.4.
    Setting to 584b6e42-ee01-4d4d-9034-05d5e328e38f.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.0.elements.5.
    Setting to dc1f1d67-71a7-4c18-9710-922a47e439dc.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.1.elements.0.
    Setting to 14d0e61d-2102-41c4-849f-ec6a616378d1.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.1.elements.1.
    Setting to 2da47b1e-0f3c-4f11-ae60-43ed7176d8ff.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.1.elements.2.
    Setting to 3a647d9e-8894-41e8-935b-385a0de6c8f0.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.2.elements.0.
    Setting to 01581420-71b2-48aa-b5de-6da4717eee17.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.3.elements.0.
    Setting to e764a21f-561e-4833-8f2f-7e346bec88ad.
    > Missing UUID at neoBlockTypes.affa80f5-448e-40bf-9453-7a29cd5a37ec.fieldLayouts.6e68766d-336a-4525-872b-1650087e03bc.tabs.3.elements.1.
    Setting to 29e80e3a-d972-41b6-b4bc-4ef8cb95a361.
    > Missing UUID at neoBlockTypes.dd9b23f9-f8d4-4fab-b45f-16ac13db1791.fieldLayouts.0209d2ad-b872-4419-b93d-f864468559ff.tabs.0.elements.0.
    Setting to aca14474-af08-4faa-8b04-89c085245d24.
    > Missing UUID at neoBlockTypes.dd9b23f9-f8d4-4fab-b45f-16ac13db1791.fieldLayouts.0209d2ad-b872-4419-b93d-f864468559ff.tabs.0.elements.1.
    Setting to 3fdac492-4662-4381-b0b5-4e4b445bcec3.
    > Missing UUID at neoBlockTypes.dd9b23f9-f8d4-4fab-b45f-16ac13db1791.fieldLayouts.0209d2ad-b872-4419-b93d-f864468559ff.tabs.1.elements.0.
    Setting to 00e0b742-7537-47e5-8547-8ef289339376.
    > Missing UUID at neoBlockTypes.eb809acb-9425-4adf-9ab0-05d934edcb7d.fieldLayouts.a0a2c006-93fe-4786-958f-9b9c381889cf.tabs.0.elements.0.
    Setting to 47682971-6f01-475f-8d6a-3783ea31881f.
    > Missing UUID at neoBlockTypes.eb809acb-9425-4adf-9ab0-05d934edcb7d.fieldLayouts.a0a2c006-93fe-4786-958f-9b9c381889cf.tabs.0.elements.1.
    Setting to ccb8201c-5522-40a4-8d15-08272ad02609.
    > Missing UUID at neoBlockTypes.eb809acb-9425-4adf-9ab0-05d934edcb7d.fieldLayouts.a0a2c006-93fe-4786-958f-9b9c381889cf.tabs.1.elements.0.
    Setting to 639a921e-623a-4f6b-8fd1-e28e180099d6.
Done. Fixed 26 duplicate or missing UUIDs.
```

Am I to understand that all my neoBlockTypes didn't have a UUID? Was it in the database or just in the project yaml files? Can that be the cause of the issue?

**Comment by ttempleton** [comment]
Thanks for sending the files @mjniland1 - that bug looks to specifically affect new blocks that live inside the child blocks UI element. I can't quite figure out how to resolve that yet, so I've split it into a new issue #777.

@davidwebca That looks like the block type's field layout elements didn't have UUIDs, I'm not sure if that would be related to a Craft or other Neo bug, but I don't think it would be related to this bug.

Has this bug ever affected the same entry more than once? And, if possible, could you please send through information about entries that this has recently happened to for the first time? Happy if you want to send that through email, just want to see if there's anything unusual in the database backup for an entry of that kind.

**Comment by ttempleton** [comment]
Hmm, if it's always sub blocks, then maybe it is related to https://github.com/spicywebau/craft-neo/issues/771#issuecomment-1684119330 / #777. I'll assume that for now, but please let me know if it happens again for you after running the UUID fix.

**Comment by davidwebca** [comment]
No news so far since I've fixed the keys and also just updated today to 3.9 so if it was (this)[https://github.com/spicywebau/craft-neo/issues/777#issuecomment-1696800289] it should be fixed too... I guess we can close this for now, but I'll re-ping / open a new one if it happens again with more details if possible. Thanks again!
