### ISSUE TITLE
FeedMe: import nested children blocks

### ISSUE THREAD

**Issue by r0skar** [spicywebau/craft-neo#772]
### What question would you like to ask?

Hei - I have setup a new FeedMe to import content. This works, but it does not seem to work nested/children blocks(?) I have basic layout component that consists of three nested blocks:

```yaml
columns:
  - column_item:
    - column_text
```

When trying to import content for `column_text`, FeedMe creates it as a top-level block (note: the top-level setting is disabled in the field settings), instead of first creating a `columns` parent , adding a `column_item` block and then adding the data as a child.

Thats the JSON I am trying to import:

```json
[
  {
    "ID": "9999",
    "Date": "2020-09-09",
    "Slug": "slug",
    "Title": "Title",
    "Content": [
      {
        "Block": {
          "title": "title",
          "text": "cleanedText"
        }
      },
      {
        "Block": {
          "title": "title",
          "text": "cleanedText"
        }
      }
    ]
  }
]
```

Foreach `Block`, I'd like to create a new child `column_item` block in the `columns` Neo field that in turn contains another child `column_text` with the `text` value.

**Comment by ttempleton** [comment]
Neo fields work with Feed Me in mostly the same way as Matrix fields, with the difference that the Neo block data you provide should also include the level property for each block. An example of how that works can be found [here](https://github.com/spicywebau/craft-neo/blob/3.8.4/docs/feed-me.md).
