### ISSUE TITLE
Transfering entry from one structure without loosing NeoField content

### ISSUE THREAD

**Issue by lexislav** [spicywebau/craft-neo#774]
### What question would you like to ask?

Hi
On a multisite Craft CMS  3.8.16 installation, I need to move entries from one site/structure section to second site/structure section (becouse one site is being removed).

With these following steps I am able to move entries from on site+strucutre to new site+structure, but content of Neofield called pageBuilder is lost. Field itself, tabs etc. seems to be transfered ok.

So my first steps (directly in DB) are:

1) moving entryType to new structure in table **entrytype**
2) in table **field** (id 593) updating groupID to proper sectionID
3) in table **neoblockstructures** update ownerSiteId to all rows with related fieldId (593).

and than  update entries like this:
```
UPDATE `elements_sites` SET `siteId` = 2 WHERE `elementId` = 84227;
UPDATE `content` SET `siteId` = 2 WHERE `elementId` = 84227;
UPDATE `entries` SET `sectionId` = 3 WHERE `elementId` = 84227;
UPDATE `searchindex` SET `siteId` = 2 WHERE `elementId` = 84227;
```

All this got me into a point where after ./craft resave/entries shell command all the entries are moved to the new site, they appear in the structure and they have all fields attached.

But the neo pageBuilder field is empty and no content is transfered with it.

Any idea what else need to be updated to keep content of Neo field attached in the entries when moving like this?

Thanks

**Comment by ttempleton** [comment]
I'd definitely recommend using a [content migration](https://craftcms.com/docs/3.x/extend/migrations.html) to do this, as the save operation on the entry after updating its type, etc. should perform all of the Neo-relevant updates for you.

If you still intend to do this by manually editing database values, could you please send in your composer.json/lock files and database backup (from before starting this process) to plugins@spicyweb.com.au so I can have a look and determine the exact additional operations you'd need to perform.

**Comment by lexislav** [comment]
OK, I will look into it. Thanks!
