### ISSUE TITLE
Fields preparsing at level 3?

### ISSUE THREAD

**Issue by rachelrine** [spicywebau/craft-neo#78]
I've got a block nested at level 3:
Multicolumn > Column > Button

The button block contains a [linkit fieldtype](https://github.com/fruitstudios/LinkIt). The button block (and linkit field) behave as expected at level 1, but at level 3 my field returns only a preparsed link, with no access to the properties that field contains. 

Additionally, the html is not rendering, only displaying as a string in the browser.

**Comment by benjamminf** [comment]
That's a strange issue - blocks at any level should behave identically. Can I see your template code?

In regards to the HTML not rendering, you can use the [raw filter](http://twig.sensiolabs.org/doc/2.x/filters/raw.html) to force it to display as HTML.

**Comment by ttempleton** [comment]
I'm going to close this issue, given its age and no other reports of the issue, but if you do continue to experience the issue, let us know and we'll reopen.
