### ISSUE TITLE
Content is not being saved

### ISSUE THREAD

**Issue by stevendierick** [spicywebau/craft-neo#787]
### Bug Description

There seems to be an issue with Neo 3.9.0 and up.

Content is not being saved, sometimes it'll work on the second attempt. Fields are not being initialized, blocks are being removed when saving, etc. Visually, it also seems to refresh when adding a new block.

I've tested and recorded this with parent and child blocks. And with plain text, asset, Vizy (named "rich text" in my test), and Hyper fields. Also tested it with Craft's Entries field, so it might be an issue for all added fields to Neo blocks.

https://share.cleanshot.com/6pyBfWq50BHKrBQFnv5l

Everything works perfectly fine when downgrading to 3.8.6.

This was originally opened at Hyper but it seems to be an issue with Neo instead:

https://github.com/verbb/hyper/issues/90

### Steps to reproduce

1. Create a Neo field
2. Add a "plain text" (or entry, asset, Vizy, Hyper,...) field to Neo
3. Add Neo field to a section
5. Add content to Neo blocks and fields
6. Save 

### Neo version

3.9.1

### Craft CMS version

4.5.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Whoops, looks like I'd forgotten to namespace new blocks when we lazy load the block type's field layout HTML. Thanks for reporting the bug, that's fixed now in 3.9.2.

**Comment by stevendierick** [comment]
There might still be an issue. Vizy won't initialize:

https://github.com/verbb/vizy/issues/260
