### ISSUE TITLE
Cannot add blocks with Vizy fields since 3.9.x 

### ISSUE THREAD

**Issue by scandella** [spicywebau/craft-neo#788]
### Bug Description

Since upgrading to Neo 3.9.x I can no longer create blocks with Vizy fields in it. 
JS error appears when pushing the add button.
`axios.js?v=1695756066:2     POST http://localhost:8888/pang/dev/web/index.php?p=admin%2Factions%2Fneo%2Finput%2Frender-blocks&v=1695756830224 500 (Internal Server Error) `
`Input.js:1149 Uncaught (in promise) o {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}`

Downgrading to 3.8.6 solved the issue.

### Steps to reproduce

1. Upgrade to Neo 3.9.x
2. Create a Neo field
3. Add a Vizy field in it
4. In a section, try to add an entry to this Neo Field

### Neo version

3.9.2

### Craft CMS version

Craft Pro 4.5.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Fixed for the next release - see https://github.com/verbb/vizy/issues/260#issuecomment-1736518993 for an explanation of what caused this.

**Comment by ttempleton** [comment]
Neo 3.9.3 has now been released.
