### ISSUE TITLE
What do neo block permissions do?

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-neo#795]
### What question would you like to ask?

Neo adds permissions for each block type - add, remove edit. But why are they needed? I have not selected any of these permissions for my user and yet i can add delete and edit blocks in neo field assigned to entries.

**Comment by ttempleton** [comment]
Those block types might have their 'Ignore Permissions' setting enabled (under 'advanced' in the block type settings). That setting is enabled by default, which is not really ideal, but when block type permissions were first introduced, it was necessary to have it to work around the permissions not being selected by default.

Permissions are still not selected for users by default - I haven't looked into how complicated it would be to implement that, but it's consistent with what happens e.g. with new Craft Commerce product types - but having Ignore Permissions enabled by default for new block types might have served its purpose by now and I'll consider having it disabled by default in future releases.
