### ISSUE TITLE
Add new native field "sub-blocks"

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-neo#798]
### What would you like to see added to or changed in Neo, and why?

This native field would allow sub-blocks to be placed within field layout tab, instead of always showing sub-blocks below field tabs.

Recently i had issue where all my blocks had two tabs, one for regular fields and other for blocks settings, like for example color scheme or padding top/bottom, which were common for all blocks.

One of the blocks had no regular fields of its own in "fields" tab, just ability to have some sub-blocks. So to still display fields tab, i had to place line separator here (because empty tabs are not displayed).

It would be better in that situation to just have ability to stick sub-blocks into fields tab.

**Comment by ttempleton** [comment]
The 'Child Blocks' UI element can be used for this purpose.
