### ISSUE TITLE
Entries from wrong site are displayed in "Entries" field in Neo block

### ISSUE THREAD

**Issue by geertvansoest** [spicywebau/craft-neo#800]
### Bug Description

After upgrading to the latest version (3.9.4) we were facing an issue when we want to select related entries inside a Neo block. While editing an English entry, in the modal with related entries Dutch items (which is the primary site) were shown.

We figured out this issue is only relevant for "new" Neo blocks. Once we reload the edit page and we want to select related entries in an "existing" Neo block, entries from the right site are shown.

In the video below you can see the right (English) entries are shown in the first block, which already exists. In the exact same block which we added later Dutch entries are shown.

https://github.com/spicywebau/craft-neo/assets/6870951/b26adce3-71f0-4086-bbf3-8fef4cd7dd01

For now we fixed this issue by downgrading to 3.8.6.

### Steps to reproduce

1. Create a new or edit an existing entry in the "non primary" site
2. Add a Neo block having an "Entries" field

### Neo version

3.9.4

### Craft CMS version

4.5.6.1

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

**Comment by ttempleton** [comment]
Guessing I missed another spot with the new block lazy loading 😅

I'm not at my dev machine at the moment, but you should be able to work around it on the latest version by setting the `enableLazyLoadingNewBlocks` plugin setting to `false` in your Craft project's `config/neo.php` file.

**Comment by ttempleton** [comment]
That should be fixed now in 3.9.5.
