### ISSUE TITLE
Button Box Elements Missing When Creating New Rows

### ISSUE THREAD

**Issue by adrianjean** [spicywebau/craft-neo#802]
### Bug Description

Issue:
- [Button Box](https://plugins.craftcms.com/buttonbox?craft4) elements are missing when creating **new** blocks/rows
- Existing entries with Button Box elements show fine. 

Behaviour started at version 3.9.3 of NEO.

CraftCMS: 4.5.6.1
NEO: 3.9.3

### Steps to reproduce

1. Create a field for a Button Box element
2. Add it to NEO
3. Create a new row/block in a NEO element that contains the Button Box field. 
4. Note that the ButtonBox element isn't being loaded

### Neo version

3.9.3

### Craft CMS version

4.5.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by adrianjean** [comment]
...... Super Table was updated recently, and I have ButtonBox elements, inside a SuperTable, in a NEO block. Wonder if that's related.

**Comment by ttempleton** [comment]
This looks to have the same cause as #790 and is fixed in 3.9.4.

**Comment by adrianjean** [comment]
Yup! — confirmed it's fixed now!
