### ISSUE TITLE
array_map(): Argument #2 ($array) must be of type array, null given in vendor/spicyweb/craft-neo/src/validators/FieldValidator.php in array_map at line 161

### ISSUE THREAD

**Issue by boboldehampsink** [spicywebau/craft-neo#804]
### Bug Description

See stacktrace: https://kotter-living-cms.sentry.io/share/issue/5c893ff810c24d279994ebe39449dfee/

### Steps to reproduce

I don't know how to reproduce since a client stumbled on to it, but I have attached the sentry log with stacktrace

### Neo version

3.9.5

### Craft CMS version

4.5.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this, and honestly a bit stumped as to what could have caused it. If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au along with information about which entry this happened with? If so, I'll see if I can work out the cause from there.

**Comment by boboldehampsink** [comment]
@ttempleton I can't reproduce it either. Maybe just play safe and add some null checks?

**Comment by ttempleton** [comment]
Fair enough - have made that change in Neo 3.9.6.
