### ISSUE TITLE
Blocks are garbage cleaned even after restoring entry

### ISSUE THREAD

**Issue by boboldehampsink** [spicywebau/craft-neo#806]
### Bug Description

Yesterday I removed a page with blocks, then restored it. Looked fine. Then last night garbage collection ran, and now the blocks seem to have dissappeared!

### Steps to reproduce

1. Create page with blocks
2. Remove page
3. Restore page
4. Run garbage collection (craft gc/run)

### Expected behaviour

Blocks should still be there

### Neo version

3.9.5

### Craft CMS version

4.5

### What is the affected Neo field's propagation method?

all

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - When I follow these steps, the live entry's blocks are still there, but the revision blocks have disappeared. Is there any chance you've applied a revision at some point during this process?

**Comment by boboldehampsink** [comment]
Yes it could very well be

**Comment by ttempleton** [comment]
I've fixed the issue with revisions in 3.9.7. I'll consider this resolved for now, but please let me know if it happens again on the live entry.

**Comment by boboldehampsink** [comment]
Thanks!
