### ISSUE TITLE
Neo block condition not working on initial conditional render

### ISSUE THREAD

**Issue by nicolascnudde** [spicywebau/craft-neo#807]
### Bug Description

When using Neo block conditions, sometimes the field won't render. See the steps to reproduce for detailed info.

### Steps to reproduce

1. Create 3 new fields: 1 lightswitch toggle or dropdown with 2 options + 2 other fields. Lightswitch default is false and dropdown default value is A.

2. Add a new block type in the Neo field, go to Field Layout and add the 3 newly created fields.

3. Add Neo Block Conditions to the 2 fields that aren't the lightswitch/dropdown type, one to show when the lightswitch is false or dropdown value is A (default state) and the other one to show when the lightswitch is true or the dropdown value is B.

![Screenshot 2023-10-19 at 11 05 22](https://github.com/spicywebau/craft-neo/assets/72446674/31d44e88-d30e-480e-a86c-f1531372afea)

![Screenshot 2023-10-19 at 11 05 28](https://github.com/spicywebau/craft-neo/assets/72446674/83650398-c929-4c39-a482-ba42257175ac)

4. Go to entries and add the Neo block type, by default the false/A conditionally field is shown.

![Screenshot 2023-10-19 at 11 03 58](https://github.com/spicywebau/craft-neo/assets/72446674/280f0230-d499-4cb0-8d8b-a1f0e34bcb70)

6. Toggle the lightswitch to true or change the dropdown value to B. Now neither fields will be shown, only the lightswitch/dropdown field.

![Screenshot 2023-10-19 at 11 03 38](https://github.com/spicywebau/craft-neo/assets/72446674/cf1f0e82-d941-4c83-b000-699bd6892a04)

7. Toggle to lightswitch to false and back to true or change the dropdown to A and back to B, and now the field is displayed correctly.

![Screenshot 2023-10-19 at 11 03 49](https://github.com/spicywebau/craft-neo/assets/72446674/011f2860-bc45-408c-be6f-8d1ca531f128)

### Neo version

3.9.5

### Craft CMS version

4.5.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release.
