### ISSUE TITLE
Nested Blocks lost on `craft resave/entries`

### ISSUE THREAD

**Issue by denisyilmaz** [spicywebau/craft-neo#812]
### Bug Description

When running `craft resave/entries` in the console the hierachy of neoblocks is lost and all children of a block are now on level 0.

### Steps to reproduce

1. create a neo block with one block on level 0 and subblocks as children
2. create an entry where you use the block and several children
3. run `craft resave/entries`
4. check the entry again, the children are now on the same level as the parent block

### Neo version

3.9.8

### Craft CMS version

4.5.10

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this - but do you also use the Preparse Field plugin? That plugin is known to have caused [loss of Neo block structure data](https://github.com/craftcms/cms/issues/13256), among other Neo content loss issues that have caused us to [document Preparse Field as being incompatible with Neo](https://github.com/spicywebau/craft-neo/blob/857175332fd821b1794f6495a0241bccc476ad5e/docs/plugin-compatibility.md).

**Comment by denisyilmaz** [comment]
Thanks for bringing that limitation to my attention. We were not aware of that Preparse Field bug and it is actually what is causing the described problem as we use a "Anchor ID" preparse field on all our section blocks... hm, not taking more of your time, but do you, by any chance, have a alternative to preparse field that is compatible with neo?

**Comment by ttempleton** [comment]
I forgot that there was some suggestion a while ago that issues with Preparse Field and Matrix fields could be resolved by cloning the block query given as the Matrix field value before using it (https://github.com/besteadfast/craft-preparse-field/issues/36), and that potentially this could resolve issues with Neo as well (https://github.com/spicywebau/craft-neo/issues/429#issuecomment-778287459) - but those discussions involved Craft 3, and I'm unsure if it's still the case with Craft 4. I think it's worth trying, at least (and if you do try it and it works, please let me know, and I'll update the documentation to reflect that).

If you try the above and it doesn't work, are you able to share the Preparse field contents and I'll try to work out exactly how the block structure data is being lost?
