### ISSUE TITLE
Performance issues after migration to craft 4.5.10

### ISSUE THREAD

**Issue by thomas-jaeger** [spicywebau/craft-neo#819]
### Bug Description

I'm not sure if it's a Neo bug or a bug at all, but since migrating to Craft 4.5.10, we've been experiencing serious performance issues on the database (thousands of calls) when opening sections in the backend editor. We even suspect that there are also infinite loops (some methods are not completing). In the profiler, we tracked this down to validation:
If we disable the validateRelatedElements flag on used fields in neo fields, the database performance improves significantly. However, we have also noticed that the infinite loop is related to the craft commit ae45e59 (Stop validating related elements recursively): if you revert the change, validation still takes a while but completes.
Any ideas? Should we more carefully choose the validation flag or is there an issue?

### Steps to reproduce

Reproducible with our model. I can provide it if necessary.

### Neo version

3.9.11

### Craft CMS version

4.5.10 and 4.5.11.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm guessing this is related to https://github.com/craftcms/cms/issues/14033 so will close this issue for now. I'll reopen it if there are still Neo-specific performance issues after that issue is resolved, though.

**Comment by thomas-jaeger** [comment]
Yes, it's now fixed. Sorry for the late response.
