### ISSUE TITLE
Conditional Fields do not show when using Neo in Solspace Calendar events

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#820]
### Bug Description

I use a "content-builder" build with Neo. On many blocks, there is a lightswitch that (if enabled) will display a couple of conditional fields with more options for that block. 
On normal entries this works perfectly fine. However, on Solspace calendar events, the conditional fields (condition benign `lightswitch == on`) are not shown.

### Steps to reproduce

1. Create a Neo field with a block with a textfield (A), a dropdown (B) and a lightswitch (C)
2. Apply conditional rules to field A and B, so that they only show when C is active.
3. Use this Neo field in a solspace calendar event
4. Add a new event, add the Neo block, turn on C, and see that fields A and B are not shown.

### Expected behaviour

I expected it to work like on all other entries: Show fields A and B when you turn the lightswitch C to "on". 

### Neo version

3.9.11 (latest)

### Craft CMS version

Craft Pro 4.5.11.1 (latest)

### What is the affected Neo field's propagation method?

Save to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
It turns out that a discussion on the Calendar repository already exists: https://github.com/solspace/craft-calendar/discussions/164
