### ISSUE TITLE
Failed Queue jobs: invalid owner ID

### ISSUE THREAD

**Issue by lenvanessen** [spicywebau/craft-neo#821]
### Bug Description

We have a lot of jobs failing due to a error message "invalid owner ID". It's caused by the Craft Scout plug-in, so maybe the resolution should be there. But i believe it could be as simple as returning a null on getOwner() like suggested by @mmikkel in #724 

If this approach is not feasible can you let me know what needs to be addressed from studioespresso's scout plug-in?
Thanks.

Our stack trace:
2023-12-18 23:00:57 [queue.ERROR] [yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 19887 in /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php:412
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(443): benf\neo\elements\Block->getOwner()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(484): craft\helpers\ElementHelper::rootElement(Object(benf\neo\elements\Block))
#2 /var/www/html/vendor/studioespresso/craft-scout/src/behaviors/SearchableBehavior.php(180): craft\helpers\ElementHelper::isDraftOrRevision(Object(benf\neo\elements\Block))
#3 [internal function]: rias\scout\behaviors\SearchableBehavior->shouldBeSearchable()
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2223): yii\base\Component->__call('shouldBeSearcha...', Array)
#6 /var/www/html/vendor/studioespresso/craft-scout/src/Scout.php(194): craft\base\Element->__call('shouldBeSearcha...', Array)
#7 [internal function]: rias\scout\Scout->rias\scout\{closure}(Object(craft\events\DeleteElementEvent))
#8 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\DeleteElementEvent))
#9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#10 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2058): yii\base\Component->trigger('beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#11 /var/www/html/vendor/spicyweb/craft-neo/src/jobs/DeleteBlock.php(49): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block), false)
#12 /var/www/html/vendor/yiisoft/yii2-queue/src/Queue.php(243): benf\neo\jobs\DeleteBlock->execute(Object(craft\queue\Queue))
#13 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('233262', 'O:25:"benf\\neo\\...', '3600', '1')
#14 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('233262', 'O:25:"benf\\neo\\...', '3600', '1', '21128')
#15 [internal function]: yii\queue\cli\Command->actionExec('233262', '3600', '1', '21128')
#16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('exec', Array)
#19 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('exec', Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\queue\Command->runAction('exec', Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('queue/exec', Array)
#23 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#25 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#26 /var/www/html/craft(13): yii\base\Application->run() 

### Steps to reproduce

1.
2.
3.

### Neo version

3.9.11

### Craft CMS version

4.5.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
In this case [it's Craft code that's calling `getOwner()`](https://github.com/craftcms/cms/blob/c94af041eaca79540eac8ce4352e7d5737de6785/src/helpers/ElementHelper.php#L433-L449), and `ElementHelper` probably isn't the right place to handle this.

Yeah, it's fair enough that `getOwner()` returns `null` if its owner no longer exists. 4.0.0 will be released later this week, including this change.

**Comment by bgrrtt** [comment]
thank you!

**Comment by ttempleton** [comment]
4.0.0 now released - let me know if issues persist with the Scout plugin.
