### ISSUE TITLE
Server error when adding blocks with more than 1 minimum child blocks.

### ISSUE THREAD

**Issue by iainhenderson** [spicywebau/craft-neo#822]
### Bug Description

When I add a block with more than 1 minimum child blocks, I often see a server error appear in Craft (toast, bottom left corner of the CMS.)

The first child block is added, but the other blocks are not created.

This error usually only appears the first time adding the block. It works as expected on subsequent attempts. Reloading the CMS edit page re-triggers the error behaviour.

I've taken a quick look a the Craft log files and network requests but didn't spot anything useful.

### Steps to reproduce

1. Configure Neo to have parent block, and child blocks, set 'min child blocks' to be >  1
2. Open an edit page with the neo field
3. Add the parent block

### Neo version

3.9.11

### Craft CMS version

4.5.13

### What is the affected Neo field's propagation method?

 Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 4.0.0.

**Comment by iainhenderson** [comment]
Brilliant.. Thank you @ttempleton
