### ISSUE TITLE
When adding block with reserver keyword, error message specifiing what was wrong doe not show up

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-neo#824]
### Bug Description

I tried adding block with handle "section". Only indication that something went wrong when saving neo field was red handle of section of blocks list. But no any error message specifying why this handle was wrong showed up.

### Steps to reproduce

1. add the block with reserved keyword for handle.
2. block wit not save correctly, but error message will not show up.

### Neo version

4.0.0

### Craft CMS version

4.5.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 4.0.1.
