### ISSUE TITLE
Blocks of type Children B are not allowed as children of blocks of type Block A.

### ISSUE THREAD

**Issue by dande-sun** [spicywebau/craft-neo#825]
### Bug Description

[Test-NEO-Field-First-bug-2.webm](https://github.com/spicywebau/craft-neo/assets/93630861/5f78692b-ffee-41ac-b036-dfc0e00eb489)

### Steps to reproduce

1. Add Block A ( do not add children for Block A )
2. Add Block B
3. Add children block for Block B
4. Click button Create entry

### Neo version

4.0.0

### Craft CMS version

4.5.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this - at first, I thought it might be related to the quite slow loading/saving times shown in your video, but after simulating a slow connection locally, everything still works as expected.

- Are there any JavaScript console errors during this process?
- If no to the above, are you able to reproduce this if you set up a fresh Craft install with Neo as the only installed plugin?

**Comment by dande-sun** [comment]
[NEO-Field-BUG.webm](https://github.com/spicywebau/craft-neo/assets/93630861/43133c96-d08c-4c3b-bb85-b8036c0f2d3d)

**Comment by dande-sun** [comment]
[NEO-Field-BUG.webm](https://github.com/spicywebau/craft-neo/assets/93630861/43133c96-d08c-4c3b-bb85-b8036c0f2d3d)

**Comment by ttempleton** [comment]
Thanks for confirming that you could reproduce it on a new Craft install. I was finally able to reproduce it and I've just released 4.0.2 to fix it. Please let me know if the issue persists, though.
