### ISSUE TITLE
[web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by DTesch-Reem** [spicywebau/craft-neo#828]
### Bug Description

When updating an Entry, with lots of Neo fields (with children), via a mutation I get this error: 
[web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

It happens mainly when making the request twice, before the initial request is finished.

Edit: It happens only when the session component is set to redis-Driver.
Edit: It also happens when doing GraphQL Requests from my Nuxt-App.

### Steps to reproduce

1. GraphiQL Playground
2. Set session component to redis-Driver.
3. Mutate/Update an entry with lots of Neo fields (with children)
4. Hit the play button 2-3 times fast
5. Error: [web.ERROR] [yii\db\Exception] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
6. The process/lockfile seems to only get released when I restart the server

### Neo version

4.0.2

### Craft CMS version

4.5.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Just to clarify - does this happen in any case where the entry has a large number of Neo blocks, regardless of the number of blocks being updated/added, or does it require a large number of blocks being updated/added in the mutation?

**Comment by DTesch-Reem** [comment]
Sorry for the late replay. This was fixed with a CraftCMS Update :)
