### ISSUE TITLE
Fields within collapsed Neo Matrix Block are still accessible

### ISSUE THREAD

**Issue by svondervoort** [spicywebau/craft-neo#830]
### Bug Description

We are using Neo in a project and just noticed that when all blocks are collapsed the fields within are still accessible (but not visible). See screenshot: The Redactor field `bold` option is hovered within the last block.

![Screenshot 2024-01-09 at 13 18 56](https://github.com/spicywebau/craft-neo/assets/5063372/06ea8cd9-e87a-4a42-8973-8ef5f4e032d9)

### Steps to reproduce

1. Create multiple blocks within a matrix.
2. Add multiple blocks to a Entry.
3. Collapse all blocks and hover the space underneath the blocks.

### Neo version

4.0.2

### Craft CMS version

4.5.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed for the next release.
