### ISSUE TITLE
Adding my own custom field block conditions

### ISSUE THREAD

**Issue by marknotton-yello** [spicywebau/craft-neo#835]
I have a custom field which is essentially returning a single value as a string. When I try to conditionally manage other fields based on the value of my custom field, the option does not exist in the "Neo Block Condition". 

Is there something I need to do to get my custom field available in the list of "rules"?

**Comment by ttempleton** [comment]
From what I can tell, in general in Craft, the fields available to use for an {element} condition rule are those which exist on an {element type} field layout (not necessarily the same field layout) when the field layout page was loaded. So your custom field should be available for Neo block condition rules after it's added to a Neo block type's field layout, and then that Neo field is saved.

If the field still can't be used for Neo block condition rules after doing that, double-check that it's available for entry conditions on an entry type's field layout, and if it is available there, let me know and I'll reopen this issue as a bug report.

**Comment by marknotton-yello** [comment]
Thanks for the quick response. The problem really just came down to my inexperience with this side of plugin development. I had it in my head that Craft would automagically parse the fields and handle the conditional stuff on it's own. 

After discovering the [getElementConditionRuleType](https://docs.craftcms.com/api/v4/craft-base-field.html#method-getelementconditionruletype) method and reviewing some of the native Craft [conditions](https://github.com/craftcms/cms/tree/develop/src/fields/conditions); I was able to put something together and get it working.
