### ISSUE TITLE
Can't create NEO Fields

### ISSUE THREAD

**Issue by davidhellmann** [spicywebau/craft-neo#837]
### Bug Description

I've installed NEO on a more or less empty website and creating a neo field is impossible. When I switch the Field Type to NEO I get a console error: `No file extensions are known for the MIME Type application/x-empty.`

After hit the save button, same error
![image](https://github.com/spicywebau/craft-neo/assets/764292/3fe08ab6-a534-400b-bce9-d945dfb6a521)

### Steps to reproduce

1. Install NEO via Plugin Store
2. Go to fields
3. Create new field
4. Select Field Type: NEO

### Expected behaviour

Creating a NEO Field :)

### Neo version

4.0.3

### Craft CMS version

4.7.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this on a fresh Craft install; if possible, could you please send your composer files and database backup to plugins@spicyweb.com.au and we'll have a look.

**Comment by davidhellmann** [comment]
Sent! Thank you

**Comment by ttempleton** [comment]
Thanks for sending those - unfortunately I haven't been able to reproduce the error here.

Could you please post the full stack trace here (or send it in to plugins@spicyweb.com.au)? I'm hoping I can get an idea of what could be going wrong, based on where and how Neo code is being called.

**Comment by davidhellmann** [comment]
Sure, will send it via mail later. But interesting. Maybe a plugin install order or something. Will also check that.

**Comment by ttempleton** [comment]
Thanks for sending that. I was able to reproduce the error when a block type icon path was set, but the file was empty. I would recommend checking that the icon files you're using aren't empty, but Neo should definitely be checking those cases before trying to load icons, and that error is now fixed for the next release.
