### ISSUE TITLE
Blocks ejected out of containers on clone to new site, can't save entry

### ISSUE THREAD

**Issue by Christopholus** [spicywebau/craft-neo#839]
### Bug Description

We've been experiencing a few bugs when cloning entries on a multi-site setup. Primarily one bug which is that Neo blocks are sometimes immediately ejected from their containers on cloning, or when an entry is being saved.

Here is a video of the issue in action:
https://www.loom.com/share/4f5f26cacf3541a4973d5015fe46276c

In the video, I clone to a new site. Thankfully this time the blocks appear to be in their respective parents initially - but as soon as the entry is saved all of them are ejected out of their containers preventing the entry from being saved. It looks like many of them are also duplicated many times which causes the page to slow to a crawl.

Thank you in advance for any advice you can provide!

### Steps to reproduce

1. Create entry with neo blocks
2. Ensure neo field is set to translatable
3. Clone page into multi-site
4. Try to save page 

### Expected behaviour

The plugin should maintain it's parent/child hierarchy on entry save, and should not create any duplicates of interior content

### Neo version

4.0.3

### Craft CMS version

4.7.1

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by Christopholus** [comment]
Just following up with a similar issue that I feel is closely related so won't create another Github Issue for it but thought this might be helpful:

https://www.loom.com/share/169c5afdd077473694532405daa8644d

In this video I "clone" the entry to the new site, but save it without changing to that site. This allows the entry to save in both sites, but when I flip back to the entry in the other site all of the blocks are ejected again. 

I think the issue might be the same in both videos, but one of the scenarios allows me to "bypass" the neo errors about the ejected blocks being at the wrong level.

**Comment by ttempleton** [comment]
By any chance are you using the Preparse Field plugin? That plugin is known to have caused [loss of Neo block structure data](https://github.com/craftcms/cms/issues/13256), among other Neo content loss issues that have caused us to [document Preparse Field as being incompatible with Neo](https://github.com/spicywebau/craft-neo/blob/de1604870423481d31e8119668112c0c958b247f/docs/plugin-compatibility.md).

If you are using Preparse Field, there have been some suggestions that issues with Preparse Field and Matrix fields could be resolved by cloning the block query given as the Matrix field value before using it (https://github.com/besteadfast/craft-preparse-field/issues/36), and that potentially this could resolve issues with Neo as well (https://github.com/spicywebau/craft-neo/issues/429#issuecomment-778287459) - but those discussions involved Craft 3, and I'm unsure if it's still the case with Craft 4.

**Comment by ttempleton** [comment]
Closing this issue for now and assuming Preparse Field is involved. Please let me know if you're not using it, though, and I'll reopen the issue.

**Comment by Christopholus** [comment]
Sorry for the delay here @ttempleton - we ended up rolling back the plugin at the time and locking the versions as we were nearing launch of the project.

Unfortunately we are not using the Preparse plugin - though I wonder if another plugin may be conflicting with it. Any others you are aware of? I will give the new version of Neo a try at a later to test again and see if the issue persists. If so, perhaps we can look to revive this again to see if we can land on a fix!

**Comment by ttempleton** [comment]
No worries @Christopholus - I can't think of any cases of this happening with other plugins, but if it happens again next time you try the new version, let me know and we'll reopen the issue.
