### ISSUE TITLE
Add option to have some kind of screenshot or image assigned to block type

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-neo#841]
### What would you like to see added to or changed in Neo, and why?

When we have tons of blocks, soon users might just forgot what they look like when trying to add new.
I had user that complained that he needs to add new block, enter some data, preview, decide that it was not one he was looking for and repeat process again.
If some kind of screenshot could be assigned to specific block type, and selection of new block was done not by dropdown, but by selecting this screenshot from some kind of gridlist (along with block name shown of course), neo field would be more comfortable to use.

**Comment by ttempleton** [comment]
This functionality is provided by the [Matrix Field Preview](https://github.com/timmyomahony/craft-matrix-field-preview) plugin.
