### ISSUE TITLE
Block order change in projectconfig doesn't cause change in Neo UI

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#845]
### Bug Description

A recent change changed how order of blocks is saved in yaml files, and this has reduced the number of VCS conflicts we're getting enormously. That's great.

I've been noticing, however, that we're sometimes getting inconsistent block orders.

It happened again just now and I investigated.

### Steps to reproduce

1. Save a Neo field with a few blocks.
2. Open its corresponding `config/project/neo/orders/*.yaml` file and change the order
3. Touch the projectconfig modified date so Craft will pick up the change (`./craft project-config/touch`)
4. Apply projectconfig (via the GUI, or `./craft project-config/apply`)
5. Open as if to edit the Neo field again, and see the order has not updated

### Expected behaviour

Neo picks up order changes from projectconfig files during projectconfig apply.

### Neo version

4.0.2

### Craft CMS version

4.6.0

### What is the affected Neo field's propagation method?

"save to all sites the owner element is saved in"

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release.
