### ISSUE TITLE
Why do the `fieldLayouts` UIDs change so much?

### ISSUE THREAD

**Issue by tremby** [spicywebau/craft-neo#846]
### What question would you like to ask?

I've noticed in code review that we sometimes get conflicts on the UID (they look like UIDs at least) keys under `fieldLayouts` in `config/project/neoBlockTypes/*.yaml` files. As far as I can tell, neither of the two UIDs in my conflict-marked file correspond to anything in any other yaml file or any filename. Maybe they correspond to something in the database? I never know what to do in this situation, and I tend to cross my fingers and guess, and so far nothing has gone horribly wrong.

I'm not sure exactly when it changes. It seems to change if I save the neo field after somebody else has edited it. It doesn't seem to change again if I then edit it again myself.

Why does it change? How can I know which value is correct? Is this a bug? Can it be made stable?

**Comment by ttempleton** [comment]
This is definitely a bug. Looking into it now.

**Comment by ttempleton** [comment]
Thanks for reporting this one as well. It's now fixed for the next release, which will be early next week (hoping to close #842 and #813 first).
