### ISSUE TITLE
How to fix "Invalid owner ID" issue?

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#850]
### Bug Description

I've got a site that's been upgraded from Craft 3.x to 4.4.17 (currently). The site generally works fine, but when I try to retrieve all Neo blocks to list in a utility template, I get the "Invalid owner ID" error.

I saw in https://github.com/spicywebau/craft-neo/issues/396 that it was due to a Craft 3.x bug that was fixed, but how do I fix it if I already have the issue and I'm not trying to update the site (or at least, I'm not encountering it _during_ a site update)?

Thanks!

### Steps to reproduce

To reproduce, I'd probably have to give you the composer files and database. For now, here's the code that reveals the issue, followed by the stack trace:

# `page-builder-blocks.twig`
```twig
{% set myNeoBlockQuery = craft.neo.blocks().all() %}

<h1>{{ myNeoBlockQuery|length }} blocks</h1>

{% set blockTypes = [] %}

{% for block in myNeoBlockQuery %}
    {% set blockTypes = blockTypes|merge(
        {
            (block.type.handle): [ block ]
        }, true) %}
{% endfor %}

<main>
    {% for key, blocks in blockTypes %}
        <details>
            <summary>{{ key }} ({{ blocks|length }})</summary>
            <table>
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Title</th>
                        <th>Links</th>
                    </tr>
                </thead>
                <tbody>
                {% for block in blocks %}
                    <tr {{ block.owner.status == 'disabled' ? ' class="disabled"' : '' }}>
                    <td>[{{ block.owner.status }}]</td>
                    <td>{{ block.owner.title }}</td>
                    <td><a href="{{ block.owner.url }}" target="_blank">View</a> | <a href="{{ block.owner.cpEditUrl }}" target="_blank">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </details>
    {% endfor %}
</main>
```
# Stack Trace

```
yii\base\InvalidConfigException: Invalid owner ID: 157157 in /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php:412
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Component.php(139): benf\neo\elements\Block->getOwner()
#1 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2169): yii\base\Component->__get('owner')
#2 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(135): craft\base\Element->__get('owner')
#3 /var/www/html/storage/runtime/compiled_templates/0b/0b41d85816d69c1092386fcf27fccb51.php(96): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(benf\neo\elements\Block), 'owner', Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_dc840e952d74546a056a3c6a4c7af37e->doDisplay(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#7 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/View.php(465): Twig\Environment->render('page-builder-bl...', Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/View.php(518): craft\web\View->renderTemplate('page-builder-bl...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('page-builder-bl...', Array, 'site')
#12 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#13 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#14 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#16 /var/www/html/web/index.php(12): yii\base\Application->run()
#17 {main}
```

### Neo version

3.8.6

### Craft CMS version

4.4.17

### Does this issue involve templating, and if so, is eager-loading used?

This is a templating issue, and eager loading is not used

**Comment by ttempleton** [comment]
It sounds like you might be experiencing the bug from issue #821 (albeit not as a result of queue jobs). I made a change in Neo 4 for `getOwner()` to return `null` if a Neo block's `ownerId` is set to the ID of an element that has been deleted, which resolves that issue. Upgrade to Neo 4 (following the [upgrade guide](https://github.com/spicywebau/craft-neo/blob/396643930c737e5c39610c15110e1e39c210912c/docs/upgrade-guides/neo-4.md) - particularly ensuring that your template handles the possibility that `block.owner` will be `null`), and please let me know how you go.

**Comment by proimage** [comment]
Ahh, thanks! Looks like Neo 4 requires Craft 4.5+, which is why I'm not even seeing the Neo updates in the CP while on Craft 4.4. Will do.

**Comment by ttempleton** [comment]
Some of the other bug reports with this error were related to the fact that Neo delegates block deletion to a queue job when an owner entry is deleted. If you have Craft's `runQueueAutomatically` setting disabled, then those blocks might have just not been deleted yet.

You could check the `content` database table for rows with the `elementId` of one of the blocks' IDs to see what they contained, but if the owner no longer exists, they'll be safe to delete.

When I get a chance, I will also add some code to clear out that data as part of Craft's garbage collection.
