### ISSUE TITLE
Overload of "Deleting old Neo blocks" queue jobs

### ISSUE THREAD

**Issue by engram-design** [spicywebau/craft-neo#852]
### Bug Description

I've got a complex multi-site, with 8 sites, and a Neo field for a content builder with the Propagation Method set to "Only save blocks to the site they were created in" (none).

Whenever I save an entry, I'm seeing a **heap** of queue jobs for "Deleting old Neo blocks" which is causing havoc on our queue and server processing.

Firstly, looking into your [code](https://github.com/spicywebau/craft-neo/blob/8e25330249b1aba2d0d98a3eec7e05ab3e5a7609/src/Field.php#L808-L825) I can see these jobs are triggered whenever an owner element (like an entry) is deleted, however we're not actually deleting _anything_, just saving a new entry. Check out the video below for an example.

But, what I believe is happening, is that the draft that gets created is technically the element getting deleted, and that's what's triggering these blocks to be deleted. They're owned by the entry draft, not the entry proper.

I'm wondering if this is correct behaviour? I suppose there's no way around it though, as the blocks belong to the draft. But this is causing our site a lot of headaches with complex entries spawning oodles of jobs. In my simple example of two blocks, there's 18 queue jobs created for "Deleting old Neo blocks" .

Secondly, is there a reason to spawn a task for every single block? Would it not be more prudent or efficient to have a single queue job that handles everything? Then at least, the block query to fetch blocks (for every site) can be offloaded to the queue job, and makes saving an entry all that much quicker?

I've put together a [PR](https://github.com/spicywebau/craft-neo/pull/853) for this if you're interested.

### Steps to reproduce

Refer to this video, where I create a new entry, and add some blocks. I've set the queue processing to be off, so you can see what sort of tasks we're dealing with.

https://share.cleanshot.com/nl3lcQyb

As I've mentioned, this is a reduced case. On a typical entry for this site with 10-30 blocks in an entry, we're looking at 200-500 queue jobs every time an entry is saved.

### Neo version

2.13.19

### Craft CMS version

3.8.14

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for putting the PR together, will merge it shortly.

> But, what I believe is happening, is that the draft that gets created is technically the element getting deleted, and that's what's triggering these blocks to be deleted. They're owned by the entry draft, not the entry proper.

That's correct; the original queue job was added to handle the deletion of blocks owned by a deleted provisional draft, thereby speeding up the entry save.

> Secondly, is there a reason to spawn a task for every single block? Would it not be more prudent or efficient to have a single queue job that handles everything? Then at least, the block query to fetch blocks (for every site) can be offloaded to the queue job, and makes saving an entry all that much quicker?

I can't actually remember if I had a reason for adding a new job per block, but if I didn't, then it is probably better to have it all done in one job.

**Comment by engram-design** [comment]
Thanks for taking a look! After a bit more messing around, I can't see a way to avoid this, it just seems _crazy_ inefficient to have all this extra work to delete Neo block elements when saving an entry. But that's just how Craft's content system works at the moment with provisional drafts.

I did also toy with the idea of a plugin setting to disable the queue job from being created immediately, as this is really a cleanup task once the draft element has been applied and deleted. I was thinking I could run a nightly cronjob to clean up owner-deleted blocks, but then we need some way to store a reference to the blocks deleted, so I stopped there.

**Comment by ttempleton** [comment]
> it just seems _crazy_ inefficient to have all this extra work to delete Neo block elements when saving an entry.

Yeah, that's fair enough. I imagine that sort of situation is part of the motivation for Matrix fields moving away from the inline block format by default in Craft 5.
