### ISSUE TITLE
Find old/bad blocks 

### ISSUE THREAD

**Issue by yannkost** [spicywebau/craft-neo#854]
### What question would you like to ask?

I have seen that in the database I'm able to find a lot of blocks in the elements table, that have no correponding entry in the neoblocks table. 

```
SELECT *
FROM elements
WHERE TYPE = 'benf\\neo\\elements\\Block'
AND id NOT IN (SELECT id FROM neoblocks)
```

Am I safe to delete those blocks? Is there a way to remove unused/old/bad blocks?

Neo Version: 4.0.5

**Comment by ttempleton** [comment]
I just checked this with Matrix blocks as well, and it does also happen with them - but the leftover data for both Matrix and Neo blocks was cleared out by Craft's garbage collection by running `php craft gc/run`, so I recommend that. If that does not clear out your leftover Neo data, please let me know.
