### ISSUE TITLE
Long-term Neo block management

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#855]
I've got many client sites that use Neo fields as page builders... add a heading block, add an image, add a text block, etc. Over the years, these page builder fields can get quite loaded with different block types as the client has new requirements.

**What I'd like to be able to do is see a list of how many times each block type is used across all entries;** sometimes I find a block is never actually used in practice and can therefore be culled. :)

Is there a (performant) way to list how many times each block is used? I've tried by fetching ALL blocks (excluding the ones I _know_ are frequently used) and then grouping them by `block.type.handle`, but that's very heavy on larger sites:

```twig
{# Fetch ALL blocks site-wide (except for most-commonly used ones) #}
{% set myNeoBlockQuery = craft.neo.blocks().type('and, not text, not heading').all() %}
{% set blockTypes = [] %}

{# Group all the blocks by block type #}
{% for block in myNeoBlockQuery %}
    {% set blockTypes = blockTypes|merge({
        (block.type.handle): [ block ]
    }, true) %}
{% endfor %}

{# Output all blocks in their groups #}
{% for key, blocks in blockTypes %}
<details>
    <summary>{{ key }} ({{ blocks|length }})</summary>
    <ul>
    {% for block in blocks %}
        <li>
            {# Entry title and status #}
            {{ block.owner.title }} ({{ block.owner.status }}) - 
            {# View and Edit links to that entry #}
            <a href="{{ block.owner.url }}" target="_blank">View</a> |
            <a href="{{ block.owner.cpEditUrl }}" target="_blank">Edit</a>
        </li>
    {% endfor %}
    </ul>
</details>
{% endfor %}
```

If there were even a way to just list the number of occurrences of a block type and then from there I could set up a button to fetch the details of the entries that use that block, I'd be happy. ;)

**Comment by chrisrowe** [comment]
https://plugins.craftcms.com/block-usage

**Comment by ttempleton** [comment]
I endorse the Block Usage plugin (with the changes proposed in https://github.com/simplygoodwork/craft-block-usage/pull/7) for this purpose.

**Comment by proimage** [comment]
@chrisrowe @ttempleton Thanks! That plugin looks like it would work great, _if_ it supported nested Neo blocks. Hopefully it gets updated soon. 🤞
