### ISSUE TITLE
Block property `field` throws an error

### ISSUE THREAD

**Issue by chrismlusk** [spicywebau/craft-neo#859]
### Bug Description

Per the [API docs](https://github.com/spicywebau/craft-neo/blob/main/docs/api.md#neo-block), the `field` property should return a block's `Field` object. When I attempt this in a template, though, I get a Twig runtime error:

```
Calling unknown method: benf\neo\elements\Block::field()
```

Since `field` is an alias, I also tried to use the `getField()` method, but I get a similar "unknown method" error.

### Neo version

4.0.5

### Craft CMS version

4.7.3

### Does this issue involve templating, and if so, is eager-loading used?

This is a templating issue, and eager loading is not used

**Comment by ttempleton** [comment]
Thanks for pointing that out - I don't think there has ever been a `getField()` public method on Neo blocks, so I'm not sure how that ended up in the docs 😅

That said, we do have a private method which it certainly wouldn't hurt to make public, so I will do that soon. In the meantime, `neoBlock.type.field` will work.

**Comment by chrismlusk** [comment]
Great, thank you!
