### ISSUE TITLE
Neo field content lost upon saving entry in multi-site environment

### ISSUE THREAD

**Issue by bavodeclercq** [spicywebau/craft-neo#863]
### Bug Description

When enabling an entry for a new site, the fields are correctly copied into the draft. However, upon saving the draft, the content of the Neo field is unexpectedly deleted.

[Video](https://share.cleanshot.com/5SQDwL64)

### Steps to reproduce

1. Create two sites.
2. Create a section with a custom propagation method and add a plain text field and a Neo field to the entry type.
3. Create a new entry for the first site.
4. Populate the Neo field with content.
5. Save the entry.
6. Reopen the saved entry and enable it for the second site, then save it.
7. Notice that the content in the Neo field is now empty on the second site, while the content in the plain text field remains intact.

### Expected behaviour

The Neo blocks should be consistent across both sites upon saving.

### Neo version

4.0.6

### Craft CMS version

4.8.0

### What is the affected Neo field's propagation method?

None

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.0.8.
