### ISSUE TITLE
Neo Not Saving Changes to Field Layout

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#869]
### Bug Description

I noticed that Neo isn't saving changes to my field layout. I can remove a field from a block's layout and if I hit the save button and then go back to the same block, the field I removed is still there even though the notification says the field changes were saved. 

### Steps to reproduce

1. Remove a field from a block's field layout. 
2. Save the field. 
3. Check the block type again after saving and the field you removed is still there.

### Neo version

4.0.8

### Craft CMS version

4.8.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Removing a field from a block type's field layout is working as expected for me. If possible, could you please send your composer files and database backup to plugins@spicyweb.com.au and let us know which Neo field and block type this is happening with, and we'll have a look.

**Comment by ttempleton** [comment]
Thanks for sending those files. That block type and a few others shared the same field layout, which is puzzling and a little concerning. I have added a console command for the next release (`php craft neo/block-types/fix-field-layouts`) to duplicate the field layout so each block type gets its own version. If you'd like to apply that fix before the next release, set your composer.json file's `spicyweb/craft-neo` requirement to `4.x-dev as 4.0.8` and run `composer update`.
