### ISSUE TITLE
Slow to load and save?

### ISSUE THREAD

**Issue by maxwellhibbert** [spicywebau/craft-neo#87]
I've just saved my first page with Neo and the performance for saving and loading the page seems a bit slow to me and I'm a bit worried about how slow a more complicated page might end up being. So I just wanted to check if it's roughly normal?

I've got an Assets field with 20 images + about 20 rich text fields with no more than a paragraph each + a handful of lightswitch and radio fields.

Loading time for an entry is about 20 seconds and saving time about 10 seconds (so quick-save is about 30sec). This is on my local test server (Mac Pro) running php7.

Is that normal, or should it be better?

**Comment by benjamminf** [comment]
That's certainly abnormal. Do you have any way to compare the Neo field with, say a Matrix field of similar size and content? I don't think it's Neo (as Neo has some performance optimisations that should outperform Matrix) but it'd be good to rule it out. My best guess is your local server is underperforming, whether that's a configuration issue or something else.

**Comment by 23d1** [comment]
I have this issue as well for large entries, and I think it's actually the Garnish JS library slowing things down. Is scrolling the entry slow in general as well (scrolling up and down, and so forth)?

**Comment by maxwellhibbert** [comment]
I setup a matrix field with similar content. It's heaps quicker - about 2 seconds to load and save. I don't have a problem scrolling the entry with the Neo field though, sorry @23d1 .

Could having fields a layer or 2 deep in the Neo field cause the delay?  I do have some fields inside a grid like setup: section->grid->cell->content fields.

**Comment by benjamminf** [comment]
Hm that's odd. I have a Neo field here that has 30-40 blocks with 5-10 fields each, including lots of rich text and assets. It's understandably slightly slower, but on this 5 year old iMac it's saves in about ~4 seconds and loads ~1 second. What browser are you using?

**Comment by maxwellhibbert** [comment]
I've tried in Safari 10.0.2, Chrome latest and have all extensions disabled. Would it matter if the fields are a few levels deep?

**Comment by 23d1** [comment]
Either way, the UI is slow, and always has been for me. I anticipate it being more of a Craft issue than a Neo issue. For example, hitting save or cmd+s makes the site appear as if it's rerouting while submitting each and every field to the database (taking up to 10 seconds to actually save and reload)—which is likely a Garnish JS issue, or potentially a rendering issue with JS related to handling Neo fields.

My setup is a Neo field like this;
```
Row
    Text
    Image
    Slideshow
        Slide
    Video
    Video Loop
    Entries
    ... Et cetera, you get the picture
```
Each of those blocks have multiple tabs, with multiple field types.
Here's an example (2 screenshots);
1.
![image](https://cloud.githubusercontent.com/assets/2627617/23445503/c6a1a8ea-fdf0-11e6-8cee-504886999220.png)
2.
![image](https://cloud.githubusercontent.com/assets/2627617/23445508/d2c2444a-fdf0-11e6-9f1e-1a8eae13bf76.png)

**Comment by maxwellhibbert** [comment]
My setup is quite similar to that, I do have grids/rows within grids/rows as well.

**Comment by maxwellhibbert** [comment]
Some more testing:

I disabled every plugin except Neo - no difference.

I setup a test entry with similar content to the other one. I began deleting Neo blocks from the entry one by one, starting with ones that had the most nested blocks - that made a massive difference. Just removing 3 blocks that contained fields nested 2-3 deep got the load time down to 2 seconds. The content in those blocks was mainly a single plain text/rich text/asset field along with a handful of switches and dropdown options (in another tab).

I put the same content back in, this time without nesting. The page now loads in 3 seconds.

**Comment by 23d1** [comment]
Seems to be Chrome specific for me, upon further testing. Very nice and responsive in Safari and Vivaldi (Webkit as well).

**Comment by cole007** [comment]
I'm experiencing similar and noticed in the console getting a garnish.js log:

```Double-instantiating a transparent text input on an element```

Could this be related?

**Comment by maxwellhibbert** [comment]
I have that in my log too. 34 times for the entry I'm testing with.

**Comment by benjamminf** [comment]
@maxwellhibbert @23d1 @cole007 Would any of you be okay with providing me a DB dump of your setups that you're experiencing these slowdowns with? I want to run a profiler on them to see what's the bottleneck and hopefully improve on it. Cheers.

**Comment by steveooo9** [comment]
@benjamminf Same here. I also have the problem that sometimes when trying to save, it doesn't save. Takes a long time 5-6s. Maybe timeout related? But no error here...

**Comment by steveooo9** [comment]
@benjamminf Well, it was better when having higher memory_limit in php.ini, but when using a lot of complex blocks, a big sum of variables get's POSTed to the server... Any way to optimize sending the data more compact (on save)?

**Comment by hisnameisjimmy** [comment]
@benjamminf I would be happy to do this (give you a db dump). I have a situation where our website has sections with as many as 5k pages, and it's multi-lingual, with approximately 15 languages. If I save one of these sections, it can be hours before all the Neo_GetSearchKeywords tasks clear. On a Digital Ocean 2 CPU-optimized instance, it can be an hour. Further, these sections generally contain fairly simple pages.

**Comment by danieltott** [comment]
I am experiencing this issue as well - the entry is taking a long long time to save. I got it to work by bumping up `max_execution_time` to `120` - before that it was set to `60` and was timing out.

This entry type has two neo fields, and while they don't have multiple tabs, each block has at least one relation and matrix field. one of the matrix fields has a block type that contains a relation as well. the entry itself that was causing the problems has like 38 neo blocks total.

I would be happy to provide a dump if this would help.

**Comment by ttempleton** [comment]
Closing this issue due to its age and inactivity since the release of Neo for Craft 3.  If anyone has any issues with the speed of loading/saving Neo field data with Craft 3, please feel free to open a new issue.

**Comment by ricricucit** [comment]
OK :) 

Here I am, reporting something that a client is experiencing:

> Saving times are growing with complexity. First 5 content elements don‘t show any effect. But with 15-20 (that is quickly reached with Accordions, etc.) page gets significantly slower, until it times out.

Do you have suggestions on how to test if this is even caused by neo? (we almost sure that's it)

**Comment by ttempleton** [comment]
@ricricucit First thing to do is to make sure you have the latest versions of Craft (3.7.29) and Neo (2.12.2) since older versions of Neo (pre-2.11 in particular) running on Craft 3.7 will have some compatibility issues that could cause a drop in performance.

If you've got the latest versions of Craft and Neo and it's still happening, then test out a similarly-sized Matrix field to narrow down whether it's affecting just Neo or block element fields in general. If it is just Neo, then feel free to open a new issue for that.
