### ISSUE TITLE
Exponential increase of blocks when adding an existing entry to another site

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-neo#870]
> It seems that a new issue has surfaced after the recent fix was pushed. I'm not sure if it's related to the fix or if it's a separate issue. When adding an existing entry to another site and saving it, the blocks appear to be recursively multiplied, resulting in an exponential increase (I guess per removal of the entry for the site, an extra block is added). This problem doesn't occur with new entries. However, it's reproducible with new entries by adding the entry to another site, then removing it for that particular site, and finally adding it again. Please see the [video](https://share.cleanshot.com/ZQ542STX) for reference.

_Originally posted by @bavodeclercq in https://github.com/spicywebau/craft-neo/issues/863#issuecomment-2017590437_

**Comment by ttempleton** [comment]
I'm unable to reproduce this - @bavodeclercq if possible, could you please send your composer files and database backup to plugins@spicyweb.com.au, and we'll have a look.

**Comment by bavodeclercq** [comment]
> I'm unable to reproduce this - @bavodeclercq if possible, could you please send your composer files and database backup to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au), and we'll have a look.

Hi, I've sent the requested files.

**Comment by BorisWRLB** [comment]
@ttempleton Did you eventually manage to recreate the issue?

For me the issue occurs when deleting an entry for a site, on an entry that exists for multiple sites.
Adjusting the entry's neo field in the site that is remaining.
Then re-adding the entry for another site, the same way the original issue described.

**Comment by ttempleton** [comment]
Thanks for sending the files @bavodeclercq - fixed now in 4.1.0.

@BorisWRLB please also upgrade to 4.1.0 and let me know if the issue persists for you.

**Comment by BorisWRLB** [comment]
@ttempleton 
> @BorisWRLB please also upgrade to 4.1.0 and let me know if the issue persists for you.

It seems to have fixed the issues I had, thank you for the quick fix.
