### ISSUE TITLE
[Craft 5] Action Menu won't open after a new Block is added

### ISSUE THREAD

**Issue by hw-01010** [spicywebau/craft-neo#874]
### Bug Description

When a block is initially created, the Action menu won't open. After a page reload, the menu opens normally

![image](https://github.com/spicywebau/craft-neo/assets/112609658/23d21e7c-65af-4b33-864c-984f2a8310d9)

### Steps to reproduce

1. Create Neo Field
2. Create Entry
3. Add a Block
4. Press the action menu dots

### Neo version

5.0.0-beta.2

### Craft CMS version

5.0.0

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Opening and closing the action menu on new blocks is working for me.

Are there any JavaScript errors showing in your browser console?

**Comment by hw-01010** [comment]
Nothing relevant, I think
![image](https://github.com/spicywebau/craft-neo/assets/112609658/a2f6681f-9410-42be-ad79-7d918c9a3930)

I believe it has something to do with the validation error from the Dropdown menu:
![image](https://github.com/spicywebau/craft-neo/assets/112609658/6cf45521-ccb0-4af5-b831-0b620449b84e)

I tested it with another neo Block without a Dropdown menu and it works fine.

**Comment by ttempleton** [comment]
Thanks for that extra information and for reporting this bug! Fixed now in 5.0.0-beta.4.
