### ISSUE TITLE
Copy / Paste of Neo Blocks

### ISSUE THREAD

**Issue by funkysoul** [spicywebau/craft-neo#878]
### Bug Description

When copying an element from page A to page B, page B receives the correct element and everything looks fine, but the original page where the element was copied from adds the copied element to iself as well. 
Seems like when copying an element the reference to it is aswell stored in the current Page. Maybe a racing-condition.

### Steps to reproduce

1. nothing really special, Page A, copy element
2. Page B, paste element
3. reload page A and disable the copied block. after saving a "new" block will appear at the top most position

### Expected behaviour

the copied element should only appear on the target page

### Neo version

5.0.0-beta.5

### Craft CMS version

5.0.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.0.0-beta.6.
