### ISSUE TITLE
Export via schematic or necessary tables to include blocks

### ISSUE THREAD

**Issue by fspeckmaier** [spicywebau/craft-neo#88]
Currently deploying one of our recent projects and found out, that our schematic export / import handles all fields correctly, but misses out the blocks within a neo field. Unfortunately we have quite a lot blocks, so remodelling would be a real pain... Exporting the "neo field" - tables from Craft's database wasn't successful either. So, any ideas how to export a neo field including its blocks?

**Comment by benjamminf** [comment]
I've never used the Schematic plugin, but from what I can see it doesn't seem to handle content, only the fields themselves. So it wouldn't export Neo blocks by design. Unless you mean the block types?

**Comment by fspeckmaier** [comment]
Yes, I meant block types. Sorry for being unclear. So, only the Neo field
itself gets  exported, but not the block types created within...

Benjamin Fleming <notifications@github.com> schrieb am Mi. 22. März 2017 um
23:09:

**Comment by agosman** [comment]
Just ran into this same issue and was wondering if there are any updates on this?

**Comment by ttempleton** [comment]
At this stage Neo for Craft 2 will not be supporting Schematic, but Neo v2.1.0 for Craft 3 will support Schematic -- thanks again @boboldehampsink!
