### ISSUE TITLE
Settings menu for fields in the layout designer not opening in Craft 5

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#880]
### Bug Description

The settings menu for editing a field's label/handle/required status doesn't open in the field layout designer for Neo fields in Craft 5.

### Steps to reproduce

1. Add a field to a the field layout of a Neo block
2. Click the three-dot settings menu

### Expected behaviour

Settings menu should open.
![2024-04-11 at 15 22 24](https://github.com/spicywebau/craft-neo/assets/42223501/b593d930-703c-445b-94bb-cfe29df0ae2b)

### Neo version

5.0.0-beta.5

### Craft CMS version

 5.0.4

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next beta release.

**Comment by ttempleton** [comment]
Just released 5.0.0-beta.6 including the fix for this.
