### ISSUE TITLE
Entries from another site can be selected in the back end, but they are not output in Twig templates.

### ISSUE THREAD

**Issue by mike-moreau** [spicywebau/craft-neo#885]
### Bug Description

I am working on a multi-site installation with two sites.

I have a section called "Articles" that is enabled for the Primary site only, and I have a section called "Pages" that is enabled for the Secondary site only.

There is a Neo field called "Blocks" that is available on both Articles and Pages.

On the Secondary Site in the Pages section, I can add selected articles to an entries field. It works as expected in the back end. When I try to output the selection on the front end, the entries field is empty.

Screenshots of the Primary Site:

<img width="1027" alt="Screenshot 2024-05-01 at 10 02 16 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/ac12985c-12b9-498a-9553-a4551ddf24ff">

<img width="930" alt="Screenshot 2024-05-01 at 10 02 25 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/69331c72-b866-48d8-885c-8cc2746856d4">

<img width="855" alt="Screenshot 2024-05-01 at 10 03 08 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/0d5f4195-288e-43a3-833b-d0f635df1982">

Screenshots of the Secondary site:
<img width="1016" alt="Screenshot 2024-05-01 at 10 03 23 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/ef77ccc4-2039-444b-84d6-590ab7d494ff">

Articles from primary site can be selected.

<img width="906" alt="Screenshot 2024-05-01 at 10 03 43 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/ea444b73-c306-4426-a9bb-073452aef19b">

<img width="876" alt="Screenshot 2024-05-01 at 10 03 50 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/47fd59d0-a0f0-445a-99ee-3c99d15c37b7">

Article relations are empty in primary site

<img width="766" alt="Screenshot 2024-05-01 at 10 04 01 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/2162c95c-c234-4689-a9ad-8cea1a6f6c08">

The related articles field allows for the site select menu:

<img width="1035" alt="Screenshot 2024-05-01 at 10 02 44 AM" src="https://github.com/spicywebau/craft-neo/assets/92817780/2cf5caa5-972b-4ccb-90e4-a82a466b9e82">

The code to render the block field looks like this:
```
{% for block in entry.blocks.all() %}
    {% if block['relatedArticles'] is defined %}
        {% for article in block.relatedArticles.all() %}
            {{ article.title }}
        {% else %}
            No related articles.
        {% endfor %}
    {% endif %}
{% endfor %}
```

### Steps to reproduce

1. Configure the test content and relations
2. Attempt to output relationship in twig from Primary site only on Secondary Site

I'm happy to provide a DB dump or other config files if it would be helpful.

### Expected behaviour

The relationships to Primary site content would be output in twig.

### Neo version

4.1.2

### Craft CMS version

4.9.0

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in.

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
This seems to be the case for me even when putting the entries field directly on the entry's field layout - could you please confirm whether that's what happens for you?
