### ISSUE TITLE
Editing doesn't output levels correctly

### ISSUE THREAD

**Issue by avr** [spicywebau/craft-neo#89]
I have a Neo field with 1 "parent" and 5 or so allow child blocks.

The edit screens for all of my previous entries work as expected, but one new entry is nesting everything one level deep.  When I try to create a new "parent", it gets nested inside the previous parent.  Looking at the content in the DB, the entry JSON has the correct levels for each block.

![2017-03-02 17 32 31](https://cloud.githubusercontent.com/assets/347482/23530111/5b776eea-ff6e-11e6-90a7-a0150edb4d92.gif)

I do have a JS error (thrown by Focuspoint - but the stack trace leads back to Block.js).  Here's that error.  I'm mostly convinced that Focuspoint can't find it's stuff because the blocks aren't where they're expected to be.

![screen shot 2017-03-02 at 5 36 05 pm](https://cloud.githubusercontent.com/assets/347482/23530219/ca144b66-ff6e-11e6-852f-051e7f046c61.png)

My question: is this an actual issue and is there a way to "fix" this without having to rebuild the whole entry?

**Comment by benjamminf** [comment]
It's most likely an issue with the focus point field throwing an error which in turn stops the Neo field from initialising correctly. If the focus point field is inside a Neo block then this would explain the above behaviour.

If you could point me to the focus point plugin you're using, I'll see if I can replicate it and hopefully come up with a way around this problem.

**Comment by avr** [comment]
Thanks, Ben.

I'm using this plugin: https://github.com/smcyr/Craft-FocusPoint

avr

**Comment by ttempleton** [comment]
Sorry for the delay with this, @avr -- you've probably resolved this situation one way or another, but I've been playing around with this and, while I was unfortunately unable to replicate the error from Focus Point (using the version that was most recent at the time of this issue report), the 'nested' blocks looks a lot like issue #128, where an extra row was somehow created in the `neoblockstructures` table for a field/owner/site.  If the affected field has a new block added which allows child blocks, it produces the same behaviour as this.  I suspect that happened in this case and that the Focus Point error was unrelated (or, if anything, that Neo's duplicate block structure situation could have caused Focus Point's error).

Changes have been made, which will be included in the soon-to-be-released Neo 1.5.1, which should ensure that the duplicate block structure situation doesn't happen again.
