### ISSUE TITLE
Blocks > EntryTypes

### ISSUE THREAD

**Issue by alexanderbuergin** [spicywebau/craft-neo#890]
### What question would you like to ask?

Hello spicy web team

Are you planning to move the blockTypes in Neo to entryTypes like the matrix fields? 

This would have the great advantage that you could use the entryTypes in matrix but also in neo fields. 

This would also make it possible to move content between 2 different neofields if the types are allowed in both.

I find the idea and the structure behind neo more logical and better for webdevs but also for authors than matrix fields. However, Craft cms has brought some good basic ideas with Craft 5 which could also be adapted in neo.

I once posted the following ideas on this topic at P&T. These would also be suitable ideas for Neo.

More: https://github.com/craftcms/cms/discussions/14179

Some ideas:

<img width="1478" alt="299119022-4b314beb-04b6-408d-8493-6ebeeccb3973" src="https://github.com/spicywebau/craft-neo/assets/85960512/b49a9235-8b6f-4aa7-9e0b-9a4d881bc90e">

<img width="1707" alt="299107719-ffa53788-3ad5-4b8c-8ad3-617512a82af6" src="https://github.com/spicywebau/craft-neo/assets/85960512/5139cefe-e4b8-4fee-baf2-bcbcfc74c639">

**Comment by ttempleton** [comment]
I'm hoping to have it done by the end of June.

**Comment by alexanderbuergin** [comment]
Cool, thanks
