### ISSUE TITLE
Neo blocks disappear after saving draft as new entry

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-neo#891]
Hi @ttempleton just got the issue on release Neo release `v4.20` which @harry2909 referenced here: https://github.com/spicywebau/craft-neo/issues/823#issuecomment-2126959634

When saving as a new entry, which has draft revisions, the original entry loses it's content.

Potentially happens after a specific job in the queue has completed so doesn't appear to happen immediately. Could be after the queue jobs: `Deleting old Neo blocks` or `Saving Neo block structures for duplicated elements`.

Manage to reproduce and capture the incident on a screen recording:

https://github.com/spicywebau/craft-neo/assets/2337910/1ffa663d-f668-4594-a485-96e5cff2e28d

Please can you take another look?

_Originally posted by @joepagan in https://github.com/spicywebau/craft-neo/issues/823#issuecomment-2145093007_

**Comment by joepagan** [comment]
Hi @ttempleton could we get an update on this one please?
 
We've got a website to put live and the content editors have been holding off adding the entire site content because of this issue.

Thanks

**Comment by ttempleton** [comment]
@joepagan That's fixed now in 4.2.3.
