### ISSUE TITLE
"A server error occurred." Notice when adding a global neo block.

### ISSUE THREAD

**Issue by mjniland1** [spicywebau/craft-neo#892]
### Bug Description

After updating to the latest version of Craft & Neo, we now receive a "A server error occurred." notice when we attempt to add blocks within a global element. This issue is consistent across local and production builds. No additional details are provided within the logs. 

### Steps to reproduce

1. add a neo field to a global element
2. attempt to add a block to the global element
3.

### Neo version

4.2.0

### Craft CMS version

Craft Pro 4.9.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.1 and 5.0.1.
