### ISSUE TITLE
New Neo blocks drop content until saved

### ISSUE THREAD

**Issue by roelvanhintum** [spicywebau/craft-neo#894]
### Bug Description

When creating a new Neo block on an entry, the content wont save the first time and is lost. The block itself is saved, but all fields in it are empty. We downgraded for now to 4.1.3, which fixes the problem.

### Steps to reproduce

1. Create a new Neo block on an entry
2. Fill content fields
3. Save
4. Content fields are empty

### Expected behaviour

Expected behavior would be content in fields within a new Neo block to be saved.

### Neo version

4.2.2

### Craft CMS version

4.10.0

### What is the affected Neo field's propagation method?

all

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this. In the past, content loss on save has tended to involve the Preparse Field plugin - are you using that plugin? If not, then are you able to reproduce the issue on a new Craft install?

**Comment by roelvanhintum** [comment]
No, but here is a complete list of the plugins we're using:

Cache control	1.0.8 // custom plugin, doesn't effect entries etc
CKEditor	3.8.3
CP Field Inspect	1.4.4
Expanded Singles	2.0.5
Field Manager	3.0.8
fortrabbit Object Storage Volume	3.0.0
Hyper	1.1.31
ImageOptimize	4.0.8
Many to Many	3.0.4
Neo	4.1.3
Read-only Field	2.0.1
SendGrid	2.0.1
Sentry SDK	2.0.1
SEOmatic	4.0.50
Super Table	3.0.14

I'll get back on the clean install.

**Comment by Mixxey** [comment]
I am experiencing the same problem (only for new entries; adding content to an existing entry works fine). Here are my installation's specs:

PHP version	8.0.30
OS version	Linux 6.5.0-35-generic
Database driver & version	MySQL 5.7.44
Image driver & version	Imagick 3.7.0 (ImageMagick 6.9.10-23)
Craft edition & version	Craft Pro 4.10.0
Yii version	2.0.50
Twig version	v3.8.0
Guzzle version	7.8.1


Asset Usage	3.3.0
Blitz	4.18.1
CKEditor	3.8.3
Cloudflare	2.1.0
CP Clear Cache	1.3.1
CP Field Inspect	1.4.4
Craft JWT Auth	dev-develop-craft-4
Dumper	5.0.1
Elements Panel	2.0.0
Embedded Assets	4.1.0
Feed Me	5.5.0
Field Manager	3.0.8
Google Cloud Storage	2.2.0
ImageOptimize	4.0.8
Logs	4.0.1
Navigation	2.0.28
Neo	4.2.2
Remote Backup	4.1.6
Retour	4.1.16
Sentry SDK	3.0.0
SEOmatic	4.0.50
Smith	2.0.1
Wordsmith	4.4.0

**Comment by Tim-Wils** [comment]
Client of ours experienced the same problem. Only when creating new entries.

**Comment by ttempleton** [comment]
@roelvanhintum @Mixxey @Tim-Wils If possible, could one of you please post a screen recording showing the full process that leads to it? I'm still unable to reproduce this, so hopefully that helps me figure out what I'm missing.

**Comment by Mixxey** [comment]
Sorry for everything being in German 😅

[Recorded Session](https://www.loom.com/share/cb751e9e1bcd4d049bce87e29ad7d320?sid=c7feda8c-5477-434d-8cb3-01900e536778) - I hope the link works!

Here is what happens:

1. I create a new entry.
2. I add some content to a Neo block.
3. I save the entry (Ctrl+S) -> Block is empty
4. I create another block + save again -> Block is empty
5. I create yet another block + save again -> Content of the block is saved

I hope this helps :)

**Comment by ttempleton** [comment]
Thanks @Mixxey - can confirm I have reproduced the issue after watching the recording.

**Comment by ttempleton** [comment]
I've just released 4.2.4 to fix this bug. Please let me know if the issue persists after updating, though.

**Comment by ayush000** [comment]
Hey! We're getting the exact same issue in Craft 5. Are you planning to fix this for Craft 5 too?

**Comment by ttempleton** [comment]
@ayush000 that's fixed now in 5.0.4.
