### ISSUE TITLE
Maximum Top Level Blocks?

### ISSUE THREAD

**Issue by away86** [spicywebau/craft-neo#90]
Do we have ability to set maximum number of top level blocks? 

I have this neo field with top-level block type called 'tabs' which is used for front-end tabs, and I have a couple of sub-matrix inside. 

When I set the 'Max Block' of this neo field to 5, I was expecting it could help limiting to 5 tabs. However,  seems like it counts every single sub blocks as well.

Current workaround is to set 'Max Block' to blank, but I sort of want to limit the tabs site admins can create.

**Comment by benjamminf** [comment]
You're right, it does count all blocks in the field. I had this setting before I had the "Max Child Blocks" setting, so it no longer makes much sense to have it count all blocks in the field. I'm very likely going to change it's behaviour for the next release.

**Comment by ttempleton** [comment]
A max top-level blocks field setting has now been added to the `dev` branch and will be included in Neo 2.3.  The existing max blocks setting has been retained (for now, at least).
