### ISSUE TITLE
"Save blocks to all sites..." saves blocks, but misses content of fields

### ISSUE THREAD

**Issue by timoGroba** [spicywebau/craft-neo#900]
### Bug Description

When saving Neo elements in a multilingual website, the elements and their contents are intended to be copied to other languages upon initial save. Currently, while the Neo blocks are duplicated across languages, the fields within these blocks remain empty in the other languages.

### Steps to reproduce

1. Create a multilingual website in Craft CMS.
2. Add Neo elements with content in the primary language. Fields should be translatable for each Site
3. Save the entry.
4. Switch to a secondary language.

### Expected behaviour

Neo elements and their contents should be copied to the other languages, with all fields populated as they are in the primary language.

### Neo version

4.2.4

### Craft CMS version

4.10.1

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by timoGroba** [comment]
Further testing has shown that this is most likely not a Neo-issue, but a general problem with craft-fields.

**Comment by timoGroba** [comment]
After chatting with Craft Support, we concluded that the issue might actually be with Neo and not with Craft.

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.6.
