### ISSUE TITLE
Preview on collapsed fields are not aligned with block title

### ISSUE THREAD

**Issue by elfacht** [spicywebau/craft-neo#901]
### Bug Description

With Craft 5.2.3 and Neo 5.0.3 the preview on collapsed fields are cut-off and image thumbnails are broken:

![Screen shot 2024-06-26 um 10 11 22](https://github.com/spicywebau/craft-neo/assets/529443/5c254381-5bd1-4f3a-b48f-12813ff86064)

### Steps to reproduce

1. Create a Neo field with multiple blocks (in this case all blocks have multiple tabs) and add different type of fields to them (entries, text, etc.)
2. Enable **Collapse all blocks?** in the Neo settings.
3. Go to an entry with the field and add several blocks with content and save.
4. The blocks should be collapsed and the preview should look like the screenshot.
 

### Expected behaviour

The preview text should be aligned with the block title:

![Screen shot 2024-06-26 um 10 18 28](https://github.com/spicywebau/craft-neo/assets/529443/0bfaf764-a2fc-45b6-9fe6-efeadfe68619)

Also the images thumbnails should no be broken.

### Neo version

5.0.3

### Craft CMS version

5.2.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.0.4.
