### ISSUE TITLE
Getting this message "Entries can only be created after the Neo block has been saved." if autoSaveDrafts is false

### ISSUE THREAD

**Issue by ayush000** [spicywebau/craft-neo#903]
### Bug Description

If I try to add a neo block to a new entry, all matrix fields within that neo block cannot be added unless a draft is saved first. In craft-neo 5.0.1, it was possible to populate matrix fields within neo block without needing to save a draft (unless there was some error in the form). But something changed in later versions. In 5.0.4, it's not possible to populate matrix fields nested within neo block. If it's a required field, there is no way to create an entry without saving a draft first
![image](https://github.com/spicywebau/craft-neo/assets/1942688/2009ecf1-c859-4760-8847-2708d620c3c3)

Once I save a draft, I'm able to create matrix within neo block.
![image](https://github.com/spicywebau/craft-neo/assets/1942688/67acbf76-c756-4d76-858f-53dfd9bb6c01)

### Steps to reproduce

1. Set `autoSaveDrafts` to false in CMS config
2. Create a new entry
3. Add a neo block that contains a matrix field
4. The matrix field shows this message "Entries can only be created after the Neo block has been saved."

### Expected behaviour

I should be able to create matrix fields within neo blocks without having to save a draft.

### Neo version

5.0.4

### Craft CMS version

5.2.0

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.0.5.
