### ISSUE TITLE
Migrate to Matrix

### ISSUE THREAD

**Issue by andrewfairlie** [spicywebau/craft-neo#905]
### What question would you like to ask?

Is there a mechanism to migrate Neo to Matrix?

I’m aware Neo has its own abilities beyond Matrix but for our usage it isn’t required anymore. Ideally there’d be a CLI to migrate to Matrix.

**Comment by ttempleton** [comment]
Neo on Craft 5 includes the equivalent functionality for converting to Matrix that has been included in Neo on previous versions of Craft - a conversion of Neo blocks to Matrix entries, conversion of Neo block types to entry types, and loss of block structure. Conversion can be activated either by a prompt that appears on the field settings page of a Neo field when changing its field type to Matrix, or when uninstalling Neo.

We have no plans to include functionality for converting child blocks into nested Matrix fields. See https://github.com/spicywebau/craft-neo/issues/895 for more of my comments on this.
