### ISSUE TITLE
No owner ID assigned to the Neo block error with Solspace Calendar events

### ISSUE THREAD

**Issue by wolf-ms** [spicywebau/craft-neo#909]
### Bug Description

When creating a new event using the Solspace Calendar plugin, new Neo blocks can't be added to the layout. An error of "Request failed of status 500" appears. The only fix I found was to rollback Neo to version 4.1.2 from 4.2.7. In the web log, there is the following error: `[yii\base\InvalidConfigException] yii\base\InvalidConfigException: No owner ID assigned to the Neo block. in /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php:604 `
![Neo-500-error](https://github.com/spicywebau/craft-neo/assets/132366871/ae166514-773e-48f8-9812-7700399cc872)

### Steps to reproduce

1. Install both Neo ^4.2.5 and Solspace Calendar ^5.0.0.
2. Create a new Calendar Event entry with a Neo field added to the layout.
3. Click to add a new Neo block

### Expected behaviour

A new Neo block should appear.

### Neo version

4.2.7

### Craft CMS version

4.10.2

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by luke-nehemedia** [comment]
Same issue here with the same CraftCMS and neo version.

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.8.
