### ISSUE TITLE
[Craft 5] "Save as new entry" looses all content from the new entry

### ISSUE THREAD

**Issue by AleksanderKampus1** [spicywebau/craft-neo#910]
### Bug Description

In Craft you can save entries as new entries. However when doing it, it duplicates the entry but all content is lost from that new entry.  

### Steps to reproduce

1. Set autoSaveDrafts to false in CMS config (not sure if it's the same with autosaveDraft turned on)
2. Choose an entry / create a new entry
3. On the right of the `Create entry` button click the `arrow down` button and from the dropdown click `Save as new entry` 
4. There is no content inside that new entry. 

### Expected behaviour

The new entry should have all the same content from the original entry. 

### Neo version

5.0.2 (tried with the latest, it's also not working)

### Craft CMS version

5.2.0 (tried with the latest, it's also not working)

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release.

**Comment by Tim-Wils** [comment]
@ttempleton Awesome! Could this also be the problem we have in 4.x? At the following line:
https://github.com/spicywebau/craft-neo/blob/4.x/src/Field.php#L1030

**Comment by ttempleton** [comment]
@Tim-Wils Saving as a new entry is working as expected for me on 4.x. If you're also using the Preparse Field plugin, disable it and try again. If it still happens, or if you're not using Preparse Field on that project, please feel free to open a new issue.
