### ISSUE TITLE
Propagation rules + Translation rules

### ISSUE THREAD

**Issue by pnpaes** [spicywebau/craft-neo#916]
### What question would you like to ask?

I have a website running on CraftCms 4.10.6 and NEO 4.2.8.
This is a multisite instalaltion with 2 sites using english and spanish langauges. What I need to achieve is to keep the content blocks the same, that means that all blocks added or removed in one site will also be added or removed int he other site.
But within those blocks some fields (text fields) will be translatable. Others like images, some settings and cross linking will not.
When I tried to keep the propagation rule "Save blocks to all sites the owner element is saved in" I manage to achieve the first part. But then all content is also changed when I translate in each site, overwritten what is in the other site.
The NEO field is at the root of the entry and is used as a page builder using each of its modules.
The fields used in the modules that should be translated (some text fields, text areas and redactor fields) are marked with the translation rule "Translatable for each language" but doesn't seem to have any effect in this case.

Would really appreciate if I could get some guidance on how can this be achieved.

**Comment by ttempleton** [comment]
That sounds like a bug - but it's working as expected for me with Craft CMS 4.11.1 and Neo 4.2.9.

I'm wondering if another plugin could be conflicting with it - if you disable all other plugins, does it work properly?

**Comment by ttempleton** [comment]
I'm going to close this for now, but let me know if you have any other questions.
