### ISSUE TITLE
[5.x] Child blocks in settings don't indent until interacted with.

### ISSUE THREAD

**Issue by turnstylerj** [spicywebau/craft-neo#918]
### Bug Description

In Neo 5.x, child blocks in the settings panel don't visually indent until they're interacted with.

![2024-07-30 at 14 23 35](https://github.com/user-attachments/assets/c88f6ded-eeff-49a1-9b36-d6ed7abc9681)

This wasn't an issue in 4.x versions of Neo, and makes it somewhat difficult to navigate larger sets of blocks.

### Steps to reproduce

Create a Neo field with at least one child block.

### Expected behaviour

Child block indents automatically.

### Neo version

5.1.1

### Craft CMS version

 5.2.9

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.1.2.
