### ISSUE TITLE
Issue with Content Loss When Migrating Neo Blocks to CraftCMS Entry Types

### ISSUE THREAD

**Issue by alexanderbuergin** [spicywebau/craft-neo#921]
### Bug Description

We encountered a significant issue when updating our Neo fields by migrating from the traditional Neo block field editor to using CraftCMS entry types. Our goal was to streamline and unify the structure of our content fields by transitioning to entry types while maintaining the existing field setup.

### Steps to reproduce
1.	Original Setup:
	•	We had several blocks configured within Neo using the classical block field editor.
	•	Each block contained a set of fields with specific handles.
2.	Migration Process:
	•	We attempted to change the field setup from Neo’s block field editor to Craft entry types.
	•	The entry types were named identically to the existing Neo blocks, and the fields used within these entry types had the same handles as those in the Neo blocks.
3.	Result:
	•	After making the change, all content within the Neo block editor was removed.
	•	Fields that were previously populated with content were now empty.

### Expected behaviour

We expected that by maintaining the same field names and handles, the migration to Craft entry types would preserve the existing content. Since the structural change did not involve altering the field handles or data types, the content should have been retained.

### Actual Behavior:

The transition resulted in complete data loss within the Neo blocks. All previously populated fields became empty despite the fields in the entry types being set up identically to those in Neo.

Please let us know if you need further details about our setup or if there are specific logs or configurations we should provide to assist in resolving this issue.

### Neo version
5.1.2

### Craft CMS version
5.2.9

**Comment by alexanderbuergin** [comment]
### Before
<img width="1672" alt="Bildschirmfoto 2024-08-03 um 00 46 40" src="https://github.com/user-attachments/assets/8c178ee2-90b6-4010-a81f-cf6154f24fb7">

### After
<img width="1675" alt="Bildschirmfoto 2024-08-03 um 00 45 36" src="https://github.com/user-attachments/assets/7ca51a7a-a0b9-47b5-994b-07a97baca52b">

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.1.3.
