### ISSUE TITLE
New version of Craft CMS breaks NEO

### ISSUE THREAD

**Issue by philippe-leeroy** [spicywebau/craft-neo#922]
### Bug Description

After the update to Craft 4.11.x, i've noticed some issues : 

- Some Neo blocks* with empty matrix, cannot be deleted.
- The button to add a matrix block inside a Neo block trigger nothings. 

*Note that, since we began to develop our project, i created a lot of Neo block with matrix field and put content inside. For most of them, after updates maybe, the matrix field was empty. On my point of view, this is not really stable and I'm a little worried when we puit that in production. :grin: 

### Steps to reproduce

Have some Neo block with matrix field.

Try to add a block in a matrix field...

### Neo version

4.2.9

### Craft CMS version

4.11.1

### What is the affected Neo field's propagation method?

Don't think it's related to that.

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm guessing this is being caused by the JavaScript error that was fixed yesterday in 4.2.10. If you still have this issue after upgrading, please let me know, along with any JavaScript errors that appear in the browser console, and I'll reopen the issue.

**Comment by leevigraham** [comment]
@ttempleton Neo 4.2.10 fixed this issue for us as well as https://github.com/verbb/hyper/issues/182

**Comment by philippe-leeroy** [comment]
Thanks @ttempleton, it seems all good.
