### ISSUE TITLE
For revisions the content of a Neo field show for a split second

### ISSUE THREAD

**Issue by bberlijn** [spicywebau/craft-neo#926]
### Bug Description

https://github.com/user-attachments/assets/88fc21fa-79d1-4fcc-bcf8-598e12a2a4c1

When viewing any revision, the content is only visible for a split second, and then just disappears. This does not happen for the current version of the entry.
Reverting to a revision would result in the Neo field having no content, so that's also not working.

Could be related to https://github.com/spicywebau/craft-neo/issues/899 since restoring the revision would result in a the Neo field being empty?

### Steps to reproduce

- Install Craft with the Quick start guide (https://craftcms.com/docs/5.x/install.html)
- Install Neo
- Create section, entry type, Neo field and add the Neo field to the entry type
- Create new entry and edit it
- Go to one the revisions
- See content disappear

### Expected behaviour

The content should stay visible.

### Neo version

5.2.0

### Craft CMS version

5.3.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed for the next release.
