### ISSUE TITLE
Newly added blocks are not expanded

### ISSUE THREAD

**Issue by erikberger** [spicywebau/craft-neo#928]
### Bug Description

I updated Neo on a Craft 4 install from 4.1.2 to 4.2.10 and now have an issue when adding new block where they are not expanded. Further, the new block does not expand when selecting "Expand" in the cog dropdown. The only way I can get the block to expand is by double clicking on its bar, which shows a flash of expansion but remains closed. However, I can then expand using the dropdown.

https://github.com/user-attachments/assets/a29515e8-ce09-4449-bc96-41f39954d228

### Steps to reproduce

Using Craft 4.11.3 and Neo 4.2.10

1. Set `'collapseAllBlocks' => true` in `/config/neo.php`
2. Add a new block to a Neo field
3. Note that that the new block is not expanded and does not expanded unless the bar is double clicked

### Expected behaviour

Newly added blocks should be expanded so they are ready for content population.

### Neo version

4.2.10

### Craft CMS version

4.11.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.11 and 5.2.1.
