### ISSUE TITLE
Reorder of child block

### ISSUE THREAD

**Issue by kringkaste** [spicywebau/craft-neo#93]
Hi!

We have a small problem here: If you only reorder the child blocks of a neo block and press save, the reorder is not saved and everything is in the same old order. But if you reorder the child blocks and change something within a child block, then the new order is saved. It seems, that the reordering of the child blocks without changing the content is not recognized as "change".

Regards,
Thomas

**Comment by benjamminf** [comment]
Reordering true Neo child blocks should always update when saving the entry. The structure for the field gets regenerated every time. When you're talking about child blocks, are you maybe referring to a Matrix or SuperTable field inside a Neo block?

Also, what browser/version are you using?

**Comment by ttempleton** [comment]
I'm going to close this issue, given its age and no other reports of the issue, but if you do continue to experience the issue, let us know and we'll reopen.
