### ISSUE TITLE
Neo Field Hierarchy Lost When Moving Entries Between Sections in Craft 5.3

### ISSUE THREAD

**Issue by alexanderbuergin** [spicywebau/craft-neo#930]
### Bug Description

We are experiencing an issue with the Neo plugin when moving entries between sections in Craft 5.3. This new feature in Craft allows us to move entries across sections, but it is causing a problem where the hierarchical content within Neo fields is being lost.

### Steps to reproduce

Create an entry with a multi-level Neo field, containing blocks structured in two or three levels.
Move this entry from one section to another using the new section moving feature in Craft 5.3.
After the move, the Neo field hierarchy is flattened to a single level. All nested blocks are lost, and only a flat list of blocks remains.

### Expected behaviour

The multi-level hierarchy of Neo blocks should be preserved when moving entries between sections.

###A ctual Behavior

The hierarchy of Neo blocks is flattened, losing all nested structures after moving entries between sections.

### Neo version
5.2.2

### Craft CMS version
5.3.4

**Comment by ttempleton** [comment]
It happens during [this call to `$entry->afterPropagate()`](https://github.com/craftcms/cms/blame/5.3.4/src/services/Entries.php#L1955), and I'm not entirely clear on why that's being called, since `afterPropagate()` would have been run when [the entry was saved](https://github.com/craftcms/cms/blame/5.3.4/src/services/Entries.php#L1930).

**Comment by ttempleton** [comment]
Fixed for the next release. In the meantime, you can get the fix by changing your `spicyweb/craft-neo` requirement in composer.json to `5.x-dev as 5.2.2` and running `composer update`. Thanks for reporting!

**Comment by alexanderbuergin** [comment]
Thanks :)

**Comment by ttempleton** [comment]
Neo 5.2.3 now released.
