### ISSUE TITLE
[Craft 5] Neo Block Conditions for fields/tabs in field layouts of of block types are not working

### ISSUE THREAD

**Issue by Odobros** [spicywebau/craft-neo#932]
### Bug Description

Every time I try to add a condition (via Neo Block Conditions) to any field or tab inside a block type created in Neo field, I see loading for a second and then nothing happens.

After this unsuccess, a response error shows in console.

### Steps to reproduce

1. Go to your neo field
2. Switch to any of your block types
3. Go to field layout
4. Click on 3 dots next to any field or tab
5. Click on settings
6. In Neo Block Conditon, try to add any condition
7. You will see a loading circle for a brief moment and then no condition appears

<img width="923" alt="Snímek obrazovky 2024-08-23 v 9 31 12" src="https://github.com/user-attachments/assets/ec2e68a1-6a9b-46b4-a749-a54b9b5cf9c1">

### Expected behaviour

After selecting any field etc in the Neo Block Condition, a condition should appear to set it up.

### Neo version

5.2.2

### Craft CMS version

5.3.4

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by lavandongen** [comment]
We had the same issue while working on a project. I downgraded NEO to version 5.1.1 and the issue disappeared. Hopefully a fix is submitted soon.

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in Neo 5.2.3.
