### ISSUE TITLE
CP UI Issue with Paddings/Lines

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#933]
### Bug Description

Not sure where the root of this issues lies but since an update of CraftCMS or Neo since the 5.x update we have some styling issues on entry edit pages.

This happens within NEO Blocks/Field. It looks like if some paddings are missing.

![Screenshot 2024-08-26 at 09 15 03](https://github.com/user-attachments/assets/7af882d4-3564-4915-8d0c-ded433304b01)

Like the HR to separate fields which has no padding, regular fields seem to always get horizontal padding.

![Screenshot 2024-08-26 at 09 22 57](https://github.com/user-attachments/assets/642d9dd5-df26-41fd-8861-e524b865afd1)
![Screenshot 2024-08-26 at 09 22 48](https://github.com/user-attachments/assets/2c0f4841-aed1-44f8-80e0-97c8243a5df7)

And then there is this vertical line showing, which shouldn't be there.

![Screenshot 2024-08-26 at 09 23 23](https://github.com/user-attachments/assets/23fc3168-8548-49aa-8173-7b050502b6a4)

I disabled all custom styling within the controlpanel, also we see this on different pages running different version of CraftCMS and the NEO Plugin since the 5.x update.

Any ideas what's happening here? Let me know if I can provide additional info.

### Steps to reproduce

Not sure.

### Neo version

5.2.2

### Craft CMS version

5.3.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release.

**Comment by ttempleton** [comment]
Neo 5.2.3 now released.
