### ISSUE TITLE
Failed task relating to invalid section which I intentionally deleted

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#934]
### What question would you like to ask?

Working on a redesign for a Craft 4 site. It previously had a "Work" Single section with an ID of 11. I've deleted that section since then and have continued working on the site with no issues.

Recently, I added another site to the install for a small satellite site. I also poked my nose into some of the existing Neo fields to update their propagation methods. As a result, there were a lot of tasks in the queue manager. All of them ran successfully, except for the one shown below:

![image](https://github.com/user-attachments/assets/e58feb17-86fd-48b9-9c26-807d1e094599)

Seeing as it's related to section 11, is this safe to just release? Is there any info I can give you to help avert this in the future? Thanks!

Craft 4.8.6 -> 4.11.4 (live site -> local dev site)
Neo 4.0.2 -> 4.2.10

**Comment by proimage** [comment]
...aaand now I've got this error when trying to save the Homepage entry: 
![image](https://github.com/user-attachments/assets/c7344486-6681-4b2e-a399-c27d7a16a4d3)

**Comment by ttempleton** [comment]
It would be safe to release that job - but I'm unsure how it happened in the first place. Is there any relevant information in the queue logs?

Regarding the other error - if possible, could you please send your database backup and Composer files to plugins@spicyweb.com.au and I'll have a look.

**Comment by proimage** [comment]
I wiped out the `storage/logs/` directory, re-ran the task, and sent the queue log along with the rest of the information by email. Thanks so much for the help!!

**Comment by proimage** [comment]
FYI, I have a number of project config changes locally that I've not pushed to the site's staging server yet. Said staging server is not affected by the issue(s) I ran into here. When I import the DB from the staging server and reapply the project config changes, the problem returns after a pretty long queue of tasks. Ergo, I think the trigger/cause of the problem is found in the uncommitted project config files I have. If those and the staging site DB would help, I can provide them as well.

**Comment by ttempleton** [comment]
Thanks for sending that through! I believe both issues should be fixed now in Neo 4.2.12. Please let me know if you continue to experience this or similar issues, though.

**Comment by proimage** [comment]
Thank you so much for the rapid response! I'll test things out and get back to you.

**Comment by proimage** [comment]
That seems to have done the trick indeed—thank you so much once again, I was under the gun with this project! 🤩💪
