### ISSUE TITLE
Saving a third-level block causes blocks to pop out to top level

### ISSUE THREAD

**Issue by TheFunkyMonk** [spicywebau/craft-neo#937]
### Bug Description

When editing content for a Neo field with blocks that can go 3 levels deep and saving, many of the child blocks that aren't allowed at the top level "pop" out of their containers, triggering validation errors and rendering the entry unable to save.

![2024-08-29 at 14 13 50](https://github.com/user-attachments/assets/2311d9b2-ed27-44d7-8ce5-b7503a60417e)

I've attempted completely deleting all the content of this field and re-creating it, after which it was working for a while, but eventually got back to the same state with no settings-level changes to the field.

### Steps to reproduce

Honestly, this one might be difficult to reproduce. I've tried reproducing it with simpler use cases but haven't been able to reliably reproduce it outside of situations where I've had content in the field for a while and return to adjust a third-level item. Glad to provide a current DB backup and composer files/repro instructions if you have a support email.

### Expected behaviour

Third-level blocks maintain their level/position on entry save.

### Neo version

5.2.3

### Craft CMS version

5.3.6

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
- Are you using the Preparse Field plugin? If so, does disabling it let saving work properly?
- If you're not using Preparse Field, does updating to 5.2.4 and running `php craft gc/run` resolve the issue? (in case this has the same underlying cause as #927)

**Comment by turnstylerj** [comment]
Unfortunately, negative for both of those. I just emailed a db backup and composer files with the entry reference to the email mentioned in that issue if it's helpful!

**Comment by ishetnogferre** [comment]
We have the same issue and also negative for the questions earlier.. It's making our production website quite unusable and deleting content that (almost) can't be brought back.

Anything we can provide that can help finding and resolving the issue? For us it's even on Neo blocks on the first level.

**Comment by turnstylerj** [comment]
Hey @ishetnogferre this may still be in-progress, but I just updated to Neo 5.2.5 (just released) and ran `php craft gc/run`, and it resolved the issue for the entry we were experiencing it on.

**Comment by ttempleton** [comment]
Thanks for sending those files @turnstylerj - I can confirm that running garbage collection with the latest version of Neo resolves the issue. I'll close this for now, but please let me know if the issue resurfaces in the future.
