### ISSUE TITLE
Missing «Select All Blocks» Functionality After Updating to Craft 5

### ISSUE THREAD

**Issue by alexanderbuergin** [spicywebau/craft-neo#944]
### Bug Description

After updating from Craft CMS 4 to Craft 5, the NEO plugin no longer supports the ability to select all blocks using Command-A. This feature was highly useful in Craft 3 and 4 for managing content efficiently with NEO fields.

I kindly request the reintroduction of this functionality in Craft 5, as it was invaluable when working with large sets of blocks in NEO.

https://github.com/user-attachments/assets/f82bfe40-fd8c-4cb3-9b06-1545d918a713

### Steps to reproduce

- Update to Craft 5
- Attempt to use Command-A to select all blocks within a NEO field
- The function no longer works

### Expected behaviour

Command-A should select all blocks in a NEO field, as it did in previous versions.

**Thank you!**

### Neo version

5.4

### Craft CMS version

5.2.6

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed now in 5.2.7.
