### ISSUE TITLE
"Calling unknown method" error when a matrix block doesn't have a field.

### ISSUE THREAD

**Issue by MargaritaBusyginaCa** [spicywebau/craft-neo#945]
### Bug Description

I'm trying to implement a check in my code to ensure variables are only used if they exist. I tried two approaches:
```
{% set testing = block.test ?? "not found" %}  
 <p>{{testing}}</p>
```
And
```
{% set testing = block.test is defined ? "found" : "not found" %}  
 <p>{{testing}}</p>
```
Both methods throw the `Calling unknown method: benf\neo\elements\Block::test()`, whereas I want them to assign a "not found" string to the `testing` variable. 

### Steps to reproduce

Call a field that doesn't exist in your matrix, for example:
```
{% set testing = block.test ?? "not found" %}  
```

### Expected behaviour

The expression is falsy and returns "not found" string.

### Neo version

4.2.13

### Craft CMS version

4

### Does this issue involve templating, and if so, is eager-loading used?

This is a templating issue, and eager loading is not used

**Comment by ttempleton** [comment]
This is the expected behaviour across Craft elements in general, not just Neo blocks. You would need to check it like this:

```twig
{% set testing = block['test'] ?? "not found" %}  
```
