### ISSUE TITLE
Conditional fields based on parent block values don't hide until draft save

### ISSUE THREAD

**Issue by TheFunkyMonk** [spicywebau/craft-neo#946]
### Bug Description

When you have a child block with conditional fields set to show/hide based on a condition in the parent block (a dropdown value in this case), all fields in the child block show on block creation and the appropriate fields only hide after content is changed/a draft is saved.

![2024-09-20 at 09 36 42](https://github.com/user-attachments/assets/3ef7db30-2a89-4f63-b90d-89445ad6ab38)

### Steps to reproduce

- Create a Neo block with a dropdown field
- Create a child block with 1 block minimum and several fields set to hide based on the selection of the dropdown
- Create an instance of the field

### Expected behaviour

Fields with visibility conditions will show/hide on block creation

### Neo version

5.2.6

### Craft CMS version

5.4.4

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by TheFunkyMonk** [comment]
Likely the same fix, but just an update that I noticed this behavior when cloning a block as well.

![2024-09-23 at 12 55 32](https://github.com/user-attachments/assets/b1300ead-53ef-4343-a144-0c4b85913300)

**Comment by ttempleton** [comment]
Thanks for reporting this - fixed for the next release.

**Comment by ttempleton** [comment]
Now fixed in 5.2.19.
