### ISSUE TITLE
Invalid field handle of the matrix field when updating search indexes

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [spicywebau/craft-neo#947]
### Bug Description

This error happens when the matrix field is assigned to some Neo block and this matrix field has enabled setting `Use this field’s values as search keywords`.

When save some entry with the Neo field and add there the block with such matrix field, the job `Updating search indexes` will be created and status in the queue will be `failed` 
<img width="1050" alt="Screen Shot 2024-09-22 в 00 54 13" src="https://github.com/user-attachments/assets/b2fd30f2-7e7c-45de-a6b0-ee4f4ac042d7">

No error is triggering if assign the same matrix field to some entry directly, outside the block of Neo field.

This happens with `Craft 5.4.0.1` and `Neo 5.2.3`, but I also tested with newest `Craft 5.4.4` and `Neo 5.2.6`, the result is the same.

### Steps to reproduce

1. Create a matrix field with enabled setting `Use this field’s values as search keywords`
2. Created the Neo field and a block type. Assign the newly created matrix field to that Neo block type
3. Assign Neo field to some section
4. Go to that section page and create a new entry. Add the Neo block type that contain that matrix field, put some values in there
5. Go to the queue page and you will see the job with status `failed`

### Expected behaviour

Job in the queue `Updating search indexes` should be finished successfully

### Neo version

5.2.3

### Craft CMS version

5.4.0.1

### What is the affected Neo field's propagation method?

Save entries to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
If possible, could you please send your composer.json, composer.lock and database backup (with some failed search index jobs left in the queue) to plugins@spicyweb.com.au, and we'll have a look.

**Comment by nikolenko-dmitriy** [comment]
@ttempleton sure, just sent files to plugins@spicyweb.com.au

**Comment by ttempleton** [comment]
Thanks for sending those files in - this is now fixed in Neo 5.2.8.
