### ISSUE TITLE
Neo blocks become unusable 

### ISSUE THREAD

**Issue by ishetnogferre** [spicywebau/craft-neo#948]
### Bug Description

A neo field with multiple nested blocks, after the first block all the functionality stops working. Tab labels overlap and collapse/expand functionality only works in first block. The rest is unresponsive.

![Screenshot 2024-09-24 at 15 03 18](https://github.com/user-attachments/assets/0aa72738-4f82-4549-a479-9b33c59645c0)

Javascript error shown in the console:
![Screenshot 2024-09-24 at 15 03 22](https://github.com/user-attachments/assets/ccd035bb-a87f-4c85-a1cb-8a0806e0a0b8)
 

### Steps to reproduce

A neo field with some sub blocks

### Neo version

4.2.14

### Craft CMS version

4.12.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
This is being caused by https://github.com/craftcms/cms/issues/15784.
