### ISSUE TITLE
Category Field w/o Categories = Internal Server Error upon Saving

### ISSUE THREAD

**Issue by spAnser** [spicywebau/craft-neo#95]
If you have no categories created and you use a category field inside a Neo field. It will prevent the entry from being saved.

**Comment by benjamminf** [comment]
I can't seem to reproduce this. Can you post the error details?

**Comment by ttempleton** [comment]
I'm going to close this issue, given its age and no other reports of the issue, but if you do continue to experience the issue, let us know and we'll reopen.
