### ISSUE TITLE
Performance of Neo after update vom Craft 4.x to Craft 5.x (CP)

### ISSUE THREAD

**Issue by mfell** [spicywebau/craft-neo#950]
### What question would you like to ask?

I’m a heavy Neo user, and my “Content Builder” contains many block types, fields, and options. I built this with Craft 4.x, and overall, I’ve been very happy with it. The performance of Neo in the Control Panel was quite satisfactory.

However, after updating to Craft 5, the performance has significantly slowed down—it’s about 30 times slower! I have one entry that houses my UI library, so there’s a lot of content within it. Now, it’s nearly unusable.

Previous setup:

	•	Craft 4.12.4.1, Neo 4.2.14

Current setup:

	•	Craft 5.4.5.1, Neo 5.2.7

The code and content remained the same, aside from dealing with the usual update issues. Have you noticed this kind of performance drop as well?

**Comment by mfell** [comment]
This is a screenshot: 1st row Craft 4 and Neo 4, 2nd row Craft 5 and Neo 5 ... equal content, just updated.

That's a huge difference?

![Bildschirmfoto 2024-09-27 um 19 00 38](https://github.com/user-attachments/assets/1c451d5c-79cc-42f7-807c-6a420e9e2a55)

**Comment by ttempleton** [comment]
It's hard to tell without knowing e.g. how many blocks the entry has or the field types being used, but two Craft 5 projects I'm working on don't seem to have any major performance issues:

<img width="1231" alt="Screenshot 2024-09-30 at 20 36 24" src="https://github.com/user-attachments/assets/9de0ea4d-2422-4542-95d5-6e134c438f26">
<img width="1322" alt="Screenshot 2024-09-30 at 20 36 48" src="https://github.com/user-attachments/assets/99dfdd06-1a3e-4d75-b9bb-1f0477239ffe">

If you disable other plugins, how much (if any) does that improve performance?

**Comment by mfell** [comment]
Hi Thomas, thanks for your response.

Yes, of course, it’s hard (if not impossible) for you to answer my question without knowing my specific code.

I noticed this issue after upgrading my boilerplate to Craft 5.x and comparing my UI library page. My content builder (Neo field) contains 40 block types and sub-block types, and overall, I’m using 116 fields in my project.

I know that’s a lot, but with Craft 4.x, everything worked perfectly, and I was still very satisfied with it. However, since upgrading to Craft 5.x, I’ve encountered a significant performance issue.

When I remove this Neo field from the entry type, everything works fine again (see the screenshots).

I’ve also tried disabling several plugins, including “ether/seo,” “robuust/craft-reverserelations,” “verbb/field-manager,” “xpertbot/craft-wheelform,” and “verbb/user-group-field.” While this has had a small positive impact, the improvement is not enough.

The issue is limited to the control panel, so I’m not sure what options I have to resolve this. When only a few block types are used in the Neo field, the slowdown is not noticeable, but reducing the number of block types isn’t a viable solution for me.

Let me know if you need any further adjustments ... or what I can do for more support.

### with my content builder (Neo field) (Control Panel)
<img width="665" alt="Bildschirmfoto 2024-09-30 um 14 09 16" src="https://github.com/user-attachments/assets/cfc17f0a-cf61-447d-b45a-9a1c183f60a2">

### WITHOUT my content builder (Neo field) (Control Panel)
<img width="1264" alt="Bildschirmfoto 2024-09-30 um 14 06 14" src="https://github.com/user-attachments/assets/f62842e2-3f56-4fad-b001-9f2ee17ff208">

### used plugins
		"craftcms/ckeditor": "4.2.0",
		"craftcms/cms": "5.4.6",
		"doublesecretagency/craft-cpbodyclasses": "3.0.0",
		"doublesecretagency/craft-cpcss": "3.0.0",
		"doublesecretagency/craft-cpjs": "3.0.0",
		"ether/seo": "v5.0.0-rc5",
		"nystudio107/craft-vite": "5.0.1",
		"putyourlightson/craft-dashboard-begone": "3.0.0",
		"robuust/craft-reverserelations": "3.0.0",
		"spicyweb/craft-embedded-assets": "5.1.2",
		"spicyweb/craft-neo": "5.2.7",
		"verbb/field-manager": "4.0.2",
		"verbb/user-group-field": "4.0.0",
		"vlucas/phpdotenv": "^5.4.0",
		"xpertbot/craft-wheelform": "4.0.2"

**Comment by mfell** [comment]
Until now, I’ve only tested this issue in a local environment using DDEV.  
Today, I set up a staging environment on my hosting (shared hosting):

Craft 4.x / Neo 4.x: No issues at all.
Craft 5.x / Neo 5.x: PHP Fatal Error (running out of memory).

The Neo configuration and the number of fields remained the same. The only change I made was replacing Hyper with Craft 5’s native link field.

Of course, I don’t want to cause too much trouble, but I’m thinking about why the database query count has increased so dramatically.

## edit

It seems that the key to solving my issue is to reduce the number of block types and field references in my content builder (Neo). This is probably doable since my boilerplate is essentially a “Swiss Army knife” for every possible use case. For real-world projects, I can streamline it and include only the necessary features.

Of course, this would be a more efficient approach, but with Craft 4 and Neo 4, I just didn’t experience any performance issues.

What I’m wondering now is: What’s causing this performance issue? Is it Neo itself, or Craft, since Neo relies on Craft’s functions under the hood? This could be a valuable insight for further development.

**Comment by mfell** [comment]
@ttempleton

In the meantime, I received support from the Craft team, but they’ve confirmed this is not a Craft issue - it seems to be specific to Neo.

Would you be able to take another look at this? I understand it’s nearly impossible to reproduce on your end, but I can provide you with a complete ZIP file containing all the source files, dummy data, and a DB dump for DDEV. I have separate versions prepared for Craft 4 / Neo 4 and Craft 5 / Neo 5.

Unfortunately, this is a major roadblock for me, as I’m unable to proceed with the Craft 5 update due to the performance issue.

**Comment by ttempleton** [comment]
Yes - could you please send that to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by ttempleton** [comment]
Thanks for sending those in @mfell - 5.2.12 has now been released to fix those performance issues. Please let me know if the issues persist, though.

**Comment by mfell** [comment]
@ttempleton Thanks Thomas ... just checked this: Now, I can deal with Neo again and sucseed with the update to Craft 5 :)
