### ISSUE TITLE
yii\base\InvalidArgumentException Cannot create a draft from another draft or revision.

### ISSUE THREAD

**Issue by xinnings** [spicywebau/craft-neo#952]
### Bug Description

<img width="890" alt="image" src="https://github.com/user-attachments/assets/8a263b81-b75f-4dae-a09c-ddb072106a6e">

### Steps to reproduce

This happened when trying to clone a Neo section.
<img width="942" alt="image" src="https://github.com/user-attachments/assets/92af5d4e-89aa-4d41-9186-29c6322d850c">

### Neo version

5.2.9

### Craft CMS version

Craft Pro 5.4.7.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.2.10.
