### ISSUE TITLE
[Craft 4] Error after Update: yii\base\ErrorException Undefined array key ""

### ISSUE THREAD

**Issue by Mixxey** [spicywebau/craft-neo#953]
### Bug Description

After updating from 4.2.13 to 4.2.16 I get the following error whenever I try to save an entry that contains a new (or duplicated) Neo block:

yii\base\ErrorException: Undefined array key "" in /www-root/vendor/spicyweb/craft-neo/src/Field.php:1572
Stack trace:
#0 /www-root/vendor/craftcms/cms/src/web/ErrorHandler.php(79): craft\web\ErrorHandler->handleError(code: '2', message: ''Undefined arra...', file: ''/www-root/vend...', line: '1572')
#1 /www-root/vendor/sentry/sentry/src/ErrorHandler.php(342): craft\web\ErrorHandler->handleError(code: '2', message: ''Undefined arra...', file: ''/www-root/vend...', line: '1572', '[]')
#2 /www-root/vendor/spicyweb/craft-neo/src/Field.php(1572): Sentry\ErrorHandler->handleError(level: '2', message: ''Undefined arra...', file: ''/www-root/vend...', line: '1572', errcontext: '???')
#3 /www-root/vendor/spicyweb/craft-neo/src/Field.php(720): benf\neo\Field->_createBlocksFromSerializedData(value: '['sortOrder' =>...', element: 'class craft\\ele...', fromRequest: 'TRUE')
#4 /www-root/vendor/spicyweb/craft-neo/src/Field.php(702): benf\neo\Field->_normalizeValueInternal(value: '['sortOrder' =>...', element: 'class craft\\ele...', fromRequest: 'TRUE')
#5 /www-root/vendor/craftcms/cms/src/base/Element.php(4229): benf\neo\Field->normalizeValueFromRequest(value: '['sortOrder' =>...', element: 'class craft\\ele...')
#6 /www-root/vendor/craftcms/cms/src/base/Element.php(4432): craft\elements\Entry->setFieldValueFromRequest(fieldHandle: ''contentBuilder...', value: '['sortOrder' =>...')
#7 /www-root/vendor/craftcms/cms/src/controllers/ElementsController.php(2111): craft\elements\Entry->setFieldValuesFromRequest(paramNamespace: ''fields'')
#8 /www-root/vendor/craftcms/cms/src/controllers/ElementsController.php(1117): craft\controllers\ElementsController->_applyParamsToElement(element: 'class craft\\ele...')
#9 /www-root/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\ElementsController->actionSave()
#10 /www-root/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/www-root/vendor/yiisoft/yii2/base/InlineAction.php:57}(callback: '[0 => class cra...', args: '[]')
#11 /www-root/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(params: '[]')
#12 /www-root/vendor/yiisoft/yii2/base/Module.php(552): craft\controllers\ElementsController->runAction(id: ''save'', params: '[]')
#13 /www-root/vendor/craftcms/cms/src/web/Application.php(341): craft\web\Application->runAction(route: ''elements/save'', params: '[]')
#14 /www-root/vendor/craftcms/cms/src/web/Application.php(640): craft\web\Application->runAction(route: ''elements/save'', params: '[]')
#15 /www-root/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(request: 'class craft\\web...')
#16 /www-root/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(request: 'class craft\\web...', skipSpecialHandling: '???')
#17 /www-root/web/index.php(21): craft\web\Application->run()
#18 {main}

![screencapture-craftcms-test-cmsadmin-entries-contentpage-129164-handwerkersoftware-2024-10-15-16_06_21](https://github.com/user-attachments/assets/7ad189b4-55c3-455b-84aa-3b344d1fe535)

### Steps to reproduce

1. Open existing entry or create new one
2. Add new Neo block or duplicate existing one
3. Save entry
4. Error occurs, entry is not saved

### Expected behaviour

Entry should be saved normally.

### Neo version

4.2.16

### Craft CMS version

4.12.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.17.

**Comment by Mixxey** [comment]
Great! Thanks so much! :)
