### ISSUE TITLE
[4.x] There was a problem getting the parent element.

### ISSUE THREAD

**Issue by npluimers** [spicywebau/craft-neo#954]
### Bug Description

When saving an entry with a new block nested inside a new block the "There was a problem getting the parent element." exception occurs

### Steps to reproduce

Disable autosave

1. Create a new entry and save it
2. Place a new NeoBlock on this page (don't save), with a field for more NeoBlocks
3. Place a child block inside this new NeoBlock
4. Try to save the page

![image](https://github.com/user-attachments/assets/d2348bac-e4c5-43ad-b172-047823d1fbf6)

### Expected behaviour

Page is saved, block structure is maintained

### Neo version

4.2.17

### Craft CMS version

4.12.6.1

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in 

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.18.
