### ISSUE TITLE
[5.2.14] Cloned Neo block is invalid and merges with the source block

### ISSUE THREAD

**Issue by mfell** [spicywebau/craft-neo#957]
### Bug Description

A cloned Neo block is invalid and merges with the source block.

Please have a look at my screen capture video: http://files.fell.hamburg/Craft5Neo5CloneBug.mov

_As always when I’m creating an issue, I can provide a full backup of my project if that would be helpful to you._

### Steps to reproduce

1. Create a Neo block with three child blocks (1, 2, 3).
2. Save the entry.
3. Clone this block.
4. Result: A new Neo block with three child blocks (1, 2, 3).
5. Save the entry.
6. In my case: The block requires at least one child, so saving isn’t possible (even though it has three child blocks!).
7. Attempt to fix: Delete all child blocks and add a new child block labeled “AAA.”
8. Save the entry.
9. Now everything is completely mixed up: The cloned block disappears, and the new child “AAA” moves into the original block.

### Expected behaviour

Well ... just a second, correct neo block ... a clone of the source block.

### Neo version

5.2.14

### Craft CMS version

5.4.9

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.2.15.

**Comment by mfell** [comment]
@ttempleton Thanks for you quick support ... just tested the update -> now it works correct! :)
