### ISSUE TITLE
JS error in the control panel when adding a new NEO block that contains a native Link field

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [spicywebau/craft-neo#963]
### Bug Description

When a new NEO block just added, it will loose the value for the `Link field` when you save the new block for the first time.

If a `Link field` is `required`, the first time you save the entry with a new NEO block, validation will fail with the error `Link cannot be blank` and you will have to fill it in again.

If a `Link field` is not `required`, the first time you save the entry with a new NEO block, the `Link field` will always be empty.

<img width="1482" alt="Screen Shot 2024-11-15 в 11 18 07" src="https://github.com/user-attachments/assets/e46cb9b5-2b69-4256-b424-ea132cda5b81">

<img width="1201" alt="Screen Shot 2024-11-15 в 11 38 15" src="https://github.com/user-attachments/assets/3b2eeb48-0fcc-4146-901e-f96c581d6482">

### Steps to reproduce

- Create a simple `NEO field` with one block type and add a `Link field` in the `Field Layout` for that block. Make `Link field` to be required
- Assign this `NEO field` to some entry type, that is used by section
- Go to the `Entries` of that section and create a new entry
- Click `Add block` in the `NEO field` and you will see JS error in the console
- Choose something in the `Link field` and try to save the entry
- You will see validation error `Link cannot be blank`
- Choose something in the `Link field` again and re-save the entry
- Entry saved, `Link field` has a value now

### Expected behaviour

No JS error, value for the `Link field` should be saved the first time you save the entry.

Also please make sure that a translatable `Link field` inside `NEO field` automatically mapped to the corresponding entry in the other site. It was fixed in Craft 5.5.0 https://github.com/craftcms/cms/issues/15821

### Neo version

5.2.15

### Craft CMS version

5.5.0.1

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed for the next release. In the meantime, you can get the fix by changing your `spicyweb/craft-neo` requirement in composer.json to `5.x-dev as 5.2.15` and running `composer update`.

**Comment by nikolenko-dmitriy** [comment]
@ttempleton thank you for a quick fix! Just tested with `5.x-dev` version, it works well now

**Comment by ttempleton** [comment]
Just released 5.2.16 including the fix for this.
