### ISSUE TITLE
[5.x] Overload on "Deleting old Neo blocks"-Jobs after pruning revisions

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#965]
### What would you like to see added to or changed in Neo, and why?

Every now and then I prune all revisions. This spawns thousands and thousands of “Deleting old Neo blocks” queue jobs, especially on larger pages. And that clogs up the entire queue and takes ages.

Can't this be done during the `utils/prune-revisions` command?

**Comment by ttempleton** [comment]
We might be able to do that for console commands in general.

**Comment by ttempleton** [comment]
Change now made in 4.2.23 and 5.2.20.
