### ISSUE TITLE
Uninstalling Neo fails to set the correct 'status' for converted fields

### ISSUE THREAD

**Issue by naboo** [spicywebau/craft-neo#966]
### Bug Description

When uninstalling Neo and the 'conversion process' starts, the elements (Matrix field entries) do not have the correct status. All element entries get the 'ENABLED' status but not 'LIVE'.

My guess is that they don't get a "Post Date" or something similuar.

It would also be nice if all statuses would be supported. Enabled (= Enabled, Live), Disabled (= Disabled).

### Steps to reproduce

Uninstall the Neo plugin to start the "convert to matrix" behaviour.

### Expected behaviour

Each neo field row would keep it's visability status (enabled, disabled).

### Neo version

4.2.20

### Craft CMS version

5.5.x

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 4.2.21 and 5.2.16.

**Comment by naboo** [comment]
@ttempleton so it seems the ENABLED/DISABLED status started working, but having the fields as ENABLED doesn't "enable" the entries. They still need to be set to LIVE (if not you'll have to go in and re-save every single relation).

Is this possible to fix you think? My guess is that they need a Post Date or something to be live. See here:

![bild](https://github.com/user-attachments/assets/5dd52b19-59fb-46ea-aa69-a10ce9f8e7c8)

**Comment by naboo** [comment]
No easy fix @ttempleton? :)

**Comment by ttempleton** [comment]
That's what I get for not checking the other Matrix display modes 😅 That's fixed now in 5.2.17.
