### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Kristomen** [spicywebau/craft-neo#969]
### Bug Description

 
When adding an additional field of type Neo to an article in CraftCMS, a 500 Internal Server Error occurs. This happens during a POST request to [index.php?p=admin%2Factions%2Fneo%2Finput%2Frender-blocks](https://website.com/index.php?p=admin%2Factions%2Fneo%2Finput%2Frender-blocks&site=Site&v=1732092234331). 

The Neo field cannot be rendered properly.

 
 

### Steps to reproduce

- Add a new field of type Neo to an existing/new CraftCMS article.
- The request fails with a 500 error, and the Neo blocks are not rendered.
    
    Error Details
Console error log:

{
  "stack": "ye@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:18434\nYe@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:31417\ny@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:36858\nEventHandlerNonNull*ct</<@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:37121\nct<@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:36469\nPt@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:47067\nvalue@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:50219\ne/<@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:48553\nh@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:3448\ns/k/<@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:4799\ns/R/</<@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:3877\nh@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:9966\na@https://website.com/cpresources/adf7fbeb/axios.js?v=1732091731:1:1732091731",
  "message": "Request failed with status code 500",
  "name": "AxiosError",
  "code": "ERR_BAD_RESPONSE",
  "status": 500
}

### Neo version

5.2.16 

### Craft CMS version

5.5.2 

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Just to clarify - this happens immediately when loading the entry editor page after adding the Neo field to the field layout, or when creating a new Neo block on the entry?

**Comment by Kristomen** [comment]
The issue occurs immediately after creating a new article and attempting to add the first NEO block. A similar situation happens when editing existing articles.

During experimentation, I discovered that adding blocks works correctly only for the Default Site but not for other sites. CraftCMS supports multiple sites (Sites), which might be a key factor in this issue.

Unfortunately, I had to roll back to a previous version of CraftCMS because reverting the NEO plugin to an earlier version did not resolve the problem. Only reverting CraftCMS itself restored full functionality.

It seems that the problem is related to the latest release of CraftCMS.

**Comment by martinleveille** [comment]
I am experiencing the same issue with the latest version of Craft CMS 5.5+. To resolve it, I had to revert to Craft CMS 5.4.10.1 to be able to add Neo blocks again in my entries.

In my case, using Craft CMS 5.5+ in a multi-site setup, I can create Neo blocks on my default site but not on my newly added second site.

**Comment by ttempleton** [comment]
Thanks both of you for the extra information regarding the issue affecting non-primary sites on multisite Craft installs. I was able to reproduce the issue on Craft 5.5.1.1, and then confirmed that creating new blocks on the non-primary site worked as expected on Craft 5.5.3. So this likely had the same cause as https://github.com/craftcms/cms/issues/16158.
