### ISSUE TITLE
Block visibility conditions based on custom fields only available after adding first condition

### ISSUE THREAD

**Issue by TheFunkyMonk** [spicywebau/craft-neo#970]
### Bug Description

When configuring visibility conditions for a block under Advanced > Entry Condition, the "Add a rule" dropdown does not contain custom fields. If you add any condition, then open the menu again, custom fields are included.

### Steps to reproduce

1. Create a Neo block
2. Expand "Advanced"
3. Open "Add a rule" menu for Entry Condition

### Expected behaviour

Custom field visibility conditions are available in the dropdown prior to adding a first condition.

### Neo version

5.2.17

### Craft CMS version

5.5.3

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Custom field condition rules aren't currently supported on block types, but the fact that they do appear as options after the first condition is added is a known issue (https://github.com/spicywebau/craft-neo/issues/779). Unfortunately there's no easy fix for removing them, but there is an open feature request for full custom field condition rule support (https://github.com/spicywebau/craft-neo/issues/778) that I'd like to get to at some point.
