### ISSUE TITLE
[5.2.18] Settings -> User Condition "Admin" not working

### ISSUE THREAD

**Issue by mfell** [spicywebau/craft-neo#971]
### Bug Description

Using **User Condition** "_Only allow this block type to be used on users if they match the following rules_" seems to have no effect.

This block is still available for non-admins (see screenshots).

Btw: The other blocks in the screenshot are just disabled ... that's working correct.

## Settings (admin, of course)
<img width="1188" alt="Bildschirmfoto 2024-11-27 um 11 08 41" src="https://github.com/user-attachments/assets/b86a5932-10e4-48b0-9e97-7ac96761673b">

## Control panel of a non-admin user
![Bildschirmfoto 2024-11-27 um 11 09 09](https://github.com/user-attachments/assets/33cc63ee-d7b3-4539-a17b-34e400405451)

### Steps to reproduce

1. Create a Neo field with some blocks and try to hide a block for non-admins
2. Create a non-admin user and use this Neo field -> the not allowed block should be still available (erroneously)

### Neo version

5.2.18

### Craft CMS version

5.5.3

### What is the affected Neo field's propagation method?

Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
That's expected; the user condition block type setting is for when the Neo field is on the user's field layout. User permissions for creating or editing blocks of specific types can be set in the permissions settings for users or user groups.

<img width="215" alt="Screenshot 2024-11-28 at 10 45 06" src="https://github.com/user-attachments/assets/fa55c156-bce9-43a8-ad62-1921a5a4125f">
<img width="259" alt="Screenshot 2024-11-28 at 10 45 20" src="https://github.com/user-attachments/assets/634224f1-5b7d-4a91-b18e-bc4e2058496f">

**Comment by mfell** [comment]
Ah ... I see ... thanks for the clarification.
