### ISSUE TITLE
[Craft 5] Undefined array key when un-installing Neo (converting to Matrix fields)

### ISSUE THREAD

**Issue by naboo** [spicywebau/craft-neo#972]
### Bug Description

When running `... craft plugin/uninstall neo` the Conversion.php at row 174 sometimes throws this exception:

```
Exception: Undefined array key "companyBonusEntry" (/var/www/html/vendor/spicyweb/craft-neo/src/services/Conversion.php:174)
```

My guess is that maybe the related matrix block has yet to be created - or is just missing?

For testing purposes I modifed the source to the following code:

```
if ($relations) {
                foreach ($relations as $relation) {
                    $neoBlockId = $relation['sourceId'];
                    $matrixEntryId = $neoToMatrixElementIds[$neoBlockId];
                    $matrixEntryTypeId = $matrixEntryTypeIdsByEntryId[$matrixEntryId];
                    $globalFieldId = $relation['fieldId'];
                    $globalField = $globalFields[$globalFieldId];
                    $matrixFieldIds = $matrixEntryTypeFieldIds[$matrixEntryTypeId];
                    $matrixFieldId = $matrixFieldIds[$globalField->handle] ?? null;

                    if(is_null($matrixFieldId))
                        continue;

                    $newRelations[] = [
                        $matrixFieldId,
                        $matrixEntryId,
                        $relation['sourceSiteId'],
                        $relation['targetId'],
                        $relation['sortOrder'],
                    ];
                }
            }
```

... and I can't see that anything contentwise is missing or not working. But I haven't gone through everything of course so maybe there is some implication anyways.

Anything that can be fixed?

### Steps to reproduce

1. Uninstall Neo

### Expected behaviour

Uninstallation goes through without the exception

### Neo version

5.2.1

### Craft CMS version

5.5.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 5.2.21.
