### ISSUE TITLE
Unable to activate license

### ISSUE THREAD

**Issue by peter-webbird** [spicywebau/craft-neo#976]
### What question would you like to ask?

We recently inherited a CraftCMS website build by another company. Upon logging in we receive an error message:
"License purchase required.
The following licensing issue can be resolved with a single purchase on Craft Console:
Neo requires purchase."

We followed the "Resolve now" link and purchased a Neo license, however there is no clear way to install or activate this license. Clicking the "Refresh" button also does not work.

How can we activate this license on the website?

**Comment by ttempleton** [comment]
Plugin licenses can be added in the Craft control panel under the Settings -> Plugins page.
